### ISSUE TITLE
Find the way to reduce the documentation packages.wazuh.com URLs length

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1047]
@s-ocando provided us with a URL list to be analyzed and find a way to shorten the URL length. The list:
```
https://packages.wazuh.com/resources/4.2/elastic-stack/elasticsearch/7.x/elasticsearch_all_in_one.yml
https://packages.wazuh.com/resources/4.2/elastic-stack/elasticsearch/7.x/elasticsearch_cluster_initial_node.yml
https://packages.wazuh.com/resources/4.2/elastic-stack/elasticsearch/7.x/elasticsearch_cluster_subsequent_nodes.yml
https://packages.wazuh.com/resources/4.2/elastic-stack/elasticsearch/7.x/elasticsearch_cluster.yml
https://packages.wazuh.com/resources/4.2/elastic-stack/elasticsearch/7.x/elasticsearch.yml
https://packages.wazuh.com/resources/4.2/elastic-stack/kibana/7.x/kibana_all_in_one.yml
https://packages.wazuh.com/resources/4.2/elastic-stack/kibana/7.x/kibana.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/7.x/elasticsearch_all_in_one.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/7.x/elasticsearch_cluster_initial_node.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/7.x/elasticsearch_cluster_subsequent_nodes.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/7.x/elasticsearch.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/roles/internal_users.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/roles/roles_mapping.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/roles/roles.yml
https://packages.wazuh.com/resources/4.2/open-distro/kibana/7.x/kibana_all_in_one.yml
https://packages.wazuh.com/resources/4.2/open-distro/kibana/7.x/kibana.yml
https://packages.wazuh.com/resources/4.2/open-distro/tools/certificate-utility/instances_aio.yml
https://packages.wazuh.com/resources/4.2/open-distro/tools/certificate-utility/instances.yml
https://packages.wazuh.com/resources/4.2/open-distro/tools/certificate-utility/wazuh-cert-tool.sh
https://packages.wazuh.com/resources/4.2/open-distro/tools/wazuh-passwords-tool.sh
https://packages.wazuh.com/resources/4.2/unattended-installation/templates/config.yml
https://packages.wazuh.com/resources/4.2/unattended-installation/unattended-installation.sh
https://packages.wazuh.com/resources/4.2/elastic-stack/filebeat/7.x/filebeat_all_in_one.yml
https://packages.wazuh.com/resources/4.2/elastic-stack/filebeat/7.x/filebeat.yml
https://packages.wazuh.com/resources/4.2/elastic-stack/instances_aio.yml
https://packages.wazuh.com/resources/4.2/elastic-stack/unattended-installation/all-in-one-installation.sh
https://packages.wazuh.com/resources/4.2/elastic-stack/unattended-installation/distributed/elastic-stack-installation.sh
https://packages.wazuh.com/resources/4.2/elastic-stack/unattended-installation/distributed/templates/config_cluster.yml
https://packages.wazuh.com/resources/4.2/elastic-stack/unattended-installation/distributed/templates/config.yml
https://packages.wazuh.com/resources/4.2/elastic-stack/unattended-installation/distributed/wazuh-server-installation.sh
https://packages.wazuh.com/resources/4.2/open-distro/filebeat/7.x/filebeat_elastic_cluster.yml
https://packages.wazuh.com/resources/4.2/unattended-installation/unattended-installation.sh
```

After analyzing the list, we concluded:

1. The following file list will be removed:
```
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/7.x/elasticsearch_all_in_one.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/7.x/elasticsearch_cluster_initial_node.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/7.x/elasticsearch_cluster_subsequent_nodes.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/7.x/elasticsearch.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/roles/internal_users.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/roles/roles_mapping.yml
https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/roles/roles.yml
https://packages.wazuh.com/resources/4.2/open-distro/filebeat/7.x/filebeat_all_in_one.yml
https://packages.wazuh.com/resources/4.2/open-distro/filebeat/7.x/filebeat_elastic_cluster.yml
https://packages.wazuh.com/resources/4.2/open-distro/kibana/7.x/kibana_all_in_one.yml
https://packages.wazuh.com/resources/4.2/open-distro/kibana/7.x/kibana.yml
https://packages.wazuh.com/resources/4.2/open-distro/tools/certificate-utility/instances_aio.yml
https://packages.wazuh.com/resources/4.2/open-distro/tools/certificate-utility/instances.yml
https://packages.wazuh.com/resources/4.2/open-distro/unattended-installation/distributed/elastic-stack-installation.sh
https://packages.wazuh.com/resources/4.2/open-distro/unattended-installation/distributed/templates/config_cluster.yml
https://packages.wazuh.com/resources/4.2/open-distro/unattended-installation/distributed/templates/config.yml
https://packages.wazuh.com/resources/4.2/open-distro/unattended-installation/distributed/wazuh-server-installation.sh
https://packages.wazuh.com/resources/4.2/open-distro/unattended-installation/unattended-installation.sh
```
2. A new place for templates must be created both in the `wazuh-packages` repository and the `packages-dev`-packages` bucket. The following table shows the corresponding folders: 

File | Place in GitHub repository | Place in packages and packages-dev
-- | -- | --
https://packages.wazuh.com/resources/4.2/elastic-stack/elasticsearch/7.x/elasticsearch_all_in_one.yml | documentation-templates/elastic-basic/ | /X.Y/tpl/elastic-basic/
https://packages.wazuh.com/resources/4.2/elastic-stack/elasticsearch/7.x/elasticsearch_cluster_initial_node.yml | documentation-templates/elastic-basic/ | /X.Y/tpl/elastic-basic/
https://packages.wazuh.com/resources/4.2/elastic-stack/elasticsearch/7.x/elasticsearch_cluster_subsequent_nodes.yml | documentation-templates/elastic-basic/ | /X.Y/tpl/elastic-basic/
https://packages.wazuh.com/resources/4.2/elastic-stack/elasticsearch/7.x/elasticsearch_cluster.yml | documentation-templates/elastic-basic/ | /X.Y/tpl/elastic-basic/
https://packages.wazuh.com/resources/4.2/elastic-stack/elasticsearch/7.x/elasticsearch.yml | documentation-templates/elastic-basic/ | /X.Y/tpl/elastic-basic/
https://packages.wazuh.com/resources/4.2/elastic-stack/filebeat/7.x/filebeat_all_in_one.yml | documentation-templates/elastic-basic/ | /X.Y/tpl/elastic-basic/
https://packages.wazuh.com/resources/4.2/elastic-stack/filebeat/7.x/filebeat.yml | documentation-templates/elastic-basic/ | /X.Y/tpl/elastic-basic/
https://packages.wazuh.com/resources/4.2/elastic-stack/instances_aio.yml | documentation-templates/elastic-basic/ | /X.Y/tpl/elastic-basic/
https://packages.wazuh.com/resources/4.2/elastic-stack/kibana/7.x/kibana_all_in_one.yml | documentation-templates/elastic-basic/ | /X.Y/tpl/elastic-basic/
https://packages.wazuh.com/resources/4.2/elastic-stack/kibana/7.x/kibana.yml | documentation-templates/elastic-basic/ | /X.Y/tpl/elastic-basic/
https://packages.wazuh.com/resources/4.2/open-distro/filebeat/7.x/filebeat.yml | documentation-templates/wazuh/filebeat/ | /X.Y/tpl/
wazuh-install.sh | unattended_installer/ (maintaining files and builder) |  X.Y/
wazuh-password-tool.sh | unattended_installer/ (maintaining files and builder) | X.Y/
wazuh-cert-tool.sh | unattended_installer/ (maintaining files and builder) | X.Y/
config.yml | documentation-templates/wazuh/ | X.Y/

## Tasks
- [x] #1311
- [x] [Make a Jenkins pipeline for uploading the github files to the corresponding bucket folder. ](https://github.com/wazuh/wazuh-jenkins/issues/3253)
- [ ] [Modify documentation in order to take new URLs.](https://github.com/wazuh/wazuh-documentation/issues/4922)
- [x] Modify Docker for taking the new URLs for wazuh-password-tool.sh and wazuh-cert-tool.sh.
- [x] Modify ansible for taking the new URLs for wazuh-password-tool.sh and wazuh-cert-tool.sh.
- [x] Modify automation for taking the new URLs for wazuh-password-tool.sh and wazuh-cert-tool.sh.
- [x] Modify training for taking the new URLs for wazuh-password-tool.sh and wazuh-cert-tool.sh.
- [x] Modify indexer/dashboards packages building for including the tools.
- [x] Modify AMI/OVA

**Comment by teddytpc1** [comment]
This could be an option:
```
https://packages.wazuh.com/install/4.2/es/elasticsearch_all_in_one.yml
https://packages.wazuh.com/install/4.2/es/elasticsearch_cluster_initial_node.yml
https://packages.wazuh.com/install/4.2/es/elasticsearch_cluster_subsequent_nodes.yml
https://packages.wazuh.com/install/4.2/es/elasticsearch_cluster.yml
https://packages.wazuh.com/install/4.2/es/elasticsearch.yml
https://packages.wazuh.com/install/4.2/es/kibana_all_in_one.yml
https://packages.wazuh.com/install/4.2/es/kibana.yml
https://packages.wazuh.com/install/4.2/od/elasticsearch_all_in_one.yml
https://packages.wazuh.com/install/4.2/od/elasticsearch_cluster_initial_node.yml
https://packages.wazuh.com/install/4.2/od/elasticsearch_cluster_subsequent_nodes.yml
https://packages.wazuh.com/install/4.2/od/elasticsearch.yml
https://packages.wazuh.com/install/4.2/od/internal_users.yml
https://packages.wazuh.com/install/4.2/od/roles_mapping.yml
https://packages.wazuh.com/install/4.2/od/roles.yml
https://packages.wazuh.com/install/4.2/od/kibana_all_in_one.yml
https://packages.wazuh.com/install/4.2/od/kibana.yml
https://packages.wazuh.com/install/4.2/od/instances_aio.yml
https://packages.wazuh.com/install/4.2/od/instances.yml
https://packages.wazuh.com/install/4.2/od/wazuh-cert-tool.sh
https://packages.wazuh.com/install/4.2/od/wazuh-passwords-tool.sh
https://packages.wazuh.com/install/4.2/od/config.yml
https://packages.wazuh.com/install/4.2/od/unattended-installation.sh
https://packages.wazuh.com/install/4.2/es/filebeat_all_in_one.yml
https://packages.wazuh.com/install/4.2/es/filebeat.yml
https://packages.wazuh.com/install/4.2/es/instances_aio.yml
https://packages.wazuh.com/install/4.2/es/all-in-one-installation.sh
https://packages.wazuh.com/install/4.2/es/distributed/elastic-stack-installation.sh
https://packages.wazuh.com/install/4.2/es/distributed/templates/config_cluster.yml
https://packages.wazuh.com/install/4.2/es/distributed/templates/config.yml
https://packages.wazuh.com/install/4.2/es/distributed/wazuh-server-installation.sh
https://packages.wazuh.com/install/4.2/od/filebeat_elastic_cluster.yml
```

**Comment by alberpilot** [comment]
This will be the option to be applied:
```

https://packages.wazuh.com/wazuh_install/4.2/elasticsearch_all_in_one.yml
https://packages.wazuh.com/wazuh_install/4.2/elasticsearch_cluster_initial_node.yml
https://packages.wazuh.com/wazuh_install/4.2/elasticsearch_cluster_subsequent_nodes.yml
https://packages.wazuh.com/wazuh_install/4.2/elasticsearch.yml
https://packages.wazuh.com/wazuh_install/4.2/internal_users.yml
https://packages.wazuh.com/wazuh_install/4.2/roles_mapping.yml
https://packages.wazuh.com/wazuh_install/4.2/roles.yml
https://packages.wazuh.com/wazuh_install/4.2/kibana_all_in_one.yml
https://packages.wazuh.com/wazuh_install/4.2/kibana.yml
https://packages.wazuh.com/wazuh_install/4.2/instances_aio.yml
https://packages.wazuh.com/wazuh_install/4.2/instances.yml
https://packages.wazuh.com/wazuh_install/4.2/wazuh-cert-tool.sh
https://packages.wazuh.com/wazuh_install/4.2/wazuh-passwords-tool.sh
https://packages.wazuh.com/wazuh_install/4.2/config.yml
https://packages.wazuh.com/wazuh_install/4.2/unattended-installation.sh
https://packages.wazuh.com/wazuh_install/4.2/filebeat_elastic_cluster.yml

https://packages.wazuh.com/wazuh_install/4.2/es/elasticsearch_all_in_one.yml
https://packages.wazuh.com/wazuh_install/4.2/es/elasticsearch_cluster_initial_node.yml
https://packages.wazuh.com/wazuh_install/4.2/es/elasticsearch_cluster_subsequent_nodes.yml
https://packages.wazuh.com/wazuh_install/4.2/es/elasticsearch_cluster.yml
https://packages.wazuh.com/wazuh_install/4.2/es/elasticsearch.yml
https://packages.wazuh.com/wazuh_install/4.2/es/kibana_all_in_one.yml
https://packages.wazuh.com/wazuh_install/4.2/es/kibana.yml
https://packages.wazuh.com/wazuh_install/4.2/es/filebeat_all_in_one.yml
https://packages.wazuh.com/wazuh_install/4.2/es/filebeat.yml
https://packages.wazuh.com/wazuh_install/4.2/es/instances_aio.yml
https://packages.wazuh.com/wazuh_install/4.2/es/all-in-one-installation.sh
https://packages.wazuh.com/wazuh_install/4.2/es/distributed/elastic-stack-installation.sh
https://packages.wazuh.com/wazuh_install/4.2/es/distributed/templates/config_cluster.yml
https://packages.wazuh.com/wazuh_install/4.2/es/distributed/templates/config.yml
https://packages.wazuh.com/wazuh_install/4.2/es/distributed/wazuh-server-installation.sh
```

**Comment by alberpilot** [comment]
We need to create a place where develop the configuration file templates used by the installation guide. For that, we will create a new folder called: `documentation-templates`, placed in the root directory. 

`documentation-templates/elastic-basic/` must be the folder that contains the following files:


https://packages.wazuh.com/wazuh_install/4.2/es/elasticsearch_all_in_one.yml
https://packages.wazuh.com/wazuh_install/4.2/es/elasticsearch_cluster_initial_node.yml
https://packages.wazuh.com/wazuh_install/4.2/es/elasticsearch_cluster_subsequent_nodes.yml
https://packages.wazuh.com/wazuh_install/4.2/es/elasticsearch_cluster.yml
https://packages.wazuh.com/wazuh_install/4.2/es/elasticsearch.yml
https://packages.wazuh.com/wazuh_install/4.2/es/kibana_all_in_one.yml
https://packages.wazuh.com/wazuh_install/4.2/es/kibana.yml
https://packages.wazuh.com/wazuh_install/4.2/es/filebeat_all_in_one.yml
https://packages.wazuh.com/wazuh_install/4.2/es/filebeat.yml
https://packages.wazuh.com/wazuh_install/4.2/es/instances_aio.yml
https://packages.wazuh.com/wazuh_install/4.2/es/all-in-one-installation.sh
https://packages.wazuh.com/wazuh_install/4.2/es/distributed/elastic-stack-installation.sh
https://packages.wazuh.com/wazuh_install/4.2/es/distributed/templates/config_cluster.yml
https://packages.wazuh.com/wazuh_install/4.2/es/distributed/templates/config.yml
https://packages.wazuh.com/wazuh_install/4.2/es/distributed/wazuh-server-installation.sh

When any of those files are modified, they must be uploaded to https://packages.wazuh.com/tpl/elastic-basic/X.Y/ or https://packages-dev.wazuh.com/tpl/elastic-basic/X.Y/ where X.Y can be extracted by the VERSION file. In addition to this, there must be a check looking if the VERSION is published. If so, packages.wazuh.com must be used. If not, packages-dev.wazuh.com must be used. 

The following files:

https://packages.wazuh.com/wazuh_install/4.2/wazuh-cert-tool.sh
https://packages.wazuh.com/wazuh_install/4.2/wazuh-passwords-tool.sh
https://packages.wazuh.com/wazuh_install/4.2/config.yml

belongs to the `unattended-installer` folder, so, if any of those are modified, the place would be packages.wazuh.com root folder and packages-dev.wazuh.com. In addition to this, the /tpl/

https://packages.wazuh.com/wazuh_install/4.2/elasticsearch_all_in_one.yml
https://packages.wazuh.com/wazuh_install/4.2/elasticsearch_cluster_initial_node.yml
https://packages.wazuh.com/wazuh_install/4.2/elasticsearch_cluster_subsequent_nodes.yml
https://packages.wazuh.com/wazuh_install/4.2/elasticsearch.yml
https://packages.wazuh.com/wazuh_install/4.2/internal_users.yml
https://packages.wazuh.com/wazuh_install/4.2/roles_mapping.yml
https://packages.wazuh.com/wazuh_install/4.2/roles.yml
https://packages.wazuh.com/wazuh_install/4.2/kibana_all_in_one.yml
https://packages.wazuh.com/wazuh_install/4.2/kibana.yml
https://packages.wazuh.com/wazuh_install/4.2/instances_aio.yml
https://packages.wazuh.com/wazuh_install/4.2/instances.yml

https://packages.wazuh.com/wazuh_install/4.2/unattended-installation.sh
https://packages.wazuh.com/wazuh_install/4.2/filebeat_elastic_cluster.yml
