### ISSUE TITLE
Support the use of the Azure module in agents installations

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh-packages#1122]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4 | Agent | Install | All  |

## Description
Since with wazuh/wazuh#10662 we start supporting the use of the Azure module in agents, we must review every package to ensure that the `wodles/azure` folder and the related files are properly set when installing an agent.

## Tasks
- [x] Change [RPM agent SPEC](https://github.com/wazuh/wazuh-packages/blob/5621adabaed6fdc718cd2e85f3c084e8ee9876b4/rpms/SPECS/4.4.0/wazuh-agent-4.4.0.spec#L603-L609)
- [x] Change [Solaris11 agent SPEC](https://github.com/wazuh/wazuh-packages/blob/master/solaris/solaris11/SPECS/template_agent_v4.4.0.json)
- [x] Review the rest of the packages

**Comment by noise-kngdm** [comment]
## Issue udpate
We have finished adding the the required lines to the Solaris and RPM SPEC files. After that, we tested creating a package using the modified branch and installing them to check if everything is working fine.

The results of installing the Solaris11 package are the following:

<details><summary>Package installation and file permissions</summary>


```
root@solaris-11:/tmp# pkg install -g ./wazuh-agent_v4.4.0-sol11-i386.p5p wazuh-agent
           Packages to install:  1
            Services to change:  1
       Create boot environment: No
Create backup boot environment: No

DOWNLOAD                                PKGS         FILES    XFER (MB)   SPEED
Completed                                1/1         86/86      5.7/5.7 95.8M/s

PHASE                                          ITEMS
Installing new actions                       137/137
Updating package state database                 Done 
Updating package cache                           0/0 
Updating image state                            Done 
Creating fast lookup database                   Done 
Updating package cache                           3/3 
root@solaris-11:/tmp# l
bash: l: command not found
root@solaris-11:/tmp# cd /var/ossec
root@solaris-11:/var/ossec# ls
active-response  backup           etc              logs             ruleset          var
agentless        bin              lib              queue            tmp              wodles
root@solaris-11:/var/ossec# cd wodles
root@solaris-11:/var/ossec/wodles# ll
bash: ll: command not found
root@solaris-11:/var/ossec/wodles# ls -l
total 13
-rwxr-x---   1 root     wazuh          0 Jan 13 17:40 __init__.py
drwxr-x---   2 root     wazuh          3 Jan 13 17:40 aws
drwxr-x---   2 root     wazuh          3 Jan 13 17:40 azure
drwxr-x---   2 root     wazuh          3 Jan 13 17:40 docker
drwxr-x---   2 root     wazuh          2 Jan 13 17:40 gcloud
root@solaris-11:/var/ossec/wodles# ls -l azure
total 72
-rwxr-x---   1 root     wazuh      36332 Jan 13 17:40 azure-logs
```


</details>


The results of installing the RPM package in a Centos8 machine are the following:

<details><summary>Package installation and file permissions</summary>

```
[root@9e957f5544e7 /]# yum install /tmp/wazuh-agent-4.4.0-1.x86_64.rpm 
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:01:01 ago on Thu Jan 13 16:04:42 2022.
Dependencies resolved.
=============================================================================================
 Package              Architecture    Version                    Repository             Size
=============================================================================================
Installing:
 wazuh-agent          x86_64          4.4.0-1                    @commandline          8.2 M
Installing dependencies:
 initscripts          x86_64          10.00.15-1.el8             baseos                339 k

Transaction Summary
=============================================================================================
Install  2 Packages

Total size: 8.6 M
Total download size: 339 k
Installed size: 25 M
Is this ok [y/N]: y
Downloading Packages:
initscripts-10.00.15-1.el8.x86_64.rpm                        1.1 MB/s | 339 kB     00:00    
---------------------------------------------------------------------------------------------
Total                                                        738 kB/s | 339 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                     1/1 
  Installing       : initscripts-10.00.15-1.el8.x86_64                                   1/2 
  Running scriptlet: initscripts-10.00.15-1.el8.x86_64                                   1/2 
  Running scriptlet: wazuh-agent-4.4.0-1.x86_64                                          2/2 
  Installing       : wazuh-agent-4.4.0-1.x86_64                                          2/2 
  Running scriptlet: wazuh-agent-4.4.0-1.x86_64                                          2/2 
  Verifying        : initscripts-10.00.15-1.el8.x86_64                                   1/2 
  Verifying        : wazuh-agent-4.4.0-1.x86_64                                          2/2 

Installed:
  initscripts-10.00.15-1.el8.x86_64                wazuh-agent-4.4.0-1.x86_64               

Complete!
[root@9e957f5544e7 /]# ls -l /var/ossec/wodles
total 20
-rwxr-x--- 1 root wazuh    0 Jan 13 16:02 __init__.py
drwxr-x--- 2 root wazuh 4096 Jan 13 16:05 aws
drwxr-x--- 2 root wazuh 4096 Jan 13 16:05 azure
drwxr-x--- 2 root wazuh 4096 Jan 13 16:05 docker
drwxr-x--- 4 root wazuh 4096 Jan 13 16:05 gcloud
-rwxr-x--- 1 root wazuh 2080 Jan 13 16:02 utils.py
[root@9e957f5544e7 /]# ls -l /var/ossec/wodles/azure/
total 36
-rwxr-x--- 1 root wazuh 36332 Jan 13 16:02 azure-logs

```

</details>


After reviewing the rest of the packages we concluded that these were the only two packages that would need to manually add the new files to a SPEC file, so we will be opening a pull request with the changes added soon.
