### ISSUE TITLE
Unattended installer publish

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1190]
We decided to publish the new unattended installer within the 4.3.0 release. The following tasks must be completed:

- [x] https://github.com/wazuh/wazuh-jenkins/issues/3138
- [x] https://github.com/wazuh/wazuh-jenkins/issues/3250
- [x] https://github.com/wazuh/wazuh-packages/issues/1176
- [x] https://github.com/wazuh/wazuh-packages/issues/1232 @verdx 
- [x] https://github.com/wazuh/wazuh-packages/issues/1228 
- [x] https://github.com/wazuh/wazuh-jenkins/issues/3321
- [x] https://github.com/wazuh/wazuh-jenkins/issues/3253 @DFolchA 
- [x] https://github.com/wazuh/wazuh-packages/issues/1047 @alberpilot 
- [x] Review changelog. @alberpilot 
- [x] Merge `unify-unattended` branch @alberpilot 

New requirements:
- [x] https://github.com/wazuh/wazuh-packages/issues/1322
- [x] https://github.com/wazuh/wazuh-packages/issues/1300
- [x] https://github.com/wazuh/wazuh-packages/issues/1301

## Tentative
- [ ] https://github.com/wazuh/wazuh-packages/issues/1212 @lastranikos 
- [ ] https://github.com/wazuh/wazuh-packages/issues/1217 @lastranikos
