### ISSUE TITLE
Unattended installer - Second iteration with improvements

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1223]
After [tagging](https://github.com/wazuh/wazuh-packages/tree/v4.2.5-unattended) the unified-unattended installer, we will move forward for including some improvements described in the following issues:

- The unattended installer should be released as a single artifact. All modules (libraries, resources, templates) must be joined into the mentioned artifact. The unattended installer development doesn't change, but a new tool for this artifact building must be created. 
- All module functions must start with the name module prefix. (i.e. `indexer_configureCertificates`). 
- All distributed messages must be reviewed, guiding the user to an unattended installation. Those messages must have links to documentation but, in addition to this, must be self-explained and could avoid the users going to the documentation for checking. 
- Error messages must explain what is happening and links to the documentation, dependencies/requirement section. 
- The unattended installer must detect the OS and check if it's compatible. Links to documentation are needed. 
- Improve the error handling including `set -Eeuxo pipefail`, using traps, and including more fail information, like line number, error code, etc. ([reference](https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/#:~:text=set%20%2Du,is%20often%20highly%20desirable%20behavior))
- Use `printf` instead of `echo`.
- Functions must return true or error code. 
- Don't assume terminal capabilities. Check if `$TERM` is set as unknown, untested, or whatever. Don't use control codes like scape chars, tputs, etc. 

## Tasks
- [x] #1231
- [x] #1232
- [ ] Distributed messages must be improved guiding the users without documentation need. 
- [ ] Error messages must be improved with better and complete explanations. 
- [x] #1228
- [ ] Improve the error handling with `set -Eeuxo pipefail`.
- [ ] `echo` replacement by `printf`. 
- [ ] Return 0 or error values in functions. 
- [ ] Check `$TERM` status and avoid control codes. 
- [ ] Change the Wazuh API default password using the unattended installer. 
- [x] https://github.com/wazuh/wazuh-packages/issues/1205
- [ ] https://github.com/wazuh/wazuh-packages/issues/1210
- [ ] https://github.com/wazuh/wazuh-packages/issues/847
- [ ] Apply preInstallation, packageInstallation, postInstallation functions modularization and template creations. (To define). 
- [ ] Add option `-o` to wazuh-cert-tool and chose the output folder. 
- [ ] [Check if firewall block an incoming connection.](https://github.com/wazuh/wazuh-packages/issues/1217) 
- [ ] [Check all necessary dependencies including the all OS supoused included ones. ](https://github.com/wazuh/wazuh-packages/issues/1212)
- [ ] https://github.com/wazuh/wazuh-packages/issues/1239

## Tentative
- [x] https://github.com/wazuh/wazuh-packages/issues/1234
- [ ] Deploy agents
- [x] https://github.com/wazuh/wazuh-packages/issues/863
- [ ] https://github.com/wazuh/wazuh-packages/issues/862
- [ ] https://github.com/wazuh/wazuh-packages/issues/968
