### ISSUE TITLE
Unattended installer single artifact builder

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1232]
## Goal
The `wazuh_install.sh` must be an artifact built by another tool. Must be the result of joining several files. 

## Context
Developing a single file with this huge functionality is not recommended. The unattended installer is designed to be developed into independent modules like `wazuh.sh` for Wazuh server component installation and configuration, `indexer.sh` for Wazuh indexer, etc. It helps to detect errors, simplify files, locate functions, etc. 

In a first approach, we designed the main file `wazuh_install.sh` to download every module like a library, loading it. This must be changed by a static unique file built picking a `main.sh` file (`wazuh_install.sh` must be renamed to `main.sh`), joining `main.sh` with all `.sh` and producing a single `wazuh_install.sh` as result. 

## Tasks
- [x] Rename `wazuh_install.sh` to `main.sh`. 
- [x] A new tool called `builder.sh` must be created. This tool will create a file `wazuh_install.sh` and will put on it all contained code of `main.sh` and all `.sh` files from the `install_functions` folder. 
- [x] The `builder.sh` tool must include as variables all configuration templates used in `config` folder. I.e: the variable `${config_certificate_config_aio.yml}` must contain the file config/certificate/config_aio.yml content. 
- [x] Instead of reading files, it is necessary to change the code for reading the variables instead. 
- [x] Import functionality must be removed, as they are included in the same script. 
- [x] The `wazuh-cert-tool.sh` and `wazuh-password-tool.sh` functions must be included in the `wazuh_install.sh` file. 
- [x] The `builder.sh` must contains the header: 
```
#!/bin/bash

# Tool to change the passwords of Open Distro internal users
# Copyright (C) 2015, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
```
and must remove the header from other files. 
- [x] The `wazuh-cert-tool.sh` and `wazuh-password-tool.sh` will be split. Under folder `tools/`, both tools will have a file `cert.sh` and a file `password` containing their corresponding functions. The common functions must be placed on `common.sh`. The `builder.sh` must be able to create the `wazuh-cert-tool.sh` and `wazuh-password-tool.sh` joining the `main.sh` and other necessary functions. 
- [x] All configuration files and functions are inside the artifact, so getConfig needs to be changed, and no file can be downloaded from online resources
