### ISSUE TITLE
Dashboard package v3

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#1258]
Hello!

In this issue, we will contemplate changes for v3 of the Wazuh-Dashboard

- [x] Create a new path for the Wazuh-Dashboard app zips
- [x] Modify the specs to contemplate the different versions of the app
- [x] Test Wazuh Dashboard Keystore behavior:
  - [x] Change the password in the dashboard.yml file without removing the Keystore [*](https://github.com/wazuh/wazuh-packages/issues/1258#issuecomment-1040175459)
  - [x] Update password in Keystore and don't touch dashboard.yml [*](https://github.com/wazuh/wazuh-packages/issues/1258#issuecomment-1040175459)
  - [x] Validate the possibility of moving the Keystore
  - [x] Change Keystore password, remove and reinstall [*](https://github.com/wazuh/wazuh-packages/issues/1258#issuecomment-1040180481)
  - [x] Change Keystore password, update wazuh-dashboard and validate if password has changed [*](https://github.com/wazuh/wazuh-packages/issues/1258#issuecomment-1040187337)

**Comment by c-bordon** [comment]
You can only edit the Keystore password interactively, in any case you have to delete the existing one and add the new one:

```
root@Debian-Buster:~# echo "test" | /usr/share/wazuh-dashboard/bin/opensearch-dashboards-keystore --allow-root add opensearch.password
Setting opensearch.password already exists. Overwrite? [y/N] test
Exiting without modifying keystore.


root@Debian-Buster:~# echo "test" | /usr/share/wazuh-dashboard/bin/opensearch-dashboards-keystore --allow-root add opensearch.password --stdin
Setting opensearch.password already exists, exiting without modifying keystore.

```

```
root@Debian-Buster:~# /usr/share/wazuh-dashboard/bin/opensearch-dashboards-keystore --allow-root remove opensearch.password 
root@Debian-Buster:~# echo "test" | /usr/share/wazuh-dashboard/bin/opensearch-dashboards-keystore --allow-root add opensearch.password --stdin
```

**Comment by c-bordon** [comment]
The error message that is thrown when Wazuh-Dashboard is not available yet has been modified
![Screenshot_20220214_162841](https://user-images.githubusercontent.com/64099752/153944796-efaa0aa5-a292-4d8e-ad2e-8583fff4fdbf.png)

**Comment by c-bordon** [comment]
I ran the tests again with the keystore, to change the password in indexer the following steps were followed:

```
root@Debian-Buster:~# /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh -p test
$2y$12$PhMpM3kUPdUF3.zrQg4bJeuqE4/.t8QA7/ysALcPlHdurfLvBG2nO
root@Debian-Buster:~# vim /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml
root@Debian-Buster:~# /usr/share/wazuh-indexer/bin/indexerSecurityInitializer.sh

```
If we replace the Keystore password, the connection is successful:
```
root@Debian-Buster:~# /usr/share/wazuh-dashboard/bin/opensearch-dashboards-keystore remove opensearch.password --allow-root                      
root@Debian-Buster:~# /usr/share/wazuh-dashboard/bin/opensearch-dashboards-keystore add opensearch.password --allow-root      
Enter value for opensearch.password: ****

```
If we go back the change, that is, we put the "kibanaserver" password back in the Keystore, and we edit the /etc/wazuh-dashboard/dashboard.yml file with the new "test" key, we will see that the dashboard is not can connect to the Indexer because the key set in the Keystore has priority.
Therefore, for the key change through the file to work, what we have to do is remove the keys from the Keystore

**Comment by c-bordon** [comment]
The remove process eliminates the /usr/share/wazuh-dashboard directory, therefore the config, that is, the Keystore is eliminated in the process, so when we do a reinstall we have to reload the password in the Keystore

**Comment by c-bordon** [comment]
After the Upgrade, in the install process it is detected that there is a Keystore and it asks us if we want to replace it or not, if we do not replace it, the upgrade is carried out correctly:

```
Setting up wazuh-dashboard (99.99.0-1) ...
An OpenSearch Dashboards keystore already exists. Overwrite? [y/N] N
Exiting without modifying keystore.

```

![Screenshot_20220215_085524](https://user-images.githubusercontent.com/64099752/154057667-6b636a15-d9a7-43e6-8693-dcad2e9afbbf.png)

![Screenshot_20220215_085723](https://user-images.githubusercontent.com/64099752/154057728-c0b7394f-f097-4f3e-bffe-d8318e14c98f.png)
