### ISSUE TITLE
Wazuh indexer default port must be 9200

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1285]
We were asked for changing the 9700 default port by the ES default port 9200 for API and 9300 for the transport layer. This change affects several repositories and it will be tracked in the following list:

- [x] [Change wazuh-indexer installer default ports to ES defaults.](https://github.com/wazuh/wazuh-packages/issues/1286)
- [x] [Change the Unattended installer 9700 and 9800 port references to 9200 and 9300.](https://github.com/wazuh/wazuh-packages/issues/1287)
- [x] [Adapt the Demo deployment to use the new Wazuh indexer default ports. ](https://github.com/wazuh/wazuh-automation/issues/744)
- [x] [Adapt the Docker deployment to use the new Wazuh indexer default ports. ](https://github.com/wazuh/wazuh-docker/issues/580)
- [x] [Adapt the Kubernetes deployment to use the new Wazuh indexer default ports. ](https://github.com/wazuh/wazuh-kubernetes/issues/219)
- [x] [Adapt the Puppet deployment to use the new Wazuh indexer default ports. ](https://github.com/wazuh/wazuh-puppet/issues/447)
- [x] [Adapt the Ansible deployment to use the new Wazuh indexer default ports. ](https://github.com/wazuh/wazuh-ansible/issues/706)
- [x] [Adapt the Training deployments to use the new Wazuh indexer default ports. ](https://github.com/wazuh/wazuh-automation/issues/745)
- [x] Adapt the OVA builder to use the new Wazuh indexer default ports. 
- [x] Adapt the Documentation. 

**If the target repository has the Wazuh indexer/dashboard merged to 4.3 branch, the corresponding pull request must point to the mentioned branch. If the Wazuh indexer/dashboard pull request was not merged yet, the pull request must be done based on the development branch of the Wazuh indexer/dashboard PR.**
