### ISSUE TITLE
Wazuh dashboard configuration file name must be changed to Opensearch default one.

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1288]
We were asked for changing the Wazuh dashboard configuration file name from `dashboard.yml` to `opensearch_dashboards.yml`. This change affects several repositories and it will be tracked in the following list:

- [x] [Change wazuh-dashboard installer default configuration file name to `opensearch_dashboards.yml`](https://github.com/wazuh/wazuh-packages/issues/1282)
- [x] [Adapt the Demo deployment to use the new Wazuh dashboard configuration file name.](https://github.com/wazuh/wazuh-automation/issues/746)
- [x] [Adapt the Ansible deployment to use the new Wazuh dashboard configuration file name.](https://github.com/wazuh/wazuh-ansible/issues/707)
- [x] [Change the Unattended installer to use the new Wazuh dashboard configuration file name.](https://github.com/wazuh/wazuh-packages/issues/1289)
- [x] [Adapt the Docker deployment to use the new Wazuh dashboard configuration file name.](https://github.com/wazuh/wazuh-docker/issues/581)
- [x] [Adapt the Kubernetes deployment to use the new Wazuh dashboard configuration file name.](https://github.com/wazuh/wazuh-kubernetes/issues/221)
- [x] [Adapt the Puppet deployment to use the new Wazuh dashboard configuration file name.](https://github.com/wazuh/wazuh-puppet/issues/448)
- [x] [Adapt the Training deployments to use the new Wazuh dashboard configuration file name.](https://github.com/wazuh/wazuh-automation/issues/747)
- [x] Adapt the OVA builder to use the new Wazuh dashboard configuration file name.
- [x] Adapt the Documentation.

**If the target repository has the Wazuh indexer/dashboard merged to 4.3 branch, the corresponding pull request must point to the mentioned branch. If the Wazuh indexer/dashboard pull request was not merged yet, the pull request must be done based on the development branch of the Wazuh indexer/dashboard PR.**
