### ISSUE TITLE
Add `wodles/gcloud/exceptions.py` to packages SPECS

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh-packages#1316]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4 | Manager & Agent | Install/Upgrade/Remove | OS version |

## Description
While working on wazuh/wazuh#12140, we added a new file, `wodles/gcloud/exceptions.py`. It is necessary to update the SPECS of all the packages affected by the change to make the module as portable as possible.

## Tasks
- [x] Investigate all the packages affected
- [x] Update  `wazuh-packages/solaris/solaris11/SPECS/template_agent_v4.4.0.json`
- [x] Test the updated packages

**Comment by noise-kngdm** [comment]
## Issue update
We added the `wodles/gcloud/exceptions.py` file to the Solaris 11 SPECS file, however, we realized that the changes added in #1126 aren't available yet. We are working on that issue and will submit a PR with the changes once we have been able to appropriately test the package.
