### ISSUE TITLE
Run automaticaly shellcheck static code analyzer over `wazuh-install.sh`, `wazuh-passwords-tool.sh`, `wazuh-certs-tool.sh` and `build.sh` using Github Actions

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1351]
Once finished https://github.com/wazuh/wazuh-packages/issues/1232, we need to have a static analysis of those produced tools. 
https://github.com/koalaman/shellcheck offers a complete static shellcode analysis. The idea is to run it for `wazuh-install.sh`, `wazuh-passwords-tool.sh`, `wazuh-certs-tool.sh` and `build.sh` files. `wazuh-install.sh`, `wazuh-passwords-tool.sh`, `wazuh-certs-tool.sh` are not statically saved, they are dynamically built. 

Using Github Actions we want to run Shellcheck over only pull request modified files. The following image shows the workflow:

![Github Actions - shellcheck](https://user-images.githubusercontent.com/3830293/159042247-57a4eea8-8191-48ed-a344-a4921dc5ea76.png)

In order to easily manage incrementally this development, let's split the tasks and make one pull request for every task. 
## Tasks:
- [x] Create a new branch called `shellcheck-github-actions-workflow` from `4.3` branch. 
- [x] The first PR (starting from `shellcheck-github-actions-workflow` and using it as a target branch) must be a GitHub action workflow that builds an artifact or artifacts depending on the modified files. 
- [x] The second PR must be the shellcheck run after the artifacts building. 
- [x] The third PR must be the results showing depending on the shellcheck report result: red check for errors, yellow check for warnings, green for clean reports.

**Comment by fcaffieri** [comment]
### Update Report

Create branches:
- poc-shellcheck-to4.3-1
- shellcheck-github-actions-workflow

Analyzing GitHub actions:

The first step was to detect the changes made in the PR. Finished, you can see the in .github/workflows/pr-reviews.yml
A check is made in the commits to list in CSV format the changes made in the PR.
Once the changes are obtained, I am trying to find a way to generate a dynamic list of strings, according to the modified directories.
So far I only found a way to do it for 1 case, but I couldn't make it dynamic.
Said list is passed to another job, to execute the builder.sh according to the changes.
If I still can't find a way to build the list according to the modified files, identifying the cases described in the flow, I will proceed to generate a docker where I pass the list of changes and the corresponding validations will be carried out in the said container. Where the builder.sh will be executed as appropriate and then the generated script(s) will be passed in the shellcheck.
Try making the dynamic list outside of docker, since I found a way to run shellcheck directly from the action, which would make everything more transparent.

**Comment by fcaffieri** [comment]
The [PR was generated](https://github.com/wazuh/wazuh-packages/pull/1385), which contains the following modifications already tested:
Workflow with the following actions:
- action1: Detection of changes according to the files modified in unattended_installer.
- action2: array generation with the artifacts that will be generated in the next step.
- action3: generation of a matrix, with the values ​​of the array to send to the construction job, so that for each value in the matrix, said job is executed, avoiding the repetition of code.
- action4: generation of artefacts according to the input of the matrix.
- action5: upload the artifacts generated, in order to be used in the next job, the shellcheck execution.

Test's:

[Test Workflow poc](https://github.com/wazuh/wazuh-packages/pull/1366)
[Test Workflow this PR](https://github.com/wazuh/wazuh-packages/pull/1385/checks)

**Comment by fcaffieri** [comment]
Working on running shellcheck and reporting the output.
So far I managed to get shellcheck running for path "." and generate status according to its completion. I also generate comments on the issue with the suggestions sent by shellcheck.
The problem I'm having is that I can't run it for a path other than ".", because if I change it, it doesn't find files according to the path and the pattern passed.

[Test with path != "."](https://github.com/wazuh/wazuh-packages/runs/5694889929?check_suite_focus=true)
[Test with path == "."](https://github.com/wazuh/wazuh-packages/runs/5691538544?check_suite_focus=true)

**Comment by fcaffieri** [comment]
After investigating the issue of the path (mentioned into the last comment), I found that the problem was due to the fact that comments such as code change suggestions can only be generated for versioned files. With which in my case the files that the shellcheck was passing, were generated at execution time and are not versioned.
On the other hand, if I make code change suggestions on the generated files, the libraries will not be changed, and when the files are generated again from the libraries, they will be generated without the proposed changes.
Talking with Alberto, we came to the conclusion of carrying out the following steps:
1- Run the shellcheck for the libraries used by the builder.sh to generate the .sh, just in case any of these had modifications.
2- Run shellcheck for the artifacts generated by builder.sh, and leave a comment if you have any problems. This case would occur only if the builder.sh wrongly copies or generates the files, since if the check in point 1 was passed, the .sh should be correct.
This entails several modifications in what has already been implemented.
Step 2 almost done.
Working on step 1.

**Comment by fcaffieri** [comment]
Changes finished.
Working on test.
I have a problem in which for some reason in some cases, it does not generate the comments on the PR of the code change suggestions.
If they appear in the changed files section.

**Comment by fcaffieri** [comment]
Seems the problem was that my test were not ok. 

The comments in the issue according to the suggestions, are placed only once per file modification, this is because it performs a diff between the files, if when re-executing the workflow this file did not have changes, it does not find differences with which does not generate a comment on the issue, it does generate suggestions in the file changes tab

PR generated to start the poc with team mates:
https://github.com/wazuh/wazuh-packages/pull/1406
