### ISSUE TITLE
`indexerSecurityInitializer.sh` tool name must be changed by `indexer-security-init.sh`

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1356]
The tool `indexerSecurityInitializer.sh` has a non-corresponding name in `/usr/share/wazuh-indexer/bin/`. All present files:
```
opensearch-env                 opensearch-node            opensearch-upgrade
opensearch                     opensearch-env-from-file   opensearch-plugin    performance-analyzer-agent-cli
opensearch-cli                 opensearch-keystore        opensearch-shard     systemd-entrypoint
```
So the name must be changed by: `indexer-security-init.sh`. 
# Tasks
- [x] [Change `indexerSecurityInitializer.sh` file name to `indexer-security-init.sh` in the `wazuh-indexer` installer. ](https://github.com/wazuh/wazuh-packages/pull/1363)
- [x] [Change `indexerSecurityInitializer.sh` file name to `indexer-security-init.sh` in documentation.](https://github.com/wazuh/wazuh-documentation/issues/4948)
- [x] [Change `indexerSecurityInitializer.sh` file name to `indexer-security-init.sh` in wazuh-jenkins. ](https://github.com/wazuh/wazuh-jenkins/issues/3376)
- [x] [Change `indexerSecurityInitializer.sh` file name to `indexer-security-init.sh` in wazuh-puppet.](https://github.com/wazuh/wazuh-puppet/issues/452)

Deliverable: 3 PRs and one open issue (wazuh-documentation) must be linked to this issue.
