### ISSUE TITLE
The unattended installer must modify existing .yml config files instead of using templates. 

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1357]
The unattended installer uses filebeat/dashboard/indexer configuration template files located here:

https://github.com/wazuh/wazuh-packages/tree/4.3/unattended_installer/config

If we want to modify an indexer option, we need to modify the unattended installer and the wazuh-indexer installed. 
In order to avoid the modification's duplicity, the unattended installer must add-remove-modify the options over the existing configuration file

## Tasks 
- [ ] Avoid using templates and include modification over installation configuration file with wazuh-indexer. 
- [ ] Avoid using templates and include modification over installation configuration file with wazuh-dashboard. 
- [ ] Avoid using templates and include modification over installation configuration file with wazuh-filebeat.
