### ISSUE TITLE
Add `wodles/azure/orm.py` file to packages SPECS

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-packages#1407]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.0 | Manager/Agent | Install/Upgrade/Remove | OS version |

## Description
While working on https://github.com/wazuh/wazuh/issues/11940, we added a new file, `wodles/azure/orm.py`. It is necessary to update the SPECS of all the packages affected by the change to make sure this file is also copied to the `wodles/` path once Wazuh is installed.

## Tasks
- [x] Determine which packages are affected 
- [x] Update SPEC templates if needed
- [x] Test the affected packages

**Comment by CarlosRS9** [comment]
## Issue update
We tested the modified packages by creating a Solaris11 package and a CentOS RPM file and installed in Solaris 11 and CentOS 7, respectively. Everything worked as expected, as can be seen in the following output:

<details><summary>Package installation and file permissions in Solaris11</summary>


	root@solaris11:/tmp# ls -l /var/ossec/wodles/azure/
	total 87
	-rwxr-x---   1 root     wazuh      35994 abr 13 10:13 azure-logs
	-rwxr-x---   1 root     wazuh       7007 abr 13 10:13 orm.py


</details>


We will open a PR with the changes as soon as possible.
