### ISSUE TITLE
Yaml format of the config.yml file to generate certificates is not correct

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-packages#1413]
Reading the documentation of `4.3.0-rc5`, I have seen that to create the necessary certificates for the communication between different Wazuh components, a `config.yml` file is used.

Reviewing the content of this file, I have seen that it contains the following:

```
nodes:
  # Wazuh indexer nodes
  indexer:
    name: node-1
    ip: <indexer-node-ip>
    name: node-2
    ip: <indexer-node-ip>
    name: node-3
    ip: <indexer-node-ip>
...
```

However, it does not comply with the actual yaml syntax, because if we parse this we would get the following:

```
nodes:
  # Wazuh indexer nodes
  indexer:
    name: node-3
    ip: <indexer-node-ip>
...
```

The correct syntax would be as follows:

```
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: <indexer-node-ip>
    - name: node-2
      ip: <indexer-node-ip>
    - name: node-3
      ip: <indexer-node-ip>
...
```

Regardless of which syntax seems to be wrong, the certificates are generated correctly. This has to be because you are using a custom parser that does not take into account that syntax error.

It is requested to correct this error to comply with the standard yaml format, or directly change the extension to another, such as `.cnf` ... to indicate that it does not comply with any specific format.

**Comment by alberpilot** [comment]
## Tasks
- [ ] Wazuh installation assistant `config.yml` modification. (https://github.com/wazuh/wazuh-packages/pull/1443)
- [ ] https://github.com/wazuh/wazuh-ansible/issues/742
- [ ] https://github.com/wazuh/wazuh-puppet/issues/475
- [ ] https://github.com/wazuh/wazuh-docker/issues/609
- [ ] https://github.com/wazuh/wazuh-kubernetes/issues/236
- [ ] https://github.com/wazuh/wazuh-automation/issues/786
