### ISSUE TITLE
wazuh-certs-tool.sh must be able to create certificate without permissions/ownership restrictions

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1449]
Currently, the `wazuh-certs-tool.sh` creates the certificate with 500 folder permissions and 400 certificate permissions. 
Additionally, it's mandatory to run it as root when it's probably not necessary. 

The goal is to modify this tool to create the certificates with flexible permissions and let the deployments set the correct permissions responsibility. 

## Tasks
- [x] Modify the `wazuh-certs-tool.sh` script avoiding the root user execution requirement. 
- [x] Modify the `wazuh-certs-tool.sh` script letting permissions 644 to certificates and containing folder. 
- [x] Verify that Wazuh installation assistance leaves the correct permissions after certificate deployment. 
- [x] Verify that wazuh-ansible deployment leaves the correct certificates permissions. 
- [x] Verify that wazuh-puppet deployment leaves the correct certificates permissions. 
- [x] Verify that wazuh-docker deployment leaves the correct certificates permissions.

**Comment by fcaffieri** [comment]
### Update report
Changes made and tested.
PR generated.
Carrying out tests and verifications in the deployments mentioned in the issue.

**Comment by fcaffieri** [comment]
### Test's:

<details><summary>Run cert_tool without root</summary>
```
fcaffieri@Fede:~/repos/wazuh-packages/unattended_installer$ ls -la
total 48
drwxrwxr-x  7 fcaffieri fcaffieri 4096 abr 12 09:05 .
drwxrwxr-x 20 fcaffieri fcaffieri 4096 abr  6 12:38 ..
-rwxrwxr-x  1 fcaffieri fcaffieri 9345 abr 11 09:24 builder.sh
drwxrwxr-x  2 fcaffieri fcaffieri 4096 abr 11 09:04 cert_tool
drwxrwxr-x  2 fcaffieri fcaffieri 4096 mar 30 15:07 common_functions
drwxrwxr-x  6 fcaffieri fcaffieri 4096 mar 21 14:55 config
-rw-------  1 fcaffieri fcaffieri  577 abr 11 17:17 config.yml
-rw-rw-r--  1 fcaffieri fcaffieri 2397 mar 21 14:55 Development-guide.md
drwxrwxr-x  2 fcaffieri fcaffieri 4096 abr 11 09:04 install_functions
drwxrwxr-x  2 fcaffieri fcaffieri 4096 abr  8 08:32 passwords_tool
```
```
fcaffieri@Fede:~/repos/wazuh-packages/unattended_installer$ ./builder.sh -c
fcaffieri@Fede:~/repos/wazuh-packages/unattended_installer$ ls -la
total 76
drwxrwxr-x  7 fcaffieri fcaffieri  4096 abr 12 09:05 .
drwxrwxr-x 20 fcaffieri fcaffieri  4096 abr  6 12:38 ..
-rwxrwxr-x  1 fcaffieri fcaffieri  9345 abr 11 09:24 builder.sh
drwxrwxr-x  2 fcaffieri fcaffieri  4096 abr 11 09:04 cert_tool
drwxrwxr-x  2 fcaffieri fcaffieri  4096 mar 30 15:07 common_functions
drwxrwxr-x  6 fcaffieri fcaffieri  4096 mar 21 14:55 config
-rw-------  1 fcaffieri fcaffieri   577 abr 11 17:17 config.yml
-rw-rw-r--  1 fcaffieri fcaffieri  2397 mar 21 14:55 Development-guide.md
drwxrwxr-x  2 fcaffieri fcaffieri  4096 abr 11 09:04 install_functions
drwxrwxr-x  2 fcaffieri fcaffieri  4096 abr  8 08:32 passwords_tool
-rw-r--r--  1 fcaffieri fcaffieri 24902 abr 12 09:05 wazuh-certs-tool.sh
```
```
fcaffieri@Fede:~/repos/wazuh-packages/unattended_installer$ bash ./wazuh-certs-tool.sh -A
12/04/2022 09:06:05 INFO: Admin certificates created.
12/04/2022 09:06:06 INFO: Wazuh indexer certificates created.
12/04/2022 09:06:06 INFO: Wazuh server certificates created.
12/04/2022 09:06:06 INFO: Wazuh dashboard certificates created.
fcaffieri@Fede:~/repos/wazuh-packages/unattended_installer$ ls -la
total 80
drwxrwxr-x  8 fcaffieri fcaffieri  4096 abr 12 09:06 .
drwxrwxr-x 20 fcaffieri fcaffieri  4096 abr  6 12:38 ..
-rwxrwxr-x  1 fcaffieri fcaffieri  9345 abr 11 09:24 builder.sh
drwxrwxr-x  2 fcaffieri fcaffieri  4096 abr 11 09:04 cert_tool
drwxrwxr-x  2 fcaffieri fcaffieri  4096 mar 30 15:07 common_functions
drwxrwxr-x  6 fcaffieri fcaffieri  4096 mar 21 14:55 config
-rw-------  1 fcaffieri fcaffieri   577 abr 12 09:06 config.yml
-rw-rw-r--  1 fcaffieri fcaffieri  2397 mar 21 14:55 Development-guide.md
drwxrwxr-x  2 fcaffieri fcaffieri  4096 abr 11 09:04 install_functions
drwxrwxr-x  2 fcaffieri fcaffieri  4096 abr  8 08:32 passwords_tool
drwxr--r--  2 fcaffieri fcaffieri  4096 abr 12 09:06 wazuh-certificates
-rw-r--r--  1 fcaffieri fcaffieri 24902 abr 12 09:05 wazuh-certs-tool.sh
fcaffieri@Fede:~/repos/wazuh-packages/unattended_installer$ ls -la wazuh-certificates/
total 48
drwxr--r-- 2 fcaffieri fcaffieri 4096 abr 12 09:06 .
drwxrwxr-x 8 fcaffieri fcaffieri 4096 abr 12 09:06 ..
-rwxr--r-- 1 fcaffieri fcaffieri 1704 abr 12 09:06 admin-key.pem
-rwxr--r-- 1 fcaffieri fcaffieri 1119 abr 12 09:06 admin.pem
-rwxr--r-- 1 fcaffieri fcaffieri 1704 abr 12 09:06 dashboard-1-key.pem
-rwxr--r-- 1 fcaffieri fcaffieri 1241 abr 12 09:06 dashboard-1.pem
-rwxr--r-- 1 fcaffieri fcaffieri 1704 abr 12 09:06 indexer-1-key.pem
-rwxr--r-- 1 fcaffieri fcaffieri 1237 abr 12 09:06 indexer-1.pem
-rwxr--r-- 1 fcaffieri fcaffieri 1704 abr 12 09:06 root-ca.key
-rwxr--r-- 1 fcaffieri fcaffieri 1204 abr 12 09:06 root-ca.pem
-rwxr--r-- 1 fcaffieri fcaffieri 1704 abr 12 09:06 server-1-key.pem
-rwxr--r-- 1 fcaffieri fcaffieri 1237 abr 12 09:06 server-1.pem
fcaffieri@Fede:~/repos/wazuh-packages/unattended_installer$ 
```

</details>

**Comment by teddytpc1** [comment]
These changes affect to the `wazuh-ansible` repository. This [PR](https://github.com/wazuh/wazuh-ansible/pull/746) was created to adapt the deployment and the changes were tested using the production deployment with 6 EC2 instances.
