### ISSUE TITLE
Third iteration of Wazuh installer assistant

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#1458]
The following improvements and corrections that are necessary to make in the Wazuh installer assistant are detailed:

- [x] Fix -v argument in conjunction with -dw https://github.com/wazuh/wazuh-packages/issues/1459
- [x] #1466
- [x] Allow running offline installation without root user https://github.com/wazuh/wazuh-packages/issues/1459
     - [x]  The created folder must have 500 permissions 
     - [x] The result of running the offline installer should be a .tar.gz file and that is just what it should output 
- [x] Remove references to wazuh dashboards, it is wazuh dashboard @DFolchA 
- [x] Remove the spinner and the -ds option @DFolchA 
- [x] Remove the references to the ${base_path} from the messages and change to a message indicating that the files are created in the same directory @DFolchA 
- [x] Change several messages that the Wazuh Install assistant throws @DFolchA 
    - [x] Change the -c option to --config-file
    - [x] Change the -g option to --generate-config-files
    - [x] Change the -fd option to --force-install-dahsboard
    - [x] Change the message it throws when we execute ctrl-c
    - [x] Change the messages of the Uninstall part, there are writing errors
    - [x] Improve -ws argument explanation
    - [x] Improve -dw argument explanation
    - [x] Fix download log messages
- [x] Add drwx permissions to wazuh-files and wazuh-packages directories, inside wazuh-offline, when downloaded with -dw https://github.com/wazuh/wazuh-packages/issues/1459
- [x] Error in filebeat.yml when downloading with -dw https://github.com/wazuh/wazuh-packages/issues/1459
- [x] Warnings when removing Wazuh indexer
- [x] Update the offline installation guide with the new changes @c-bordon

**Comment by alberpilot** [comment]
The checkbox `Warnings when removing Wazuh indexer` was selected because it seems a box problem due to other tests. 
All others merged.
