### ISSUE TITLE
Improve wazuh-packages directory structure

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#1536]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.x |- | - | - |

Since we are only maintaining one SPEC file on each branch maintaining the old directory structure only makes it harder to maintain the repository.

## Proposed change
```
rpms/
├── build.sh
├── CentOS
│   ├── 5
│   │   ├── i386
│   │   │   ├── CentOS-Base.repo
│   │   │   ├── docker_builder.sh
│   │   │   ├── Dockerfile
│   │   │   └── Vagrantfile
│   │   └── x86_64
│   │       ├── CentOS-Base.repo
│   │       └── Dockerfile
│   ├── 6
│   │   ├── i386
│   │   │   ├── CentOS-Base.repo
│   │   │   └── Dockerfile
│   │   └── x86_64
│   │       ├── CentOS-Base.repo
│   │       └── Dockerfile
│   └── 7
│       ├── aarch64
│       │   └── Dockerfile
│       ├── armv7hl
│       │   ├── build_deps.sh
│       │   └── Dockerfile
│       └── ppc64le
│           └── Dockerfile
├── generate_rpm_package.sh
├── README.md
└── SPECS
    ├── wazuh-agent.spec
    └── wazuh-manager.spec
```

## Tasks
- [ ] Change directory structure
- [ ] Modify docker image building
- [ ] Create and upload images
- [ ] Modify Jenkins pipelines according to the changes

**Comment by DFolchA** [comment]
## Update report

- Change SPEC path and build new docker images
- Modify scripts to use new SPEC path
- Test new building scripts

**Comment by DFolchA** [comment]
## Update report

- Improve on new docker images
- Build and test new images

**Comment by DFolchA** [comment]
## Update report
- Test new images on Jenkins:
  - RPM x86 :heavy_check_mark: 
  - DEB amd64 :heavy_check_mark: 
  - RPM i386 :heavy_check_mark: 
  - DEB i386 :heavy_check_mark: 
  - RPM ARM64 :heavy_check_mark: 
  - DEB ARM64 :heavy_check_mark: 
  - RPM ARM32 :heavy_check_mark: 
  - DEB ARM32 :heavy_check_mark: 
-Test package building:
 - MacOS :red_circle:  investigating issue when building package
 - Solaris 11 :heavy_check_mark:
