### ISSUE TITLE
Implement check for default used ports by Wazuh central components. 

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1578]
When the installation assistant tries to install a component that uses a port (indexer 9200, dashboard 443, Wazuh API 5500, etc), it's needed to check if any of those ports are in use before installing the mentioned component. If the check fails, at the beginning of the script, it should show a message "The port X required by Y is in use so the installation can't be completed unit this port is released." or similar. 

## Tasks
- [ ] Develop a function that checks in `-a` option if ports 1515, 1514, 9200, 9300, 443, 55000 are in use. 
- [ ] Develop a functions that checks in `-ws` option if ports 1514, 1515, 1516, 55000 are in use.
- [ ] Develop a functions that checks in `-wi` option if ports 9200 and 9300 are in use. 
- [ ] Develop a functions that checks in `-wd` option if port 443 is in use. 

Thanks, @72nomada for the suggestion.

**Comment by alberpilot** [comment]
Done.
