### ISSUE TITLE
Filebeat logs analysis

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1667]
It was requested to check the filebeat logs to investigate what is checking filebeat in the following logs:

![image](https://user-images.githubusercontent.com/3830293/174554577-a5010946-7ab7-42b4-957c-f7d0683fdb07.png)
![image](https://user-images.githubusercontent.com/3830293/174554607-40bb5b4c-3ca0-42a3-8ec3-f585c461d03c.png)

**Comment by fcaffieri** [comment]
### Update report

The log that is displayed in the second image is only presented when starting the filebeat, and gives information about the paths, the version, the operating system where it runs, etc. of the configured filebeat.
From what I could see, this message is not logged again, until the filebeat is restarted.
Regarding other logs, when disabling the filebeat metrics, no log was displayed that was not referred to wazuh.
Some more exhaustive tests will be carried out, to rule this out.

**Comment by fcaffieri** [comment]
It was decided to implement the change, for this the following tasks are required:

## Tasks
- [X] Modify template into wazuh-packages.
- [X] Modify template into wazuh-docker.
- [ ] Push new docker images to used by wazuh-kubernetes.
- [ ] Modify template into wazuh-ansible.
- [ ] Modify template into cloud resources.

**Comment by okynos** [comment]
All changes merged, great job @fcaffieri 🚀
