### ISSUE TITLE
Bump Wazuh indexer and dashboard 4.4 packages to OpenSearch 2.3.0

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-packages#1844]
Hello all,

## Description

We want to bump Wazuh indexer and dashboard packages from OpenSearch 2.1.0 to 2.3.0.
To achieve this goal we will need to perform a number of tasks described below.
This development is requested by the support team in addition with front-end team. It is pushed by the CVE discovered into the reporting plugin. Solved in 2.3.0.

### Indexer
- [x] Research about file differences between versions 2.1.0 to 2.3.0
- [x] Check base build steps to check if something has changed into the code
- [x] Build package from base
- [x] Review package build errors
- [x] Test the package 

### Dashboard
- [x] Research about file differences between versions 2.1.0 to 2.3.0
- [x] Check base build steps to check if something has changed into the code
- [x] Build package from base
- [x] Review package build errors
- [x] Test the package 
- [x] https://github.com/wazuh/wazuh-jenkins/issues/3758
## Test install:
- [x] https://github.com/wazuh/wazuh-jenkins/issues/4029

### Indexer
- [x] Build the package
- [x] Check the package installs correctly
  - [x] CentOS 7
  - [x] CentOS 8
  - [x] Ubuntu 16.04
  - [x] Ubuntu 18.04
  - [x] Ubuntu 20.04
  - [x] Ubuntu 22.04
  - [x] Amazon Linux 2
  - [x] Red Hat Enterprise Linux 7
  - [x] Red Hat Enterprise Linux 8
  - [x] Red Hat Enterprise Linux 9
- [x] Check the package uninstall correctly
  - [x] CentOS 7
  - [x] CentOS 8
  - [x] Ubuntu 16.04
  - [x] Ubuntu 18.04
  - [x] Ubuntu 20.04
  - [x] Ubuntu 22.04
  - [x] Amazon Linux 2
  - [x] Red Hat Enterprise Linux 7
  - [x] Red Hat Enterprise Linux 8
  - [x] Red Hat Enterprise Linux 9
- [x] Check the service start
- [x] Check the service stop
- [x] Check the service restart
- [x] Check the removal of service in uninstall
- [x] Check files removal in uninstall except `/var/lib`
- [x] Check indexer is working using `curl`
- [x] Check indexer cluster health
- [x] Check package purge
- [x] Check package remove
- [x] Check file permissions
- [x] Run and review check-files test
- [x] Check default password credentials

### Dashboard
- [x] Build the package
- [x] Check the package installs correctly
  - [x] CentOS 7
  - [x] CentOS 8
  - [x] Ubuntu 16.04
  - [x] Ubuntu 18.04
  - [x] Ubuntu 20.04
  - [x] Ubuntu 22.04
  - [x] Amazon Linux 2
  - [x] Red Hat Enterprise Linux 7
  - [x] Red Hat Enterprise Linux 8
  - [x] Red Hat Enterprise Linux 9
- [x] Check the package uninstall correctly
  - [x] CentOS 7
  - [x] CentOS 8
  - [x] Ubuntu 16.04
  - [x] Ubuntu 18.04
  - [x] Ubuntu 20.04
  - [x] Ubuntu 22.04
  - [x] Amazon Linux 2
  - [x] Red Hat Enterprise Linux 7
  - [x] Red Hat Enterprise Linux 8
  - [x] Red Hat Enterprise Linux 9
- [x] Check the service start
- [x] Check the service stop
- [x] Check the service restart
- [x] Check the removal of service in uninstall
- [x] Check files removal in uninstall
- [x] Check dashboard is working using `curl`
- [x] Check if dashboard interface loads and works
- [x] Check package purge
- [x] Check package remove
- [x] Check file permissions
- [x] Run and review check-files test
- [x] Check default password credentials

**Comment by c-bordon** [comment]
I'm testing with Opensearch 2.3.0, I'm currently having some problems trying to start Indexer, I'm checking permissions:
```
-- A start job for unit wazuh-indexer.service has begun execution.
-- 
-- The job identifier is 1733.
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]: Exception in thread "main" java.io.IOException: Cannot run program "/usr/share/wazuh-indexer/jdk/bin/java": error=13, Permission denied
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]:         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]:         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]:         at org.opensearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:113)
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]:         at org.opensearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:87)
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]:         at org.opensearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:70)
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]:         at org.opensearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:150)
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]:         at org.opensearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:108)
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]: Caused by: java.io.IOException: error=13, Permission denied
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]:         at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]:         at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]:         at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
Sep 26 18:35:51 ubuntu20 systemd-entrypoint[5053]:         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)

```

**Comment by c-bordon** [comment]
I continue to work on the error found when starting indexer, apparently there is an issue with the jvm options, I continue to investigate and test

```
root@ubuntu20:~# /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -cp '/usr/share/wazuh-indexer/lib/*' org.opensearch.tools.launchers.JvmOptionsParser /etc/wazuh-indexer
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1625)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
        at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1650)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.opensearch.tools.launchers.JvmOptionsParser.substitutePlaceholders(JvmOptionsParser.java:197)
        at org.opensearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:149)
        at org.opensearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:108)
root@ubuntu20:~# /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -cp '/usr/share/wazuh-indexer/lib/*' org.opensearch.tools.launchers.JvmOptionsParser /etc/wazuh-indexer
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1625)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
        at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1650)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.opensearch.tools.launchers.JvmOptionsParser.substitutePlaceholders(JvmOptionsParser.java:197)
        at org.opensearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:149)
        at org.opensearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:108)
```

**Comment by c-bordon** [comment]
After multiple tests and investigation, the only conclusion I came to is that for some reason the JDK included in the opensearch tar has a bug, the test I did was:
- install Opensearch from the package
- install Wazuh indexer on another node
- compress the JDK included in the Opensearch 2.3.0 installation
- copy this JDK to node with Wazuh indexer
- remove /usr/share/wazuh-indexer/jdk directory
- unpack the JDK into /usr/share/wazuh-indexer with the command: runuser wazuh-indexer --shell="/bin/bash" --command="tar xvf /usr/share/wazuh-indexer/jdk. tar"

After this, the application started correctly.

It remains for me to investigate the difference between the files that come in the JDK of the tar and the package to identify the file with the bug and solve it in the creation of our package

```
[root@centos7-1 wazuh-indexer]# systemctl status wazuh-indexer
● wazuh-indexer.service - Wazuh-indexer
   Loaded: loaded (/usr/lib/systemd/system/wazuh-indexer.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-09-28 17:44:41 UTC; 31min ago
     Docs: https://documentation.wazuh.com
 Main PID: 26294 (java)
   CGroup: /system.slice/wazuh-indexer.service
           └─26294 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8...

Sep 28 17:44:34 centos7-1 systemd-entrypoint[26294]: + exec /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTo...howCodeDetailsIn
Sep 28 17:44:34 centos7-1 systemd-entrypoint[26294]: WARNING: A terminally deprecated method in java.lang.System has been called
Sep 28 17:44:34 centos7-1 systemd-entrypoint[26294]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/share/wazuh-indexer/lib/opensearch-2.3.0.jar)
Sep 28 17:44:34 centos7-1 systemd-entrypoint[26294]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
Sep 28 17:44:34 centos7-1 systemd-entrypoint[26294]: WARNING: System::setSecurityManager will be removed in a future release
Sep 28 17:44:35 centos7-1 systemd-entrypoint[26294]: WARNING: A terminally deprecated method in java.lang.System has been called
Sep 28 17:44:35 centos7-1 systemd-entrypoint[26294]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (file:/usr/share/wazuh-indexer/lib/opensearch-2.3.0.jar)
Sep 28 17:44:35 centos7-1 systemd-entrypoint[26294]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
Sep 28 17:44:35 centos7-1 systemd-entrypoint[26294]: WARNING: System::setSecurityManager will be removed in a future release
Sep 28 17:44:41 centos7-1 systemd[1]: Started Wazuh-indexer.
Hint: Some lines were ellipsized, use -l to show in full.

```

**Comment by c-bordon** [comment]
I continue to investigate the problem, I was able to detect that the JDK binaries are modified in the creation of our packages, and it is possible that this change is the one that causes the operation problem.

This is the comparison of the files:
![image](https://user-images.githubusercontent.com/64099752/193129511-ea464fa8-64a8-4cd2-9b4b-7f147d5015af.png)


This is the opensearch base and tar comparison:
![image](https://user-images.githubusercontent.com/64099752/193129537-afa3f9c3-3ecf-4002-9267-e0f3d9ea1b79.png)

I've been researching if there is any process that generates this change in our build but I haven't found anything.
I am currently investigating how packages are made in Opensearch, I am analyzing the Gradle files that they use to create the packages to see if I find something that helps us solve this problem

**Comment by c-bordon** [comment]
A summary of the issue with the JDK found when making our packages with the Opensearch 2.3.0 base:
After building the first indexer package built from Opensearch 2.3.0, both for RPM and DEB, the service failed to start. This error occurred when trying to parse the jvm.options file to include it as an argument in the startup of the indexer service.

make comparisons between the 2 files to identify differences that could generate this parsing problem, but the problem continued despite updating the jvm.options file.

The investigation led me to compare the size of the JDK binaries, there I was able to identify that the binaries of our package have a larger size than the binaries found both in our base and in the tar provided by Opensearch, with this we can deduce that in some part of the compilation of our package, the binaries are being modified and possibly this is what causes the error in the parsing of the jvm.options file.

At the moment I continue without finding a solution to this problem, I have not been able to identify why the JDK binaries are modified in this version, since this problem did not appear when we compiled our packages in previous versions of Wazuh indexer

There is a difference in the JAVA version for this version of Opensearch, the JAVA version for 2.1.0 is openjdk 17.0.3 while for 2.3.0 the version is openjdk 17.0.4

**Comment by c-bordon** [comment]
## Indexer changes:
The jvm.options file has some changes, the most significant being the following configuration:
```
# Explicitly allow security manager (https://bugs.openjdk.java.net/browse/JDK-8270380)
18-:-Djava.security.manager=allow

## OpenSearch Performance Analyzer
-Dclk.tck=100
-Djdk.attach.allowAttachSelf=true
-Djava.security.policy=file:///etc/wazuh-indexer/opensearch-performance-analyzer/opensearch_security.policy
--add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED
```

**Comment by c-bordon** [comment]
## Dashboard changes:

### Plugins:
![Screenshot_20220930_170010](https://user-images.githubusercontent.com/64099752/193347451-3671a3b1-cc7d-42ab-a912-171cadeb4366.png)

**Comment by c-bordon** [comment]
## Dashboard remove:

### DEB
```
root@ubuntu20:~# apt remove -y wazuh-dashboard 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  wazuh-dashboard
0 upgraded, 0 newly installed, 1 to remove and 165 not upgraded.
After this operation, 775 MB disk space will be freed.
(Reading database ... 169936 files and directories currently installed.)
Removing wazuh-dashboard (4.4.0-1) ...
Stopping wazuh-dashboard service... OK
Deleting PID directory... OK
Deleting installation directory... OK
```

### RPM
```
[root@centos7-1 ~]# yum remove -y wazuh-dashboard.x86_64 
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Resolving Dependencies
--> Running transaction check
---> Package wazuh-dashboard.x86_64 0:4.4.0-1 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

=============================================================================================================================================================================================================================================
 Package                                                  Arch                                            Version                                            Repository                                                                 Size
=============================================================================================================================================================================================================================================
Removing:
 wazuh-dashboard                                          x86_64                                          4.4.0-1                                            @/wazuh-dashboard-4.4.0-1.x86_64                                          702 M

Transaction Summary
=============================================================================================================================================================================================================================================
Remove  1 Package

Installed size: 702 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Erasing    : wazuh-dashboard-4.4.0-1.x86_64                                                                                                                                                                                            1/1 
  Verifying  : wazuh-dashboard-4.4.0-1.x86_64                                                                                                                                                                                            1/1 

Removed:
  wazuh-dashboard.x86_64 0:4.4.0-1                                                                                                                                                                                                           

Complete!
```

**Comment by c-bordon** [comment]
### Curl Tests:

Tests:
indexer: curl -k -u admin:admin https://localhost:9200
dashboard: curl -Is -k https://localhost/app/login?nextUrl=%2F | head -n 1
#### Centos 7:
```
Curl to Indexer
-----------------------------
{
  "name" : "node-1",
  "cluster_name" : "wazuh-cluster",
  "cluster_uuid" : "uE3tldi2S7qfCapcdSjebw",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "rpm",
    "build_hash" : "6f6e84ebc54af31a976f53af36a5c69d474a5140",
    "build_date" : "2022-09-09T00:07:12.137133581Z",
    "build_snapshot" : false,
    "lucene_version" : "9.3.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
Curl to Dashboard
-----------------------------
HTTP/1.1 200 OK

```

#### Ubuntu focal:
```
Curl to Indexer
-----------------------------
{
  "name" : "node-1",
  "cluster_name" : "wazuh-cluster",
  "cluster_uuid" : "ybrOAx_HQ2SsqeOmqs1FZA",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "rpm",
    "build_hash" : "6f6e84ebc54af31a976f53af36a5c69d474a5140",
    "build_date" : "2022-09-09T00:07:12.137133581Z",
    "build_snapshot" : false,
    "lucene_version" : "9.3.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
Curl to Dashboard
-----------------------------
HTTP/1.1 200 OK

```

**Comment by c-bordon** [comment]
### Cluster health:
```
[root@centos7-1 ~]# curl -k -u admin:admin https://localhost:9200/_cluster/health
{"cluster_name":"wazuh-cluster","status":"green","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"discovered_master":true,"discovered_cluster_manager":true,"active_primary_shards":8,"active_shards":8,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}
```

**Comment by c-bordon** [comment]
The error we had with starting the Wazuh indexer service was due to a file permission issue: `/usr/share/wazuh-indexer/jdk/lib/jspawnhelper`

Once the file permissions were corrected, the service started correctly and the tests could be carried out without problems.

**Comment by c-bordon** [comment]
I've been working on the PR with the bump as some fixes came up. I was also working on this issue related to stack install tests: https://github.com/wazuh/wazuh-jenkins/issues/4029

**Comment by c-bordon** [comment]
This proposed workaround in this [comment](https://github.com/wazuh/wazuh-packages/issues/1733#issuecomment-1268399875) is added

**Comment by c-bordon** [comment]
The tasks indicated in the epic are finished, the issue is closed
