### ISSUE TITLE
Add IPv6 support to `packages.wazuh.com` domain

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#1848]
## Description

We were [notified](https://groups.google.com/g/wazuh/c/5sYApXGJVHc) that the packages in `packages.wazuh.com` cannot be accessed when using only IPv6.

## Tasks

- [ ] Research how to implement IPv6 support in `packages.wazuh.com`.
- [ ] Validate the research and the proposed solution.
- [ ] Implement IPv6 support in `packages.wazuh.com`

## Validation

- [ ] Test repository using IPv4
- [ ] Test repository using IPv6
- [ ] Download packages using IPv4
- [ ] Download packages using IPv6
