### ISSUE TITLE
Fix Wazuh indexer and dashboard permissions in 4.4.0

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#1889]
## Description
From the tests carried out to update the check-files for Wazuh indexer and dashboard, some directories with incorrect permissions were detected:

indexer:
```
15:44:07  Different:
15:44:07  /etc/wazuh-indexer/opensearch-notifications [Wrong:  user group mode]
15:44:07  	Expected: root root  0755  # drwxr-xr-x
15:44:07  	Found   : wazuh-indexer wazuh-indexer  0750  # drwxr-x---
15:44:07  
15:44:07  /etc/wazuh-indexer/opensearch-notifications-core [Wrong:  user group mode]
15:44:07  	Expected: root root  0755  # drwxr-xr-x
15:44:07  	Found   : wazuh-indexer wazuh-indexer  0750  # drwxr-x---
15:44:07  
15:44:07  /etc/wazuh-indexer/opensearch-performance-analyzer [Wrong:  user group mode]
15:44:07  	Expected: root root  0755  # drwxr-xr-x
15:44:07  	Found   : wazuh-indexer wazuh-indexer  0750  # drwxr-x---
15:44:07  
15:44:07  /etc/wazuh-indexer/opensearch-security [Wrong:  user group mode]
15:44:07  	Expected: root root  0755  # drwxr-xr-x
15:44:07  	Found   : wazuh-indexer wazuh-indexer  0750  # drwxr-x---
15:44:07  
15:44:07  /usr/share/wazuh-indexer/bin/opensearch-performance-analyzer [Wrong:  user group]
15:44:07  	Expected: root root  0755  # drwxr-xr-x
15:44:07  	Found   : wazuh-indexer wazuh-indexer  0755  # drwxr-xr-x
15:44:07  
15:44:07  /usr/share/wazuh-indexer/modules/reindex/parent-join [Wrong:  user group]
15:44:07  	Expected: root root  0755  # drwxr-xr-x
15:44:07  	Found   : wazuh-indexer wazuh-indexer  0755  # drwxr-xr-x
15:44:07  
15:44:07  /usr/share/wazuh-indexer/modules/reindex/transport-netty4 [Wrong:  user group]
15:44:07  	Expected: root root  0755  # drwxr-xr-x
15:44:07  	Found   : wazuh-indexer wazuh-indexer  0755  # drwxr-xr-x
15:44:07  
15:44:07  /usr/share/wazuh-indexer/performance-analyzer-rca/config [Wrong:  user group]
15:44:07  	Expected: root root  0755  # drwxr-xr-x
15:44:07  	Found   : wazuh-indexer wazuh-indexer  0755  # drwxr-xr-x
15:44:07  
15:44:07  /usr/share/wazuh-indexer/plugins/opensearch-knn/lib [Wrong:  user group]
15:44:07  	Expected: root root  0755  # drwxr-xr-x
15:44:07  	Found   : wazuh-indexer wazuh-indexer  0755  # drwxr-xr-x
15:44:07  
15:44:07  /usr/share/wazuh-indexer/plugins/opensearch-ml [Wrong:  user group]
15:44:07  	Expected: root root  0755  # drwxr-xr-x
15:44:07  	Found   : wazuh-indexer wazuh-indexer  0755  # drwxr-xr-x
15:44:07  
15:44:07  /usr/share/wazuh-indexer/plugins/opensearch-notifications [Wrong:  user group]
15:44:07  	Expected: root root  0755  # drwxr-xr-x
15:44:07  	Found   : wazuh-indexer wazuh-indexer  0755  # drwxr-xr-x
15:44:07  
15:44:07  /usr/share/wazuh-indexer/plugins/opensearch-notifications-core [Wrong:  user group]
15:44:07  	Expected: root root  0755  # drwxr-xr-x
15:44:07  	Found   : wazuh-indexer wazuh-indexer  0755  # drwxr-xr-x
```

## Tasks

- [x] Replace the permissions of the mentioned directories for Wazuh indexer to 0750
- [x] Change the files that have permissions 0744 by 0740 in Wazuh dashboard

## Validation

- [x] Validate that the affected directories and files have the correct permissions

**Comment by c-bordon** [comment]
Many files and permissions were updated in indexer and dashboard, it was possible to leave similar permissions between both components, the changes are in this [PR](https://github.com/wazuh/wazuh-packages/pull/1890)

**Comment by c-bordon** [comment]
The following change was made to match the permissions that the Wazuh indexer and Opensearch dashboards package have in this files:
```
chown root:root %{buildroot}/etc/systemd/system/wazuh-dashboard.service
chown root:root %{buildroot}/etc/init.d/wazuh-dashboard
```
