### ISSUE TITLE
Investigate the need of increase `TimeoutStartSec` in wazuh-indexer service

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1919]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.9-1 | Wazuh indexer | Start | Deb/RPM |

An error was reported starting the Wazuh indexer: 
```
job for wazuh-indexer.service failed because a timeout was exceeded
```
This is commonly due to not enough host resources (either not enough total CPU/RAM or available CPU/RAM). The service tries to start the process but this one is taking longer than foreseen. 

The service variable `TimeoutStartSec` determines the timeout of starting the process. Increasing this value could allow starting the service in those hosts with resource limitations. 

## Tasks
- [ ] Determine why the current value was set to 75. 
- [ ] Investigate Opensearch and Elasticsearch values. 
- [ ] Investigate the pros/cons of increasing this value. 
- [ ] If the investigation concludes with increasing value, change the code. 
- [ ] Test with the older package and limited host, reproducing the error. Then, test the new one that results in a started service.
