### ISSUE TITLE
Wazuh dashboard should use a light logo on the dark mode loading screen

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1924]
# Description

- When using the dark mode of the Wazuh dashboard, it has been seen that the loading screen logo does not stand out enough when using the dark mode, when checking the [template.js](https://github.com/wazuh/wazuh-packages/blob/4.4/stack/dashboard/base/files/etc/template.js#L60-L75) file, it has been observed that the image used is hard coded in the file and is the same for both modes.
- It would be necessary to add the necessary functionality to allow the said file to specify which image to use depending on whether the dark mode is used or not.

![dark](https://user-images.githubusercontent.com/14913942/200055127-4afe6f6e-66b1-40de-873e-6480a84c538d.png)

# Tasks

- [x] Adapt the current `template.js` file to be able to select an `SVG` image in light mode and another in dark mode.
- [ ] If issue https://github.com/wazuh/wazuh-packages/issues/1923 has been completed:
   - [ ] Request a GIF file with light letters to the @wazuh/marketing team.
   - [ ] Change what is necessary to use the new files.
- [x] Validate changes.
 
# Validation

- [x] The light mode of the Wazuh dashboard uses a logo on the loading screen with dark letters.
- [x] The dark mode of the Wazuh dashboard uses a logo on the loading screen with light letters.

**Comment by alberpilot** [comment]
Please make the logo smaller than the current one. (light and dark).

**Comment by rauldpm** [comment]
## Update report

### Research

- It has been found that the image is defined in the variable `openSearchLogoSpinner` and not in `openSearchLogo`
- I have been investigating how to create and modify SVG PURE images in javascript

---

### Development

#### Change loading logo image

<details><summary>Black letters and white edge</summary>

![image](https://user-images.githubusercontent.com/14913942/201215124-2ca0aa77-63f3-4b30-b3bf-3d6b9ec21a45.png)


```
const openSearchLogoSpinner = _react.default.createElement("svg", {
  viewBox:"0 0 1024 200",
  fill: "none",
  xmlns: "http://www.w3.org/2000/svg"
},
_react.default.createElement("polygon",{points:"204.11 142.81 174.37 46.12 150.88 46.12 121.13 142.81 91.65 46.06 64.64 46.06 107.69 187.04 129.61 187.04 162.63 85 195.5 187.04 217.42 187.04 260.48 46.12 233.6 46.12 204.11 142.81", stroke:"white", strokeWidth:2, fill:"black"}),
_react.default.createElement("polygon",{points:"451.67 70.52 524.33 70.52 444.36 182.73 444.36 187.04 563.74 187.04 563.74 162.64 487.81 162.64 567.65 50.56 567.65 46.12 451.67 46.12 451.67 70.52", stroke:"white", strokeWidth:2, fill:"black"}),
_react.default.createElement("path",{d:"M390,61c-12.09-12.61-28.57-19.24-48-19.24-41,0-72,32.22-72,75s30.95,75,72,75c19.35,0,35.84-6.6,48-19.12v16.16h27.58V44.7H390Zm-45.15,104.7c-27.1,0-46.77-20.6-46.77-49s19.67-48.84,46.77-48.84S391.5,88.4,391.5,116.7,371.89,165.68,344.88,165.68Z", stroke:"white", strokeWidth:2, fill:"black"}),
_react.default.createElement("path",{d:"M696.14,125.88c0,25.29-13.92,39.8-38.18,39.8s-38.32-14.51-38.32-39.8V44.7H592v83.39c0,46.91,35.51,63.56,65.92,63.56s65.77-16.65,65.77-63.56V44.7H696.14Z", stroke:"white", strokeWidth:2, fill:"black"}),
_react.default.createElement("path",{d:"M883.3,93.62A85.09,85.09,0,0,0,878.86,76a56.88,56.88,0,0,0-9.46-16.64A45.46,45.46,0,0,0,853.3,47q-9.93-4.71-24.54-4.7-19.05,0-32.48,8.22A53,53,0,0,0,782.19,63V8.35h-24.4V187h27.66V113.71q0-12.52,2.8-21.27A37.82,37.82,0,0,1,796,78.35a28.86,28.86,0,0,1,11.42-7.76,39.44,39.44,0,0,1,13.83-2.42c7.47,0,13.55,1.53,18.2,4.57a31.27,31.27,0,0,1,10.82,12,52.22,52.22,0,0,1,5.22,16.12,107.39,107.39,0,0,1,1.38,16.89V187h27.66V108.75A114.2,114.2,0,0,0,883.3,93.62Z", stroke:"white", strokeWidth:2, fill:"black"}),
_react.default.createElement("circle",{fill:"#3585F9",cx:"937.12",cy:"167.6",r:"22.24"}));
```

</details>

<details><summary>Dark mode - White letters</summary>

![image](https://user-images.githubusercontent.com/14913942/201215150-e56102e2-64c6-412a-a093-b2a647f426e6.png)

```
const openSearchLogoSpinner = _react.default.createElement("svg", {
  viewBox:"0 0 1024 200",
  fill: "none",
  xmlns: "http://www.w3.org/2000/svg"
},
_react.default.createElement("polygon",{points:"204.11 142.81 174.37 46.12 150.88 46.12 121.13 142.81 91.65 46.06 64.64 46.06 107.69 187.04 129.61 187.04 162.63 85 195.5 187.04 217.42 187.04 260.48 46.12 233.6 46.12 204.11 142.81", fill:"white"}),
_react.default.createElement("polygon",{points:"451.67 70.52 524.33 70.52 444.36 182.73 444.36 187.04 563.74 187.04 563.74 162.64 487.81 162.64 567.65 50.56 567.65 46.12 451.67 46.12 451.67 70.52", fill:"white"}),
_react.default.createElement("path",{d:"M390,61c-12.09-12.61-28.57-19.24-48-19.24-41,0-72,32.22-72,75s30.95,75,72,75c19.35,0,35.84-6.6,48-19.12v16.16h27.58V44.7H390Zm-45.15,104.7c-27.1,0-46.77-20.6-46.77-49s19.67-48.84,46.77-48.84S391.5,88.4,391.5,116.7,371.89,165.68,344.88,165.68Z", fill:"white"}),
_react.default.createElement("path",{d:"M696.14,125.88c0,25.29-13.92,39.8-38.18,39.8s-38.32-14.51-38.32-39.8V44.7H592v83.39c0,46.91,35.51,63.56,65.92,63.56s65.77-16.65,65.77-63.56V44.7H696.14Z", fill:"white"}),
_react.default.createElement("path",{d:"M883.3,93.62A85.09,85.09,0,0,0,878.86,76a56.88,56.88,0,0,0-9.46-16.64A45.46,45.46,0,0,0,853.3,47q-9.93-4.71-24.54-4.7-19.05,0-32.48,8.22A53,53,0,0,0,782.19,63V8.35h-24.4V187h27.66V113.71q0-12.52,2.8-21.27A37.82,37.82,0,0,1,796,78.35a28.86,28.86,0,0,1,11.42-7.76,39.44,39.44,0,0,1,13.83-2.42c7.47,0,13.55,1.53,18.2,4.57a31.27,31.27,0,0,1,10.82,12,52.22,52.22,0,0,1,5.22,16.12,107.39,107.39,0,0,1,1.38,16.89V187h27.66V108.75A114.2,114.2,0,0,0,883.3,93.62Z", fill:"white"}),
_react.default.createElement("circle",{fill:"#3585F9",cx:"937.12",cy:"167.6",r:"22.24"}));
```

</details>

<details><summary>Light mode - Black letters</summary>

![image](https://user-images.githubusercontent.com/14913942/201215395-ca6ad88d-92c3-4e73-90a9-43f8b1a3238c.png)


```
const openSearchLogoSpinner = _react.default.createElement("svg", {
  viewBox:"0 0 1024 200",
  fill: "none",
  xmlns: "http://www.w3.org/2000/svg"
},
_react.default.createElement("polygon",{points:"204.11 142.81 174.37 46.12 150.88 46.12 121.13 142.81 91.65 46.06 64.64 46.06 107.69 187.04 129.61 187.04 162.63 85 195.5 187.04 217.42 187.04 260.48 46.12 233.6 46.12 204.11 142.81", fill:"black"}),
_react.default.createElement("polygon",{points:"451.67 70.52 524.33 70.52 444.36 182.73 444.36 187.04 563.74 187.04 563.74 162.64 487.81 162.64 567.65 50.56 567.65 46.12 451.67 46.12 451.67 70.52", fill:"black"}),
_react.default.createElement("path",{d:"M390,61c-12.09-12.61-28.57-19.24-48-19.24-41,0-72,32.22-72,75s30.95,75,72,75c19.35,0,35.84-6.6,48-19.12v16.16h27.58V44.7H390Zm-45.15,104.7c-27.1,0-46.77-20.6-46.77-49s19.67-48.84,46.77-48.84S391.5,88.4,391.5,116.7,371.89,165.68,344.88,165.68Z", fill:"black"}),
_react.default.createElement("path",{d:"M696.14,125.88c0,25.29-13.92,39.8-38.18,39.8s-38.32-14.51-38.32-39.8V44.7H592v83.39c0,46.91,35.51,63.56,65.92,63.56s65.77-16.65,65.77-63.56V44.7H696.14Z", fill:"black"}),
_react.default.createElement("path",{d:"M883.3,93.62A85.09,85.09,0,0,0,878.86,76a56.88,56.88,0,0,0-9.46-16.64A45.46,45.46,0,0,0,853.3,47q-9.93-4.71-24.54-4.7-19.05,0-32.48,8.22A53,53,0,0,0,782.19,63V8.35h-24.4V187h27.66V113.71q0-12.52,2.8-21.27A37.82,37.82,0,0,1,796,78.35a28.86,28.86,0,0,1,11.42-7.76,39.44,39.44,0,0,1,13.83-2.42c7.47,0,13.55,1.53,18.2,4.57a31.27,31.27,0,0,1,10.82,12,52.22,52.22,0,0,1,5.22,16.12,107.39,107.39,0,0,1,1.38,16.89V187h27.66V108.75A114.2,114.2,0,0,0,883.3,93.62Z", fill:"black"}),
_react.default.createElement("circle",{fill:"#3585F9",cx:"937.12",cy:"167.6",r:"22.24"}));
```

</details>

- A new `openSearchLogoSpinnerDark` variable has been created and a conditional `return` has been created in the `renderBrandingEnabledOrDisabledLoadingLogo` function as follows:

```
return darkMode ? openSearchLogoSpinnerDark : openSearchLogoSpinner;
```

- With this modification, the logo changes depending on whether it is in dark mode or not.


#### Change loading logo size

- To modify the size of the logo, it is necessary to modify the values of the `.osdLoaderWrap svg` component in the `style.js` file, with an initial value of `512px` width and `150px` height.

```
.osdLoaderWrap svg {
  width: 512px;
  height: 150px;
  margin: auto;
  line-height: 1;
}
```

- The file has been modified to obtain screenshots of `512px,150px` (100%), `384px,112px` (75%), and `256px,75px` (50%) sizes.

<details><summary>Loading screen logo with differents sizes</summary>

+ <details><summary>512px, 150px (100%)</summary>

  ![image](https://user-images.githubusercontent.com/14913942/201215587-6c9d8455-2b81-4f20-b140-390e5dc14a53.png)
  ![image](https://user-images.githubusercontent.com/14913942/201215719-d0e35d2c-acb4-4032-afe5-6730a9e2c72e.png)
    
  </details>
  
+ <details><summary>384px, 112px (75%)</summary>

  ![image](https://user-images.githubusercontent.com/14913942/201215605-75d5a355-243c-4571-9d77-3201634f0283.png)
  ![image](https://user-images.githubusercontent.com/14913942/201215748-8379bebc-bea1-496a-9b96-eed2586f6aab.png)
    
  </details>
  
+ <details><summary>256px, 75px (50%)</summary>

  ![image](https://user-images.githubusercontent.com/14913942/201215635-cc1940b9-a83b-438d-9f31-b2e3fb1bbbb4.png)
  ![image](https://user-images.githubusercontent.com/14913942/201215774-39cfe872-88c5-44a8-826a-226bb8f0ce15.png)
    
  </details>


</details>

---

### Nexts steps

- Try to get the template.js file to read an SVG image file.

**Comment by rauldpm** [comment]
## Update report

- After a meeting with the team it has been decided that developing the necessary functionality to read the image from a file is not a priority and will be done in another issue (https://github.com/wazuh/wazuh-packages/issues/1923)
- Final packages have been generated for testing with `wp.1924` revision.
- A pull request to the 4.4 branch has been created.

### Testing

- Wazuh dashboard
  - DEB
    - https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/8959/ 
    - https://packages-dev.wazuh.com/warehouse/test/4.4/deb/wazuh-dashboard_4.4.0-wp.1924_amd64.deb
  - RPM
    - https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/8964/ 
    - https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/wazuh-dashboard-4.4.0-wp.1924.x86_64.rpm
- Wazuh indexer
  - DEB
    - https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/8961/ 
    - https://packages-dev.wazuh.com/warehouse/test/4.4/deb/wazuh-indexer_4.4.0-wp.1924_amd64.deb
  - RPM
    - https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/8967/ 
    - https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/wazuh-indexer-4.4.0-wp.1924.x86_64.rpm


<details><summary>All in One installation - 4.4.0</summary>

```
root@ubuntu20:/home/vagrant/packages# bash wazuh-install.sh -a -i
11/11/2022 19:27:42 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
11/11/2022 19:27:42 INFO: Verbose logging redirected to /var/log/wazuh-install.log
11/11/2022 19:27:43 WARNING: Hardware and system checks ignored.
11/11/2022 19:27:50 INFO: Wazuh development repository added.
11/11/2022 19:27:50 INFO: --- Configuration files ---
11/11/2022 19:27:50 INFO: Generating configuration files.
11/11/2022 19:27:51 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
11/11/2022 19:27:51 INFO: --- Wazuh indexer ---
11/11/2022 19:27:51 INFO: Starting Wazuh indexer installation.
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  wazuh-indexer
0 upgraded, 1 newly installed, 0 to remove and 13 not upgraded.
Need to get 0 B/391 MB of archives.
After this operation, 670 MB of additional disk space will be used.
Get:1 /home/vagrant/packages/wazuh-indexer_4.4.0-wp.1924_amd64.deb wazuh-indexer amd64 4.4.0-wp.1924 [391 MB]
Selecting previously unselected package wazuh-indexer.
(Reading database ... 111722 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.4.0-wp.1924_amd64.deb ...
Creating wazuh-indexer group... OK
Creating wazuh-indexer user... OK
Unpacking wazuh-indexer (4.4.0-wp.1924) ...
Setting up wazuh-indexer (4.4.0-wp.1924) ...
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
Processing triggers for systemd (245.4-4ubuntu3.18) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
11/11/2022 19:28:20 INFO: Wazuh indexer installation finished.
11/11/2022 19:28:20 INFO: Wazuh indexer post-install configuration finished.
11/11/2022 19:28:20 INFO: Starting service wazuh-indexer.
11/11/2022 19:28:31 INFO: wazuh-indexer service started.
11/11/2022 19:28:31 INFO: Initializing Wazuh indexer cluster security settings.
11/11/2022 19:28:41 INFO: Wazuh indexer cluster initialized.
11/11/2022 19:28:41 INFO: --- Wazuh server ---
11/11/2022 19:28:41 INFO: Starting the Wazuh manager installation.
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  expect
The following NEW packages will be installed:
  wazuh-manager
0 upgraded, 1 newly installed, 0 to remove and 13 not upgraded.
Need to get 0 B/122 MB of archives.
After this operation, 466 MB of additional disk space will be used.
Get:1 /home/vagrant/packages/wazuh-manager_4.4.0-wp.1924_amd64.deb wazuh-manager amd64 4.4.0-0.0 [122 MB]
Selecting previously unselected package wazuh-manager.
(Reading database ... 112785 files and directories currently installed.)
Preparing to unpack .../wazuh-manager_4.4.0-wp.1924_amd64.deb ...
Unpacking wazuh-manager (4.4.0-0.0) ...
Setting up wazuh-manager (4.4.0-0.0) ...
Processing triggers for systemd (245.4-4ubuntu3.18) ...
11/11/2022 19:29:10 INFO: Wazuh manager installation finished.
11/11/2022 19:29:10 INFO: Starting service wazuh-manager.
11/11/2022 19:29:22 INFO: wazuh-manager service started.
11/11/2022 19:29:22 INFO: Starting Filebeat installation.
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  filebeat
0 upgraded, 1 newly installed, 0 to remove and 13 not upgraded.
Need to get 22.1 MB of archives.
After this operation, 73.6 MB of additional disk space will be used.
Get:1 https://packages-dev.wazuh.com/pre-release/apt unstable/main amd64 filebeat amd64 7.10.2 [22.1 MB]
Fetched 22.1 MB in 3s (7,857 kB/s)
Selecting previously unselected package filebeat.
(Reading database ... 131512 files and directories currently installed.)
Preparing to unpack .../filebeat_7.10.2_amd64.deb ...
Unpacking filebeat (7.10.2) ...
Setting up filebeat (7.10.2) ...
Processing triggers for systemd (245.4-4ubuntu3.18) ...
11/11/2022 19:29:29 INFO: Filebeat installation finished.
11/11/2022 19:29:31 INFO: Filebeat post-install configuration finished.
11/11/2022 19:29:31 INFO: Starting service filebeat.
11/11/2022 19:29:32 INFO: filebeat service started.
11/11/2022 19:29:32 INFO: --- Wazuh dashboard ---
11/11/2022 19:29:32 INFO: Starting Wazuh dashboard installation.
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  wazuh-dashboard
0 upgraded, 1 newly installed, 0 to remove and 13 not upgraded.
Need to get 0 B/156 MB of archives.
After this operation, 848 MB of additional disk space will be used.
Get:1 /home/vagrant/packages/wazuh-dashboard_4.4.0-wp.1924_amd64.deb wazuh-dashboard amd64 4.4.0-wp.1924 [156 MB]
Selecting previously unselected package wazuh-dashboard.
(Reading database ... 131831 files and directories currently installed.)
Preparing to unpack .../wazuh-dashboard_4.4.0-wp.1924_amd64.deb ...
Creating wazuh-dashboard group... OK
Creating wazuh-dashboard user... OK
Unpacking wazuh-dashboard (4.4.0-wp.1924) ...
Setting up wazuh-dashboard (4.4.0-wp.1924) ...
11/11/2022 19:30:05 INFO: Wazuh dashboard installation finished.
11/11/2022 19:30:05 INFO: Wazuh dashboard post-install configuration finished.
11/11/2022 19:30:05 INFO: Starting service wazuh-dashboard.
11/11/2022 19:30:06 INFO: wazuh-dashboard service started.
11/11/2022 19:30:25 INFO: Initializing Wazuh dashboard web application.
11/11/2022 19:30:26 INFO: Wazuh dashboard web application initialized.
11/11/2022 19:30:26 INFO: --- Summary ---
11/11/2022 19:30:26 INFO: You can access the web interface https://<wazuh-dashboard-ip>
    User: admin
    Password: h.V6RP*j8sGkCi2Bde8znNvGguOyNzc*
11/11/2022 19:30:26 INFO: Installation finished.
```
</details>

<details><summary>New logo screenshots</summary>

- Dark mode loading screen

![image](https://user-images.githubusercontent.com/14913942/201417637-ab791496-139b-4e29-99dc-b7e570d3d53e.png)

- Light mode loading screen

![image](https://user-images.githubusercontent.com/14913942/201418556-f1e78710-d02b-43dd-8385-dcbe609131a0.png)


</details>
