### ISSUE TITLE
Error uninstalling the Wazuh agent when using `--purge`

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1931]
## Description

@davidcr01 has found a problem uninstalling the Wazuh agent in the Ubuntu 20 system, after investigating the error it has been discovered that if a user/group exists in the system that starts with `wazuh` (wazuh-user, wazuh-dashboard, wazuh-indexer, wazuhX, etc.) on the same node where a Wazuh agent is installed, the Wazuh agent uninstall will fail when using the `--purge` option in the following command:

```
apt remove --purge wazuh-agent
```

The error occurs in the following lines of code:

https://github.com/wazuh/wazuh-packages/blob/4.3/debs/SPECS/wazuh-agent/debian/postrm#L43-L48

```
if getent passwd | grep -q "^wazuh" ; then
    deluser wazuh > /dev/null 2>&1
fi
if getent group | grep -q "^wazuh" ; then
    delgroup wazuh > /dev/null 2>&1
fi
```

In a normal uninstall process, the process followed is as follows:

1. Check if the `^wazuh` regex exists in the `passwd` file
2. If it exists, the user `wazuh` is deleted
3. Check if the `^wazuh` regex exists in the `group` file
4. If it exists, the group `wazuh` is deleted

In the event that, for example, the `wazuh-indexer` or `wazuh-dashboard` user exists in the node, the second conditional detects that there is a `wazuh` entry in the `group` file, so when trying to delete the `wazuh` group an error is produced (it does not exist), causing the package to uninstall to fail, keeping a corrupt package in the system (it cannot be reinstalled or uninstalled correctly until this state is fixed)

<details><summary>Failed uninstall</summary>

```
root@ubuntu20:/home/vagrant# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

root@ubuntu20:/home/vagrant# useradd wazuh-dashboard

root@ubuntu20:/home/vagrant# getent passwd | grep "^wazuh"
wazuh:x:113:123::/var/ossec:/sbin/nologin
wazuh-dashboard:x:1001:1001::/home/wazuh-dashboard:/bin/sh

root@ubuntu20:/home/vagrant# getent group | grep "^wazuh"
wazuh:x:123:
wazuh-dashboard:x:1001:

root@ubuntu20:/home/vagrant# apt remove --purge wazuh-agent 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  wazuh-agent*
0 upgraded, 0 newly installed, 1 to remove and 8 not upgraded.
After this operation, 29.5 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 112101 files and directories currently installed.)
Removing wazuh-agent (4.3.9-1) ...
+ DIR=/var/ossec
+ WAZUH_TMP_DIR=/var/ossec/packages_files/agent_config_files
+ [ -d /var/ossec/packages_files/agent_config_files ]
+ [ ! -d /var/ossec/etc ]
+ mkdir -p /var/ossec/etc
+ ls -A /var/ossec/tmp/conffiles
+ mv /var/ossec/tmp/conffiles/client.keys /var/ossec/tmp/conffiles/local_interna
l_options.conf /var/ossec/tmp/conffiles/ossec.conf /var/ossec/tmp/conffiles/shar
ed /var/ossec/etc
+ rm -rf /var/ossec/tmp
+ [ remove = remove ]
+ rm -rf /var/ossec/ruleset
+ rm -rf /var/ossec/var
+ rm -rf /var/ossec/logs
+ find /var/ossec/etc/ -type f -name *save -exec rm -f {} ;
+ find /var/ossec/etc/ -type f -exec mv {} {}.save ;
+ exit 0
(Reading database ... 111755 files and directories currently installed.)
Purging configuration files for wazuh-agent (4.3.9-1) ...
+ DIR=/var/ossec
+ WAZUH_TMP_DIR=/var/ossec/packages_files/agent_config_files
+ grep ^wazuh
+ getent passwd
wazuh:x:113:123::/var/ossec:/sbin/nologin
wazuh-dashboard:x:1001:1001::/home/wazuh-dashboard:/bin/sh
+ deluser wazuh
Removing user `wazuh' ...
Warning: group `wazuh' has no more members.
Done.
+ grep ^wazuh
+ getent group
wazuh-dashboard:x:1001:
+ delgroup wazuh
The group `wazuh' does not exist.
dpkg: error processing package wazuh-agent (--purge):
 installed wazuh-agent package post-removal script subprocess returned error exi
t status 3
Errors were encountered while processing:
 wazuh-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

</details>

It is necessary to review the SPECS files of the Wazuh server, Wazuh agent, Wazuh dashboard, and Wazuh indexer for `RPM` and `DEB` systems so that the install, upgrade, and uninstall processes are always successful.

## Tasks

- [ ] Review the Wazuh agent SPECS files
- [ ] Review the Wazuh server SPECS files
- [ ] Review the Wazuh dashboard SPECS files
- [ ] Review the Wazuh indexer SPECS files
- [ ] Fix the SPECS files so that the user/group to delete/created is specific to the package to be installed/upgraded/uninstalled (do not use regex)
- [ ] Validate the changes

## Validation

- [ ] DEB systems
  - [ ] Install, upgrade and uninstall of the Wazuh agent is successful
  - [ ] Install, upgrade and uninstall of the Wazuh server is successful
  - [ ] Install, upgrade and uninstall of the Wazuh dashboard is successful
  - [ ] Install, upgrade and uninstall of the Wazuh indexer is successful
  - [ ] Wazuh agent, Wazuh dashboard, and Wazuh indexer are correctly installed/upgraded/uninstalled when used on the same node
  - [ ] Wazuh server, Wazuh dashboard, and Wazuh indexer are correctly installed/upgraded/uninstalled when used on the same node
- [ ] RPM systems
  - [ ] Install, upgrade and uninstall of the Wazuh agent is successful
  - [ ] Install, upgrade and uninstall of the Wazuh server is successful
  - [ ] Install, upgrade and uninstall of the Wazuh dashboard is successful
  - [ ] Install, upgrade and uninstall of Wazuh indexer is successful
  - [ ] Wazuh agent, Wazuh dashboard, and Wazuh indexer are correctly installed/upgraded/uninstalled when used on the same node
  - [ ] Wazuh server, Wazuh dashboard, and Wazuh indexer are correctly installed/upgraded/uninstalled when used on the same node

**Comment by DFolchA** [comment]
## Update

Review SPECS:
- [x] Wazuh agent RPM
- [x] Wazuh agent DEB
- [x] Wazuh manager RPM
- [x] Wazuh manager DEB
- [x] Wazuh indexer RPM
- [x] Wazuh indexer DEB
- [x] Wazuh dashboard RPM
- [x] Wazuh dashboard DEB

Fix call to `getent` and avoid using grep:
https://github.com/wazuh/wazuh-packages/commit/48d31af1377469321e338cd1d61bc09f47c9a2f8

## Testing

- [ ] DEB systems
  - [ ] Install, upgrade and uninstall of the Wazuh agent is successful
  - [ ] Install, upgrade and uninstall of the Wazuh server is successful
  - [ ] Install, upgrade and uninstall of the Wazuh dashboard is successful
  - [ ] Install, upgrade and uninstall of the Wazuh indexer is successful
  - [ ] Wazuh agent, Wazuh dashboard, and Wazuh indexer are correctly installed/upgraded/uninstalled when used on the same node
  - [ ] Wazuh server, Wazuh dashboard, and Wazuh indexer are correctly installed/upgraded/uninstalled when used on the same node
- [ ] RPM systems
  - [ ] Install, upgrade and uninstall of the Wazuh agent is successful
  - [ ] Install, upgrade and uninstall of the Wazuh server is successful
  - [ ] Install, upgrade and uninstall of the Wazuh dashboard is successful
  - [ ] Install, upgrade and uninstall of Wazuh indexer is successful
  - [ ] Wazuh agent, Wazuh dashboard, and Wazuh indexer are correctly installed/upgraded/uninstalled when used on the same node
  - [ ] Wazuh server, Wazuh dashboard, and Wazuh indexer are correctly installed/upgraded/uninstalled when used on the same node
  
 - [ ] Solaris 10
  - [ ] Install and uninstall of the Wazuh agent is successful
