### ISSUE TITLE
Changelog is not in descending chronological order

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1943]
## Description

@fdalmaup has reported a problem with the [pull request checks](https://github.com/wazuh/wazuh/pull/15466/checks?check_run_id=9652106925), where failed `CentOS 5` builds can be observed, when investigating it, the following message has been found:

```
+ linux32 rpmbuild --define '_sysconfdir /etc' --define '_topdir /build_wazuh/rpmbuild' --define '_threads 4' --define '_release 0.commit16915ed.el5' --define '_localstatedir /var/ossec' --define '_de
bugenabled no' --target i386 -ba /build_wazuh/rpmbuild/SPECS/wazuh-agent-4.4.0.spec
error: %changelog not in descending chronological order
```

Analyzing the other RPM system builds, this message can also be observed with the difference that the build continues until the package is generated. It is necessary to fix the changelog of each system so that it is in descending order.

```
* Thu Nov 03 2022 support <info@wazuh.com> - 4.4.0
- More info: https://documentation.wazuh.com/current/release-notes/
* Thu Nov 10 2022 support <info@wazuh.com> - 4.3.10
- More info: https://documentation.wazuh.com/current/release-notes/
* Mon Oct 03 2022 support <info@wazuh.com> - 4.3.9
```

Likewise, it is necessary to check that all the systems that use a changelog, reference all the versions, for example, in the master branch AIX changelog, version 4.3.10 is missing, probably because said branch needs the changes of the 4.4 branch

## Tasks

- [ ] Review all systems that have a changelog in the 4.4 branch
- [ ] Fix the changelog so that the order of the versions according to their publication date is correct in the 4.4 branch
- [ ] Validate changes in the 4.4 branch
- [ ] Create a pull request to the 4.4 branch
- [ ] Update the master branch with the 4.4 branch and check that said changelogs are correct

## Validation

- [ ] The changelogs of the following systems are correct and with all versions present
  - [ ] AIX
  - [ ] Wazuh indexer
  - [ ] Wazuh dashboard
  - [ ] RPMs
  - [ ] DEBs
  - [ ] CHANGELOG.md
- [ ] The packages generated for the Wazuh indexer, Wazuh dashboard, RPMs and DEBs systems finish correctly without showing an error message about the changelog.
