### ISSUE TITLE
The certificate creation tool does not create all the certificates specified in the configuration file

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1954]
## Description

An error has been found in the pull request check runs of the 4.4.0 distributed deployment in which it was seen that the Red Hat 9 certificates were not being generated.

When checking the manual generation of certificates using the [config.yml.txt](https://github.com/wazuh/wazuh-packages/files/10105998/config.yml.txt) configuration file (remove `.txt` extension), it has been observed that the same behavior is repeated.

If the Red Hat 9 node is moved to the top of the list, leaving the Red Hat 8 node at the bottom of the list, it can be verified that in this case, the Red Hat 8 certificate is the one that is not created.

Upon investigation, it is believed that the issue may be present in the function [certs_ParseYaml](https://github.com/wazuh/wazuh-packages/blob/e0ddcb5ee11dedc53642f7aca0dd6beb11c7c09f/unattended_installer/cert_tool/certFunctions.sh#L181), this behavior has not been reproduced in the v4.3.10 tag

<details><summary>Certificate creation output</summary>

```
╰─➤  sudo bash wazuh-install.sh -g -i && sudo tar -vxf wazuh-install-files.tar && ls -l wazuh-install-files
28/11/2022 18:18:13 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
28/11/2022 18:18:13 INFO: Verbose logging redirected to /var/log/wazuh-install.log
28/11/2022 18:18:14 WARNING: Hardware and system checks ignored.
28/11/2022 18:18:14 INFO: --- Configuration files ---
28/11/2022 18:18:14 INFO: Generating configuration files.
28/11/2022 18:18:19 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
wazuh-install-files/
wazuh-install-files/ubuntu_bionic-indexer-key.pem
wazuh-install-files/ubuntu_focal-dashboard.pem
wazuh-install-files/ubuntu_focal-indexer-key.pem
wazuh-install-files/redhat_7-indexer-key.pem
wazuh-install-files/centos_7-indexer-key.pem
wazuh-install-files/amazonlinux_2_base-indexer.pem
wazuh-install-files/amazonlinux_2_base-dashboard.pem
wazuh-install-files/centos_8-indexer.pem
wazuh-install-files/centos_7-dashboard-key.pem
wazuh-install-files/ubuntu_jammy-indexer-key.pem
wazuh-install-files/ubuntu_xenial-indexer.pem
wazuh-install-files/centos_7-indexer.pem
wazuh-install-files/amazonlinux_2_base-indexer-key.pem
wazuh-install-files/redhat_7-indexer.pem
wazuh-install-files/centos_7-wazuh.pem
wazuh-install-files/redhat_8-dashboard.pem
wazuh-install-files/admin.pem
wazuh-install-files/root-ca.pem
wazuh-install-files/ubuntu_jammy-dashboard-key.pem
wazuh-install-files/redhat_7-wazuh-key.pem
wazuh-install-files/ubuntu_xenial-wazuh.pem
wazuh-install-files/centos_7-dashboard.pem
wazuh-install-files/ubuntu_jammy-dashboard.pem
wazuh-install-files/config.yml
wazuh-install-files/amazonlinux_2_base-wazuh.pem
wazuh-install-files/ubuntu_jammy-wazuh.pem
wazuh-install-files/centos_8-wazuh-key.pem
wazuh-install-files/centos_8-dashboard.pem
wazuh-install-files/redhat_8-indexer.pem
wazuh-install-files/redhat_8-wazuh.pem
wazuh-install-files/ubuntu_bionic-indexer.pem
wazuh-install-files/redhat_8-indexer-key.pem
wazuh-install-files/admin-key.pem
wazuh-install-files/ubuntu_bionic-wazuh.pem
wazuh-install-files/ubuntu_bionic-wazuh-key.pem
wazuh-install-files/centos_8-indexer-key.pem
wazuh-install-files/ubuntu_xenial-wazuh-key.pem
wazuh-install-files/ubuntu_focal-indexer.pem
wazuh-install-files/ubuntu_bionic-dashboard-key.pem
wazuh-install-files/wazuh-passwords.txt
wazuh-install-files/centos_7-wazuh-key.pem
wazuh-install-files/clusterkey
wazuh-install-files/redhat_8-wazuh-key.pem
wazuh-install-files/redhat_7-dashboard.pem
wazuh-install-files/ubuntu_focal-wazuh.pem
wazuh-install-files/ubuntu_jammy-indexer.pem
wazuh-install-files/amazonlinux_2_base-wazuh-key.pem
wazuh-install-files/redhat_7-wazuh.pem
wazuh-install-files/ubuntu_bionic-dashboard.pem
wazuh-install-files/centos_8-dashboard-key.pem
wazuh-install-files/ubuntu_xenial-dashboard-key.pem
wazuh-install-files/amazonlinux_2_base-dashboard-key.pem
wazuh-install-files/ubuntu_focal-wazuh-key.pem
wazuh-install-files/ubuntu_focal-dashboard-key.pem
wazuh-install-files/redhat_8-dashboard-key.pem
wazuh-install-files/ubuntu_xenial-dashboard.pem
wazuh-install-files/centos_8-wazuh.pem
wazuh-install-files/redhat_7-dashboard-key.pem
wazuh-install-files/root-ca.key
wazuh-install-files/ubuntu_xenial-indexer-key.pem
wazuh-install-files/ubuntu_jammy-wazuh-key.pem
total 244
-r-------- 1 root root 1704 Nov 28 18:18 admin-key.pem
-r-------- 1 root root 1119 Nov 28 18:18 admin.pem
-r-------- 1 root root 1704 Nov 28 18:18 amazonlinux_2_base-dashboard-key.pem
-r-------- 1 root root 1306 Nov 28 18:18 amazonlinux_2_base-dashboard.pem
-r-------- 1 root root 1704 Nov 28 18:18 amazonlinux_2_base-indexer-key.pem
-r-------- 1 root root 1302 Nov 28 18:18 amazonlinux_2_base-indexer.pem
-r-------- 1 root root 1704 Nov 28 18:18 amazonlinux_2_base-wazuh-key.pem
-r-------- 1 root root 1302 Nov 28 18:18 amazonlinux_2_base-wazuh.pem
-r-------- 1 root root 1704 Nov 28 18:18 centos_7-dashboard-key.pem
-r-------- 1 root root 1294 Nov 28 18:18 centos_7-dashboard.pem
-r-------- 1 root root 1704 Nov 28 18:18 centos_7-indexer-key.pem
-r-------- 1 root root 1289 Nov 28 18:18 centos_7-indexer.pem
-r-------- 1 root root 1704 Nov 28 18:18 centos_7-wazuh-key.pem
-r-------- 1 root root 1285 Nov 28 18:18 centos_7-wazuh.pem
-r-------- 1 root root 1704 Nov 28 18:18 centos_8-dashboard-key.pem
-r-------- 1 root root 1294 Nov 28 18:18 centos_8-dashboard.pem
-r-------- 1 root root 1704 Nov 28 18:18 centos_8-indexer-key.pem
-r-------- 1 root root 1289 Nov 28 18:18 centos_8-indexer.pem
-r-------- 1 root root 1704 Nov 28 18:18 centos_8-wazuh-key.pem
-r-------- 1 root root 1285 Nov 28 18:18 centos_8-wazuh.pem
-rw------- 1 root root   33 Nov 28 18:18 clusterkey
-rw------- 1 root root 2048 Nov 28 18:18 config.yml
-r-------- 1 root root 1704 Nov 28 18:18 redhat_7-dashboard-key.pem
-r-------- 1 root root 1294 Nov 28 18:18 redhat_7-dashboard.pem
-r-------- 1 root root 1704 Nov 28 18:18 redhat_7-indexer-key.pem
-r-------- 1 root root 1289 Nov 28 18:18 redhat_7-indexer.pem
-r-------- 1 root root 1704 Nov 28 18:18 redhat_7-wazuh-key.pem
-r-------- 1 root root 1285 Nov 28 18:18 redhat_7-wazuh.pem
-r-------- 1 root root 1704 Nov 28 18:18 redhat_8-dashboard-key.pem
-r-------- 1 root root 1294 Nov 28 18:18 redhat_8-dashboard.pem
-r-------- 1 root root 1704 Nov 28 18:18 redhat_8-indexer-key.pem
-r-------- 1 root root 1289 Nov 28 18:18 redhat_8-indexer.pem
-r-------- 1 root root 1704 Nov 28 18:18 redhat_8-wazuh-key.pem
-r-------- 1 root root 1285 Nov 28 18:18 redhat_8-wazuh.pem
-r-------- 1 root root 1704 Nov 28 18:18 root-ca.key
-r-------- 1 root root 1204 Nov 28 18:18 root-ca.pem
-r-------- 1 root root 1704 Nov 28 18:18 ubuntu_bionic-dashboard-key.pem
-r-------- 1 root root 1298 Nov 28 18:18 ubuntu_bionic-dashboard.pem
-r-------- 1 root root 1704 Nov 28 18:18 ubuntu_bionic-indexer-key.pem
-r-------- 1 root root 1298 Nov 28 18:18 ubuntu_bionic-indexer.pem
-r-------- 1 root root 1704 Nov 28 18:18 ubuntu_bionic-wazuh-key.pem
-r-------- 1 root root 1294 Nov 28 18:18 ubuntu_bionic-wazuh.pem
-r-------- 1 root root 1704 Nov 28 18:18 ubuntu_focal-dashboard-key.pem
-r-------- 1 root root 1298 Nov 28 18:18 ubuntu_focal-dashboard.pem
-r-------- 1 root root 1704 Nov 28 18:18 ubuntu_focal-indexer-key.pem
-r-------- 1 root root 1294 Nov 28 18:18 ubuntu_focal-indexer.pem
-r-------- 1 root root 1704 Nov 28 18:18 ubuntu_focal-wazuh-key.pem
-r-------- 1 root root 1294 Nov 28 18:18 ubuntu_focal-wazuh.pem
-r-------- 1 root root 1704 Nov 28 18:18 ubuntu_jammy-dashboard-key.pem
-r-------- 1 root root 1298 Nov 28 18:18 ubuntu_jammy-dashboard.pem
-r-------- 1 root root 1704 Nov 28 18:18 ubuntu_jammy-indexer-key.pem
-r-------- 1 root root 1294 Nov 28 18:18 ubuntu_jammy-indexer.pem
-r-------- 1 root root 1704 Nov 28 18:18 ubuntu_jammy-wazuh-key.pem
-r-------- 1 root root 1294 Nov 28 18:18 ubuntu_jammy-wazuh.pem
-r-------- 1 root root 1704 Nov 28 18:18 ubuntu_xenial-dashboard-key.pem
-r-------- 1 root root 1298 Nov 28 18:18 ubuntu_xenial-dashboard.pem
-r-------- 1 root root 1704 Nov 28 18:18 ubuntu_xenial-indexer-key.pem
-r-------- 1 root root 1298 Nov 28 18:18 ubuntu_xenial-indexer.pem
-r-------- 1 root root 1704 Nov 28 18:18 ubuntu_xenial-wazuh-key.pem
-r-------- 1 root root 1294 Nov 28 18:18 ubuntu_xenial-wazuh.pem
-rw------- 1 root root 1192 Nov 28 18:18 wazuh-passwords.txt

```

</details>

## Tasks

- [x] Investigate and identify the error.
- [x] Fix the error.
- [x] Validate fix.

## Validation

- [x] All node certificates specified in a configuration file are created, regardless of their number or position in the list.

**Comment by davidcr01** [comment]
## Update Report

I have been reproducing the problem, apparently, none of the last nodes of indexer, manager, and dashboard certificates are created.

Here is an example with the `verbose` options that do not show the RedHat 9 certificates, which is the last one of the list of nodes.
<details><summary>Example</summary>

```
root@vagrant:/home/vagrant# bash wazuh-install.sh -g -i -v
30/11/2022 12:19:37 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.0
30/11/2022 12:19:37 INFO: Verbose logging redirected to /var/log/wazuh-install.log
30/11/2022 12:19:39 WARNING: Hardware and system checks ignored.
30/11/2022 12:19:39 INFO: --- Configuration files ---
30/11/2022 12:19:39 INFO: Generating configuration files.
30/11/2022 12:19:40 DEBUG: Creating the root certificate.
Can't load /root/.rnd into RNG
139899826098624:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/root/.rnd
Generating a RSA private key
......................................................+++++
..........................................................................................................+++++
writing new private key to '/tmp/wazuh-certificates//root-ca.key'
-----
Generating RSA private key, 2048 bit long modulus (2 primes)
..............+++++
...........+++++
e is 65537 (0x010001)
Can't load /root/.rnd into RNG
139722789163456:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/root/.rnd
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = admin
Getting CA Private Key
30/11/2022 12:19:40 DEBUG: Creating the Wazuh indexer certificates.
30/11/2022 12:19:40 DEBUG: 8
Ignoring -days; not generating a certificate
Generating a RSA private key
........................................................+++++
........+++++
writing new private key to '/tmp/wazuh-certificates//centos_7-indexer-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = centos_7-indexer
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
......................................+++++
........................+++++
writing new private key to '/tmp/wazuh-certificates//centos_8-indexer-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = centos_8-indexer
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
...................+++++
..........................+++++
writing new private key to '/tmp/wazuh-certificates//ubuntu_xenial-indexer-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = ubuntu_xenial-indexer
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
...............................................................................+++++
....................................................+++++
writing new private key to '/tmp/wazuh-certificates//ubuntu_bionic-indexer-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = ubuntu_bionic-indexer
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
....+++++
.............................................+++++
writing new private key to '/tmp/wazuh-certificates//ubuntu_focal-indexer-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = ubuntu_focal-indexer
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
.....................+++++
...+++++
writing new private key to '/tmp/wazuh-certificates//ubuntu_jammy-indexer-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = ubuntu_jammy-indexer
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
........+++++
.............+++++
writing new private key to '/tmp/wazuh-certificates//amazonlinux_2_base-indexer-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = amazonlinux_2_base-indexer
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
............+++++
.......................................................+++++
writing new private key to '/tmp/wazuh-certificates//redhat_7-indexer-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = redhat_7-indexer
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
...............+++++
.................+++++
writing new private key to '/tmp/wazuh-certificates//redhat_8-indexer-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = redhat_8-indexer
Getting CA Private Key
30/11/2022 12:19:41 DEBUG: Creating the Wazuh server certificates.
Ignoring -days; not generating a certificate
Generating a RSA private key
.........+++++
....................+++++
writing new private key to '/tmp/wazuh-certificates//centos_7-wazuh-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = centos_7-wazuh
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
................................................................................+++++
......................................+++++
writing new private key to '/tmp/wazuh-certificates//centos_8-wazuh-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = centos_8-wazuh
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
..............+++++
...........................................................................................................................................................................................................................+++++
writing new private key to '/tmp/wazuh-certificates//ubuntu_xenial-wazuh-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = ubuntu_xenial-wazuh
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
..+++++
..............+++++
writing new private key to '/tmp/wazuh-certificates//ubuntu_bionic-wazuh-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = ubuntu_bionic-wazuh
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
........+++++
...............................................+++++
writing new private key to '/tmp/wazuh-certificates//ubuntu_focal-wazuh-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = ubuntu_focal-wazuh
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
....................+++++
.+++++
writing new private key to '/tmp/wazuh-certificates//ubuntu_jammy-wazuh-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = ubuntu_jammy-wazuh
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
..................................................+++++
..............+++++
writing new private key to '/tmp/wazuh-certificates//amazonlinux_2_base-wazuh-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = amazonlinux_2_base-wazuh
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
.....................+++++
.....................................+++++
writing new private key to '/tmp/wazuh-certificates//redhat_7-wazuh-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = redhat_7-wazuh
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
.............................................................................................+++++
....................................................................................+++++
writing new private key to '/tmp/wazuh-certificates//redhat_8-wazuh-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = redhat_8-wazuh
Getting CA Private Key
30/11/2022 12:19:42 DEBUG: Creating the Wazuh dashboard certificates.
Ignoring -days; not generating a certificate
Generating a RSA private key
.....................+++++
................................+++++
writing new private key to '/tmp/wazuh-certificates//centos_7-dashboard-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = centos_7-dashboard
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
......................+++++
.....................................................................................................+++++
writing new private key to '/tmp/wazuh-certificates//centos_8-dashboard-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = centos_8-dashboard
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
........+++++
..............................................................+++++
writing new private key to '/tmp/wazuh-certificates//ubuntu_xenial-dashboard-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = ubuntu_xenial-dashboard
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
..+++++
............................................+++++
writing new private key to '/tmp/wazuh-certificates//ubuntu_bionic-dashboard-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = ubuntu_bionic-dashboard
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
..............................+++++
...........+++++
writing new private key to '/tmp/wazuh-certificates//ubuntu_focal-dashboard-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = ubuntu_focal-dashboard
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
......................................................+++++
.......................+++++
writing new private key to '/tmp/wazuh-certificates//ubuntu_jammy-dashboard-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = ubuntu_jammy-dashboard
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
.............................+++++
..................................................................................+++++
writing new private key to '/tmp/wazuh-certificates//amazonlinux_2_base-dashboard-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = amazonlinux_2_base-dashboard
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
.............................+++++
.....................+++++
writing new private key to '/tmp/wazuh-certificates//redhat_7-dashboard-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = redhat_7-dashboard
Getting CA Private Key
Ignoring -days; not generating a certificate
Generating a RSA private key
.....................+++++
.......+++++
writing new private key to '/tmp/wazuh-certificates//redhat_8-dashboard-key.pem'
-----
Signature ok
subject=C = US, L = California, O = Wazuh, OU = Wazuh, CN = redhat_8-dashboard
Getting CA Private Key
30/11/2022 12:19:43 DEBUG: Generating random passwords.
30/11/2022 12:19:43 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
```

</details>

It is compulsory to understand the code of the `cert_parseYaml` function in order to fix this problem. This could take quite some time.

**Comment by DFolchA** [comment]
## Update

Test and reproduce error:

<details><summary>config.yml</summary>

```

nodes:
  # Wazuh indexer server nodes
  indexer:
    - name: centos_7-indexer
      ip: 172.31.7.130
    - name: centos_8-indexer
      ip: 172.31.2.66
    - name: ubuntu_xenial-indexer
      ip: 172.31.10.59
    - name: ubuntu_bionic-indexer
      ip: 172.31.13.18
    - name: ubuntu_focal-indexer
      ip: 172.31.12.2
    - name: ubuntu_jammy-indexer
      ip: 172.31.2.67
    - name: amazonlinux_1_base-indexer
      ip: 172.31.2.7
    - name: amazonlinux_2_base-indexer
      ip: 172.31.2.71
    - name: redhat_7-indexer
      ip: 172.31.1.36
    - name: redhat_8-indexer
      ip: 172.31.4.183
    - name: redhat_9-indexer
      ip: 172.31.6.96
    - name: test1-indexer
      ip: 172.31.6.1
    - name: test2-indexer
      ip: 172.31.6.2
    - name: test3-indexer
      ip: 172.31.6.3
    - name: test4-indexer
      ip: 172.31.6.4
    - name: test5-indexer
      ip: 172.31.6.5
    - name: test6-indexer
      ip: 172.31.6.6
    - name: test7-indexer
      ip: 172.31.6.7
```
</details>

```
dfolcha@pop-os:~/wazuh-packages/unattended_installer$ ./builder.sh -i -d
dfolcha@pop-os:~/wazuh-packages/unattended_installer$ sudo bash ./wazuh-install.sh -g -i 
01/12/2022 17:41:12 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
01/12/2022 17:41:12 INFO: Verbose logging redirected to /var/log/wazuh-install.log
01/12/2022 17:41:14 WARNING: Hardware and system checks ignored.
01/12/2022 17:41:14 INFO: --- Configuration files ---
01/12/2022 17:41:14 INFO: Generating configuration files.
01/12/2022 17:41:16 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
dfolcha@pop-os:~/wazuh-packages/unattended_installer$ sudo tar -tvf wazuh-install-files.tar | grep indexer-key | wc -l
9
```

Built script to test the parseYaml function:

<details><summary>test.sh</summary>

```
function cert_parseYaml() {

    local prefix=$2
    local separator=${3:-_}
    local indexfix
    # Detect awk flavor
    if awk --version 2>&1 | grep -q "GNU Awk" ; then
    # GNU Awk detected
    indexfix=-1
    elif awk -Wv 2>&1 | grep -q "mawk" ; then
    # mawk detected
    indexfix=0
    fi

    local s='[[:space:]]*' sm='[ \t]*' w='[a-zA-Z0-9_]*' fs=${fs:-$(echo @|tr @ '\034')} i=${i:-  }
    cat $1 2>/dev/null | \
    awk -F$fs "{multi=0; 
        if(match(\$0,/$sm\|$sm$/)){multi=1; sub(/$sm\|$sm$/,\"\");}
        if(match(\$0,/$sm>$sm$/)){multi=2; sub(/$sm>$sm$/,\"\");}
        while(multi>0){
            str=\$0; gsub(/^$sm/,\"\", str);
            indent=index(\$0,str);
            indentstr=substr(\$0, 0, indent+$indexfix) \"$i\";
            obuf=\$0;
            getline;
            while(index(\$0,indentstr)){
                obuf=obuf substr(\$0, length(indentstr)+1);
                if (multi==1){obuf=obuf \"\\\\n\";}
                if (multi==2){
                    if(match(\$0,/^$sm$/))
                        obuf=obuf \"\\\\n\";
                        else obuf=obuf \" \";
                }
                getline;
            }
            sub(/$sm$/,\"\",obuf);
            print obuf;
            multi=0;
            if(match(\$0,/$sm\|$sm$/)){multi=1; sub(/$sm\|$sm$/,\"\");}
            if(match(\$0,/$sm>$sm$/)){multi=2; sub(/$sm>$sm$/,\"\");}
        }
    print}" | \
    sed  -e "s|^\($s\)?|\1-|" \
        -ne "s|^$s#.*||;s|$s#[^\"']*$||;s|^\([^\"'#]*\)#.*|\1|;t1;t;:1;s|^$s\$||;t2;p;:2;d" | \
    sed -ne "s|,$s\]$s\$|]|" \
        -e ":1;s|^\($s\)\($w\)$s:$s\(&$w\)\?$s\[$s\(.*\)$s,$s\(.*\)$s\]|\1\2: \3[\4]\n\1$i- \5|;t1" \
        -e "s|^\($s\)\($w\)$s:$s\(&$w\)\?$s\[$s\(.*\)$s\]|\1\2: \3\n\1$i- \4|;" \
        -e ":2;s|^\($s\)-$s\[$s\(.*\)$s,$s\(.*\)$s\]|\1- [\2]\n\1$i- \3|;t2" \
        -e "s|^\($s\)-$s\[$s\(.*\)$s\]|\1-\n\1$i- \2|;p" | \
    sed -ne "s|,$s}$s\$|}|" \
        -e ":1;s|^\($s\)-$s{$s\(.*\)$s,$s\($w\)$s:$s\(.*\)$s}|\1- {\2}\n\1$i\3: \4|;t1" \
        -e "s|^\($s\)-$s{$s\(.*\)$s}|\1-\n\1$i\2|;" \
        -e ":2;s|^\($s\)\($w\)$s:$s\(&$w\)\?$s{$s\(.*\)$s,$s\($w\)$s:$s\(.*\)$s}|\1\2: \3 {\4}\n\1$i\5: \6|;t2" \
        -e "s|^\($s\)\($w\)$s:$s\(&$w\)\?$s{$s\(.*\)$s}|\1\2: \3\n\1$i\4|;p" | \
    sed  -e "s|^\($s\)\($w\)$s:$s\(&$w\)\(.*\)|\1\2:\4\n\3|" \
        -e "s|^\($s\)-$s\(&$w\)\(.*\)|\1- \3\n\2|" | \
    sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\(---\)\($s\)||" \
        -e "s|^\($s\)\(\.\.\.\)\($s\)||" \
        -e "s|^\($s\)-$s[\"']\(.*\)[\"']$s\$|\1$fs$fs\2|p;t" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p;t" \
        -e "s|^\($s\)-$s\(.*\)$s\$|\1$fs$fs\2|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\?\(.*\)$s\$|\1$fs\2$fs\3|" \
        -e "s|^\($s\)[\"']\?\([^&][^$fs]\+\)[\"']$s\$|\1$fs$fs$fs\2|" \
        -e "s|^\($s\)[\"']\?\([^&][^$fs]\+\)$s\$|\1$fs$fs$fs\2|" \
        -e "s|$s\$||p" | \
    awk -F$fs "{
        gsub(/\t/,\"        \",\$1);
        gsub(\"name: \", \"\");
        if(NF>3){if(value!=\"\"){value = value \" \";}value = value  \$4;}
        else {
        if(match(\$1,/^&/)){anchor[substr(\$1,2)]=full_vn;getline};
        indent = length(\$1)/length(\"$i\");
        vname[indent] = \$2;
        value= \$3;
        for (i in vname) {if (i > indent) {delete vname[i]; idx[i]=0}}
        if(length(\$2)== 0){  vname[indent]= ++idx[indent] };
        vn=\"\"; for (i=0; i<indent; i++) { vn=(vn)(vname[i])(\"$separator\")}
        vn=\"$prefix\" vn;
        full_vn=vn vname[indent];
        if(vn==\"$prefix\")vn=\"$prefix$separator\";
        if(vn==\"_\")vn=\"__\";
        }
        assignment[full_vn]=value;
        if(!match(assignment[vn], full_vn))assignment[vn]=assignment[vn] \" \" full_vn;
        if(match(value,/^\*/)){
            ref=anchor[substr(value,2)];
            if(length(ref)==0){
            printf(\"%s=\\\"%s\\\"\n\", full_vn, value);
            } else {
            for(val in assignment){
                if((length(ref)>0)&&index(val, ref)==1){
                    tmpval=assignment[val];
                    sub(ref,full_vn,val);
                if(match(val,\"$separator\$\")){
                    gsub(ref,full_vn,tmpval);
                } else if (length(tmpval) > 0) {
                    printf(\"%s=\\\"%s\\\"\n\", val, tmpval);
                }
                assignment[val]=tmpval;
                }
            }
        }
    } else if (length(value) > 0) {
        printf(\"%s=\\\"%s\\\"\n\", full_vn, value);
    }
    }END{
        for(val in assignment){
            if(match(val,\"$separator\$\"))
                printf(\"%s=\\\"%s\\\"\n\", val, assignment[val]);
        }
    }"

}

cert_parseYaml config.yml"
```
</details>

Using this script we could determine that the error was not located in the `cert_parseYaml` function.

After this, we determined that the error had to be located in the `cert_readConfig` function, and we located the error in the following lines:

https://github.com/wazuh/wazuh-packages/blob/4ea226db5e29ede078f86b3b799eb04b1a5bac84/unattended_installer/cert_tool/certFunctions.sh#L306-L324

The error appeared because the regex used in the grep commands only covered numbers from 0 to 9 to fix this we can extend the regex to:
```
grep "nodes_indexer_[0-9]+="
```

**Comment by davidcr01** [comment]
## Update Report

With this change, there is another problem with certificate generation. It seems the array of the server IPs is not initialized correctly and the script throws the error when creating the certificate for the 10th server node:
`01/12/2022 17:32:42 ERROR: No IP or DNS specified`

https://ci.wazuh.info/job/Test_unattended_distributed/257/

**Comment by DFolchA** [comment]
## Update 

Investigate the error described here:
https://github.com/wazuh/wazuh-packages/issues/1954#issuecomment-1334239234

We used the same test script to determine that the error was not related to the `parseYaml` function.

After investigating we determined that the error was located here:
https://github.com/wazuh/wazuh-packages/blob/4ea226db5e29ede078f86b3b799eb04b1a5bac84/unattended_installer/cert_tool/certFunctions.sh#L327-L328

And finally, we determined that the error was caused  by a wrong sed expression, so we fixed it by improving the regex used in the sed command:
https://github.com/wazuh/wazuh-packages/pull/1963/commits/c244ac958bf2664808509dc81653b2d75fbddab3
