### ISSUE TITLE
The Wazuh installation assistant does not show a message about uninstalling the Wazuh indexer

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1972]
## Description

When trying to install a `4.4.0 Alpha 1` All In One environment after manually uninstalling the Wazuh indexer, a message is displayed indicating that the Wazuh indexer is installed (probably because it did not remove certain directories), but when using the `-u` option of the `wazuh-install.sh` script, it can be seen that there is no informative message about the uninstallation or deletion of files related to the Wazuh indexer:

```
[root@centos7 vagrant]# yum remove wazuh-indexer.x86_64 
Loaded plugins: fastestmirror
Resolving Dependencies
--> Running transaction check
---> Package wazuh-indexer.x86_64 0:4.4.0-1 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================================================================================================================
 Package                                           Arch                                       Version                                     Repository                                                          Size
===================================================================================================================================================================================================================
Removing:
 wazuh-indexer                                     x86_64                                     4.4.0-1                                     @/wazuh-indexer-4.4.0-1.x86_64                                     644 M

Transaction Summary
===================================================================================================================================================================================================================
Remove  1 Package

Installed size: 644 M
Is this ok [y/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Stopping wazuh-indexer service... OK
  Erasing    : wazuh-indexer-4.4.0-1.x86_64                                                                                                                                                                    1/1 
  Verifying  : wazuh-indexer-4.4.0-1.x86_64                                                                                                                                                                    1/1 

Removed:
  wazuh-indexer.x86_64 0:4.4.0-1                                                                                                                                                                                   

Complete!
[root@centos7 vagrant]# curl -sO https://packages-dev.wazuh.com/4.4/wazuh-install.sh
[root@centos7 vagrant]# bash wazuh-install.sh -a
07/12/2022 18:55:47 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
07/12/2022 18:55:47 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/12/2022 18:55:48 ERROR: Wazuh indexer already installed.
07/12/2022 18:55:48 INFO: If you want to overwrite the current installation, run this script adding the option -o/--overwrite. This will erase all the existing configuration and data.
[root@centos7 vagrant]# bash wazuh-install.sh -u
07/12/2022 18:55:55 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
07/12/2022 18:55:55 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/12/2022 18:55:56 INFO: Wazuh manager not found in the system so it was not uninstalled.
07/12/2022 18:55:56 INFO: Filebeat not found in the system so it was not uninstalled.
07/12/2022 18:55:56 INFO: Wazuh dashboard not found in the system so it was not uninstalled.
07/12/2022 18:55:56 INFO: Wazuh GPG key not found in the system
```

Despite there being no informative message about the Wazuh indexer, the subsequent installation is successful.

In addition, the messages displayed with the following proposals should be reviewed:

- If you want to overwrite the current installation, run this script `by` adding the option -o/--overwrite.
- Wazuh manager `was` not found in the system so it was not uninstalled.
- Filebeat `was` not found in the system so it was not uninstalled.
- Wazuh dashboard `was` not found in the system so it was not uninstalled.
- Wazuh GPG key `was` not found in the system`.`

## Tasks

- [ ] Modify the wazuh-install.sh script to show information or error messages when this behavior occurs.
- [ ] Check the grammar of all messages displayed by the wazuh-install.sh script
- [ ] Check if this behavior is repeated with the Wazuh dashboard, Filebeat, and Wazuh server.

## Validation

- [ ] An information or error message is displayed when the Wazuh indexer is uninstalled using the wazuh-install.sh script.
- [ ] The grammar and spelling of the messages are correct.

**Comment by DFolchA** [comment]
## Update

- Fix the error causing the message not to show.
- Improve messages following suggestions.
- Test wazuh install.

**Comment by DFolchA** [comment]
On hold due to: https://github.com/wazuh/wazuh-packages/issues/1977

**Comment by davidjiglesias** [comment]
Does this replicate in v4.3.X?

**Comment by alberpilot** [comment]
No, it doesn't.
