### ISSUE TITLE
Error in URL of Filebeat template in master branch 

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2000]
## Description

This issue is created from this comment: https://github.com/wazuh/wazuh-packages/issues/1995#issuecomment-1355269385

To summarize, when the version to install is `4.5.0` (current master) the `wazuh-template.json` of Filebeat is downloaded but with the wrong content as the `https://raw.githubusercontent.com/wazuh/wazuh/4.5/extensions/elasticsearch/7.x/wazuh-template.json` URL does not exist.

![image](https://user-images.githubusercontent.com/72193239/208727128-acc2c5a4-b4bb-4c13-98ca-62ed18c3aa67.png)

It would be necessary to modify the `builder.sh` and change that URL in case of this error happens.

## Tasks

- [x] Identify the error.
- [ ] Fix the error.
- [ ] Validate fix.

## Validation

- [ ] The Filebeat template is downloaded with the right content in case of `4.5` branch.

**Comment by davidcr01** [comment]
## Update Report

To perform this new feature, I created a new function in the `builder.sh` script that checks the responses of the proposed URL, written in the `installVariables.sh`, and if it does not exists, change that URL to a new one, replacing the `${wazuh_major}` variable to `master` only if that new URL exist.

**Comment by davidcr01** [comment]
## Failing tests

**Test** https://github.com/wazuh/wazuh-packages/pull/2001/checks?check_run_id=10228640492 
- Centos8 failed because of a known issue https://github.com/wazuh/wazuh-jenkins/issues/4507
- Redhat8 and Ubuntu 20 (focal) failed because of `test_unattended.py::test_check_cluster_log_errors FAILED`.

After login into a Redhat8 machine and seeing the `cluster.log`, it seems that the error is produced by a problem connection that works after some retries.

```
2022/12/21 12:40:22 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2022/12/21 12:40:22 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2022/12/21 12:40:32 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2022/12/21 12:40:42 INFO: [Worker redhat_8-wazuh] [Main] Successfully connected to master.
2022/12/21 12:40:51 INFO: [Worker redhat_8-wazuh] [Integrity check] Starting.
2022/12/21 12:40:51 INFO: [Worker redhat_8-wazuh] [Integrity check] Finished in 0.071s. Sync required.
2022/12/21 12:40:51 INFO: [Worker redhat_8-wazuh] [Integrity sync] Starting.
```

With this, the Redhat8 worker is connected to its master, but the error is displayed because the `test_check_cluster_log_errors` function searches for an `ERROR` in the log file, but finally, the worker Redhat8 connects to the master node.

This behavior may seem aleatory because I executed the same pipeline on Jenkins several times an the error is produced sometimes in different machines.

<details><summary>Show screenshot</summary>

![image](https://user-images.githubusercontent.com/72193239/208921423-5de0e3ff-8fd2-49df-9154-348796a10ffc.png)

</details>

**Test** https://github.com/wazuh/wazuh-packages/pull/2001/checks?check_run_id=10228483518 (indexer) failed because it used the `pre-release` repository for unknown reasons. The test was re-launched using `staging` https://devel.ci.wazuh.info/job/Test_unattended_distributed/631/

For instance, in the Centos 7 machine (extracted from the previous link):
<details><summary>Show log</summary>

```
[2022-12-21T10:32:38.522Z] [0;33m        "centos_7-indexer",[0m


[2022-12-21T10:32:38.522Z] [0;33m21/12/2022 10:31:03 INFO: --- Wazuh indexer ---[0m
[2022-12-21T10:32:38.522Z] [0;33m21/12/2022 10:31:03 INFO: Starting Wazuh indexer installation.[0m
[2022-12-21T10:32:38.522Z] [0;33mLoaded plugins: fastestmirror[0m
[2022-12-21T10:32:38.522Z] [0;33mLoading mirror speeds from cached hostfile[0m
[2022-12-21T10:32:38.522Z] [0;33m * base: download.cf.centos.org[0m
[2022-12-21T10:32:38.522Z] [0;33m * epel: d2lzkl7pfhq30w.cloudfront.net[0m
[2022-12-21T10:32:38.522Z] [0;33m * extras: download.cf.centos.org[0m
[2022-12-21T10:32:38.522Z] [0;33m * updates: download.cf.centos.org[0m
[2022-12-21T10:32:38.522Z] [0;33mResolving Dependencies[0m
[2022-12-21T10:32:38.522Z] [0;33m--> Running transaction check[0m
[2022-12-21T10:32:38.522Z] [0;33m---> Package wazuh-indexer.x86_64 0:4.5.0-40500 will be installed[0m
[2022-12-21T10:32:38.522Z] [0;33m--> Finished Dependency Resolution[0m
[2022-12-21T10:32:38.522Z] [0;33m[0m
[2022-12-21T10:32:38.522Z] [0;33mDependencies Resolved[0m
[2022-12-21T10:32:38.522Z] [0;33m[0m
[2022-12-21T10:32:38.522Z] [0;33m================================================================================[0m
[2022-12-21T10:32:38.522Z] [0;33m Package               Arch           Version               Repository     Size[0m
[2022-12-21T10:32:38.522Z] [0;33m================================================================================[0m
[2022-12-21T10:32:38.522Z] [0;33mInstalling:[0m
[2022-12-21T10:32:38.522Z] [0;33m wazuh-indexer         x86_64         4.5.0-40500           wazuh         397 M[0m
[2022-12-21T10:32:38.522Z] [0;33m[0m
[2022-12-21T10:32:38.522Z] [0;33mTransaction Summary[0m
[2022-12-21T10:32:38.522Z] [0;33m================================================================================[0m
[2022-12-21T10:32:38.522Z] [0;33mInstall  1 Package[0m
[2022-12-21T10:32:38.522Z] [0;33m[0m
[2022-12-21T10:32:38.522Z] [0;33mTotal download size: 397 M[0m
[2022-12-21T10:32:38.522Z] [0;33mInstalled size: 644 M[0m
[2022-12-21T10:32:38.522Z] [0;33mDownloading packages:[0m
[2022-12-21T10:32:38.522Z] [0;33mRunning transaction check[0m
[2022-12-21T10:32:38.522Z] [0;33mRunning transaction test[0m
[2022-12-21T10:32:38.522Z] [0;33mTransaction test succeeded[0m
[2022-12-21T10:32:38.522Z] [0;33mRunning transaction[0m
[2022-12-21T10:32:38.522Z] [0;33m  Installing : wazuh-indexer-4.5.0-40500.x86_64                             1/1 [0m
[2022-12-21T10:32:38.522Z] [0;33mCreated opensearch keystore in /etc/wazuh-indexer/opensearch.keystore[0m
[2022-12-21T10:32:38.522Z] [0;33m  Verifying  : wazuh-indexer-4.5.0-40500.x86_64                             1/1 [0m
[2022-12-21T10:32:38.522Z] [0;33m[0m
[2022-12-21T10:32:38.522Z] [0;33mInstalled:[0m
[2022-12-21T10:32:38.522Z] [0;33m  wazuh-indexer.x86_64 0:4.5.0-40500                                            [0m
[2022-12-21T10:32:38.522Z] [0;33m[0m
[2022-12-21T10:32:38.522Z] [0;33mComplete![0m
[2022-12-21T10:32:38.522Z] [0;33m21/12/2022 10:32:03 INFO: Wazuh indexer installation finished.[0
```
<details>

**Comment by davidcr01** [comment]
## Update Report

Currently working on some changes to the new function after talking about it with the @wazuh/cicd. The new approach consists in:
- Avoid loading the entire `installVariable.sh` file by fetching the necessary variables with the `grep` command.
- Avoid hardcoding the `new_filebeat_url` variable by setting it with the `sed` command.
- Improving the regex of the existing `sed` command.

**Comment by DFolchA** [comment]
## Update 

Found error with building wazuh install:
```
dfolcha@pop-os:~/wazuh-packages/unattended_installer$ ./builder.sh -i -d
/home/dfolcha/wazuh-packages/unattended_installer/install_functions/installVariables.sh: line 18: base_path: readonly variable
Changing Filebeat URL...

```

Changed variable name to solve it:
[8b98b00](https://github.com/wazuh/wazuh-packages/pull/2001/commits/8b98b000428fd6efebb97e3a79ee2146ff022cef)

Revert changes in `installVariables` at the end of `builder.sh` if necessary:
https://github.com/wazuh/wazuh-packages/pull/2001/commits/822fa51f81feef4fda8c50794f4ca923012ede20

**Comment by davidcr01** [comment]
This issue goes to Blocked until https://github.com/wazuh/wazuh/issues/15802 is closed and merged.
