### ISSUE TITLE
Graphical error in `Windows XP` Wazuh agent

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2005]
## Description

The Wazuh agent shows a `dot` next to the `Help` tab on `Windows XP`, this is not seen in `Windows 7` and later systems

![UI](https://user-images.githubusercontent.com/14913942/209239735-481ec0a6-a49d-4af5-a4b9-d5bbd0bfa13e.png)
![UI](https://user-images.githubusercontent.com/14913942/209239737-389e5df0-1f41-404a-92f4-5df96004c9e8.png)

It is necessary to determine the origin of this graphic error and fix it.

## Tasks

- [ ] Investigate the origin and cause of this error.
- [ ] Fix the Wazuh agent UI to be similar to other systems.
- [ ] Validate changes.

## Validation

- [ ] Wazuh agent UI does not show the `dot` next to the `Help` tab.
- [ ] All systems (Windows XP to Windows server 2022) show the same UI without errors.
