### ISSUE TITLE
Change the build number of the Wazuh dashboard packages.json with the same as the Wazuh plugin

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#2012]
## Description
It is necessary that the build number of the Wazuh dashboard packages.json matches that of the Wazuh plugin, for this, it is necessary to modify the construction of the base to remove the lines:
https://github.com/wazuh/wazuh-packages/blob/ee55f21fed27ecfa9603a3523854ac99a3a2f101/stack/dashboard/base/builder.sh#L128-L130

and move them to the specs to be done after the plugin installation

## Tasks

- [x] Remove lines from the base builder
- [x] Obtain the version and revision numbers from /usr/share/wazuh-dashboard/plugins/wazuh/package.json
- [x] Remove . from version number and concatenate with revision number
- [x] Replace build number with the new parameter in /usr/share/wazuh-dashboard/package.json
- [x] Do this steps in rpm and deb packages

## Validation

- [x] Verify that the build number of the Wazuh dashboard packages.json matches the version and revision numbers of the Wazuh plugin packages.json

**Comment by c-bordon** [comment]
## Update Report

### Tasks
- I am working on the modification so that the build number parameter is assigned in the deb rules, but I am having many problems doing it in a simple way
- The first intention was to keep the command as it was done in the base, but this generated problems since the execution of commands within the same line are not allowed within the rules:
![Screenshot_20221230_154445](https://user-images.githubusercontent.com/64099752/210102794-2e854f18-d84e-449a-8c8e-d3a0c02cda2c.png)
- I had to split the commands by lines and save the outputs in a temporary file:
```console
	jq -r '.version' $(TARGET_DIR)$(INSTALLATION_DIR)/plugins/wazuh/package.json | tr -d '.' >> $(TARGET_DIR)$(INSTALLATION_DIR)/tmp2.txt
	jq -r '.revision' $(TARGET_DIR)$(INSTALLATION_DIR)/plugins/wazuh/package.json >> $(TARGET_DIR)$(INSTALLATION_DIR)/tmp.txt
	tr -d '\n' < $(TARGET_DIR)$(INSTALLATION_DIR)/tmp.txt >> $(TARGET_DIR)$(INSTALLATION_DIR)/tmp2.txt
	cat $(TARGET_DIR)$(INSTALLATION_DIR)/tmp2.txt
	jq --slurpfile BUILD_NUMBER $(TARGET_DIR)$(INSTALLATION_DIR)/tmp2.txt '.build.number=${BUILD_NUMBER}' $(TARGET_DIR)$(INSTALLATION_DIR)/package.json > $(TARGET_DIR)$(INSTALLATION_DIR)/package.json.tmp
	mv $(TARGET_DIR)$(INSTALLATION_DIR)/package.json.tmp $(TARGET_DIR)$(INSTALLATION_DIR)/package.json
	rm -f $(TARGET_DIR)$(INSTALLATION_DIR)/tmp.txt $(TARGET_DIR)$(INSTALLATION_DIR)/tmp2.txt
```
- This at the moment doesn't work as the variable is not known, I need to give it some additional correction

**Comment by c-bordon** [comment]
## Update Report

### Tasks
- I was doing various tests in adapting this change in the DEB package and I ran into many problems that made me change the approach and move the installation of the dashboard app to the base.
The problem occurred with the debian rules, since inside override_dh_install I can't execute commands inside other commands, example var=$(command) since $() are used for variables.

This command cannot be executed:
```
jq ".build.number=$(jq -r '.version' ./plugins/wazuh/package.json | tr -d '.')$(jq -r '.revision' ./plugins/wazuh/package. json)" ./package.json > ./package.json.tmp
```
- Look into some workarounds like saving the output of intermediate commands to get the version and revision and then trying to read the value obtained from the app by reading a file but it doesn't work
I was trying to use the `--argfile variable-name filename` option 
- But this does not work because the intermediate variable used by jq is not loaded, after trying different options and not being able to obtain the desired result, I decided to move all this to the moment of building the database. In this way, I was able to assemble the packages as expected
- This new approach means that we must update the images used in S3 to build the packages in Jenkins and then we will have to see what changes are necessary to make in Docker and Cloud
- After installing the packages I found the same cache error message, so I'm checking with the frontend team to validate if the solution is correct:
![Screenshot_20230102_145439](https://user-images.githubusercontent.com/64099752/210267658-f115dab5-3fad-4ce1-8669-e6aaa5fb4525.png)

![Screenshot_20230102_145115](https://user-images.githubusercontent.com/64099752/210267667-3ba43e64-0ac4-47fe-aba5-74719fda6445.png)

```console
root@ubuntu20:~# cat /usr/share/wazuh-dashboard/package.json 
{
  "name": "opensearch-dashboards",
  "description": "OpenSearch Dashboards is a browser based analytics and search dashboard for OpenSearch. OpenSearch Dashboards is a snap to setup and start using. OpenSearch Dashboards strives to be easy to get started with, while also being flexible and powerful, just like OpenSearch.",
  "keywords": [
    "opensearch-dashboards",
    "opensearch",
    "logstash",
    "analytics",
    "visualizations",
    "dashboards",
    "dashboarding"
  ],
  "version": "2.4.1",
  "branch": "2.4",
  "build": {
    "number": 44000,
    "sha": "ea36827cdedf1e726e7cb8315ffc49f73f9b4eb7",
    "distributable": true,
    "release": true
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/opensearch-project/opensearch-dashboards.git"
  },
  "engines": {
    "node": "14.20.0"
  }
}
```

**Comment by c-bordon** [comment]
On Hold: Waiting for response from the Frontend team

**Comment by c-bordon** [comment]
After checking with the frontend team, they told me that the revision change has to be done in 2 files in the app, after executing changes and testing the error keeps appearing, I attach the results:

/usr/share/wazuh-dashboard/package.json 
```console
{
  "name": "opensearch-dashboards",
  "description": "OpenSearch Dashboards is a browser based analytics and search dashboard for OpenSearch. OpenSearch Dashboards is a snap to setup and start using. OpenSearch Dashboards strives to be easy to get started with, while also being flexible and powerful, just like OpenSearch.",
  "keywords": [
    "opensearch-dashboards",
    "opensearch",
    "logstash",
    "analytics",
    "visualizations",
    "dashboards",
    "dashboarding"
  ],
  "version": "2.4.1",
  "branch": "2.4",
  "build": {
    "number": 44000,
    "sha": "ea36827cdedf1e726e7cb8315ffc49f73f9b4eb7",
    "distributable": true,
    "release": true
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/opensearch-project/opensearch-dashboards.git"
  },
  "engines": {
    "node": "14.20.0"
  }
}
```

/usr/share/wazuh-dashboard/plugins/wazuh/opensearch_dashboards.json 
```console
{
  "id": "wazuh",
  "version": "4.4.0-00",
  "opensearchDashboardsVersion": "2.4.1",
  "configPath": [
    "wazuh"
  ],
  "requiredPlugins": [
    "navigation",
    "data",
    "discover",
    "inspector",
    "visualizations",
    "uiActions",
    "charts",
    "savedObjects",
    "opensearchDashboardsReact",
    "opensearchDashboardsUtils",
    "opensearchDashboardsLegacy"
  ],
  "optionalPlugins": [
    "security",
    "securityDashboards",
    "searchguard",
    "telemetry"
  ],
  "server": true,
  "ui": true
}
```

/usr/share/wazuh-dashboard/plugins/wazuh/package.json 
```console
{
  "name": "wazuh",
  "version": "4.4.0",
  "revision": "00",
  "code": "alpha2",
  "pluginPlatform": {
    "version": "2.4.1"
  },
  "description": "Wazuh dashboard",
  "keywords": [
    "opensearch_dashboards",
    "wazuh",
    "ossec"
  ],
  "node_build": "10.23.1",
  "author": "Wazuh, Inc",
  "license": "GPL-2.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/wazuh/wazuh-kibana-app.git"
  },
  "bugs": {
    "url": "https://github.com/wazuh/wazuh-kibana-app/issues"
  },
  "homepage": "https://www.wazuh.com/",
  "scripts": {
    "lint": "eslint {public,server,common}/**/*.{js,jsx,ts,tsx,json}",
    "lint:public": "eslint public/**/*.{js,jsx,ts,tsx,json}",
    "lint:server": "eslint server/**/*.{js,jsx,ts,tsx,json}",
    "lint:common": "eslint common/**/*.{js,jsx,ts,tsx,json}",
    "lint:fix": "eslint --fix '{public,server,common}/**/*.{js,jsx,ts,tsx,json}'",
    "format": "prettier --write '{public,server,common}/**/*.{js,jsx,ts,tsx,css,md,json}' --config ./.prettierrc",
    "kbn": "node ../../scripts/kbn",
    "es": "node ../../scripts/es",
    "start": "plugin-helpers start",
    "build": "yarn plugin-helpers build --opensearch-dashboards-version=$OPENSEARCH_DASHBOARDS_VERSION",
    "plugin-helpers": "node ../../scripts/plugin_helpers",
    "test:ui:runner": "node ../../scripts/functional_test_runner.js",
    "test:server": "plugin-helpers test:server",
    "test:browser": "plugin-helpers test:browser",
    "test:jest": "node scripts/jest",
    "generate:api-4.0-info": "cd scripts/generate-api-4.0-info;./generate-api-4.0-info.sh;cd ../..",
    "prebuild": "node scripts/generate-build-version"
  },
  "dependencies": {
    "angular-animate": "1.7.8",
    "angular-material": "1.1.18",
    "axios": "^0.21.1",
    "install": "^0.10.1",
    "js2xmlparser": "^3.0.0",
    "json2csv": "^4.1.2",
    "jwt-decode": "^2.2.0",
    "loglevel": "^1.7.1",
    "markdown-it-link-attributes": "^3.0.0",
    "md5": "^2.3.0",
    "needle": "^2.0.1",
    "node-cron": "^1.1.2",
    "pdfmake": "0.2.6",
    "pug-loader": "^2.4.0",
    "querystring-browser": "1.0.4",
    "react-codemirror": "^1.0.0",
    "react-cookie": "^4.0.3",
    "read-last-lines": "^1.7.2",
    "timsort": "^0.3.0",
    "typescript": "^4.4.2",
    "winston": "3.5.1"
  },
  "devDependencies": {
    "@types/node-cron": "^2.0.3",
    "@typescript-eslint/eslint-plugin": "^5.38.1",
    "@typescript-eslint/parser": "^5.38.1",
    "eslint": "^8.24.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-typescript": "2.7.1",
    "eslint-plugin-async-await": "^0.0.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-filenames-simple": "^0.7.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.31.8",
    "eslint-plugin-react-hooks": "^4.6.0",
    "prettier": "^2.7.1",
    "redux-mock-store": "^1.5.4",
    "tslint": "^5.11.0",
    "typescript-eslint-parser": "^18.0.0"
  },
  "opensearchDashboards": {
    "version": "2.4.1"
  }
}
```

![image](https://user-images.githubusercontent.com/64099752/210614536-2268abf9-7607-4741-83ad-cf0e46cdb86d.png)

**Comment by c-bordon** [comment]
Blocked: Waiting for response from the https://github.com/orgs/wazuh/teams/frontend team

**Comment by c-bordon** [comment]
## Update Report

### Tasks
- Development and testing is resumed with a new zip provided by the frontend team. Tests are being carried out with this package to validate that the cache problems have been mitigated:
![image](https://user-images.githubusercontent.com/64099752/213291422-0637eccf-a576-40e8-9b59-7e11d5de37cd.png)
![image](https://user-images.githubusercontent.com/64099752/213291437-1e0bbe50-f6c1-42ec-8017-cde34424d090.png)
![image](https://user-images.githubusercontent.com/64099752/213291452-bfa1fab6-a8da-4b02-9771-ed448eaae91c.png)
![image](https://user-images.githubusercontent.com/64099752/213291493-bfd345b4-3eac-4974-925d-afb7e0c34b52.png)

```console
root@ubuntu20:~# cat /usr/share/wazuh-dashboard/package.json 
{
  "name": "opensearch-dashboards",
  "description": "OpenSearch Dashboards is a browser based analytics and search dashboard for OpenSearch. OpenSearch Dashboards is a snap to setup and start using. OpenSearch Dashboards strives to be easy to get started with, while also being flexible and powerful, just like OpenSearch.",
  "keywords": [
    "opensearch-dashboards",
    "opensearch",
    "logstash",
    "analytics",
    "visualizations",
    "dashboards",
    "dashboarding"
  ],
  "version": "2.4.1",
  "branch": "2.4",
  "build": {
    "number": 44001,
    "sha": "ea36827cdedf1e726e7cb8315ffc49f73f9b4eb7",
    "distributable": true,
    "release": true
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/opensearch-project/opensearch-dashboards.git"
  },
  "engines": {
    "node": "14.20.0"
  }
}
```

### Next steps
- I'm working on building the rpm package, at the moment I'm running into some problems with jq:

```console
+ jq-linux64 '.build.number=%{buildnumber}' /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.4.0-1.x86_64/usr/share/wazuh-dashboard/package.json
jq: error: syntax error, unexpected '%' (Unix shell quoting issues?) at <top-level>, line 1:
.build.number=%{buildnumber}              
jq: 1 compile error
error: Bad exit status from /var/tmp/rpm-tmp.HwleD0 (%install)

```
