### ISSUE TITLE
The Wazuh Manager package can not be removed after reinstallation

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2024]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.5.0 | All-In-One | Install/Reinstall | Ubuntu 18 |

## Description

Note: **This problem has been detected in Ubuntu 18, but may be reproduced in other systems.**

It has been found an error when trying to remove the `wazuh-manager` package after an install/re-install of an All In One installation of Wazuh through the Installation Assistant.
The error is:
```
root@vagrant:/home/vagrant# dpkg --remove wazuh-manager
(Reading database ... 61252 files and directories currently installed.)
Removing wazuh-manager (4.5.0-40500) ...
+ DIR=/var/ossec
+ command -v systemctl
+ systemctl
+ systemctl is-active --quiet wazuh-manager
+ command -v service
+ service wazuh-manager status
+ grep running
+ service wazuh-manager stop
+ /var/ossec/bin/wazuh-control stop
dpkg: error processing package wazuh-manager (--remove):
 installed wazuh-manager package pre-removal script subprocess returned error exit status 127
Errors were encountered while processing:
 wazuh-manager
root@vagrant:/home/vagrant# 
```
## Steps to reproduce

1. Install all the components of Wazuh with the Installation Assistant using the AIO option `(-a)`
<details><summary>Show log</summary>

```
root@vagrant:/home/vagrant# bash wazuh-install.sh -a -i
10/01/2023 08:46:11 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.0
10/01/2023 08:46:11 INFO: Verbose logging redirected to /var/log/wazuh-install.log
10/01/2023 08:46:14 WARNING: Hardware and system checks ignored.
10/01/2023 08:46:30 INFO: Wazuh development repository added.
10/01/2023 08:46:30 INFO: --- Configuration files ---
10/01/2023 08:46:30 INFO: Generating configuration files.
10/01/2023 08:46:31 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
10/01/2023 08:46:31 INFO: --- Wazuh indexer ---
10/01/2023 08:46:31 INFO: Starting Wazuh indexer installation.
10/01/2023 08:47:14 INFO: Wazuh indexer installation finished.
10/01/2023 08:47:14 INFO: Wazuh indexer post-install configuration finished.
10/01/2023 08:47:14 INFO: Starting service wazuh-indexer.
10/01/2023 08:47:33 INFO: wazuh-indexer service started.
10/01/2023 08:47:33 INFO: Initializing Wazuh indexer cluster security settings.
10/01/2023 08:47:43 INFO: Wazuh indexer cluster initialized.
10/01/2023 08:47:43 INFO: --- Wazuh server ---
10/01/2023 08:47:43 INFO: Starting the Wazuh manager installation.
10/01/2023 08:48:35 INFO: Wazuh manager installation finished.
10/01/2023 08:48:35 INFO: Starting service wazuh-manager.
10/01/2023 08:48:56 INFO: wazuh-manager service started.
10/01/2023 08:48:56 INFO: Starting Filebeat installation.
10/01/2023 08:49:14 INFO: Filebeat installation finished.
10/01/2023 08:49:16 INFO: Filebeat post-install configuration finished.
10/01/2023 08:49:16 INFO: Starting service filebeat.
10/01/2023 08:49:17 INFO: filebeat service started.
10/01/2023 08:49:17 INFO: --- Wazuh dashboard ---
10/01/2023 08:49:17 INFO: Starting Wazuh dashboard installation.
10/01/2023 08:51:30 INFO: Wazuh dashboard installation finished.
10/01/2023 08:51:30 INFO: Wazuh dashboard post-install configuration finished.
10/01/2023 08:51:30 INFO: Starting service wazuh-dashboard.
10/01/2023 08:51:31 INFO: wazuh-dashboard service started.
10/01/2023 08:52:14 INFO: Initializing Wazuh dashboard web application.
10/01/2023 08:52:15 INFO: Wazuh dashboard web application initialized.
10/01/2023 08:52:15 INFO: --- Summary ---
10/01/2023 08:52:15 INFO: You can access the web interface https://<wazuh-dashboard-ip>
    User: admin
    Password: WULMt5+GtjCWyezy2QV+yMVuXWpajHU2
10/01/2023 08:52:15 INFO: Installation finished.
```
</details>

2. Reinstall it with the overwrite option `(-o)` and cancel the installation when the Wazuh Manager is installing. Confirm the removal of the installation when asked.

```
root@vagrant:/home/vagrant# bash wazuh-install.sh -a -o -i
10/01/2023 08:55:16 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.0
10/01/2023 08:55:16 INFO: Verbose logging redirected to /var/log/wazuh-install.log
10/01/2023 08:55:22 INFO: --- Removing existing Wazuh installation ---
10/01/2023 08:55:22 INFO: Removing Wazuh manager.
10/01/2023 08:55:36 INFO: Wazuh manager removed.
10/01/2023 08:55:36 INFO: Removing Wazuh indexer.
10/01/2023 08:55:42 INFO: Wazuh indexer removed.
10/01/2023 08:55:42 INFO: Removing Filebeat.
10/01/2023 08:55:48 INFO: Filebeat removed.
10/01/2023 08:55:48 INFO: Removing Wazuh dashboard.
10/01/2023 08:55:59 INFO: Wazuh dashboard removed.
10/01/2023 08:55:59 INFO: Installation cleaned.
10/01/2023 08:55:59 WARNING: Hardware and system checks ignored.
10/01/2023 08:56:14 INFO: Wazuh development repository added.
10/01/2023 08:56:14 INFO: --- Configuration files ---
10/01/2023 08:56:14 INFO: Generating configuration files.
10/01/2023 08:56:15 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
10/01/2023 08:56:15 INFO: --- Wazuh indexer ---
10/01/2023 08:56:15 INFO: Starting Wazuh indexer installation.
10/01/2023 08:57:01 INFO: Wazuh indexer installation finished.
10/01/2023 08:57:01 INFO: Wazuh indexer post-install configuration finished.
10/01/2023 08:57:01 INFO: Starting service wazuh-indexer.
10/01/2023 08:57:20 INFO: wazuh-indexer service started.
10/01/2023 08:57:20 INFO: Initializing Wazuh indexer cluster security settings.
10/01/2023 08:57:30 INFO: Wazuh indexer cluster initialized.
10/01/2023 08:57:30 INFO: --- Wazuh server ---
10/01/2023 08:57:30 INFO: Starting the Wazuh manager installation.

Do you want to remove the ongoing installation?[Y/N]Y
10/01/2023 08:58:34 INFO: --- Removing existing Wazuh installation ---
10/01/2023 08:58:34 INFO: Removing Wazuh indexer.
10/01/2023 08:58:44 INFO: Wazuh indexer removed.
10/01/2023 08:58:44 INFO: Installation cleaned.
```

3. Try to remove the `wazuh-manager` package using either `apt` or `dpkg` commands. 

```
root@vagrant:/home/vagrant# dpkg --remove wazuh-manager
(Reading database ... 61252 files and directories currently installed.)
Removing wazuh-manager (4.5.0-40500) ...
dpkg: error processing package wazuh-manager (--remove):
 installed wazuh-manager package pre-removal script subprocess returned error exit status 127
Errors were encountered while processing:
 wazuh-manager
root@vagrant:/home/vagrant# 
```

If the `set -x` command is added to the `prerm` file of the Wazuh Manager `(/var/lib/dpkg/info/wazuh-manager.prerm)` we noticed that the line which is failing is `/var/ossec/bin/wazuh-control stop`

```
root@vagrant:/home/vagrant# dpkg --remove wazuh-manager
(Reading database ... 61252 files and directories currently installed.)
Removing wazuh-manager (4.5.0-40500) ...
+ DIR=/var/ossec
+ command -v systemctl
+ systemctl
+ systemctl is-active --quiet wazuh-manager
+ command -v service
+ service wazuh-manager status
+ grep running
+ service wazuh-manager stop
+ /var/ossec/bin/wazuh-control stop
dpkg: error processing package wazuh-manager (--remove):
 installed wazuh-manager package pre-removal script subprocess returned error exit status 127
Errors were encountered while processing:
 wazuh-manager
```

So, the error is that the `wazuh-control` module has been deleted and the removal of the Wazuh Manager package can not be done.

## Tasks

- [x] Identify the error.
- [ ] Fix the error.
- [ ] Validate fix.

## Validation

- [ ] The `wazuh-control` is not removed after the re-installation and the package can be removed.

**Comment by DFolchA** [comment]
## Update

Reproduce the error and investigate causes.

The error appears if the user stops the script while the installation of a package is in progress leaving the package half installed. This causes the package manager to not recognize the package as installed so it is not completely removed.

A possible solution would be to force the script to finish all installations before stopping with a `cntrl+c` we have been testing this solution.

**Comment by DFolchA** [comment]
## Update

**Identify the cause of the error**: The error appeared because if we stop the installation of wazuh-manager halfway in DEB systems the package is considered as installed by APT. Still, the status inside the script has not been updated which leaves a broken installation.

We have fixed the error by using the function `common_checkInstalled` before running `installCommon_rollBack` in the trap function.

**Comment by DFolchA** [comment]
## Update

**Identified new cause of the error:** Some files from `wazuh-indexer` package were not being deleted when uninstalling leading to the script detecting them in subsequent installation attempts and causing the error.

Add necessary changes to delete them to the rollback function.
46677985d257bb300b8d0b96bab4cfd3d5a87dc5

Test the resulting script and verify that the error no longer appears.
