### ISSUE TITLE
Wazuh Windows agent does not update the Status field correctly

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2027]
## Description

- Detected in 4.4.0 Alpha 2, this behavior has also been reproduced in 4.3.10.

- An unwanted behavior has been found in the graphical interface of the Wazuh agent for Windows. When using the `Manage` tab options, the following behaviors are observed regarding the `Status` field:
  - Status: Not Running -> (Manage/Start)
    - Status remains at `Not Running` -> (`Refresh`) -> Status: `Running`
  - Status: Running -> (Manage/Stop)
    - Status changed from `Running` to `Stopped`
  - Status: Stopped -> (Manage/Start)
    - Status remains at `Stopped` -> (`Refresh`) -> Status: `Running`
  - Status: Running -> (Manage/Restart)
    - Status changes to `Stopped`, but does not change to `Running` again -> (`Refresh`) -> Status: `Running`
    
- The `Status` field should reflect the state of the agent at all times without the need to use the `Refresh` button, in the same way, that it is updated when using `Stop`, an agent that is started or restarted must end up in a `Running` state regardless of the initial state.

- This behavior can be observed in the following video:

https://user-images.githubusercontent.com/14913942/211573734-8e6b3d18-c873-4bff-a24d-8eb79e34f4bf.mp4

## Tasks

- [ ] Analyze the cause of the status not being updated when using the `Start` or `Restart` option.
- [ ] Analyze why the status is updated when using the `Stop` option.
- [ ] Modify the behavior so that all options correctly update the desired state.

## Validation

- [ ] All the options to modify the agent's status correctly update the final value of the `Status` field.

**Comment by vikman90** [comment]
@rauldpm I cannot reproduce this issue.

![image](https://github.com/wazuh/wazuh-packages/assets/10536251/2fca15ba-8f90-4911-a980-9004adaf810b)
![image](https://github.com/wazuh/wazuh-packages/assets/10536251/932926be-d114-4776-beef-97c515963f7d)

This might be a performance/timing issue.

**Comment by rauldpm** [comment]
@vikman90 Maybe fixed in 4.4.3? I reported it in 4.4.0

It could be performance, it's a Vagrant machine with 4GB of RAM and 2CPU, and the box is `mwrock/Windows2016`

**Comment by vikman90** [comment]
@rauldpm We will check it once again, but I suspect it's a performance issue.

The "Start" action of the UI performs these actions:
1. Start the agent. Show a modal error panel if the startup fails.
2. Immediately after, check the service status. 

In some circumstances, it's possible that the UI checks the service status before it's completely up. That's why it works if you click "Refresh".
