### ISSUE TITLE
Error in the offline installation using the staging repository

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2043]
## Description
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.5.0| Offline Installation | Install | Ubuntu 18 |

Note: **This problem has been detected in Ubuntu 18, but may be reproduced in other systems.**

An error following the steps of the Wazuh offline installation has been found. It seems when the `wazuh-install.sh` script is built with the `-d staging` option, the packages specified in the script do not download correctly as they do not exist in that repository (`-1` revision).

## Steps to reproduce

1. Generate the `wazuh-install.sh` with the `-d staging` option.
```
bash builder.sh -i -d staging
```

2. Execute the script with the offline installation option.

```
root@vagrant:/home/vagrant# bash wazuh-install.sh -dw deb
13/01/2023 19:02:40 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.0
13/01/2023 19:02:40 INFO: Verbose logging redirected to /var/log/wazuh-install.log
13/01/2023 19:02:42 INFO: --- Download Packages ---
13/01/2023 19:02:42 INFO: Starting Wazuh packages download.
13/01/2023 19:02:42 INFO: Downloading Wazuh deb packages for x86_64.
13/01/2023 19:02:44 INFO: The manager package was downloaded.
13/01/2023 19:02:52 INFO: The filebeat package was downloaded.
13/01/2023 19:02:52 INFO: The indexer package was downloaded.
13/01/2023 19:02:52 INFO: The dashboard package was downloaded.
13/01/2023 19:02:52 INFO: The packages are in wazuh-offline/wazuh-packages
13/01/2023 19:02:52 INFO: Downloading configuration files and assets.
13/01/2023 19:02:53 INFO: The resource https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH was downloaded.
13/01/2023 19:02:54 INFO: The resource https://packages-dev.wazuh.com/4.5/tpl/wazuh/filebeat/filebeat.yml was downloaded.
13/01/2023 19:02:54 INFO: The resource https://raw.githubusercontent.com/wazuh/wazuh/master/extensions/elasticsearch/7.x/wazuh-template.json was downloaded.
13/01/2023 19:02:55 INFO: The resource https://packages-dev.wazuh.com/staging/filebeat/wazuh-filebeat-0.2.tar.gz was downloaded.
13/01/2023 19:02:55 INFO: The configuration files and assets are in wazuh-offline.tar.gz
13/01/2023 19:02:56 INFO: You can follow the installation guide here https://documentation.wazuh.com/current/deployment-options/offline-installation.html
root@vagrant:/home/vagrant#
```

3. Follow the steps of the documentation: download and edit `config.yml`, generate the certificates, and decompress files.
```
root@vagrant:/home/vagrant# curl -sO https://packages.wazuh.com/4.3/config.yml
root@vagrant:/home/vagrant# nano config.yml 
root@vagrant:/home/vagrant# curl -sO https://packages.wazuh.com/4.3/wazuh-certs-tool.sh
root@vagrant:/home/vagrant# chmod 744 wazuh-certs-tool.sh
root@vagrant:/home/vagrant# ./wazuh-certs-tool.sh --all
13/01/2023 19:06:21 INFO: Admin certificates created.
13/01/2023 19:06:21 INFO: Wazuh indexer certificates created.
13/01/2023 19:06:21 INFO: Wazuh server certificates created.
13/01/2023 19:06:21 INFO: Wazuh dashboard certificates created.
root@vagrant:/home/vagrant# tar xf wazuh-offline.tar.gz
```
4. Try to install the `wazuh-indexer` package (or any package).
```
dpkg -i ./wazuh-offline/wazuh-packages/wazuh-indexer*.deb
dpkg-deb: error: './wazuh-offline/wazuh-packages/wazuh-indexer_4.5.0-1_amd64.deb' is not a Debian format archive
dpkg: error processing archive ./wazuh-offline/wazuh-packages/wazuh-indexer_4.5.0-1_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 ./wazuh-offline/wazuh-packages/wazuh-indexer_4.5.0-1_amd64.deb
root@vagrant:/home/vagrant# 
```

This error is generated because the packages with revision `-1` do not exist in the `staging` repository. If we check the content of the packages we can see they are not correct.

```
root@vagrant:/home/vagrant/wazuh-offline/wazuh-packages# cat wazuh-indexer_4.5.0-1_amd64.deb 
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>staging/apt/pool/main/w/wazuh-indexer/wazuh-indexer_4.5.0-1_amd64.deb</Key><RequestId>VSWMFQZGRQ3YAEZH</RequestId><HostId>gMPd/XBYK8R3fY+v9vb70wrM5J0hr60udUA6FsJZrqTE0K5NnR0FjgNQmC1tAKNfvkwK/jHAltY=</HostId></Error>
```

Besides, in the second step, no error is displayed in the process although the packages are downloading with the wrong content.

## Tasks

- [x] Identify the error.
- [ ] Fix the error.
- [ ] Validate fix.

## Validation

- [ ] The packages are downloaded correctly using the `staging` repository.

**Comment by davidcr01** [comment]
# Update Report

## Workaround

After some testing and several tries, I have encountered the problem that `curl` does not support wildcards. This causes the WIA can not perform a curl such as:
```console
curl -O https://packages-dev.wazuh.com/staging/apt/pool/main/w/wazuh-manager/wazuh-manager_4.7.0-*_amd64.deb
```

Currently, the offline installation downloads the packages of the higher revision possible. In the case of staging, this repository has the packages with revision (-M.RRRRR.YYYYMMDD), where the "M" is the minor version, the "R" is the revision, and the "YYYYMMDD" is the date of creation of the package.

With this structure, it seems impossible to fetch a package with any revision and the specified version of the WIA, as the exact name is needed. 

## Conclusion

After discussing it with the team, we have reached the conclusion that fetching the staging packages in the Offline Installation is not very important. Taking into account that the staging repository is used for testing, the aim of the Offline Installation is to check the correct functionality of the offline task, but not the packages installed.

With this, it is not recommended to use the staging repository when testing the offline installation. Instead, use the pre-release packages.
