### ISSUE TITLE
Improve the checks of curl while downloading big resources

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2049]
## Description

I noticed that some curl commands that fetch resources with a significant size can be improved.

For example, in the offline installation, the current script:
1. Checks the viability of the resource by downloading it completely and checking the HTTP code response.
  `curl -s -o /dev/null -w "%{http_code}" "${manager_base_url}/${manager_package}" | grep -q "200"`

2. Later, the package is downloaded again and stored in a file
  `eval "curl -so ${dest_path}/${!package_name} ${!package_base_url}/${!package_name}"`

With this, the resource is downloaded twice. This does not concern only the Offline installation but **any `curl` command** that fetches a big resource.

### Proposed solution

The proposed solution is to make a HEAD request to the resource to check the viability instead of a GET request. This can be achieved with the `-I` option or the `--head` option of the `curl` command. For instance:

```
if curl -s -I -w '%{http_code}' https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.4.0-1.x86_64.rpm | grep -q "200"; then 
  curl -so /wazuh-offline/wazuh-packages/wazuh-manager-4.4.0-1.x86_64.rpm https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.4.0-1.x86_64.rpm
fi
```
With this, the time of installation could be reduced significantly.

## Tasks

- [x] Search for an improvement.
- [ ] Apply the improvement.
- [ ] Validate the improvement.

## Validation

- [ ] The resources are downloaded correctly checking their viability without downloading them several times.

**Comment by davidcr01** [comment]
## Update Report

I have found that the Offline installation is the only one that fetches big resources with the `curl` command.

Because of the lack of an automatic test, a GitHub action will be created to test the Offline installation both in RPM and DEB systems.

**Comment by davidcr01** [comment]
## Update Report

I am currently working on the GitHub action of the Offline installation. I have achieved an initial version of it. This action will be modularized and adapted to both DEB and RPM systems. This action is based on the documentation of the Offline Installation: https://documentation.wazuh.com/current/deployment-options/offline-installation.html

**Action:**
https://github.com/wazuh/wazuh-packages/blob/4f0b2eed9ad6350ae657509aa0a05f36c033ac26/.github/actions/offline-installation/offline-installation.sh

**Comment by davidcr01** [comment]
## Update Report

The GitHub action has improved significantly. It is split into two scripts:
- `common.sh`: it contains all the functions to achieve the Offline Installation. The functions are as separated as possible, allowing high scalability in the future, instead of having a monolithic script.
- `offline-installation.sh`: it contains the necessary function calls of the `common.sh` file, making the script pretty simple.

In the installation, some checks are performed to ensure the installation does not continue with hidden errors:
- Check the packages are downloaded.
- Check if every package is installed.
- Check if every service is started.
- Other checks with the `curl` command, such as checking the connectivity to the Wazuh indexer and Wazuh dashboard.

These two scripts can be executed both in RPM and DEB systems. The files that have to be edited in the Offline installation are automatized using the `sed` command.

**Comment by davidcr01** [comment]
## Update Report

:green_circle: The test in DEB system is passing correctly.

:red_circle: A problem has been found in the RPM system test. As the test is performed in a docker container, the `systemctl` command is not supported. To solve this, the services has to be launched manually, using the commands that the `systemctl` command would use.

**Comment by davidcr01** [comment]
## Update Report

I achieved starting the services manually:
- **indexer**: 
```runuser "wazuh-indexer" --shell="/bin/bash" --command="OPENSEARCH_PATH_CONF=/etc/wazuh-indexer /usr/share/wazuh-indexer/bin/opensearch" > /dev/null 1>&2 &```.
 The `/usr/share/wazuh-indexer/bin/indexer-security-init.sh` has to be executed while the previous command is running to initialize the cluster and avoid getting errors.
- **manager**: `/var/ossec/bin/wazuh-control start`
- **filebeat**: 
`/usr/share/filebeat/bin/filebeat --environment systemd -c /etc/filebeat/filebeat.yml --path.home /usr/share/filebeat --path.config /etc/filebeat --path.data /var/lib/filebeat --path.logs /var/log/filebeat &`
- **dashboard**: 
`/usr/share/wazuh-dashboard/bin/opensearch-dashboards "-c /etc/wazuh-dashboard/opensearch_dashboards.yml" --allow-root`. The `--allow-root` parameter is needed in Docker.

These commands have been extracted from the `.service` files of those components.

:bulb: Another alternative is to use https://github.com/gdraheim/docker-systemctl-replacement (tested and worked). In this repository, there are various Python scripts that replace the functionality of `systemd`. Instead of calling `systemctl <parameters>`, call `/path/to/script.py <parameters>`. These could be useful if the whole functionality of `systemd` is needed but take into count that it is an external resource and a dependency if it is used.
