### ISSUE TITLE
Replace the "Loading wazuh..." message with "Loading ..." in the loading logo

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#2052]
## Description
It is necessary to replace the loading screen message as it is repetitive:

The actual message is: "Loading wazuh"
The new message should be: "Loading ..."

## Tasks

- [x] Update the loading logo with the new message, help from the design team may be required
- [x] Build new RPM and DEB packages

## Validation

- [x] Validate in the interface that the logo is displayed correctly
