### ISSUE TITLE
Avoid using a proxy in scripts

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2066]
## Description

It would be desirable that all `curl` commands done in the Installation Assistant ignore the use of a proxy. 

This, apparently, can be performed with the `--no-proxy` option of the `curl` command added in the `[7.19.4]` (http://curl.haxx.se/changes.html#7_19_4) version.

## Tasks

- [x] Search for an improvement.
- [ ] Apply the improvement.
- [ ] Validate the improvement.

## Validation

- [ ] All curls of the Installation Assistant are executed correctly without using a proxy.

**Comment by davidcr01** [comment]
## Update Report

The used option is `--noproxy '*'`, where the wildcard `'*'` that matches all hosts, and effectively disables the proxy. This information is extracted from the [curl manual](https://linux.die.net/man/1/curl)
