### ISSUE TITLE
Offline Installation must install dependencies

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2067]
## Description

It has been detected in an RPM system (but it concerns every supported system) that the Offline Installation fails when the `openssl` tool is not installed. This is not only reduced to the `openssl` tool but all the dependencies that the Offline Installation uses, like for instance the `curl` command.

Here is an example of a CentOS 7 system, using the `wazuh-certs-tool.sh` script after downloading the packages:

```
31/01/2023 13:14:59 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
31/01/2023 13:[14](https://github.com/davidcr01/wazuh-packages/actions/runs/4054444170/jobs/6976291251#step:6:15):59 INFO: Verbose logging redirected to /var/log/wazuh-install.log
31/01/2023 13:[15](https://github.com/davidcr01/wazuh-packages/actions/runs/4054444170/jobs/6976291251#step:6:16):00 INFO: --- Download Packages ---
31/01/2023 13:15:00 INFO: Starting Wazuh packages download.
31/01/2023 13:15:00 INFO: Downloading Wazuh rpm packages for x86_64.
31/01/2023 13:15:12 INFO: The manager package was downloaded.
31/01/2023 13:15:12 INFO: The filebeat package was downloaded.
31/01/2023 13:15:14 INFO: The indexer package was downloaded.
31/01/2023 13:15:15 INFO: The dashboard package was downloaded.
31/01/2023 13:15:15 INFO: The packages are in wazuh-offline/wazuh-packages
31/01/2023 13:15:15 INFO: Downloading configuration files and assets.
31/01/2023 13:15:15 INFO: The resource https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH was downloaded.
31/01/2023 13:15:[16](https://github.com/davidcr01/wazuh-packages/actions/runs/4054444170/jobs/6976291251#step:6:17) INFO: The resource https://packages-dev.wazuh.com/4.4/tpl/wazuh/filebeat/filebeat.yml was downloaded.
31/01/[20](https://github.com/davidcr01/wazuh-packages/actions/runs/4054444170/jobs/6976291251#step:6:21)[23](https://github.com/davidcr01/wazuh-packages/actions/runs/4054444170/jobs/6976291251#step:6:24) 13:15:16 INFO: The resource https://raw.githubusercontent.com/wazuh/wazuh/master/extensions/elasticsearch/7.x/wazuh-template.json was downloaded.
31/01/2023 13:15:16 INFO: The resource https://packages-dev.wazuh.com/pre-release/filebeat/wazuh-filebeat-0.2.tar.gz was downloaded.
31/01/2023 13:15:16 INFO: The configuration files and assets are in wazuh-offline.tar.gz
31/01/2023 13:15:53 INFO: You can follow the installation guide here https://documentation.wazuh.com/current/deployment-options/offline-installation.html
Downloading the resources...
[31](https://github.com/davidcr01/wazuh-packages/actions/runs/4054444170/jobs/6976291251#step:6:32)/01/2023 13:15:54 ERROR: OpenSSL not installed.
```

## Tasks

- [ ] Search for all the necessary dependencies.
- [ ] Search for a solution.
- [ ] Apply the fix.
- [ ] Validate the fix.

## Validation

- [ ] The resources are downloaded correctly in a system without the necessary dependencies.
