### ISSUE TITLE
Installation Assistant should perform a complete offline installation

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2073]
## Description

It would be interesting for the Installation Assitant to perform the whole process of the Offline Installation, instead of just downloading the necessary packages.

The aim of this improval is to prevent the user from following the step-by-step installation of the Offline alternative, so this process is done automatically by the Installation Assistant.

With this, in the documentation (https://documentation.wazuh.com/current/deployment-options/offline-installation.html) there should be two methods as the [Installation Guide](https://documentation.wazuh.com/current/installation-guide/index.html) suggests: an installation using the Installation Assistant, and a Step-by-step installation.

## Useful resources
The GitHub Action done in https://github.com/wazuh/wazuh-packages/pull/2071 to test the Offline Installation could be helpful to solve this issue.

**Action:** https://github.com/wazuh/wazuh-packages/tree/1eda46be9517179d44c28ae854e32b078d880347/.github/actions/offline-installation

## Tasks

- [ ] Search for a solution.
- [ ] Apply the fix.
- [ ] Validate the fix.

## Validation

- [ ] The whole installation of the Offline alternative is performed correctly.

**Comment by davidcr01** [comment]
Duplicated of https://github.com/wazuh/wazuh-packages/issues/1422.
