### ISSUE TITLE
Common variables should be in the same variables file

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2092]
## Description

In https://github.com/wazuh/wazuh-packages/pull/2090/, a new file `commonVariables.sh` has been created. This file should contain all the common variables used in the different tools.

It would be necessary to research which of the variables defined in `certVariables.sh`, `passwordsVariables.sh`, and `installVariables.sh` can be moved to the common variables file. 

## Tasks
- [ ] Research the variables that can be moved.
- [ ] Apply the change.
- [ ] Validate the change.

## Validation
- [ ] The different components work correctly, using the common variables.
