### ISSUE TITLE
Backup error in AIO installation

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2116]
## Description

|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.0 & 4.5.0 | AIO | Install | Ubuntu 16.04 |

It has been detected that in a fresh Ubuntu 16, while installing all the central components of Wazuh (indexer, manager, dashboard) using the Installation Assistant with the AIO option, an error is generated after executing the Wazuh dashboard.

```
root@ubuntu16:/home/vagrant# bash wazuh-install.sh -a -i
07/03/2023 10:10:06 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.0
07/03/2023 10:10:06 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/03/2023 10:10:13 WARNING: Hardware and system checks ignored.
07/03/2023 10:10:18 INFO: Wazuh development repository added.
07/03/2023 10:10:18 INFO: --- Configuration files ---
07/03/2023 10:10:18 INFO: Generating configuration files.
07/03/2023 10:10:18 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
07/03/2023 10:10:18 INFO: --- Wazuh indexer ---
07/03/2023 10:10:18 INFO: Starting Wazuh indexer installation.
07/03/2023 10:12:51 INFO: Wazuh indexer installation finished.
07/03/2023 10:12:51 INFO: Wazuh indexer post-install configuration finished.
07/03/2023 10:12:51 INFO: Starting service wazuh-indexer.
07/03/2023 10:13:06 INFO: wazuh-indexer service started.
07/03/2023 10:13:06 INFO: Initializing Wazuh indexer cluster security settings.
07/03/2023 10:13:16 INFO: Wazuh indexer cluster initialized.
07/03/2023 10:13:16 INFO: --- Wazuh server ---
07/03/2023 10:13:16 INFO: Starting the Wazuh manager installation.
07/03/2023 10:14:10 INFO: Wazuh manager installation finished.
07/03/2023 10:14:10 INFO: Starting service wazuh-manager.
07/03/2023 10:14:26 INFO: wazuh-manager service started.
07/03/2023 10:14:26 INFO: Starting Filebeat installation.
07/03/2023 10:14:33 INFO: Filebeat installation finished.
07/03/2023 10:14:34 INFO: Filebeat post-install configuration finished.
07/03/2023 10:14:34 INFO: Starting service filebeat.
07/03/2023 10:14:34 INFO: filebeat service started.
07/03/2023 10:14:34 INFO: --- Wazuh dashboard ---
07/03/2023 10:14:34 INFO: Starting Wazuh dashboard installation.
07/03/2023 10:15:34 INFO: Wazuh dashboard installation finished.
07/03/2023 10:15:34 INFO: Wazuh dashboard post-install configuration finished.
07/03/2023 10:15:34 INFO: Starting service wazuh-dashboard.
07/03/2023 10:15:34 INFO: wazuh-dashboard service started.
07/03/2023 10:15:44 ERROR: The backup could not be created
root@ubuntu16:/home/vagrant# 
```

If the backup directory is listed, it is seen that the files are saved:

```
root@ubuntu16:/home/vagrant# ls /etc/wazuh-indexer/backup/
action_groups.yml  audit.yml   internal_users.yml  opensearch.yml.example  roles.yml    whitelist.yml
allowlist.yml      config.yml  nodes_dn.yml        roles_mapping.yml       tenants.yml
root@ubuntu16:/home/vagrant# 
```

This error message is generated in these lines:
https://github.com/wazuh/wazuh-packages/blob/acccbedc4f622ec3735e28e944c13ec9d42de5f6/unattended_installer/passwords_tool/passwordsFunctions.sh#L182-L187

## Tasks

- [ ] Search for a solution.
- [ ] Apply the solution.
- [ ] Validate the solution.

## Validation

- [ ] The AIO installation is done correctly, making the backup and showing no errors.
