### ISSUE TITLE
Error with AWS CLI in WPK Linux builder container

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#2124]
## Description
An error was detected in the process of obtaining AWS secrets using the AWS CLI within the `package-generation:lwpk_builder_x86_64_gcc9` image.

As far as we could detect, there is a compatibility issue between AWS CLI and the python version installed in the image (3.4).

```console
15:42:50  + aws --region=us-east-1 secretsmanager get-secret-value --secret-id *******
15:42:50  + jq .
15:42:50  Traceback (most recent call last):
15:42:50    File "/usr/bin/aws", line 19, in <module>
15:42:50      import awscli.clidriver
15:42:50    File "/usr/lib/python3.4/site-packages/awscli/clidriver.py", line 37, in <module>
15:42:50      from awscli.help import ProviderHelpCommand
15:42:50    File "/usr/lib/python3.4/site-packages/awscli/help.py", line 23, in <module>
15:42:50      from awscli.clidocs import ProviderDocumentEventHandler
15:42:50    File "/usr/lib/python3.4/site-packages/awscli/clidocs.py", line 303
15:42:50      [f'``{key}``' for key in shape.members.keys()]
15:42:50                  ^
```
Jenkins Job: https://ci.wazuh.info/view/Packages/job/Packages_builder/132460/console

## Tasks

- [x] Update the version of one of the components for the package creation to work (Python, AWS CLI, or both).
- [x] Update the image in ECR

## Validation

- [x] Validate that the changes made allow the creation of the wpk package.
- [x] Verify that the built wpk package works correctly

**Comment by c-bordon** [comment]
## UpdateReport

### Tasks
- Validated that AWS CLI was not working with the Python version installed (3.4):
```console
Step 13/17 : RUN aws --version
 ---> Running in dc6aaf4c1fce
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python3.4/site-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/lib/python3.4/site-packages/botocore/__init__.py", line 96
    name = f"{name[: -len(matched)]}{sep}{matched.lower()}"
                                                          ^
SyntaxError: invalid syntax
The command '/bin/sh -c was
```
- I researched the compatibility matrix of AWS CLI with Python and downgraded the AWS CLI to be compatible with the installed Python version, the version command works correctly but the calls to the secret manager kept failing, so the option will be to upgrade the version of Python:

https://docs.aws.amazon.com/cli/v1/userguide/cli-chap-install.html#cli-chap-install-python
![image](https://user-images.githubusercontent.com/64099752/224112412-7dd398df-317e-4a93-895e-a4db2c5af825.png)


- I installed Python 3.7 to use the latest versions of the AWS CLI, but this version of python affects the compilation of GCC, so I had to look for a different alternative.

**Comment by c-bordon** [comment]
I was testing with the first approach, it consists of installing python 3.4 for gcc9 compilation and then python 3.7 for AWS CLI, this way you can build the container and create the WPK packages:

https://ci.wazuh.info/view/Packages/job/Packages_builder/132606/console

So far this works, the WPK packages are built and the WPK package works as expected, although I don't like it, I am looking for the alternative to not having to install 2 versions of Python.

Upgrade with WPK:

```console
[root@centos7-1 ~]# /var/ossec/bin/agent_control -i 010

Wazuh agent_control. Agent information:
   Agent ID:   010
   Agent Name: 9c648367d550
   IP address: any
   Status:     Active

   Operating system:    Linux |9c648367d550 |5.19.0-35-generic |#36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 |x86_64
   Client version:      Wazuh v4.3.10
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1678390573

   Syscheck last started at:  Thu Mar  9 18:53:24 2023
   Syscheck last ended at:    Thu Mar  9 18:53:25 2023

[root@centos7-1 ~]# /var/ossec/bin/agent_upgrade -a 010 -r https://packages-dev.wazuh.com/trash/wpk -v v4.4.0

Upgrading...

Upgraded agents:
        Agent 010 upgraded: Wazuh v4.3.10 -> v4.4.0
[root@centos7-1 ~]# /var/ossec/bin/agent_control -i 010

Wazuh agent_control. Agent information:
   Agent ID:   010
   Agent Name: 9c648367d550
   IP address: any
   Status:     Active

   Operating system:    Linux |9c648367d550 |5.19.0-35-generic |#36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 |x86_64
   Client version:      Wazuh v4.4.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1678390721

   Syscheck last started at:  Thu Mar  9 19:38:02 2023
   Syscheck last ended at:    Thu Mar  9 19:38:03 2023

```
