### ISSUE TITLE
Add cached package check in the Wazuh installation assistant

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2194]
## Description

A user has reported a problem when performing an installation with the Wazuh installation assistant, where the following message is observed in the installation log:

```
Unpacking wazuh-indexer (4.4.1-1) ...
dpkg-deb (subprocess): decompressing archive '/var/cache/apt/archives/wazuh-indexer_4.4.1-1_amd64.deb' (size=687024926) member 'data.tar': lzma error: compressed data is corrupt
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/wazuh-indexer_4.4.1-1_amd64.deb (--unpack):
 cannot copy extracted data for './etc/wazuh-indexer/opensearch.yml' to '/etc/wazuh-indexer/opensearch.yml.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 /var/cache/apt/archives/wazuh-indexer_4.4.1-1_amd64.deb
```

By deleting the package from the system cache, the user reports that the installation successfully passes the package installation stage.

It is necessary to determine if we should include a cache cleaning stage in the installation or uninstallation process through the Wazuh installation assistant to avoid this case because if the package stored in the cache is corrupt, all subsequent installations fail.

## Tasks

- [ ] Determine if we should add a cache cleaning stage for Wazuh packages
- [ ] Add what is necessary to clean the cached packages when using the installation assistant in the following cases:
   - [ ] Uninstall
   - [ ] Overwrite
   - [ ] Fresh install
- [ ] Consider adding a cached package integrity check if it exists

## Validation

- [ ] Wazuh cached packages are correct
- [ ] The installation assistant works without problems when using all its options

**Comment by teddytpc1** [comment]
As we will install using the package URL from 5.0.0, we don't plan to include a fix for this issue.
