### ISSUE TITLE
Use proper installation path for macOS agent

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#2203]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.2 | Agent | Install | macOS|

The current installation path is not the default one used by the majority of packages for macOS systems, we need to modify the SPECS to change this path.

### Tasks
- [ ] Investigate the correct path to use.
- [ ] Modify the SPECS with the new path.
- [ ] Investigate possible upgrade errors derived from this change.

### Validation
- [ ] Package installs on the new path and agent runs properly.
- [ ] Upgrade tests.

**Comment by rauldpm** [comment]
## Update report


- The current installation path is `/Library/Ossec` since that is how it is specified in the `generate_wazuh_packages.sh` script, not through the SPECS file, but this must be modified to modify the installation path references in certain attributes
- The actual installation path was included in the PR https://github.com/wazuh/wazuh-packages/pull/175/, also used by the installation by sources shown in the documentation: https://github .com/wazuh/wazuh-documentation/pull/1681
- The `/Applications` path is used by the `App Store`, this is not the case for Wazuh, which is not available in the App Store
- `Homebrew` uses the path `/usr/local/` for its installations, Wazuh is not installed by this package manager
- Since the Wazuh package is not installed by package managers, the Wazuh package should not use the paths used by these packages managers, in order to avoid possible conflicts
- Currently, the path used (`/Library`) would not be correct by definition, since Wazuh includes many more files than necessary, as binaries:

```
/Library – it contains files and resources that are used by all apps installed on your Mac, as well as preferences and settings that are shared across all user accounts on the computer.
```

- The ideal case would be to maintain a separation between files, placing each file in its own location as Homebrew does, but using these paths could create a conflict, besides that currently it is not possible to divide the package file structure.

```
By default, Homebrew will install all packages in the directory /usr/local/Cellar/, and also creates symbolic links at /usr/local/opt/ and /usr/local/bin/ (for executable files).
```

- When checking the installation method of `Ossec-HIDS`, it is observed that there is no `.pkg` package for macOS, but the installation by sources can be done
- During the process it asks where you want to install Ossec, giving the path `/var/ossec` by default, where it seems to be installed correctly

```
sh-3.2# /var/ossec/bin/ossec-control status
ossec-logcollector not running...
ossec-syscheckd not running...
ossec-agentd not running...
ossec-execd not running...
```

- Ossec-HIDS complete installation log: [install.log](https://github.com/wazuh/wazuh-packages/files/11519443/install.log)


Related:

- https://mkyong.com/mac/where-does-homebrew-install-packages-on-mac/
- https://www.quora.com/Where-do-you-install-external-packages-on-OS-X

Packages path installation tests:

- https://zoom.us/client/latest/zoomusInstallerFull.pkg

```
sh-3.2# installer -pkg /Users/vagrant/PKG/zoomusInstallerFull.pkg -target /
installer: Package name is Zoom
installer: Installing at base path /
installer: The install was successful.
sh-3.2# find / -name "*zoom*"
/Library/PrivilegedHelperTools/us.zoom.ZoomDaemon
/Library/Logs/zoomusinstall.log
/Library/LaunchDaemons/us.zoom.ZoomDaemon.plist
/System/Volumes/Data/Library/PrivilegedHelperTools/us.zoom.ZoomDaemon
/System/Volumes/Data/Library/Logs/zoomusinstall.log
/System/Volumes/Data/Library/LaunchDaemons/us.zoom.ZoomDaemon.plist
/System/Volumes/Data/private/var/root/Library/Application Support/zoom.us
/System/Volumes/Data/private/var/db/receipts/us.zoom.pkg.videomeeting.plist
/System/Volumes/Data/private/var/db/receipts/us.zoom.pkg.videomeeting.bom
/System/Volumes/Data/Applications/zoom.us.app
/System/Volumes/Data/Applications/zoom.us.app/Contents/MacOS/zoom.us
/System/Volumes/Data/Applications/zoom.us.app/Contents/Library/LaunchServices/us.zoom.ZoomDaemon
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/zoom.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/zoom_warning@2x.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/zoom@2x.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/zoom_warning.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/gift_zoom_pro.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/zapp_logo_zoom@2x.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/gift_zoom_pro@2x.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/zapp_logo_zoom.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zChatUIEx.bundle/Contents/Resources/WebUI/static/fonts/icozoom.1d8f0bd8.ttf
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zChatUIEx.bundle/Contents/Resources/WebUI/static/fonts/icozoom.0c8360ba.ttf
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zChatUIEx.bundle/Contents/Resources/HuddleView/static/fonts/icozoom.45258ff3.woff
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zChatUIEx.bundle/Contents/Resources/HuddleView/static/fonts/icozoom.e6a1f19a.ttf
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zCalendarUI.bundle/Contents/Resources/WebUI/static/js/zoomUI~zm-tree.78bd97d9.js
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zCalendarUI.bundle/Contents/Resources/WebUI/static/fonts/icozoom.0c8360ba.ttf
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMacRes.bundle/Contents/Resources/zoom.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMacRes.bundle/Contents/Resources/zoom_warning.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMacRes.bundle/Contents/Resources/gift_zoom_pro.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMacRes.bundle/Contents/Resources/zapp_logo_zoom.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/ZoomAutoUpdater.app/Contents/Resources/zoom_logo.tiff
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/libzoombase_crypto_shared.dylib
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/Transcode.app/Contents/Resources/zoom.png
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/Lottie.framework/Versions/A/Resources/zoom_logo_animation.json
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMailUI.bundle/Contents/Resources/WebUI/static/img/zoom.76b2aa6f.svg
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMailUI.bundle/Contents/Resources/WebUI/static/fonts/icozoom.45258ff3.woff
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/zMailUI.bundle/Contents/Resources/WebUI/static/fonts/icozoom.e6a1f19a.ttf
/private/var/root/Library/Application Support/zoom.us
/private/var/db/receipts/us.zoom.pkg.videomeeting.plist
/private/var/db/receipts/us.zoom.pkg.videomeeting.bom
/Applications/zoom.us.app
/Applications/zoom.us.app/Contents/MacOS/zoom.us
/Applications/zoom.us.app/Contents/Library/LaunchServices/us.zoom.ZoomDaemon
/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/zoom.png
/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/zoom_warning@2x.png
/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/zoom@2x.png
/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/zoom_warning.png
/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/gift_zoom_pro.png
/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/zapp_logo_zoom@2x.png
/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/gift_zoom_pro@2x.png
/Applications/zoom.us.app/Contents/Frameworks/zMacResRetina.bundle/Contents/Resources/zapp_logo_zoom.png
/Applications/zoom.us.app/Contents/Frameworks/zChatUIEx.bundle/Contents/Resources/WebUI/static/fonts/icozoom.1d8f0bd8.ttf
/Applications/zoom.us.app/Contents/Frameworks/zChatUIEx.bundle/Contents/Resources/WebUI/static/fonts/icozoom.0c8360ba.ttf
/Applications/zoom.us.app/Contents/Frameworks/zChatUIEx.bundle/Contents/Resources/HuddleView/static/fonts/icozoom.45258ff3.woff
/Applications/zoom.us.app/Contents/Frameworks/zChatUIEx.bundle/Contents/Resources/HuddleView/static/fonts/icozoom.e6a1f19a.ttf
/Applications/zoom.us.app/Contents/Frameworks/zCalendarUI.bundle/Contents/Resources/WebUI/static/js/zoomUI~zm-tree.78bd97d9.js
/Applications/zoom.us.app/Contents/Frameworks/zCalendarUI.bundle/Contents/Resources/WebUI/static/fonts/icozoom.0c8360ba.ttf
/Applications/zoom.us.app/Contents/Frameworks/zMacRes.bundle/Contents/Resources/zoom.png
/Applications/zoom.us.app/Contents/Frameworks/zMacRes.bundle/Contents/Resources/zoom_warning.png
/Applications/zoom.us.app/Contents/Frameworks/zMacRes.bundle/Contents/Resources/gift_zoom_pro.png
/Applications/zoom.us.app/Contents/Frameworks/zMacRes.bundle/Contents/Resources/zapp_logo_zoom.png
/Applications/zoom.us.app/Contents/Frameworks/ZoomAutoUpdater.app/Contents/Resources/zoom_logo.tiff
/Applications/zoom.us.app/Contents/Frameworks/libzoombase_crypto_shared.dylib
/Applications/zoom.us.app/Contents/Frameworks/Transcode.app/Contents/Resources/zoom.png
/Applications/zoom.us.app/Contents/Frameworks/Lottie.framework/Versions/A/Resources/zoom_logo_animation.json
/Applications/zoom.us.app/Contents/Frameworks/zMailUI.bundle/Contents/Resources/WebUI/static/img/zoom.76b2aa6f.svg
/Applications/zoom.us.app/Contents/Frameworks/zMailUI.bundle/Contents/Resources/WebUI/static/fonts/icozoom.45258ff3.woff
/Applications/zoom.us.app/Contents/Frameworks/zMailUI.bundle/Contents/Resources/WebUI/static/fonts/icozoom.e6a1f19a.ttf
```

- https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_mac_hotspot_16.0.2_7.pkg

```
sh-3.2# installer -pkg /Users/vagrant/PKG/OpenJDK16U-jdk_x64_mac_hotspot_16.0.2_7.pkg -target /
installer: Package name is Eclipse Temurin
installer: Installing at base path /
installer: The install was successful.
/Library/Java/JavaVirtualMachines/temurin-16.jdk
find: /System/Volumes/Data/.Spotlight-V100: No such file or directory
/System/Volumes/Data/Library/Java/JavaVirtualMachines/temurin-16.jdk
/System/Volumes/Data/private/var/db/receipts/net.temurin.16.jdk.bom
/System/Volumes/Data/private/var/db/receipts/net.temurin.16.jdk.plist
find: /System/DriverKit: No such file or directory
/private/var/db/receipts/net.temurin.16.jdk.bom
/private/var/db/receipts/net.temurin.16.jdk.plist
```

---

- The default path for installed packages is `/Applications`, but it is necessary to determine if we really want to establish the installation in this path since it does not follow the same structure as the rest of the packages installed in this path, nor has it been installed through the App Store
- The installer has been modified to establish the installation path by a parameter (-p, --install-path)
- The installer has been modified so that it modifies all the files that identify the installation path with the one established in the main script without the need for it to be hardcoded

---

- Working branch: https://github.com/wazuh/wazuh-packages/tree/2203-change-macos-path-4.4

**Comment by mjcr99** [comment]
Hi team, 

I have updated [this branch](https://github.com/wazuh/wazuh/tree/change/2203-use-proper-installation-path-for-macos-agent) to make the package installation install the wazuh-agent in the `/var/ossec` folder as it's done in the UNIX OS. Another possible installation path would be the `/opt`, the [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html) stats this about `/opt*`:

```
/opt is reserved for the installation of add-on application software packages.
```
