### ISSUE TITLE
macOS upgrade using deployment variables corrupts `ossec.conf`

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#2204]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.2| Agent | Upgrade| macOS |

We have noticed that using the `deployment variables` when upgrading macOS packages modifies the configuration file `ossec.conf`, resulting on a corrupted `ossec.conf`. Moreover, the `ossec.conf` is replaced which should not happen on upgrade.

The usage of deployment variables should be ignored on upgrades to avoid this from happening.

### Tasks

- [ ] Investigate the cause of the error.
- [ ] Ignore deployment variables on upgrade.

### Validation

- [ ] Configuration files are preserved on upgrade with deployment variables.
- [ ] Configuration files are preserved on upgrade without deployment variables.
- [ ] Configuration files do not get corrupted on upgrade.

**Comment by snaow** [comment]
Duplicated: https://github.com/wazuh/wazuh-packages/issues/2201
