### ISSUE TITLE
Erroneous encapsulation in macOS conditionals during post-install process

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2210]
## Description

A problem has been detected in the conditionals of the `postinstall.sh` file since the conditions are not well defined

https://github.com/wazuh/wazuh-packages/blob/2e884db30dbe766fe153f497b7117837c1bf2a66/macos/package_files/postinstall.sh#L123

It is necessary to fix the encapsulation of these conditionals

## Tasks

- [x] Fix the conditionals encapsulation 

## Validation

- [x] The package is installed successfully
- [x] Package successfully upgrades
- [x] Users and groups are correct after installation and upgrade

**Comment by rauldpm** [comment]
## Update report

- Package build: https://ci.wazuh.info/view/Packages/job/Packages_builder_macos/9876/

### Testing

- Packages used
  - https://packages-dev.wazuh.com/warehouse/test/4.4/macos/wazuh-agent-4.4.3-2210.pkg
  - https://packages-dev.wazuh.com/pre-release/macos/wazuh-agent-4.2.7-1.pkg
  - https://packages-dev.wazuh.com/pre-release/macos/wazuh-agent-4.0.4-1.pkg
  - https://packages.wazuh.com/osx/wazuh-agent-2.1.1-1.pkg

- 4.4.3 Fresh install

```
sh-3.2# launchctl setenv WAZUH_MANAGER "192.168.56.147" && installer -pkg wazuh-agent-4.4.3-2210.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
sh-3.2# /usr/bin/dscl . -read /Users/wazuh | grep -i -E "RealName|UniqueID"
RealName: wazuh
UniqueID: 101
sh-3.2# /usr/bin/dscl . -read /Users/ossec | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Users/ossecm | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Users/ossecr | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Groups/wazuh | grep -i -E "RealName|UniqueID"
RealName: wazuh
sh-3.2# /usr/bin/dscl . -read /Groups/ossec | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
```

- 4.2.7 -> 4.4.3
  - The package does not have the `ossecr` or `ossecm` user

```
sh-3.2# launchctl setenv WAZUH_MANAGER "192.168.56.147" && installer -pkg wazuh-agent-4.2.7-1.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
sh-3.2# /usr/bin/dscl . -read /Users/wazuh | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Users/ossec | grep -i -E "RealName|UniqueID"
RealName: ossec
UniqueID: 101
sh-3.2# /usr/bin/dscl . -read /Users/ossecm | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Users/ossecr | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Groups/wazuh | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Groups/ossec | grep -i -E "RealName|UniqueID"
RealName: ossec
sh-3.2# launchctl setenv WAZUH_MANAGER "192.168.56.147" && installer -pkg wazuh-agent-4.4.3-2210.pkg -target /
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
installer: The upgrade was successful.
sh-3.2# /usr/bin/dscl . -read /Users/wazuh | grep -i -E "RealName|UniqueID"
RealName: wazuh
UniqueID: 102
sh-3.2# /usr/bin/dscl . -read /Users/ossec | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Users/ossecm | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Users/ossecr | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Groups/wazuh | grep -i -E "RealName|UniqueID"
RealName: wazuh
sh-3.2# /usr/bin/dscl . -read /Groups/ossec | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
```


- 2.1.1 -> 4.4.3 
  - The package does not have the `ossecr` or `ossecm` user

```
sh-3.2# installer -pkg wazuh-agent-2.1.1-1.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
sh-3.2# /usr/bin/dscl . -read /Users/wazuh | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Users/ossec | grep -i -E "RealName|UniqueID"
RealName: ossec
UniqueID: 101
sh-3.2# /usr/bin/dscl . -read /Users/ossecm | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Users/ossecr | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Groups/wazuh | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Groups/ossec | grep -i -E "RealName|UniqueID"
RealName: ossec
sh-3.2# cat /etc/ossec-init.conf 
DIRECTORY="/Library/Ossec"
NAME="Wazuh"
VERSION="v2.1.1"
REVISION="3485"
DATE="Tue Sep 19 11:39:12 CEST 2017"
TYPE="agent"
sh-3.2# launchctl setenv WAZUH_MANAGER "192.168.56.147" && installer -pkg wazuh-agent-4.4.3-2210.pkg -target /
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
installer: The upgrade was successful.
sh-3.2# grep "VERSION" /Library/Ossec/bin/wazuh-control 
VERSION="v4.4.3"
sh-3.2# /usr/bin/dscl . -read /Users/wazuh | grep -i -E "RealName|UniqueID"
RealName: wazuh
UniqueID: 102
sh-3.2# /usr/bin/dscl . -read /Users/ossec | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Users/ossecm | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Users/ossecr | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2# /usr/bin/dscl . -read /Groups/wazuh | grep -i -E "RealName|UniqueID"
RealName: wazuh
sh-3.2# /usr/bin/dscl . -read /Groups/ossec | grep -i -E "RealName|UniqueID"
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
sh-3.2#
```

---

- No installed package shows the existence of the `ossecr` or `ossecm` users
- These conditionals were added in the pull request: https://github.com/wazuh/wazuh-packages/pull/716/ as part of the https://github.com/wazuh/wazuh/issues/7646 epic
- If these two users are not needed, the following code could be removed since it is never used:

```
if [[ $(dscl . -read /Users/ossecm) ]]; then
    find ${DIR}/ -group ossec -user ossecm -exec chown wazuh:wazuh {} \ > /dev/null 2>&1 || true
    sudo /usr/bin/dscl . -delete "/Users/ossecm"
fi
if [[ $(dscl . -read /Users/ossecr) ]]; then
    find ${DIR}/ -group ossec -user ossecr -exec chown wazuh:wazuh {} \ > /dev/null 2>&1 || true
    sudo /usr/bin/dscl . -delete "/Users/ossecr"
fi
```
