### ISSUE TITLE
Remove `Login item` configuration from the macOS agent

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2212]
## Description

It is necessary to remove the `Login item` from macOS and replace it with a system service management since it is not desired for the agent to start with the system but instead to be managed by a system service such as `LaunchServices` or ` launchd`

![image](https://github.com/wazuh/wazuh-packages/assets/14913942/0ed4f69b-498d-425b-b6a7-d9f6f1933b41)

Related: https://developer.apple.com/documentation/servicemanagement/updating_your_app_package_installer_to_use_the_new_service_management_api?language=objc

## Tasks

- [ ] Remove macOS `Login item` configuration
- [ ] Add what is necessary for the agent to start through a system service, as it is done in other systems

## Validation

- [ ] The agent is started by service and not as `Login item`
- [ ] The agent does not appear in the `Login item` list (interface)
- [ ] The agent is built, installed, and working properly

**Comment by verdx** [comment]
# Update: Test leaving only the `LaunchDaemon`

Based on this article(https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html#//apple_ref/doc/uid/10000172i-SW7-BCIEDDBJ), a test has been done to remove the Wazuh Login Item, trying to only leave the LaunchDaemon, to use `launchctl` as a system service.

The LaunchDaemon calls a different script to start the application, and the one in `/Library/StartupItems/WAZUH` was being used, so to remove the StartupItem, the launcher script should be moved elsewhere, for example, `/Libary/Ossec`.

To avoid having to create a different branch in https://github.com/wazuh/wazuh, the `darwin-init.sh` script run in `postinstall.sh` has been removed, and the changes have been done in `preinstall.sh`. A package has been [created](https://ci.wazuh.info/job/Packages_builder_macos/9964) and the installation tested, but it fails with an unknown error:

```
sh-3.2# launchctl setenv WAZUH_MANAGER "10.0.0.2" && installer -pkg wazuh-agent-4.4.2-2212.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “wazuh-agent-4.4.2-2212.pkg”.)
sh-3.2# launchctl setenv WAZUH_MANAGER "10.0.0.2" && installer -pkg wazuh-agent-4.4.2-2212.pkg -target / -verbose 
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: Preparing for installation….....
installer: Preparing the disk….....
installer: Preparing Wazuh Agent….....
installer: Waiting for other installations to complete….....
installer: Configuring the installation….....
installer: 	
#
installer: Writing files….....
#
installer: Writing files….....
installer: Writing files….....
installer: Writing files….....
installer: Writing files….....
installer: Validating packages….....
#
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “wazuh-agent-4.4.2-2212.pkg”.)
sh-3.2# launchctl setenv WAZUH_MANAGER "10.0.0.2" && installer -pkg wazuh-agent-4.4.2-2212.pkg -target / -verboseR 
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Wazuh Agent…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%8.844464
installer:PHASE:Writing files…
installer:%12.699488
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:%36.084737
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “wazuh-agent-4.4.2-2212.pkg”.)
``` 

A new test will be done, now changing only `darwin-init.sh`, even if it is temporary for the testing, as it is much simpler, only a script run after installing, instead of having to worry with the package creation.

**Comment by lchico** [comment]
# Update

Just started working on this, conducting some research.

**Comment by rjcausarano** [comment]
- The current 4.14.X code already uses the modern launchctl system service to start the agent
- There is still, however, Login item code remaining that should be cleaned up.
- https://github.com/wazuh/internal-devel-requests/issues/5991 was created in order to test the changes

**Comment by rjcausarano** [comment]
- Ran all the manual tests mentioned above including a WPK upgrade test
- PR is under Review

**Comment by cborla** [comment]
@vikman90 ready to close!
