### ISSUE TITLE
Change notarization tool from `altool` to `notarytool`

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#2233]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.4| Agent | Install/Upgrade/Remove | macOS |

The command `altool` has been deprecated and notarization using it won't be available from November 1st. We need to replace it with the new command `notarytool`

**Comment by DFolchA** [comment]
## Update

The new tool needed to notarize the macOS packages is included in `Xcode 13` which is only available from macOS Bigsur 11.3.

After some investigation, we found that the tool can also be run on macOS Catalina if we extract the `notarytool` binary from the `Xcode` package.

With the current infrastructure, we may need to migrate the notarization of the package from the current Mac mini to the macOS Ventura one. To mitigate the impact of future changes we should move the notarization credential to AWS.

## Tasks

- [ ] Modify wazuh-packages script to use `notarytool`
- [ ] Migrate notarization credentials to AWS
- [ ] Modify pipeline to change notarization host

**Comment by DFolchA** [comment]
## Update

Modify `generate_wazuh_packages.sh` script to use the new `notarytool` instead of `altool`, resources:

https://successfulsoftware.net/2023/04/28/moving-from-altool-to-notarytool-for-mac-notarization/
https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool

Work in Jenkins pipeline.

**Comment by DFolchA** [comment]
Blocked by https://github.com/wazuh/wazuh-packages/issues/2391

**Comment by DFolchA** [comment]
## Update

Work on jenkins pipeline:

- Deploy Ventura machine to sign packages instead of macmini
- Use AWS secrets instead of Jenkins secrets
- Launch wazuh-packages to build and notarize the package

**Comment by DFolchA** [comment]
## Update

Continue working with Jenkins pipeline:

- Remove unnecessary tasks and unify procedures for ARM and AMD packages.
- Test pipeline and fix issues deploying machine.

**Comment by DFolchA** [comment]
## Update

Due to unforeseen infrastructure constraints, it is necessary to separate the signing and notarizing procedures in two steps, this will be implemented in wazuh-packages in this commit:
https://github.com/wazuh/wazuh-packages/commit/caac725d1be47d1e170b1b393783062093c41c29
Jenkins will use these changes to sign the packages in the signing machine and use a Big Sur machine to notarize.

**Comment by DFolchA** [comment]
## Update

Added necessary changes to notarize using notarytool to wazuh-packages

https://github.com/wazuh/wazuh-packages/commit/38c006cdb8a57c2b83c9a8a6acae478090911959

Found error when notarizing due to package signing not done correctly:
```
    {
      "severity": "error",
      "code": null,
      "path": "wazuh-agent-4.6.0-0.0.0.todelete.intel64.pkg/agent.pkg Contents/Payload/Library/Ossec/active-response/bin/kaspersky",
      "message": "The binary is not signed.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "x86_64"
    },

```
Currently investigating the signing issue.

**Comment by ncvicchi** [comment]
Moved ETA to 10/31 for signing issue analysis
