### ISSUE TITLE
Support new Wazuh version 4.5.2 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2289]
## Description

This issue attempts to support a new version 4.5.2 in the wazuh-packages repository.

## Tasks

- [ ] Create numbered branch for current master version (4.5.1) using master branch on wazuh-packages repository.
- [ ] Bump master branch to 4.5.2 (including changelog) on wazuh-packages repository.
- [ ] Build and push testing images for GitHub actions.
