### ISSUE TITLE
Support new Wazuh version 4.5.2 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2291]
## Description

This issue attempts to support a new version 4.5.2 in the wazuh-packages repository.

## Tasks

- [ ] Create numbered branch for version (4.5.2) using branch 4.5.1 on wazuh-packages repository.
- [ ] Bump 4.5.2 branch to 4.5.2 version, including revision and changelog.
- [ ] Build and push testing images for GitHub actions.
