### ISSUE TITLE
Incorrect path to the Wazuh indexer binary `performance-analyzer-agent-cli`

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2321]
## Description

An error has been detected in the `wazuh-indexer-performance-analyzer` service as a result of what was reported by a community user and @jftuduri 

```
root@ubuntu-jammy:~# systemctl status wazuh-indexer-performance-analyzer.service
× wazuh-indexer-performance-analyzer.service - Wazuh-indexer Performance Analyzer
      Loaded: loaded (/lib/systemd/system/wazuh-indexer-performance-analyzer.service; disabled; vendor preset: enabled)
      Active: failed (Result: exit-code) since Wed 2023-07-26 16:24:46 UTC; 681ms ago
     Process: 51055 ExecStart=/usr/share/wazuh-indexer/bin/performance-analyzer-agent-cli (code=exited, status=203/EXEC)
    Main PID: 51055 (code=exited, status=203/EXEC)
         CPU: 7ms

Jul 26 16:24:46 ubuntu-jammy systemd[1]: wazuh-indexer-performance-analyzer.service: Scheduled restart job, restart counter is at 5.
Jul 26 16:24:46 ubuntu-jammy systemd[1]: Stopped Wazuh-indexer Performance Analyzer.
Jul 26 16:24:46 ubuntu-jammy systemd[1]: wazuh-indexer-performance-analyzer.service: Start request repeated too quickly.
Jul 26 16:24:46 ubuntu-jammy systemd[1]: wazuh-indexer-performance-analyzer.service: Failed with result 'exit-code'.
Jul 26 16:24:46 ubuntu-jammy systemd[1]: Failed to start Wazuh-indexer Performance Analyzer.
```

As commented by @Desvelao, the error seems to come from the service file, since `ExecStart` is not pointing to the binary correctly

https://github.com/wazuh/wazuh-packages/blob/014bd30edf8264fdb3bb4c270d43484eda458a83/stack/indexer/base/files/usr/lib/systemd/system/wazuh-indexer-performance-analyzer.service#L7

In the OpenSearch GitHub repository of the plugin, it is possible to see that it does not have the correct path

https://github.com/opensearch-project/performance-analyzer/blob/7c32918b5434c04af40c072d0a972ddf7818b556/packaging/opensearch-performance-analyzer.service#L6

```
ExecStart=/usr/share/opensearch/bin/opensearch-performance-analyzer/performance-analyzer-agent-cli
```

Possibly this is a lack of updating procedure with respect to OpenSearch since the initial versions of said file do share the path with respect to our service file

https://github.com/opensearch-project/performance-analyzer/blob/1.0.1.0/packaging/opensearch-performance-analyzer.service

```
ExecStart=/usr/share/opensearch/bin/performance-analyzer-agent-cli
```

It is necessary to adapt the correct path for the service to work normally

### Related:

https://github.com/wazuh/wazuh-packages/blob/973e69edfdde48e171f226e41bf8e29b327a48bb/stack/indexer/rpm/wazuh-indexer.spec#L402-L404

## Tasks

- [ ] Fix the `performance-analyzer-agent-cli` path in the service file

## Validation

- [ ] Wazuh indexer works without error
- [ ] The plugin service starts and works normally

**Comment by rauldpm** [comment]
## Update report

- Still happening in Wazuh indexer 4.6.0 - 2.8.0

```
root@debian11:/home/vagrant# cat /usr/share/wazuh-indexer/VERSION 
4.6.0
root@debian11:/home/vagrant# systemctl start wazuh-indexer-performance-analyzer.service
root@debian11:/home/vagrant# systemctl status wazuh-indexer-performance-analyzer.service
● wazuh-indexer-performance-analyzer.service - Wazuh-indexer Performance Analyzer
     Loaded: loaded (/lib/systemd/system/wazuh-indexer-performance-analyzer.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-09-04 12:28:16 UTC; 897ms ago
    Process: 9535 ExecStart=/usr/share/wazuh-indexer/bin/performance-analyzer-agent-cli (code=exited, status=203/EXEC)
   Main PID: 9535 (code=exited, status=203/EXEC)
        CPU: 3ms

Sep 04 12:28:16 debian11 systemd[1]: wazuh-indexer-performance-analyzer.service: Scheduled restart job, restart counter is at 5.
Sep 04 12:28:16 debian11 systemd[1]: Stopped Wazuh-indexer Performance Analyzer.
Sep 04 12:28:16 debian11 systemd[1]: wazuh-indexer-performance-analyzer.service: Start request repeated too quickly.
Sep 04 12:28:16 debian11 systemd[1]: wazuh-indexer-performance-analyzer.service: Failed with result 'exit-code'.
Sep 04 12:28:16 debian11 systemd[1]: Failed to start Wazuh-indexer Performance Analyzer.
```

**Comment by rauldpm** [comment]
## Update report

- Still happening in Wazuh indexer 4.8.0 - 2.10.0

```
root@ubuntu20stack:/home/vagrant# cat /usr/share/wazuh-indexer/VERSION 
4.8.0
root@ubuntu20stack:/home/vagrant# systemctl start wazuh-indexer-performance-analyzer.service
root@ubuntu20stack:/home/vagrant# systemctl status wazuh-indexer-performance-analyzer.service
● wazuh-indexer-performance-analyzer.service - Wazuh-indexer Performance Analyzer
     Loaded: loaded (/lib/systemd/system/wazuh-indexer-performance-analyzer.service; disabled; vendor preset>
     Active: failed (Result: exit-code) since Mon 2023-10-16 16:20:33 UTC; 5ms ago
    Process: 6018 ExecStart=/usr/share/wazuh-indexer/bin/performance-analyzer-agent-cli (code=exited, status>
   Main PID: 6018 (code=exited, status=203/EXEC)

Oct 16 16:20:33 ubuntu20stack systemd[1]: wazuh-indexer-performance-analyzer.service: Scheduled restart job,>
Oct 16 16:20:33 ubuntu20stack systemd[1]: Stopped Wazuh-indexer Performance Analyzer.
Oct 16 16:20:33 ubuntu20stack systemd[1]: wazuh-indexer-performance-analyzer.service: Start request repeated>
Oct 16 16:20:33 ubuntu20stack systemd[1]: wazuh-indexer-performance-analyzer.service: Failed with result 'ex>
Oct 16 16:20:33 ubuntu20stack systemd[1]: Failed to start Wazuh-indexer Performance Analyzer.
```

**Comment by Deblintrake09** [comment]
## Update

After fixing the path and building new package, the system still does not start. A new error appears:

```
The job identifier is 13115 and the job result is done.
dic 19 22:38:28 pop-os systemd[1]: Started Wazuh-indexer Performance Analyzer.
░░ Subject: A start job for unit wazuh-indexer-performance-analyzer.service has finished successfully
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit wazuh-indexer-performance-analyzer.service has finished successfully.
░░ 
░░ The job identifier is 13115.
dic 19 22:38:28 pop-os performance-analyzer-agent-cli[386208]: OPENSEARCH_PATH_CONF variable needs to be set or passed in as a parameter.
dic 19 22:38:28 pop-os performance-analyzer-agent-cli[386208]: Note: It should be set to /usr/share/wazuh-indexer/config (for docker or tar) or /etc/opensearch (for rpm or deb)
dic 19 22:38:28 pop-os systemd[1]: wazuh-indexer-performance-analyzer.service: Main process exited, code=exited, status=1/FAILURE
```

The deb package was installed in an ubuntu endpoint but neither of both proposed paths were present in the system.

More research needed.

**Comment by Deblintrake09** [comment]
## Research 20/12

Looking at the [perferormance-analyzer repository](https://github.com/opensearch-project/performance-analyzer-rca/blob/main) we can see that there are two instances of the  `log4j2.xml` file, one being inside the tests folder and the other one inside `perferormance-analyzer-rca/config`

![image](https://github.com/wazuh/wazuh-packages/assets/14501079/670807f1-9774-4fc8-8f1d-542a2d9f01d8)


- We can find the file located inside that folder in our build inside the same folder that it is located insidye the `performance-analyzer` repository

- When checking the [opensearch-build repository](https://github.com/opensearch-project/opensearch-build/tree/main) that is used as a base for our package, the only reference to the file is inside the installer script used when installing from tar file.

https://github.com/opensearch-project/opensearch-build/blob/a13aa1c950d663bb9cec138eac78f7745a4338ef/scripts/startup/tar/linux/opensearch-tar-install.sh#L7-L19

**Comment by pro-akim** [comment]
## Review Notes

LGTM

Tested :green_circle: 

```
root@mediumubuntu:/home/vagrant/wazuh-packages/stack/indexer/deb# systemctl status wazuh-indexer-performance-analyzer
● wazuh-indexer-performance-analyzer.service - Wazuh-indexer Performance Analyzer
     Loaded: loaded (/lib/systemd/system/wazuh-indexer-performance-analyzer.service; disabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-12-20 15:19:33 UTC; 5s ago
   Main PID: 35732 (java)
      Tasks: 24 (limit: 14266)
     Memory: 116.2M
     CGroup: /system.slice/wazuh-indexer-performance-analyzer.service
             └─35732 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Xms4m -Xmx64m -XX:+UseSerialGC -Dlog4j.configurationFile=/etc/wazuh-indexe>

```

**Comment by davidjiglesias** [comment]
Please @Deblintrake09, ensure all commits for the PR are signed.

**Comment by davidjiglesias** [comment]
Still 1 commit unsigned.

**Comment by davidjiglesias** [comment]
LGTM
