### ISSUE TITLE
Upward merge into 4.5.0 branch for wazuh-packages repository due to OVA `4.4.5` changes

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-packages#2330]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.4-into-4.5.0`.

## Tasks
- [x] Merge branch `4.4.5` into `4.4` on wazuh-packages repository.
- [x] Delete branch `4.4.5` from wazuh-packages repository.
- [ ] Merge branch `4.4` into branch `4.5.0` on wazuh-packages repository.

Parent issue: https://github.com/wazuh/wazuh/issues/18208
