### ISSUE TITLE
Support new stage Alpha 1 for 4.5.1 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2335]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.1 in the wazuh-packages repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.1
- [x] Create tag v4.5.1-alpha1 from branch 4.5.1 on wazuh-packages repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.5.1-alpha1
