### ISSUE TITLE
Support new Wazuh version 4.5.3 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2387]
## Description

This issue attempts to support a new version 4.5.3 in the wazuh-packages repository.

## Tasks

- [x] Create numbered branch for version (4.5.3) using branch 4.5.2 on wazuh-packages repository.
- [x] Bump 4.5.3 branch to 4.5.3 version, including revision and changelog.
- [x] Build and push testing images for GitHub actions.
