### ISSUE TITLE
Create vulnerabilities index

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-packages#2390]
## Description

We're working on a new vulnerability detector module (see https://github.com/wazuh/wazuh/issues/14153) which will upload all the vulnerabilities it finds into `wazuh-indexer`.

The module will create an index and set it up with a mappings' template.

We want to adopt the ECS fields as our schema for this index, so it must contain ECS valid documents only. We will support the following fields in the vulnerability index:

- ecs
- base
- event
- agent
- package
- operating system
- vulnerability

The description for each field is described in https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html and the mappings' definition for each field is in the repository https://github.com/elastic/ecs

## Implementation restrictions

- [ ] We must adapt the mappings to work correctly on `wazuh-indexer`
- [ ] Mappings compliance must be mandatory

## Plan

- [ ] Create VD mappings for `wazuh-indexer`
- [ ] Design vulnerability index to support up to 50000 endpoints
- [ ] Design vulnerability index queries alongside frontend team
