### ISSUE TITLE
Bump Wazuh indexer to OpenSearch 2.8.0

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2391]
## Description

It is necessary to adapt the Wazuh indexer to version 2.8.0 of OpenSearch
Request: https://github.com/wazuh/internal-devel-requests/issues/194

## Tasks

- [x] Bump OpenSearch version https://github.com/wazuh/wazuh-packages/blob/55cfe35dfa163ac951884c22a390fe1838651766/stack/indexer/base/builder.sh#L19
- [x] Build the package locally
  - [x] RPM
  - [x] DEB
- [ ] ~~Test the package (CentOS/Debian)~~
   - [ ] ~~Install~~
   - [ ] ~~Upgrade~~
   - [ ] ~~Remove~~
   - [ ] ~~Logs~~
   - [ ] ~~Alerts~~
   - [ ] ~~Versions references~~
 - [x] Modify https://github.com/wazuh/wazuh-packages/blob/master/README.md matrix with the new version 
 - [x] Test the package using the Test_stack pipeline

## Validation

- [ ] The package presents normal operation and without errors

---

### Working branch

- https://github.com/wazuh/wazuh-packages/tree/2391-bump-wazuh-indexer

**Comment by Deblintrake09** [comment]
## Update 30/08/2023
- Bumped opensearch version to 2.8.0
- Tried to generate new version.
   - Found permission errors caused by files versions and names changing

**Comment by rauldpm** [comment]
## Update report

- I am working on Wazuh indexer RPM
- Changed base version on custom branch, building package

**Comment by Deblintrake09** [comment]
## Testing on debian package

- Install
```
# apt install -f /home/qa/wazuh-packages/stack/indexer/deb/output/wazuh-indexer_4.6.0-1_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'wazuh-indexer' instead of '/home/qa/wazuh-packages/stack/indexer/deb/output/wazuh-indexer_4.6.0-1_amd64.deb'
The following packages were automatically installed and are no longer required:
  libpython2-dev libpython2.7 libpython2.7-dev linux-image-5.13.0-1021-aws linux-modules-5.13.0-1021-aws python2-dev python2.7-dev
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  wazuh-indexer
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/685 MB of archives.
After this operation, 969 MB of additional disk space will be used.
Get:1 /home/qa/wazuh-packages/stack/indexer/deb/output/wazuh-indexer_4.6.0-1_amd64.deb wazuh-indexer amd64 4.6.0-1 [685 MB]
Selecting previously unselected package wazuh-indexer.
(Reading database ... 120151 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.6.0-1_amd64.deb ...
Unpacking wazuh-indexer (4.6.0-1) ...
Setting up wazuh-indexer (4.6.0-1) ...
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
Processing triggers for libc-bin (2.35-0ubuntu3) ...
Scanning processes...                                                                                                                                                                                      
Scanning linux images...                                                                                                                                                                                   

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
```
- Uninstall
```
# apt remove --purge wazuh-indexer
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libpython2-dev libpython2.7 libpython2.7-dev linux-image-5.13.0-1021-aws linux-modules-5.13.0-1021-aws python2-dev python2.7-dev
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  wazuh-indexer*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 969 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 121240 files and directories currently installed.)
Removing wazuh-indexer (4.6.0-1) ...
Stopping wazuh-indexer service... OK
(Reading database ... 120151 files and directories currently installed.)
Purging configuration files for wazuh-indexer (4.6.0-1) ...
Deleting configuration directory... OK
dpkg: warning: while removing wazuh-indexer, directory '/var/lib/wazuh-indexer' not empty so not removed
```

**Comment by Deblintrake09** [comment]
## Local Testing on RPM package

- Build :green_circle: 
```
Provides: wazuh-indexer = 4.6.0-1 wazuh-indexer(x86-64) = 4.6.0-1
Requires(interp): /bin/sh /bin/sh /bin/sh /bin/sh /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires(pre): /bin/sh
Requires(post): /bin/sh
Requires(preun): /bin/sh
Requires(postun): /bin/sh
Requires(posttrans): /bin/sh
Checking for unpackaged file(s): /usr/lib/rpm/check-files /build/rpmbuild/BUILDROOT/wazuh-indexer-4.6.0-1.x86_64
Wrote: /build/rpmbuild/SRPMS/wazuh-indexer-4.6.0-1.src.rpm
Wrote: /build/rpmbuild/RPMS/x86_64/wazuh-indexer-4.6.0-1.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.AqiN0q
+ umask 022
+ cd /build/rpmbuild/BUILD
+ rm -fr /build/rpmbuild/BUILDROOT/wazuh-indexer-4.6.0-1.x86_64
+ exit 0
+ cd /build/rpmbuild/RPMS/x86_64
+ sha512sum wazuh-indexer-4.6.0-1.x86_64.rpm
+ find /build/rpmbuild/RPMS/x86_64/ -maxdepth 3 -type f -name 'wazuh-indexer-4.6.0-1*' -exec mv '{}' /tmp/ ';'
++ ls -Art /home/qa/wazuh-packages/stack/indexer/rpm/output
++ tail -n 1
+ echo 'Package wazuh-indexer-4.6.0-1.x86_64.rpm.sha512 added to /home/qa/wazuh-packages/stack/indexer/rpm/output.'
Package wazuh-indexer-4.6.0-1.x86_64.rpm.sha512 added to /home/qa/wazuh-packages/stack/indexer/rpm/output.
```

- Install :green_circle: 
```
# yum install output/wazuh-indexer-4.6.0-1.x86_64.rpm
Última comprobación de caducidad de metadatos hecha hace 2:35:51, el jue 31 ago 2023 19:05:10 UTC.
Dependencias resueltas.
===========================================================================================================================================================================================================
 Paquete                                             Arquitectura                                 Versión                                         Repositorio                                         Tam.
===========================================================================================================================================================================================================
Instalando:
 wazuh-indexer                                       x86_64                                       4.6.0-1                                         @commandline                                       673 M

Resumen de la transacción
===========================================================================================================================================================================================================
Instalar  1 Paquete

Tamaño total: 673 M
Tamaño instalado: 930 M
¿Está de acuerdo [s/N]?: s
Descargando paquetes:
Ejecutando verificación de operación
Verificación de operación exitosa.
Ejecutando prueba de operaciones
Prueba de operación exitosa.
Ejecutando operación
  Preparando          :                                                                                                                                                                                1/1 
  Ejecutando scriptlet: wazuh-indexer-4.6.0-1.x86_64                                                                                                                                                   1/1 
  Instalando          : wazuh-indexer-4.6.0-1.x86_64                                                                                                                                                   1/1 
  Ejecutando scriptlet: wazuh-indexer-4.6.0-1.x86_64                                                                                                                                                   1/1 
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore

[/usr/lib/tmpfiles.d/pesign.conf:1] Line references path below legacy directory /var/run/, updating /var/run/pesign → /run/pesign; please update the tmpfiles.d/ drop-in file accordingly.

  Verificando         : wazuh-indexer-4.6.0-1.x86_64                                                                                                                                                   1/1 

Instalado:
  wazuh-indexer-4.6.0-1.x86_64                                                                                                                                                                             

¡Listo!
```
- Remove :green_circle: 
```
# yum remove -y wazuh-indexer
Dependencias resueltas.
===========================================================================================================================================================================================================
 Paquete                                             Arquitectura                                 Versión                                        Repositorio                                          Tam.
===========================================================================================================================================================================================================
Eliminando:
 wazuh-indexer                                       x86_64                                       4.6.0-1                                        @@commandline                                       930 M

Resumen de la transacción
===========================================================================================================================================================================================================
Eliminar  1 Paquete

Espacio liberado: 930 M
Ejecutando verificación de operación
Verificación de operación exitosa.
Ejecutando prueba de operaciones
Prueba de operación exitosa.
Ejecutando operación
  Preparando          :                                                                                                                                                                                1/1 
  Ejecutando scriptlet: wazuh-indexer-4.6.0-1.x86_64                                                                                                                                                   1/1 
Stopping wazuh-indexer service... OK

  Eliminando          : wazuh-indexer-4.6.0-1.x86_64                                                                                                                                                   1/1 
  Ejecutando scriptlet: wazuh-indexer-4.6.0-1.x86_64                                                                                                                                                   1/1 
  Verificando         : wazuh-indexer-4.6.0-1.x86_64                                                                                                                                                   1/1 

Eliminado:
  wazuh-indexer-4.6.0-1.x86_64                                                                                                                                                                             

¡Listo!
```

**Comment by Deblintrake09** [comment]
## Update Report

Package building has been sucessful for RPM and Debian in Jenkins:
- RPM: https://ci.wazuh.info/view/Packages/job/Packages_builder/163730/
- Debian: https://ci.wazuh.info/view/Packages/job/Packages_builder/163663/

- Testing on the `test_stack`:
   - Debian: https://ci.wazuh.info/job/Test_stack_tier/
   - RPM: Waiting for indexer package to be uploaded to S3

**Comment by Deblintrake09** [comment]
## Update report - Local test of RPM stack

<details><summary> Installed Indexer :green_circle: </summary>
```

```
</details>
<details><summary> Installed Manager :green_circle: </summary>
```
# bash wazuh-install.sh --wazuh-server wazuh-1 -o
31/08/2023 22:42:50 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
31/08/2023 22:42:50 INFO: Verbose logging redirected to /var/log/wazuh-install.log
31/08/2023 22:42:52 INFO: --- Removing existing Wazuh installation ---
31/08/2023 22:42:52 INFO: Removing Filebeat.
31/08/2023 22:42:53 INFO: Filebeat removed.
31/08/2023 22:42:53 INFO: Installation cleaned.
31/08/2023 22:43:00 INFO: Wazuh repository added.
31/08/2023 22:43:00 INFO: --- Wazuh server ---
31/08/2023 22:43:00 INFO: Starting the Wazuh manager installation.
31/08/2023 22:43:51 INFO: Wazuh manager installation finished.
31/08/2023 22:43:51 INFO: Starting service wazuh-manager.
31/08/2023 22:44:02 INFO: wazuh-manager service started.
31/08/2023 22:44:02 INFO: Starting Filebeat installation.
31/08/2023 22:44:11 INFO: Filebeat installation finished.
31/08/2023 22:44:11 INFO: Filebeat post-install configuration finished.
31/08/2023 22:44:17 INFO: Starting service filebeat.
31/08/2023 22:44:17 INFO: filebeat service started.
31/08/2023 22:44:17 INFO: Installation finished.
```
</details>
<details><summary> Installed Dashboard :green_circle: </summary>
```
[root@ip-172-31-14-71 /]# bash wazuh-install.sh --wazuh-dashboard dashboard -o
31/08/2023 22:44:55 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
31/08/2023 22:44:55 INFO: Verbose logging redirected to /var/log/wazuh-install.log
31/08/2023 22:44:58 INFO: --- Removing existing Wazuh installation ---
31/08/2023 22:44:58 INFO: Installation cleaned.
31/08/2023 22:45:05 INFO: Wazuh repository added.
dashboard
31/08/2023 22:45:05 INFO: --- Wazuh dashboard ----
31/08/2023 22:45:05 INFO: Starting Wazuh dashboard installation.
31/08/2023 22:46:11 INFO: Wazuh dashboard installation finished.
31/08/2023 22:46:12 INFO: Wazuh dashboard post-install configuration finished.
31/08/2023 22:46:12 INFO: Starting service wazuh-dashboard.
31/08/2023 22:46:12 INFO: wazuh-dashboard service started.
31
/08/2023 22:46:26 INFO: Initializing Wazuh dashboard web application.
31/08/2023 22:46:26 INFO: Wazuh dashboard web application initialized.
31/08/2023 22:46:26 INFO: --- Summary ---
31/08/2023 22:46:26 INFO: You can access the web interface https://172.31.14.71
    User: admin
    Password: TYS.pAjVx2db7Ypjw+BC?Zp8r4ykms7j
31/08/2023 22:46:26 INFO: Installation finished.

# systemctl status wazuh-dashboard
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2023-08-31 22:46:16 UTC; 39min ago
 Main PID: 58026 (node)
    Tasks: 11 (limit: 47400)
   Memory: 140.4M
   CGroup: /system.slice/wazuh-dashboard.service
```
</details>

<details><summary> Test app behavior  :red_circle:  </summary>

- Login works properly :green_circle: 
![Login](https://github.com/wazuh/wazuh-packages/assets/14501079/05d817ac-28e8-494a-aab1-acd540751674)

- Healthcheck works properly :red_circle: 
![imagen](https://github.com/wazuh/wazuh-packages/assets/14501079/ae80796b-ba2d-410c-8046-3e0607b8dce3)

- Connect agent to cluster :green_circle: 
![imagen](https://github.com/wazuh/wazuh-packages/assets/14501079/2d45562e-1408-495f-a5b4-3928839a7259)

- Check agents alerts :red_circle: 
No alerts shown for agent since the `wazuh-alerts-*` is not present.
- Alerts in manager
```
# cat /var/ossec/logs/alerts/alerts.json | grep 001
{"timestamp":"2023-09-01T00:02:07.379+0000","rule":{"level":3,"description":"Log file rotated.","id":"591","firedtimes":1,"mail":false,"groups":["ossec"],"pci_dss":["10.5.2","10.5.5"],"gpg13":["10.1"],"gdpr":["II_5.1.f","IV_35.7.d"],"hipaa":["164.312.b"],"nist_800_53":["AU.9"],"tsc":["CC6.1","CC7.2","CC7.3","PI1.4","PI1.5","CC7.1","CC8.1"]},"agent":{"id":"001","name":"ubuntu2204.localdomain","ip":"10.0.2.15"},"manager":{"name":"ip-172-31-14-71.ec2.internal"},"id":"1693526527.0","full_log":"ossec: File rotated (inode changed): '/var/log/dpkg.log'.","decoder":{"name":"ossec"},"location":"logcollector"}
```

</details>

**Comment by juliamagan** [comment]
<details>
<summary>RPM indexer :red_circle:</summary>
<br>

- Install:

```shell
[root@wazuh-manager vagrant]# yum install -y /home/vagrant/wazuh-indexer-4.6.0-wp.2392.x86_64.rpm 
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:08:14 ago on Fri Sep  1 06:52:26 2023.
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                              Architecture                                  Version                                              Repository                                           Size
===================================================================================================================================================================================================================
Installing:
 wazuh-indexer                                        x86_64                                        4.6.0-wp.2392                                        @commandline                                        673 M

Transaction Summary
===================================================================================================================================================================================================================
Install  1 Package

Total size: 673 M
Installed size: 930 M
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                           1/1 
  Running scriptlet: wazuh-indexer-4.6.0-wp.2392.x86_64                                                                                                                                                        1/1 
  Installing       : wazuh-indexer-4.6.0-wp.2392.x86_64                                                                                                                                                        1/1 
  Running scriptlet: wazuh-indexer-4.6.0-wp.2392.x86_64                                                                                                                                                        1/1 
could not find java in bundled jdk at /usr/share/wazuh-indexer/jdk/bin/java
chown: cannot access '/etc/wazuh-indexer/opensearch.keystore': No such file or directory
chmod: cannot access '/etc/wazuh-indexer/opensearch.keystore': No such file or directory
md5sum: /etc/wazuh-indexer/opensearch.keystore: No such file or directory

[/usr/lib/tmpfiles.d/pesign.conf:1] Line references path below legacy directory /var/run/, updating /var/run/pesign → /run/pesign; please update the tmpfiles.d/ drop-in file accordingly.

  Verifying        : wazuh-indexer-4.6.0-wp.2392.x86_64                                                                                                                                                        1/1 

Installed:
  wazuh-indexer-4.6.0-wp.2392.x86_64                                                                                                                                                                               

Complete!
```

- Configure certificates:

```shell
[root@wazuh-manager vagrant]# nano /etc/wazuh-indexer/opensearch.yml 
[root@wazuh-manager vagrant]# NODE_NAME=node-1
[root@wazuh-manager vagrant]# mkdir /etc/wazuh-indexer/certs
[root@wazuh-manager vagrant]# tar -xf ./wazuh-certificates.tar -C /etc/wazuh-indexer/certs/ ./$NODE_NAME.pem ./$NODE_NAME-key.pem ./admin.pem ./admin-key.pem ./root-ca.pem
[root@wazuh-manager vagrant]# mv -n /etc/wazuh-indexer/certs/$NODE_NAME.pem /etc/wazuh-indexer/certs/indexer.pem
[root@wazuh-manager vagrant]# mv -n /etc/wazuh-indexer/certs/$NODE_NAME-key.pem /etc/wazuh-indexer/certs/indexer-key.pem
[root@wazuh-manager vagrant]# chmod 500 /etc/wazuh-indexer/certs
[root@wazuh-manager vagrant]# chmod 400 /etc/wazuh-indexer/certs/*
[root@wazuh-manager vagrant]# chown -R wazuh-indexer:wazuh-indexer /etc/wazuh-indexer/certs
```

- Start indexer:

```shell
[root@wazuh-manager vagrant]# systemctl start wazuh-indexer
Job for wazuh-indexer.service failed because the control process exited with error code.
See "systemctl status wazuh-indexer.service" and "journalctl -xe" for details.
```

- Error:

```
-- Unit wazuh-indexer.service has begun starting up.
Sep 01 07:13:16 wazuh-manager systemd-entrypoint[51382]: could not find java in bundled jdk at /usr/share/wazuh-indexer/jdk/bin/java
Sep 01 07:13:16 wazuh-manager systemd[1]: wazuh-indexer.service: Main process exited, code=exited, status=1/FAILURE
Sep 01 07:13:16 wazuh-manager systemd[1]: wazuh-indexer.service: Failed with result 'exit-code'.
```

</details>

<details>
<summary>DEB indexer :red_circle:</summary>
<br>

- Install:

```shell
[root@wazuh-manager vagrant]# yum install -y /home/vagrant/wazuh-indexer-4.6.0-wp.2392.x86_64.rpm 
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:08:14 ago on Fri Sep  1 06:52:26 2023.
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                              Architecture                                  Version                                              Repository                                           Size
===================================================================================================================================================================================================================
Installing:
 wazuh-indexer                                        x86_64                                        4.6.0-wp.2392                                        @commandline                                        673 M

Transaction Summary
===================================================================================================================================================================================================================
Install  1 Package

Total size: 673 M
Installed size: 930 M
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                           1/1 
  Running scriptlet: wazuh-indexer-4.6.0-wp.2392.x86_64                                                                                                                                                        1/1 root@ubuntu-focal:/home/vagrant# apt install -y /home/vagrant/wazuh-indexer_4.6.0-wp.2392_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'wazuh-indexer' instead of '/home/vagrant/wazuh-indexer_4.6.0-wp.2392_amd64.deb'
The following NEW packages will be installed:
  wazuh-indexer
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/685 MB of archives.
After this operation, 969 MB of additional disk space will be used.
Get:1 /home/vagrant/wazuh-indexer_4.6.0-wp.2392_amd64.deb wazuh-indexer amd64 4.6.0-wp.2392 [685 MB]
Selecting previously unselected package wazuh-indexer.
(Reading database ... 63489 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.6.0-wp.2392_amd64.deb ...
Creating wazuh-indexer group... OK
Creating wazuh-indexer user... OK
Unpacking wazuh-indexer (4.6.0-wp.2392) ...
Setting up wazuh-indexer (4.6.0-wp.2392) ...
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
Processing triggers for systemd (245.4-4ubuntu3.17) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
```

- Configure certificates:

```shell
root@ubuntu-focal:/home/vagrant# nano /etc/wazuh-indexer/opensearch.yml 
root@ubuntu-focal:/home/vagrant# NODE_NAME=node-1
root@ubuntu-focal:/home/vagrant# mkdir /etc/wazuh-indexer/certs
root@ubuntu-focal:/home/vagrant# tar -xf ./wazuh-certificates.tar -C /etc/wazuh-indexer/certs/ ./$NODE_NAME.pem ./$NODE_NAME-key.pem ./admin.pem ./admin-key.pem ./root-ca.pem
root@ubuntu-focal:/home/vagrant# mv -n /etc/wazuh-indexer/certs/$NODE_NAME.pem /etc/wazuh-indexer/certs/indexer.pem
root@ubuntu-focal:/home/vagrant# mv -n /etc/wazuh-indexer/certs/$NODE_NAME-key.pem /etc/wazuh-indexer/certs/indexer-key.pem
root@ubuntu-focal:/home/vagrant# chmod 500 /etc/wazuh-indexer/certs
root@ubuntu-focal:/home/vagrant# chmod 400 /etc/wazuh-indexer/certs/*
root@ubuntu-focal:/home/vagrant# chown -R wazuh-indexer:wazuh-indexer /etc/wazuh-indexer/certs
```

- Start indexer:

```shell
root@ubuntu-focal:/home/vagrant# systemctl daemon-reload
root@ubuntu-focal:/home/vagrant# systemctl enable wazuh-indexer
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-indexer.service → /lib/systemd/system/wazuh-indexer.service.
root@ubuntu-focal:/home/vagrant# systemctl start wazuh-indexer
Job for wazuh-indexer.service failed because the control process exited with error code.
See "systemctl status wazuh-indexer.service" and "journalctl -xe" for details.
```

- Error:

```
-- A start job for unit wazuh-indexer.service has begun execution.
-- 
-- The job identifier is 928.
Sep 01 07:44:36 ubuntu-focal systemd[3335]: wazuh-indexer.service: Failed to execute command: Permission denied
Sep 01 07:44:36 ubuntu-focal systemd[3335]: wazuh-indexer.service: Failed at step EXEC spawning /usr/share/wazuh-indexer/bin/systemd-entrypoint: Permission denied
-- Subject: Process /usr/share/wazuh-indexer/bin/systemd-entrypoint could not be executed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The process /usr/share/wazuh-indexer/bin/systemd-entrypoint could not be executed and failed.
```

`systemd-entrypoint` permissions should be 750, but they are:

```shell
root@ubuntu-focal:/home/vagrant# ls -lah /usr/share/wazuh-indexer/bin/systemd-entrypoint 
-rw-r----- 1 wazuh-indexer wazuh-indexer 583 Aug 31 18:54 /usr/share/wazuh-indexer/bin/systemd-entrypoint
```

</details>

**Comment by rauldpm** [comment]
## Update report

- Error installing Wazuh indexer 4.6.0 wp.2392

```
Running transaction
  Installing : wazuh-indexer-4.6.0-wp.2392.x86_64                                                                                                                                                              1/1 
could not find java in bundled jdk at /usr/share/wazuh-indexer/jdk/bin/java
chown: cannot access ‘/etc/wazuh-indexer/opensearch.keystore’: No such file or directory
chmod: cannot access ‘/etc/wazuh-indexer/opensearch.keystore’: No such file or directory
md5sum: /etc/wazuh-indexer/opensearch.keystore: No such file or directory
  Verifying  : wazuh-indexer-4.6.0-wp.2392.x86_64  
```

**Comment by rauldpm** [comment]
## Update report - DEB

- The Wazuh indexer package has been installed without error

```
root@debian11:/home/vagrant# apt install ./wazuh-indexer_4.6.0-1_amd64.deb -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'wazuh-indexer' instead of './wazuh-indexer_4.6.0-1_amd64.deb'
The following NEW packages will be installed:
  wazuh-indexer
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/684 MB of archives.
After this operation, 969 MB of additional disk space will be used.
Get:1 /home/vagrant/wazuh-indexer_4.6.0-1_amd64.deb wazuh-indexer amd64 4.6.0-1 [684 MB]
Selecting previously unselected package wazuh-indexer.
(Reading database ... 68876 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.6.0-1_amd64.deb ...
Creating wazuh-indexer group... OK
Creating wazuh-indexer user... OK
Unpacking wazuh-indexer (4.6.0-1) ...
Setting up wazuh-indexer (4.6.0-1) ...
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
```

**Comment by rauldpm** [comment]
## Update report

- Building new packages for final testing
  - https://packages-dev.wazuh.com/warehouse/test/4.6/rpm/wazuh-dashboard-4.6.0-wp.2392.x86_64.rpm
  - https://packages-dev.wazuh.com/warehouse/test/4.6/rpm/wazuh-indexer-4.6.0-wp.2392.x86_64.rpm
  - https://packages-dev.wazuh.com/warehouse/test/4.6/rpm/wazuh-manager-4.6.0-wp.2392.x86_64.rpm
  - https://packages-dev.wazuh.com/warehouse/test/4.6/deb/wazuh-dashboard_4.6.0-wp.2392_amd64.deb
  - https://packages-dev.wazuh.com/warehouse/test/4.6/deb/wazuh-indexer_4.6.0-wp.2392_amd64.deb
  - https://packages-dev.wazuh.com/warehouse/test/4.6/deb/wazuh-manager_4.6.0-wp.2392_amd64.deb
- Launched: https://ci.wazuh.info/job/Test_stack_tier/78/

**Comment by Deblintrake09** [comment]
## Update report

Manual testing of setting up the Wazuh Indexer shows that it is installed and starts correctly, but when connecting to a dashboard we can see the `wazuh-alerts*` template is missing, as it was reported [here](https://github.com/wazuh/wazuh-packages/issues/2391#issuecomment-1701931288).

- This issue is related to https://github.com/wazuh/wazuh-packages/issues/2404.

**Comment by Deblintrake09** [comment]
## Update report

Testing done on `test_stack` pipeline :green_circle: 
- https://ci.wazuh.info/job/Test_stack_tier/79/
- https://ci.wazuh.info/job/Test_stack_tier/80/

**Comment by rauldpm** [comment]
## Update report

- Working on a bug when changing passwords with the Wazuh indexer script

**Comment by Deblintrake09** [comment]
# Update report
- Working on indexer template installation
