### ISSUE TITLE
Bump Wazuh dashboard to OpenSearch Dashboards 2.9.0

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2403]
## Description
It is necessary to adapt the Wazuh dashboard to version 2.9.0 of OpenSearch Dashboards
Request: https://github.com/wazuh/internal-devel-requests/issues/197

## Tasks

- [x] Bump OpenSearch Dashboards version https://github.com/wazuh/wazuh-packages/blob/4.7.0/stack/dashboard/base/builder.sh#L19
- [x] Build the package locally
  - [x] RPM
  - [x] DEB
 - [ ] Test the packages locally
 - [x] Modify https://github.com/wazuh/wazuh-packages/blob/master/README.md matrix with the new version 
 - [ ] Test the package using the Test_stack pipeline
 - [ ] Test the package using the Wazuh installation assistant
 - [ ] Create ECS and ECR resources (base, rpm, deb)

## Validation

- [ ] The package presents normal operation and without errors

---

### Working branch

- TBD

## Tasks

- [ ]

## Validation

- [ ]

---

## Conclusion 

Due to the errors and warnings detected in the bump from OpenSearch, it was decided to stop the bump process and keep 2.8.0 for 4.7.0

**Comment by Deblintrake09** [comment]
## Update 05/10
- Start applying changes
- Try to build package
- Cannot build dashboardapp on pipeline
   - Build locally - Requested permissions to upload package to s3 bucket.

**Comment by Deblintrake09** [comment]
## Update

- Created RPM dashboard package
```
[root@centos7 rpm]# ./build_package.sh -b no --app-url https://packages-dev.wazuh.com/trash/ui/dashboard/wazuh-4.7.0-2403.zip
[+] Building 1.7s (14/14) FINISHED                                                                                                                                                          docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                  0.0s
 => => transferring dockerfile: 826B                                                                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/amd64/centos:7                                                                                                                                             1.7s
 => [1/9] FROM docker.io/amd64/centos:7@sha256:dead07b4d8ed7e29e98de0f4504d87e8880d4347859d839686a31da35a3b532f                                                                                       0.0s
 => [internal] load build context                                                                                                                                                                     0.0s
 => => transferring context: 2.77kB                                                                                                                                                                   0.0s
 => CACHED [2/9] RUN yum install -y http://packages.wazuh.com/utils/pkg/epel-release-latest-7.noarch.rpm                                                                                              0.0s
 => CACHED [3/9] RUN yum clean all && yum update -y                                                                                                                                                   0.0s
 => CACHED [4/9] RUN yum install -y openssh-clients sudo gnupg     yum-utils redhat-rpm-config rpm-devel     zlib zlib-devel rpm-build autoconf automake     glibc-devel libtool perl                 0.0s
 => CACHED [5/9] RUN yum install -y https://repo.ius.io/ius-release-el$(rpm -E '%{rhel}').rpm                                                                                                         0.0s
 => CACHED [6/9] RUN yum update -y && yum install -y python3                                                                                                                                          0.0s
 => CACHED [7/9] RUN ln -fs /usr/bin/python3.6 /usr/bin/python                                                                                                                                        0.0s
 => CACHED [8/9] ADD builder.sh /usr/local/bin/builder                                                                                                                                                0.0s
 => CACHED [9/9] RUN chmod +x /usr/local/bin/builder                                                                                                                                                  0.0s
 => exporting to image                                                                                                                                                                                0.0s
 => => exporting layers                                                                                                                                                                               0.0s
 => => writing image sha256:61904d1408ce0c9453442272511603168478465582bd32bb8de1995bc17099b8                                                                                                          0.0s
 => => naming to docker.io/library/rpm_dashboard_builder_x86                                                                                                                                          0.0s
Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.36Cjwj
+ umask 022
+ cd /build/rpmbuild/BUILD
+ cp /tmp/wazuh-dashboard-base-4.7.0-1-linux-x64.tar.xz ./
+ groupadd wazuh-dashboard
+ useradd -g wazuh-dashboard wazuh-dashboard
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.6Fd0Wg
+ umask 022
+ cd /build/rpmbuild/BUILD
+ tar -xf wazuh-dashboard-base-4.7.0-1-linux-x64.tar.xz
+ sed -i 's/OSD_NODE_OPTS_PREFIX/OSD_PATH_CONF="\/etc\/wazuh-dashboard" OSD_NODE_OPTS_PREFIX/g' wazuh-dashboard-base/bin/opensearch-dashboards
+ sed -i 's/OSD_USE_NODE_JS_FILE_PATH/OSD_PATH_CONF="\/etc\/wazuh-dashboard" OSD_USE_NODE_JS_FILE_PATH/g' wazuh-dashboard-base/bin/opensearch-dashboards-keystore
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.Ha3V7R
+ umask 022
+ cd /build/rpmbuild/BUILD
+ '[' /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64 '!=' / ']'
+ rm -rf /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64
++ dirname /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64
+ mkdir -p /build/rpmbuild/BUILDROOT
+ mkdir /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64
+ mkdir -p /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/etc/wazuh-dashboard
+ mkdir -p /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard
+ mkdir -p /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/etc/systemd/system
+ mkdir -p /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/etc/rc.d/init.d
+ mkdir -p /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/etc/default
+ cp wazuh-dashboard-base/etc/node.options /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/etc/wazuh-dashboard
+ cp wazuh-dashboard-base/etc/opensearch_dashboards.yml /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/etc/wazuh-dashboard
+ cp wazuh-dashboard-base/VERSION /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard
+ mv wazuh-dashboard-base/LICENSE.txt wazuh-dashboard-base/NOTICE.txt wazuh-dashboard-base/README.txt wazuh-dashboard-base/VERSION wazuh-dashboard-base/assets wazuh-dashboard-base/bin wazuh-dashboard-base/config wazuh-dashboard-base/data wazuh-dashboard-base/etc wazuh-dashboard-base/manifest.yml wazuh-dashboard-base/node wazuh-dashboard-base/node_modules wazuh-dashboard-base/package.json wazuh-dashboard-base/plugins wazuh-dashboard-base/src /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard
+ mkdir -p /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard/config
+ cp /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard/etc/services/wazuh-dashboard.service /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/etc/systemd/system/wazuh-dashboard.service
+ cp /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard/etc/services/default /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/etc/default/wazuh-dashboard
+ chmod 640 /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/etc/systemd/system/wazuh-dashboard.service
+ chmod 640 /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/etc/default/wazuh-dashboard
+ rm -rf /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard/etc/
+ find /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard -exec chown wazuh-dashboard:wazuh-dashboard '{}' ';'
+ find /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/etc/wazuh-dashboard -exec chown wazuh-dashboard:wazuh-dashboard '{}' ';'
+ chown root:root /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/etc/systemd/system/wazuh-dashboard.service
+ '[' 4.7.0 = 99.99.0 ']'
+ runuser wazuh-dashboard --shell=/bin/bash '--command=/build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard/bin/opensearch-dashboards-plugin install https://packages-dev.wazuh.com/trash/ui/dashboard/wazuh-4.7.0-2403.zip'
Attempting to transfer from https://packages-dev.wazuh.com/trash/ui/dashboard/wazuh-4.7.0-2403.zip
Transferring 35445301 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete
+ find /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard/plugins/wazuh/ -exec chown wazuh-dashboard:wazuh-dashboard '{}' ';'
+ find /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard/plugins/wazuh/ -type f -perm 644 -exec chmod 640 '{}' ';'
+ find /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard/plugins/wazuh/ -type f -perm 755 -exec chmod 750 '{}' ';'
+ find /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard/plugins/wazuh/ -type d -exec chmod 750 '{}' ';'
+ find /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64/usr/share/wazuh-dashboard/plugins/wazuh/ -type f -perm 744 -exec chmod 740 '{}' ';'
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: wazuh-dashboard-4.7.0-1.x86_64
warning: File listed twice: /usr/share/wazuh-dashboard/node/bin/node
Provides: wazuh-dashboard = 4.7.0-1 wazuh-dashboard(x86-64) = 4.7.0-1
Requires(interp): /bin/sh /bin/sh /bin/sh /bin/sh /bin/sh
Requires(rpmlib): rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(CompressedFileNames) <= 3.0.4-1
Requires(pre): /usr/sbin/groupadd /usr/sbin/useradd /bin/sh
Requires(post): /bin/sh
Requires(preun): /sbin/service /bin/sh
Requires(postun): /sbin/service /bin/sh
Requires(posttrans): /bin/sh
Checking for unpackaged file(s): /usr/lib/rpm/check-files /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64
Wrote: /build/rpmbuild/SRPMS/wazuh-dashboard-4.7.0-1.src.rpm
Wrote: /build/rpmbuild/RPMS/x86_64/wazuh-dashboard-4.7.0-1.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.08NkyI
+ umask 022
+ cd /build/rpmbuild/BUILD
+ rm -fr /build/rpmbuild/BUILDROOT/wazuh-dashboard-4.7.0-1.x86_64
+ exit 0
Package wazuh-dashboard-4.7.0-1.x86_64.rpm.sha512 added to /vagrant/wazuh-packages/stack/dashboard/rpm/output.

```

**Comment by Deblintrake09** [comment]
## Update 10/10/2023

<details><summary>Test RPM dashboard locally</summary>

- Install Indexer
```
# curl -OL https://packages-dev.wazuh.com/warehouse/test/4.7/rpm/var/wazuh-indexer-4.7.0-wp2402.x86_64.rpm
# curl -OL https://packages-dev.wazuh.com/4.8/config.yml
# curl -OL https://packages-dev.wazuh.com/4.8/wazuh-certs-tool.sh 
# nano ./config.yml 
# bash ./wazuh-certs-tool.sh -A
10/10/2023 15:09:34 INFO: Admin certificates created.
10/10/2023 15:09:34 INFO: Wazuh indexer certificates created.
10/10/2023 15:09:34 INFO: Wazuh server certificates created.
10/10/2023 15:09:35 INFO: Wazuh dashboard certificates created.
# tar -cvf ./wazuh-certificates.tar -C ./wazuh-certificates/ .

./
./root-ca.key
./root-ca.pem
./admin-key.pem
./admin.pem
./node-1-key.pem
./node-1.pem
./wazuh-1-key.pem
./wazuh-1.pem
./dashboard-key.pem
./dashboard.pem
# rm -rf ./wazuh-certificates


# yum localinstall ./wazuh-indexer-4.7.0-wp2402.x86_64.rpm 
Última comprobación de caducidad de metadatos hecha hace 0:00:37, el mar 10 oct 2023 15:11:04 UTC.
Dependencias resueltas.
===========================================================================================================================================================================================================
 Paquete                                            Arquitectura                                Versión                                            Repositorio                                        Tam.
===========================================================================================================================================================================================================
Instalando:
 wazuh-indexer                                      x86_64                                      4.7.0-wp2402                                       @commandline                                      731 M

Resumen de la transacción
===========================================================================================================================================================================================================
Instalar  1 Paquete

Tamaño total: 731 M
Tamaño instalado: 993 M
¿Está de acuerdo [s/N]?: s
Descargando paquetes:
Ejecutando verificación de operación
Verificación de operación exitosa.
Ejecutando prueba de operaciones
Prueba de operación exitosa.
Ejecutando operación
  Preparando          :                                                                                                                                                                                1/1 
  Ejecutando scriptlet: wazuh-indexer-4.7.0-wp2402.x86_64                                                                                                                                              1/1 
  Instalando          : wazuh-indexer-4.7.0-wp2402.x86_64                                                                                                                                              1/1 
  Ejecutando scriptlet: wazuh-indexer-4.7.0-wp2402.x86_64                                                                                                                                              1/1 
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore

[/usr/lib/tmpfiles.d/pesign.conf:1] Line references path below legacy directory /var/run/, updating /var/run/pesign → /run/pesign; please update the tmpfiles.d/ drop-in file accordingly.

  Verificando         : wazuh-indexer-4.7.0-wp2402.x86_64                                                                                                                                              1/1 

Instalado:
  wazuh-indexer-4.7.0-wp2402.x86_64                                                                                                                                                                        

¡Listo!
# nano /etc/wazuh-indexer/opensearch.yml
# NODE_NAME=node-1
# mkdir /etc/wazuh-indexer/certs
# tar -xf ./wazuh-certificates.tar -C /etc/wazuh-indexer/certs/ ./$NODE_NAME.pem ./$NODE_NAME-key.pem ./admin.pem ./admin-key.pem ./root-ca.pem
# mv -n /etc/wazuh-indexer/certs/$NODE_NAME.pem /etc/wazuh-indexer/certs/indexer.pem
# mv -n /etc/wazuh-indexer/certs/$NODE_NAME-key.pem /etc/wazuh-indexer/certs/indexer-key.pem
# chmod 500 /etc/wazuh-indexer/certs
# chmod 400 /etc/wazuh-indexer/certs/*
# chown -R wazuh-indexer:wazuh-indexer /etc/wazuh-indexer/certs
# systemctl daemon-reload
# systemctl enable wazuh-indexer
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-indexer.service → /usr/lib/systemd/system/wazuh-indexer.service.
# systemctl start wazuh-indexer
# systemctl status wazuh-indexer
● wazuh-indexer.service - Wazuh-indexer
   Loaded: loaded (/usr/lib/systemd/system/wazuh-indexer.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2023-10-10 15:18:41 UTC; 1min 4s ago
     Docs: https://documentation.wazuh.com
 Main PID: 1933 (java)
    Tasks: 66 (limit: 23108)
   Memory: 1.3G
   CGroup: /system.slice/wazuh-indexer.service
           └─1933 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.head>

oct 10 15:18:17 ip-172-31-6-251.ec2.internal systemd[1]: Starting Wazuh-indexer...
oct 10 15:18:19 ip-172-31-6-251.ec2.internal systemd-entrypoint[1933]: WARNING: A terminally deprecated method in java.lang.System has been called
oct 10 15:18:19 ip-172-31-6-251.ec2.internal systemd-entrypoint[1933]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/share/wazuh-indexer/lib/opens>
oct 10 15:18:19 ip-172-31-6-251.ec2.internal systemd-entrypoint[1933]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
oct 10 15:18:19 ip-172-31-6-251.ec2.internal systemd-entrypoint[1933]: WARNING: System::setSecurityManager will be removed in a future release
oct 10 15:18:22 ip-172-31-6-251.ec2.internal systemd-entrypoint[1933]: WARNING: A terminally deprecated method in java.lang.System has been called
oct 10 15:18:22 ip-172-31-6-251.ec2.internal systemd-entrypoint[1933]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (file:/usr/share/wazuh-indexer/lib/opensea>
oct 10 15:18:22 ip-172-31-6-251.ec2.internal systemd-entrypoint[1933]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
oct 10 15:18:22 ip-172-31-6-251.ec2.internal systemd-entrypoint[1933]: WARNING: System::setSecurityManager will be removed in a future release
oct 10 15:18:41 ip-172-31-6-251.ec2.internal systemd[1]: Started Wazuh-indexer.


# /usr/share/wazuh-indexer/bin/indexer-security-init.sh
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 172.31.6.251:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.9.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: YELLOW
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index does not exists, attempt to create it ... done (0-all replicas)
Populate config from /etc/wazuh-indexer/opensearch-security/
Will update '/config' with /etc/wazuh-indexer/opensearch-security/config.yml 
   SUCC: Configuration for 'config' created or updated
Will update '/roles' with /etc/wazuh-indexer/opensearch-security/roles.yml 
   SUCC: Configuration for 'roles' created or updated
Will update '/rolesmapping' with /etc/wazuh-indexer/opensearch-security/roles_mapping.yml 
   SUCC: Configuration for 'rolesmapping' created or updated
Will update '/internalusers' with /etc/wazuh-indexer/opensearch-security/internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
Will update '/actiongroups' with /etc/wazuh-indexer/opensearch-security/action_groups.yml 
   SUCC: Configuration for 'actiongroups' created or updated
Will update '/tenants' with /etc/wazuh-indexer/opensearch-security/tenants.yml 
   SUCC: Configuration for 'tenants' created or updated
Will update '/nodesdn' with /etc/wazuh-indexer/opensearch-security/nodes_dn.yml 
   SUCC: Configuration for 'nodesdn' created or updated
Will update '/whitelist' with /etc/wazuh-indexer/opensearch-security/whitelist.yml 
   SUCC: Configuration for 'whitelist' created or updated
Will update '/audit' with /etc/wazuh-indexer/opensearch-security/audit.yml 
   SUCC: Configuration for 'audit' created or updated
Will update '/allowlist' with /etc/wazuh-indexer/opensearch-security/allowlist.yml 
   SUCC: Configuration for 'allowlist' created or updated
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
Done with success


# curl -k -u admin:admin https://172.31.6.251:9200/_cat/nodes?v
ip           heap.percent ram.percent cpu load_1m load_5m load_15m node.role node.roles                                        cluster_manager name
172.31.6.251           33          93  10    0.10    0.37     0.30 dimr      cluster_manager,data,ingest,remote_cluster_client *               node-1
```

- Install Manager and Filebeat
```
# yum install -y https://packages-dev.wazuh.com/warehouse/pullrequests/4.7/rpm/var/wazuh-manager-4.7.1-0.commitd9563b2.x86_64.rpm
Última comprobación de caducidad de metadatos hecha hace 1:27:55, el mar 10 oct 2023 15:29:41 UTC.
wazuh-manager-4.7.1-0.commitd9563b2.x86_64.rpm                                                                                                                              47 MB/s | 165 MB     00:03    
Dependencias resueltas.
===========================================================================================================================================================================================================
 Paquete                                          Arquitectura                              Versión                                                  Repositorio                                      Tam.
===========================================================================================================================================================================================================
Instalando:
 wazuh-manager                                    x86_64                                    4.7.1-0.commitd9563b2                                    @commandline                                    165 M

Resumen de la transacción
===========================================================================================================================================================================================================
Instalar  1 Paquete

Tamaño total: 165 M
Tamaño instalado: 600 M
Descargando paquetes:
Ejecutando verificación de operación
Verificación de operación exitosa.
Ejecutando prueba de operaciones
Prueba de operación exitosa.
Ejecutando operación
  Preparando          :                                                                                                                                                                                1/1 
  Ejecutando scriptlet: wazuh-manager-4.7.1-0.commitd9563b2.x86_64                                                                                                                                     1/1 
  Instalando          : wazuh-manager-4.7.1-0.commitd9563b2.x86_64                                                                                                                                     1/1 
  Ejecutando scriptlet: wazuh-manager-4.7.1-0.commitd9563b2.x86_64                                                                                                                                     1/1 
  Verificando         : wazuh-manager-4.7.1-0.commitd9563b2.x86_64                                                                                                                                     1/1 

Instalado:
  wazuh-manager-4.7.1-0.commitd9563b2.x86_64                                                                                                                                                               

¡Listo!

# systemctl daemon-reload
# systemctl enable wazuh-manager
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-manager.service → /usr/lib/systemd/system/wazuh-manager.service.

[root@ip-172-31-6-251 qa]# systemctl start wazuh-manager

# yum -y install filebeat
EL-8 - Wazuh                                                                                                                                                                72 MB/s |  19 MB     00:00    
Última comprobación de caducidad de metadatos hecha hace 0:00:08, el mar 10 oct 2023 15:29:28 UTC.
Dependencias resueltas.
===========================================================================================================================================================================================================
 Paquete                                           Arquitectura                                    Versión                                            Repositorio                                     Tam.
===========================================================================================================================================================================================================
Instalando:
 filebeat                                          x86_64                                          7.10.2-1                                           wazuh                                           21 M

Resumen de la transacción
===========================================================================================================================================================================================================
Instalar  1 Paquete

Tamaño total de la descarga: 21 M
Tamaño instalado: 70 M
Descargando paquetes:
filebeat-oss-7.10.2-x86_64.rpm                                                                                                                                              60 MB/s |  21 MB     00:00    
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                       59 MB/s |  21 MB     00:00     
Ejecutando verificación de operación
Verificación de operación exitosa.
Ejecutando prueba de operaciones
Prueba de operación exitosa.
Ejecutando operación
  Preparando          :                                                                                                                                                                                1/1 
  Instalando          : filebeat-7.10.2-1.x86_64                                                                                                                                                       1/1 
advertencia:/etc/filebeat/filebeat.yml creado como /etc/filebeat/filebeat.yml.rpmnew

  Ejecutando scriptlet: filebeat-7.10.2-1.x86_64                                                                                                                                                       1/1 
  Verificando         : filebeat-7.10.2-1.x86_64                                                                                                                                                       1/1 

Instalado:
  filebeat-7.10.2-1.x86_64                                                                                                                                                                                 

¡Listo!

# curl -OL https://packages-dev.wazuh.com/4.8/tpl/wazuh/filebeat/filebeat.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   867  100   867    0     0   1447      0 --:--:-- --:--:-- --:--:--  1445

# cp filebeat.yml /etc/filebeat/
# filebeat keystore create
Created filebeat keystore
# echo admin | filebeat keystore add username --stdin --force
Successfully updated the keystore
# echo admin | filebeat keystore add password --stdin --force
Successfully updated the keystore

# curl -OL  https://raw.githubusercontent.com/wazuh/wazuh/master/extensions/elasticsearch/7.x/wazuh-template.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 62776  100 62776    0     0   957k      0 --:--:-- --:--:-- --:--:--  957k
# cp wazuh-template.json /etc/filebeat/
# chmod go+r /etc/filebeat/wazuh-template.json


# curl -s https://packages.wazuh.com/4.x/filebeat/wazuh-filebeat-0.2.tar.gz | tar -xvz -C /usr/share/filebeat/module
wazuh/alerts/
wazuh/alerts/config/
wazuh/alerts/config/alerts.yml
wazuh/alerts/manifest.yml
wazuh/alerts/ingest/
wazuh/alerts/ingest/pipeline.json
wazuh/archives/
wazuh/archives/config/
wazuh/archives/config/archives.yml
wazuh/archives/manifest.yml
wazuh/archives/ingest/
wazuh/archives/ingest/pipeline.json
wazuh/module.yml
# nano ./config.yml 
# NODE_NAME=wazuh-1
# mkdir /etc/filebeat/certs
# tar -xf ./wazuh-certificates.tar -C /etc/filebeat/certs/ ./$NODE_NAME.pem ./$NODE_NAME-key.pem ./root-ca.pem
# mv -n /etc/filebeat/certs/$NODE_NAME.pem /etc/filebeat/certs/filebeat.pem
# mv -n /etc/filebeat/certs/$NODE_NAME-key.pem /etc/filebeat/certs/filebeat-key.pem
# chmod 500 /etc/filebeat/certs
# chmod 400 /etc/filebeat/certs/*
# chown -R root:root /etc/filebeat/certs



# systemctl daemon-reload
# systemctl enable filebeat
Synchronizing state of filebeat.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable filebeat

Created symlink /etc/systemd/system/multi-user.target.wants/filebeat.service → /usr/lib/systemd/system/filebeat.service.
# systemctl start filebeat


# filebeat test output
elasticsearch: https://172.31.6.251:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 172.31.6.251
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.2
```

- Install Dashboard
```
# yum localinstall ./wazuh-dashboard-4.7.0-1.x86_64.rpm 
Última comprobación de caducidad de metadatos hecha hace 0:23:59, el mar 10 oct 2023 15:29:41 UTC.
Dependencias resueltas.
===========================================================================================================================================================================================================
 Paquete                                               Arquitectura                                 Versión                                       Repositorio                                         Tam.
===========================================================================================================================================================================================================
Instalando:
 wazuh-dashboard                                       x86_64                                       4.7.0-1                                       @commandline                                       261 M

Resumen de la transacción
===========================================================================================================================================================================================================
Instalar  1 Paquete

Tamaño total: 261 M
Tamaño instalado: 865 M
¿Está de acuerdo [s/N]?: s
Descargando paquetes:
Ejecutando verificación de operación
Verificación de operación exitosa.
Ejecutando prueba de operaciones
Prueba de operación exitosa.
Ejecutando operación
  Preparando          :                                                                                                                                                                                1/1 
  Ejecutando scriptlet: wazuh-dashboard-4.7.0-1.x86_64                                                                                                                                                 1/1 
  Instalando          : wazuh-dashboard-4.7.0-1.x86_64                                                                                                                                                 1/1 
  Ejecutando scriptlet: wazuh-dashboard-4.7.0-1.x86_64                                                                                                                                                 1/1 
  Verificando         : wazuh-dashboard-4.7.0-1.x86_64                                                                                                                                                 1/1 

Instalado:
  wazuh-dashboard-4.7.0-1.x86_64                                                                                                                                                                           

¡Listo!


# nano /etc/wazuh-dashboard/opensearch_dashboards.yml
# NODE_NAME=dashboard
# mkdir /etc/wazuh-dashboard/certs
# tar -xf ./wazuh-certificates.tar -C /etc/wazuh-dashboard/certs/ ./$NODE_NAME.pem ./$NODE_NAME-key.pem ./root-ca.pem
# mv -n /etc/wazuh-dashboard/certs/$NODE_NAME.pem /etc/wazuh-dashboard/certs/dashboard.pem
# mv -n /etc/wazuh-dashboard/certs/$NODE_NAME-key.pem /etc/wazuh-dashboard/certs/dashboard-key.pem
# chmod 500 /etc/wazuh-dashboard/certs
# chmod 400 /etc/wazuh-dashboard/certs/*
# chown -R wazuh-dashboard:wazuh-dashboard /etc/wazuh-dashboard/certs


# systemctl daemon-reload
# systemctl enable wazuh-dashboard
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-dashboard.service → /etc/systemd/system/wazuh-dashboard.service.
# systemctl start wazuh-dashboard


# systemctl status wazuh-dashboard
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2023-10-10 16:00:59 UTC; 4min 16s ago
 Main PID: 3623 (node)
    Tasks: 11 (limit: 23108)
   Memory: 155.5M
   CGroup: /system.slice/wazuh-dashboard.service
           └─3623 /usr/share/wazuh-dashboard/node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dashboard/src/cli/dist -c /etc/wazuh-dashboard/opensear>
```

![imagen](https://github.com/wazuh/wazuh-packages/assets/14501079/d158887b-6889-48a7-a5af-06fb896a94dd)
</details>

**Comment by davidjiglesias** [comment]
LGTM!
