### ISSUE TITLE
Incorrect handling of the Wazuh indexer backup directory

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2414]
## Description

When changing the passwords of a `4.6.0-2.8.0` deployment, anomalous behavior is encountered with the creation of the backup directory.

It has been observed that a message is displayed indicating that the directory exists even though it does not really exist and that the passwords are modified correctly. Additionally, this message stops appearing after using the parameters related to API users.

Another behavior observed is that if the backup directory is created by hand, the password change is done in the same way, when the execution should stop.

<details><summary>Commands output</summary>

```
[root@centos7 vagrant]# /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh -a -v
04/09/2023 13:50:11 INFO: Wazuh API admin credentials not provided, Wazuh API passwords not changed.
Installed wazuh-indexer.x86_64                4.6.0-wp.2392               @wazuh          
Backup 
mkdir: cannot create directory ‘/etc/wazuh-indexer/backup’: File exists
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 0.0.0.0:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.8.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Will retrieve '/config' into /etc/wazuh-indexer/backup/config.yml 
   SUCC: Configuration for 'config' stored in /etc/wazuh-indexer/backup/config.yml
Will retrieve '/roles' into /etc/wazuh-indexer/backup/roles.yml 
   SUCC: Configuration for 'roles' stored in /etc/wazuh-indexer/backup/roles.yml
Will retrieve '/rolesmapping' into /etc/wazuh-indexer/backup/roles_mapping.yml 
   SUCC: Configuration for 'rolesmapping' stored in /etc/wazuh-indexer/backup/roles_mapping.yml
Will retrieve '/internalusers' into /etc/wazuh-indexer/backup/internal_users.yml 
   SUCC: Configuration for 'internalusers' stored in /etc/wazuh-indexer/backup/internal_users.yml
Will retrieve '/actiongroups' into /etc/wazuh-indexer/backup/action_groups.yml 
   SUCC: Configuration for 'actiongroups' stored in /etc/wazuh-indexer/backup/action_groups.yml
Will retrieve '/tenants' into /etc/wazuh-indexer/backup/tenants.yml 
   SUCC: Configuration for 'tenants' stored in /etc/wazuh-indexer/backup/tenants.yml
Will retrieve '/nodesdn' into /etc/wazuh-indexer/backup/nodes_dn.yml 
   SUCC: Configuration for 'nodesdn' stored in /etc/wazuh-indexer/backup/nodes_dn.yml
Will retrieve '/whitelist' into /etc/wazuh-indexer/backup/whitelist.yml 
   SUCC: Configuration for 'whitelist' stored in /etc/wazuh-indexer/backup/whitelist.yml
Will retrieve '/allowlist' into /etc/wazuh-indexer/backup/allowlist.yml 
   SUCC: Configuration for 'allowlist' stored in /etc/wazuh-indexer/backup/allowlist.yml
Will retrieve '/audit' into /etc/wazuh-indexer/backup/audit.yml 
   SUCC: Configuration for 'audit' stored in /etc/wazuh-indexer/backup/audit.yml
Successfully updated the keystore
v16.20.0
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 0.0.0.0:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.8.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /home/vagrant
Force type: internalusers
Will update '/internalusers' with /etc/wazuh-indexer/backup/internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
SUCC: Expected 1 config types for node {"updated_config_types":["internalusers"],"updated_config_size":1,"message":null} is 1 (["internalusers"]) due to: null
Done with success
04/09/2023 13:50:16 INFO: The password for user admin is eNyztypPH6ZuG6fT7?poijqGQd?qndVS
04/09/2023 13:50:16 INFO: The password for user kibanaserver is FLwbhRprDC65X3lzNHrdZaRU+Yn.g7EE
04/09/2023 13:50:16 INFO: The password for user kibanaro is ?F+0lyTHcdfdaF+ltn*T4b0XNJM4Rb36
04/09/2023 13:50:16 INFO: The password for user logstash is vJAdCFrFPz2?1ZdUTp3oMBp*m8ATKzNT
04/09/2023 13:50:16 INFO: The password for user readall is zsnM5yJ6JW6pM?i?wEQ+AXd?rtl58Dv1
04/09/2023 13:50:16 INFO: The password for user snapshotrestore is ZPUKaHQoPlPt1VM2f+0GSttXl?wrM+t+
04/09/2023 13:50:16 WARNING: Wazuh indexer passwords changed. Remember to update the password in the Wazuh dashboard and Filebeat nodes if necessary, and restart the services.
[root@centos7 vagrant]# nano /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh 
[root@centos7 vagrant]# /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh -a
04/09/2023 13:53:04 INFO: Wazuh API admin credentials not provided, Wazuh API passwords not changed.
Installed wazuh-indexer.x86_64                4.6.0-wp.2392               @wazuh          
Backup 
v16.20.0
04/09/2023 13:53:10 INFO: The password for user admin is SGE+edTnVuF3fw?fFZK2DQtLbk+Hl6J0
04/09/2023 13:53:10 INFO: The password for user kibanaserver is KJB6QDOLMA7?NupbdgpjI9qD8rtwXfbA
04/09/2023 13:53:10 INFO: The password for user kibanaro is xW*sN1ahFMqgIHl9Olv0nBpGzERRE4l2
04/09/2023 13:53:10 INFO: The password for user logstash is MHhhpJxvvWinf4Rp4+Z?phH07od6f8hp
04/09/2023 13:53:10 INFO: The password for user readall is 0*8j6*oPNip73D2aZshHRhyljkvd+snm
04/09/2023 13:53:10 INFO: The password for user snapshotrestore is XojWW0r?*NykIri*hUSuuZ?Kg*y1NZ61
04/09/2023 13:53:10 WARNING: Wazuh indexer passwords changed. Remember to update the password in the Wazuh dashboard and Filebeat nodes if necessary, and restart the services.
[root@centos7 vagrant]# /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh --change-all --admin-user wazuh --admin-password wazuh
Installed wazuh-indexer.x86_64                4.6.0-wp.2392               @wazuh          
Backup 
v16.20.0
04/09/2023 13:54:46 INFO: The password for user admin is VFwDn.*4lrY2L*gmJvy2Dp5j+S4v3hyU
04/09/2023 13:54:46 INFO: The password for user kibanaserver is bcmjB6DAMZid0*X4B+X8k2n.ZZtOKUa3
04/09/2023 13:54:46 INFO: The password for user kibanaro is q5fmQ6nQf6Vdodz2GrP*o0Nvpu?ScDwq
04/09/2023 13:54:46 INFO: The password for user logstash is Qw.xyO14umGCeMw6?7o..RXcrFfeHTzg
04/09/2023 13:54:46 INFO: The password for user readall is z2LiETNXstnTG3kO5M.P.GM3N4vnxFCq
04/09/2023 13:54:46 INFO: The password for user snapshotrestore is NNv5KZTNqY.8b2wbC.*vbP*gWBmBHMuC
04/09/2023 13:54:46 WARNING: Wazuh indexer passwords changed. Remember to update the password in the Wazuh dashboard and Filebeat nodes if necessary, and restart the services.
04/09/2023 13:54:47 INFO: The password for Wazuh API user wazuh is K+9O4Eie5Cw2gUJkiwWtwN4F5L*uA00f
04/09/2023 13:54:47 INFO: The password for Wazuh API user wazuh-wui is flAez4GmFqxciFTg4ACRlb3FsvP*i79.
04/09/2023 13:54:47 INFO: Updated wazuh-wui user password in wazuh dashboard. Remember to restart the service.
[root@centos7 vagrant]# /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh --change-all --admin-user wazuh --admin-password wazuh
04/09/2023 13:55:47 ERROR: Invalid admin user credentials
[root@centos7 vagrant]# /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh --change-all --admin-user wazuh --admin-password K+9O4Eie5Cw2gUJkiwWtwN4F5L*uA00f
Installed wazuh-indexer.x86_64                4.6.0-wp.2392               @wazuh          
Backup 
v16.20.0
04/09/2023 13:56:06 INFO: The password for user admin is 8E.zs*gcAellB8iHpqPVelxU6V2uJE.?
04/09/2023 13:56:06 INFO: The password for user kibanaserver is eDcZ7nbDK40E?.JFM4X18XlDfHXV4J.U
04/09/2023 13:56:06 INFO: The password for user kibanaro is QuCoSYolopm+kg*4j.gr7BvI3lU*ZEI7
04/09/2023 13:56:06 INFO: The password for user logstash is b31uZ14Py6qUL7WpUYQv0E1lv+3fDpKI
04/09/2023 13:56:06 INFO: The password for user readall is neHA55Qe8tGlmH9Hy29th?iaEj0daeOc
04/09/2023 13:56:06 INFO: The password for user snapshotrestore is T6jXMfN0MWUGM4CEihEmMMTiRu*0w.nM
04/09/2023 13:56:06 WARNING: Wazuh indexer passwords changed. Remember to update the password in the Wazuh dashboard and Filebeat nodes if necessary, and restart the services.
04/09/2023 13:56:07 INFO: The password for Wazuh API user wazuh is kVAD5+CSBFvuEH7U89YPcc.svqTpCvGw
04/09/2023 13:56:08 INFO: The password for Wazuh API user wazuh-wui is jP3izx3McA*t6B7+AohPqBNP6g7R2Bhq
04/09/2023 13:56:08 INFO: Updated wazuh-wui user password in wazuh dashboard. Remember to restart the service.
[root@centos7 vagrant]# /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh --change-all
04/09/2023 13:56:19 INFO: Wazuh API admin credentials not provided, Wazuh API passwords not changed.
Installed wazuh-indexer.x86_64                4.6.0-wp.2392               @wazuh          
Backup 
v16.20.0
04/09/2023 13:56:25 INFO: The password for user admin is hXx+RuOdq+0rrp+UnhUWReiXtF399AL0
04/09/2023 13:56:25 INFO: The password for user kibanaserver is gEY?Ue1wqA5sqpA8Lp84pcNdIN*buLal
04/09/2023 13:56:25 INFO: The password for user kibanaro is sw7uFvRnfj4pfTN9.kZ94hs0qtWXD+6z
04/09/2023 13:56:25 INFO: The password for user logstash is +O1QZ+hLGRwOJ6XYNdkOBTvhHSFnJtVl
04/09/2023 13:56:25 INFO: The password for user readall is MUqQoeq9vvXlty1wFOuu3Ig?4do?OXD+
04/09/2023 13:56:25 INFO: The password for user snapshotrestore is NQCdPU.evtophQJ2?v*KXM13Zs9R5AuQ
04/09/2023 13:56:25 WARNING: Wazuh indexer passwords changed. Remember to update the password in the Wazuh dashboard and Filebeat nodes if necessary, and restart the services.
[root@centos7 vagrant]# /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh -a
04/09/2023 13:56:41 INFO: Wazuh API admin credentials not provided, Wazuh API passwords not changed.
Installed wazuh-indexer.x86_64                4.6.0-wp.2392               @wazuh          
Backup 
v16.20.0
04/09/2023 13:56:47 INFO: The password for user admin is 9vkqM1vpq.76pkYb0+dbX*FYaBFQAR8P
04/09/2023 13:56:47 INFO: The password for user kibanaserver is *dCxA?+Zu.s6rfWvBMSZi2t+UnmR*1A0
04/09/2023 13:56:47 INFO: The password for user kibanaro is 4E35tE6vAqJLVJHZQqtYhrsL.EUYIsbO
04/09/2023 13:56:47 INFO: The password for user logstash is QOlsAC5W0TGWI0huEPiwOkb+uKm+KvAj
04/09/2023 13:56:47 INFO: The password for user readall is 3DpDCTIUoOTOeRp?OEUgkAvjhWO7MIx7
04/09/2023 13:56:47 INFO: The password for user snapshotrestore is CMi9gkT7Ztmd*8W5PbOC6uybO4pyjNcj
04/09/2023 13:56:47 WARNING: Wazuh indexer passwords changed. Remember to update the password in the Wazuh dashboard and Filebeat nodes if necessary, and restart the services.
[root@centos7 vagrant]# mkdir /etc/wazuh-indexer/backup
[root@centos7 vagrant]# /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh -a
04/09/2023 13:57:59 INFO: Wazuh API admin credentials not provided, Wazuh API passwords not changed.
Installed wazuh-indexer.x86_64                4.6.0-wp.2392               @wazuh          
Backup 
v16.20.0
04/09/2023 13:58:04 INFO: The password for user admin is *JYHEOVz9Sw1.IgJZ80AaRHS0Ub8bM7t
04/09/2023 13:58:04 INFO: The password for user kibanaserver is 0++t90ucS3yWHYQDL40OsPacxHc.gn?C
04/09/2023 13:58:04 INFO: The password for user kibanaro is wmi95DdVaZMGvRxm6Yy?xPAG29G0uqnl
04/09/2023 13:58:04 INFO: The password for user logstash is Oewk6Ipr+?3WM8ZukiMhG1gac5l974RN
04/09/2023 13:58:04 INFO: The password for user readall is eNJeTvoLTo*.ArFB5T5t4Tn3dVaXHbr4
04/09/2023 13:58:04 INFO: The password for user snapshotrestore is aB*OUsqK8eioSM0uRk3lhDIjCWi*IWzI
04/09/2023 13:58:04 WARNING: Wazuh indexer passwords changed. Remember to update the password in the Wazuh dashboard and Filebeat nodes if necessary, and restart the services.
```

</details>

## Tasks

- [x] Fix the wazuh-passwords-tool.sh script to correctly handle the backup directory

## Validation

- [x] ~~The script stops and does not update passwords if the directory exists~~ Not planned.
- [x] The script correctly detects if the directory exists or not

## Related

- https://github.com/wazuh/wazuh-packages/issues/2391
- https://github.com/wazuh/wazuh-packages/issues/2392

**Comment by davidcr01** [comment]
# Update Report

## Research

After an in-depth investigation, it has been concluded that the problem is related to error handling.

On execution with the -v (verbose) option, both stderr and stdout are being redirected to the log file (/var/log/wazuh-passwords-tool.log) using 2>&1 | tee -a /var/log/wazuh-passwords-tool.log. This means that both error messages and normal output are logged in the log file. In this run, when an attempt is made to create the backup directory and it already exists, an error message is logged in the log file.

On execution without the -v option, only stderr is being redirected to the log file using 2>/dev/null. This means that error messages are being discarded and are not logged in the log file. Therefore, when you try to create the backup directory that already exists, an error message is not shown in the output because it is being redirected to /dev/null.

- Using the verbose option:
```console
+ eval 'mkdir /etc/wazuh-indexer/backup/ 2>/dev/null'
+ eval 'mkdir /etc/wazuh-indexer/backup/ 2>/dev/null'
++ mkdir /etc/wazuh-indexer/backup/
++ mkdir /etc/wazuh-indexer/backup/
+ eval 'cp /etc/wazuh-indexer/opensearch-security/* /etc/wazuh-indexer/backup/ 2>/dev/null'

...

+ eval 'mkdir /etc/wazuh-indexer/backup 2>&1 | tee -a /var/log/wazuh-passwords-tool.log'
+ eval 'mkdir /etc/wazuh-indexer/backup >> /var/log/wazuh-passwords-tool.log 2>&1'
++ mkdir /etc/wazuh-indexer/backup
++ mkdir /etc/wazuh-indexer/backup
++ tee -a /var/log/wazuh-passwords-tool.log
mkdir: cannot create directory ‘/etc/wazuh-indexer/backup’: File exists
```
The error in the second `mkdir` command is expected as the directory is already created.

- Without using the verbose option:
```console
+ eval 'mkdir /etc/wazuh-indexer/backup/ 2>/dev/null'
++ mkdir /etc/wazuh-indexer/backup/
++ mkdir /etc/wazuh-indexer/backup/
+ eval 'cp /etc/wazuh-indexer/opensearch-security/* /etc/wazuh-indexer/backup/ 2>/dev/null'
+ eval 'cp /etc/wazuh-indexer/opensearch-security/* /etc/wazuh-indexer/backup/ 2>/dev/null'

...

+ eval 'mkdir /etc/wazuh-indexer/backup >> /var/log/wazuh-passwords-tool.log 2>&1'
++ mkdir /etc/wazuh-indexer/backup
++ mkdir /etc/wazuh-indexer/backup
++ tee -a /var/log/wazuh-passwords-tool.log
```
In this trace, the error is not displayed. However, it is generated but redirected to `/dev/null`, so it is not shown.
The key difference here is how error messages are handled. On execution with `-v`, error messages are logged to the log file, while on execution without `-v`, they are muted and are not displayed on `stdout` or logged to the log file. This explains why you see the error message on one run and not the other.

If the redirection to `/dev/null` is removed from the code, the error is displayed in both executions:

- Using the verbose option:
```console


+ eval 'mkdir /etc/wazuh-indexer/backup/' |   | 9 | + eval 'mkdir /etc/wazuh-indexer/backup/'
++ mkdir /etc/wazuh-indexer/backup/ |   | 10 | ++ mkdir /etc/wazuh-indexer/backup/
+ eval 'cp /etc/wazuh-indexer/opensearch-security/* /etc/wazuh-indexer/backup/ 2>/dev/null'

...


+ eval 'mkdir /etc/wazuh-indexer/backup' |   | 40 | + eval 'mkdir /etc/wazuh-indexer/backup'
++ mkdir /etc/wazuh-indexer/backup |   | 41 | ++ mkdir /etc/wazuh-indexer/backup
mkdir: cannot create directory ‘/etc/wazuh-indexer/backup’: File exists
```

- Without using the verbose option:
```console
+ eval 'mkdir /etc/wazuh-indexer/backup/'
++ mkdir /etc/wazuh-indexer/backup/ |   | 10 | ++ mkdir /etc/wazuh-indexer/backup/

...

+ eval 'mkdir /etc/wazuh-indexer/backup'
++ mkdir /etc/wazuh-indexer/backup |   | 41 | ++ mkdir /etc/wazuh-indexer/backup
mkdir: cannot create directory ‘/etc/wazuh-indexer/backup’: File exists |   | 42 | mkdir: cannot create directory ‘/etc/wazuh-indexer/backup’: File exists
```

The issue is that the backup directory is being created twice:
```console
eval "mkdir /etc/wazuh-indexer/backup/ 2>/dev/null"eval "cp /etc/wazuh-indexer/opensearch-security/* /etc/wazuh-indexer/backup/ 2>/dev/null"passwords_createBackUp

// Then, inside the passwords_createBackUp functioncommon_logger -d "Creating password backup."
eval "mkdir /etc/wazuh-indexer/backup ${debug}"
```

The proposed solution is to remove the second `mkdir` command or insert a check in the second `mkdir` command to avoid creating the directory if it already exists.

## Development

With the following conditional added, the error is not displayed as the directory is not being created twice.
```bash
if [ ! -d "/etc/wazuh-indexer/backup" ]; then
        eval "mkdir /etc/wazuh-indexer/backup ${debug}"
fi
```

## Testing

<details><summary>With verbose</summary>

```
root@ubuntu22:/home/vagrant# /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh -a -v
05/09/2023 09:55:08 INFO: Wazuh API admin credentials not provided, Wazuh API passwords not changed.
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 127.0.0.1:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.8.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-indexer-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Will retrieve '/config' into /etc/wazuh-indexer/backup/config.yml 
   SUCC: Configuration for 'config' stored in /etc/wazuh-indexer/backup/config.yml
Will retrieve '/roles' into /etc/wazuh-indexer/backup/roles.yml 
   SUCC: Configuration for 'roles' stored in /etc/wazuh-indexer/backup/roles.yml
Will retrieve '/rolesmapping' into /etc/wazuh-indexer/backup/roles_mapping.yml 
   SUCC: Configuration for 'rolesmapping' stored in /etc/wazuh-indexer/backup/roles_mapping.yml
Will retrieve '/internalusers' into /etc/wazuh-indexer/backup/internal_users.yml 
   SUCC: Configuration for 'internalusers' stored in /etc/wazuh-indexer/backup/internal_users.yml
Will retrieve '/actiongroups' into /etc/wazuh-indexer/backup/action_groups.yml 
   SUCC: Configuration for 'actiongroups' stored in /etc/wazuh-indexer/backup/action_groups.yml
Will retrieve '/tenants' into /etc/wazuh-indexer/backup/tenants.yml 
   SUCC: Configuration for 'tenants' stored in /etc/wazuh-indexer/backup/tenants.yml
Will retrieve '/nodesdn' into /etc/wazuh-indexer/backup/nodes_dn.yml 
   SUCC: Configuration for 'nodesdn' stored in /etc/wazuh-indexer/backup/nodes_dn.yml
Will retrieve '/whitelist' into /etc/wazuh-indexer/backup/whitelist.yml 
   SUCC: Configuration for 'whitelist' stored in /etc/wazuh-indexer/backup/whitelist.yml
Will retrieve '/allowlist' into /etc/wazuh-indexer/backup/allowlist.yml 
   SUCC: Configuration for 'allowlist' stored in /etc/wazuh-indexer/backup/allowlist.yml
Will retrieve '/audit' into /etc/wazuh-indexer/backup/audit.yml 
   SUCC: Configuration for 'audit' stored in /etc/wazuh-indexer/backup/audit.yml
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 127.0.0.1:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.8.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-indexer-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /home/vagrant
Force type: internalusers
Will update '/internalusers' with /etc/wazuh-indexer/backup/internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
SUCC: Expected 1 config types for node {"updated_config_types":["internalusers"],"updated_config_size":1,"message":null} is 1 (["internalusers"]) due to: null
Done with success
05/09/2023 09:55:13 INFO: The password for user admin is Od5dzCaRle2*GKm2c?.Ns87XT71lFfW3
05/09/2023 09:55:13 INFO: The password for user kibanaserver is Mf6vPfpFoOWqkgZ40GHsLT6mzH*Dchjd
05/09/2023 09:55:13 INFO: The password for user kibanaro is H0rshTfl++1gW4oPA6qe01JwHVjmVEQ9
05/09/2023 09:55:13 INFO: The password for user logstash is PZt.oPEWvW3k8KkiUA*oQW1MgJU15pL?
05/09/2023 09:55:13 INFO: The password for user readall is 0ny.ldVJqCfgQB6vc?AwFPz8zhpVsIPs
05/09/2023 09:55:13 INFO: The password for user snapshotrestore is ELq6HjtMp7*oHJnBQR8fCdaV.B+7X670
05/09/2023 09:55:13 WARNING: Wazuh indexer passwords changed. Remember to update the password in the Wazuh dashboard and Filebeat nodes if necessary, and restart the services.

```
</details>


<details><summary>Without verbose</summary>

```
root@ubuntu22:/home/vagrant# /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh -a
05/09/2023 09:58:06 INFO: Wazuh API admin credentials not provided, Wazuh API passwords not changed.
05/09/2023 09:58:12 INFO: The password for user admin is xU2OIP6+TSj+2dKWfTj1f1g3gkSG1x8O
05/09/2023 09:58:12 INFO: The password for user kibanaserver is bu1vti0ycbK+tIDF0xBDIlS4HT6x?b7i
05/09/2023 09:58:12 INFO: The password for user kibanaro is 34D4iW1d2ip.N735PlDvFcrfsjn3ack?
05/09/2023 09:58:12 INFO: The password for user logstash is 2hp*Ld+pGSni9GZvXUkuK?+LI9a007tH
05/09/2023 09:58:12 INFO: The password for user readall is TLFV2McP0uFq25zXHx6Szd?nnyguiGsl
05/09/2023 09:58:12 INFO: The password for user snapshotrestore is Wgz1WOS*ELnhxdZ+Wa.EYgRBKPe1ie0D
05/09/2023 09:58:12 WARNING: Wazuh indexer passwords changed. Remember to update the password in the Wazuh dashboard and Filebeat nodes if necessary, and restart the services.
```
</details>

## Conclusion

The error was related to the error management. The backup directory could not be created but the tool wasn't displaying the error. Adding a conditional to the `mkdir` command fixes the issue.

**Comment by davidcr01** [comment]
# Update Report

After talking with the team, we decided not to stop the script when the backup exists. This backup is not actually a backup, but a temporary directory to store all the old configuration of OpenSearch before applying the changes.
Taking into account that the directory is all managed by the script (created and removed) we do not see this task necessary. 
Besides, it could generate some trouble for the users as they should remove manually the directory and have a bad user experience.
