### ISSUE TITLE
Fix Wazuh dashboard binary with new OpenSearch 2.8.0 modifications

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2420]
## Description

It is necessary to add changes to the Wazuh dashboard bump for OpenSearch 2.8.0 since due to a `DeprecationWarning` it is not possible to use IP in the configuration to connect with the Wazuh indexer

```
DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
```

Debugging this error with @Tostti the following was discovered:

- The `opensearch-dashboard` binary has been modified and the `sed` command used to add configuration does not work
- These binary modifications are now specified in a new binary called `use_node`
- The configuration set in the `node.options` file is not working

All this is solved as follows:

- Use the node fallback binary (Node 14) instead of the default binary (Node 16), for this it is necessary to modify the `use_node` binary
- Restoring the contents of the `opensearch-dashboards` binary by default, since the configuration that specifies the `/etc/wazuh-dashboard` directory is established internally in the base file
- It is necessary to add the variable `OSD_PATH_CONF="/etc/wazuh-dashboard"` to the `opensearch-dashboards` binary so that it establishes the configuration directory (this makes the `node.options` to work again)

```
OSD_PATH_CONF="/etc/wazuh-dashboard" OSD_NODE_OPTS_PREFIX="--no-warnings --max-http-header-size=65536" OSD_USE_NODE_JS_FILE_PATH=/src/cli/dist NODE_ENV=production exec ${OSD_HOME}/bin/use_node "${@}"
```

- Due to the previous change it is necessary to move the file `/usr/share/wazuh-dashboard/config/opensearch_dashboards.keystore` to `/etc/wazuh-indexer/`

---

:yellow_circle:  It is necessary to try to make the package work using Node 16 instead of using Node 14

---

## Tasks 1

- [x] Modify the `opensearch-dashboards` binary with the described modifications
- [x] Modify the use_node binary to use Node 14 (fallback)
- [x] Modify the SPECS to change the path of the opensearch_dashboards.keystore file

## Validation 1

- [x] The package works in the same way as Wazuh dashboard 4.5.1

---

## Tasks 2

- [x] Modify what is necessary for the package to work correctly using Node 16

## Validation

- [x] The package works in the same way as Wazuh dashboard 4.5.1

---

### Working branch

- https://github.com/wazuh/wazuh-packages/tree/enhancement/2420-bump-wazuh-dashboard-2.8.0-4.6.0

---

### Related

- https://github.com/wazuh/wazuh-packages/issues/2392

**Comment by rauldpm** [comment]
## Update report

- Apparently, the option of using Node 14 is not viable since:
   - The `/usr/share/wazuh-dashboard/bin/opensearch-dashboards-keystore` binary creates the keystore in the installation directory, looking at the binary, it may require the same modification as the main binary to set the modified configuration directory
   - This implies that with the proposed modifications, this file is duplicated, which is not acceptable
- By establishing the configuration path in the main binary, it has been achieved that the service does not fail when using an IP using Node 16, but the following message is observed: `Wazuh dashboard server is not ready yet`

**Comment by davidjiglesias** [comment]
LGTM!
