### ISSUE TITLE
Change error message to warning in not recommended systems

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2464]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| Any | Installation Assistant | Install | Any |

Related: https://github.com/wazuh/wazuh-packages/issues/2434
Currently, when the Installation Assistant detects the system that is trying to install Wazuh is not recommended, it generates an error and stops the execution of the script.
It would be recommended to be a warning instead of an error, and not to stop the execution but to warn that the installation may not finish successfully.

## Tasks

- [x] Change the error message to a warning message.
- [x] Perform an installation in a recommended system.
- [x] Perform an installation in a not-recommended system and check if the installation is not stopped.

**Comment by davidcr01** [comment]
# Update Report

## Development

The error message of the not recommended system has been changed to a warning. This message was in the `check_dist` function of the `checks.sh` file:

Before: 
https://github.com/wazuh/wazuh-packages/blob/35d25cbc5e65cc9cfcc40f2b0057a8504a700040/unattended_installer/install_functions/checks.sh#L210-L212

The change consists of modifying the `common_logger` option to `-w` instead of the `-e` option and removing the exit command.

**Comment by teddytpc1** [comment]
We have decided not to implement this change.
