### ISSUE TITLE
Migrate NodeJS installation from official repository to an unofficial source

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-packages#2466]
Because of the recent migration of NodeJS to a new repository our installation/upgrade tests were affected.

> Ref.:
> - https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository
> - https://github.com/nodesource/distributions/discussions/1639#discussioncomment-6885565

This mainly affected some old OS we support, e.g., Ubuntu Trusty.

So, I'd recommend:
1. Add the required NodeJS packages to AWS S3 and use them in our code
2. Use other repositories (e.g.: https://unofficial-builds.nodejs.org/download/)

### Tasks

- [ ] Change the way we install NodeJS in all our Docker files
- [ ] Generate and push the base images
- [ ] Generate and push the targeted images
- [ ] Run affected tests
  - [ ] Installation tests
  - [ ] Upgrade tests
  - [ ] More (if required)

**Comment by mauromalara** [comment]
**Justifying the objective:** "Very high impact bugs"

NodeJS deciding that its repository is not available anymore or deleting the scripts could delay a release.
