### ISSUE TITLE
Support new Wazuh version 4.7.1 in wazuh-packages repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-packages#2467]
## Description

This issue attempts to support a new version 4.7.1 in the wazuh-packages repository.

## Tasks

- [x] Create numbered branch for version (4.7.1) using branch 4.7.0 on wazuh-packages repository.
- [x] Bump 4.7.1 branch to 4.7.1 version on wazuh-packages repository, including revision and changelog.
- [x] Build and push testing images for GitHub actions.
