### ISSUE TITLE
Support new stage RC 1 for 4.5.3 in wazuh-packages repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-packages#2470]
## Description

This issue attempts to support a new stage RC 1 for 4.5.3 in the wazuh-packages repository.

## Tasks

- [ ] ~Ensure changelog is updated for 4.5.3 (if applicable).~
- [ ] ~Bump revision for branch 4.5.3 on wazuh-packages repository.~
- [x] Create tag v4.5.3-rc1 from branch 4.5.3 on wazuh-packages repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.5.3-rc1.
