### ISSUE TITLE
Support new stage RC 3 for 4.5.3 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2500]
## Description

This issue attempts to support a new stage RC 3 for 4.5.3 in the wazuh-packages repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.3 (if applicable).
- [x] Bump revision for branch 4.5.3 on wazuh-packages repository.
- [x] Add release ETA
- [x] Create tag v4.5.3-rc3 from branch 4.5.3 on wazuh-packages repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.5.3-rc3.
