### ISSUE TITLE
Connection error in Wazuh indexer 2.10.0

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2514]
## Description

During the bump of the Wazuh indexer to 2.9.0 https://github.com/wazuh/wazuh-packages/issues/2402, a new error was encountered when starting the Wazuh indexer service

```
/var/log/wazuh-indexer/wazuh-cluster.log:[2023-10-09T13:56:19,120][ERROR][o.o.s.t.SecurityRequestHandler] [node-1] OpenSearchException[Transport client authentication no longer supported.]
/var/log/wazuh-indexer/wazuh-cluster.log:[2023-10-09T13:56:19,121][ERROR][o.o.s.t.SecurityRequestHandler] [node-1] OpenSearchException[Transport client authentication no longer supported.]
```

It has not been possible to reproduce this error again in other installations, investigating the origin, the error seems to be determined by a connection problem, either due to the HTTP connection or due to an incorrect configuration of the certificates

#### Related

- https://forum.opensearch.org/t/opensearch-transport-auth-auth-no-longer-supported-still-attempts-handshake-on-9300/9874
- https://forum.opensearch.org/t/transport-client-authentication-no-longer-supported-error-when-deploying-cluster-with-security-plugin-enabled/9814

## Tasks

- [ ] Investigate the origin of the error
- [ ] Determine the impact on normal operation
- [ ] Apply necessary changes to fix the error if necessary

## Validation

- [ ] The error is harmless or the error has been fixed

**Comment by rauldpm** [comment]
Closed since the 2.9.0 bump will not be performed

**Comment by rauldpm** [comment]
Issue present in OpenSearch 2.10.0, as the 2.9.0 bump was canceled, this issue will reference the 2.10.0 bump
