### ISSUE TITLE
Support new Wazuh version 4.9.0 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2526]
## Description

This issue attempts to support a new version 4.9.0 in the wazuh-packages repository.

## Tasks

- [x] Create numbered branch for current master version (4.8.0) using master branch on wazuh-packages repository.
- [x] Bump master branch to 4.9.0 on wazuh-packages repository, including revision and changelog.
- [x] Build and push testing images for GitHub actions.

**Comment by JcabreraC** [comment]
LGTM !
