### ISSUE TITLE
Support new Wazuh version 4.5.4 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2530]
## Description

This issue attempts to support a new version 4.5.4 in the wazuh-packages repository.

## Tasks

- [x] Create numbered branch for version (4.5.4) using branch 4.5.4 on wazuh-packages repository.
- [x] Bump 4.5.4 branch to 4.5.4 version on wazuh-packages repository, including revision and changelog.
- [ ] ~Build and push testing images for GitHub actions.~
