### ISSUE TITLE
Post release tasks for 4.6.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2566]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.6.0.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.6.0-into-4.7.0`.

## Tasks

- [x] https://github.com/wazuh/wazuh-packages/pull/2570
- [x] https://github.com/wazuh/wazuh-packages/pull/2572
- [x] https://github.com/wazuh/wazuh-packages/pull/2580
- [ ] https://github.com/wazuh/wazuh-packages/pull/2581
- [ ] Publish GitHub release as latest.
- [ ] Delete all stage pre-releases for 4.6.0 (https://github.com/wazuh/wazuh-packages/releases).
- [ ] Delete all stage tags for v4.6.0. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.6.0-rc1, 4.6.0-alpha1, etc.
- [ ] Delete branch `4.6.0`.
