### ISSUE TITLE
Wazuh central components removal is not checked in WIA

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2574]
## Description

|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| Any | Wazuh central components | Remove | Any |

In https://github.com/wazuh/wazuh-packages/issues/1493, I found a bug when removing the Wazuh central components.

In the following log, it is seen that the Wazuh Installation Assistant (WIA) does not check if the central components were removed correctly. The WIA informs that the component was removed successfully, but it is still installed in the system. This can lead to errors:

```console
root@ubuntu22:/home/vagrant# bash wazuh-install.sh -u
02/11/2023 10:12:00 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
02/11/2023 10:12:00 INFO: Verbose logging redirected to /var/log/wazuh-install.log
02/11/2023 10:12:02 INFO: Wazuh manager not found in the system so it was not uninstalled.
02/11/2023 10:12:02 INFO: Filebeat not found in the system so it was not uninstalled.
02/11/2023 10:12:02 INFO: Wazuh dashboard not found in the system so it was not uninstalled.
02/11/2023 10:12:02 INFO: Removing Wazuh indexer.
02/11/2023 10:12:02 INFO: Wazuh indexer removed.

root@ubuntu22:/home/vagrant# apt list --installed | grep wazuh
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
wazuh-indexer/now 4.8.0-40800 amd64 [installed,local]
```

## Tasks

- [x] Add checks to the `installCommon_rollBack` function to check if the central component is removed correctly.
- [x] Validate if the removal is correctly performed.
- [x] Force an incorrect removal (for example forcing a lock of the package manager) and check that an error message is generated.

**Comment by davidcr01** [comment]
# Update Report

## Testing

Some testing has been done to check the behavior of the development. The test consists in
- Performing an AIO installation or an installation of a Wazuh component
- Force the APT/YUM lock. Related: https://github.com/wazuh/wazuh-packages/pull/2577
- Perform an uninstallation.

<details><summary>:green_circle: AIO Installation</summary>

```console
root@ip-172-31-73-213:/home/ubuntu# bash wazuh-install.sh -a
08/11/2023 20:29:34 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
08/11/2023 20:29:34 INFO: Verbose logging redirected to /var/log/wazuh-install.log
08/11/2023 20:29:50 INFO: Verifying that your system meets the recommended minimum hardware requirements.
08/11/2023 20:29:50 INFO: Wazuh web interface port will be 443.
08/11/2023 20:29:58 INFO: Wazuh development repository added.
08/11/2023 20:29:59 INFO: --- Configuration files ---
08/11/2023 20:29:59 INFO: Generating configuration files.
08/11/2023 20:30:01 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
08/11/2023 20:30:01 INFO: --- Wazuh indexer ---
08/11/2023 20:30:01 INFO: Starting Wazuh indexer installation.
08/11/2023 20:31:11 INFO: Wazuh indexer installation finished.
08/11/2023 20:31:11 INFO: Wazuh indexer post-install configuration finished.
08/11/2023 20:31:11 INFO: Starting service wazuh-indexer.
08/11/2023 20:31:30 INFO: wazuh-indexer service started.
08/11/2023 20:31:30 INFO: Initializing Wazuh indexer cluster security settings.
08/11/2023 20:31:42 INFO: Wazuh indexer cluster initialized.
08/11/2023 20:31:42 INFO: --- Wazuh server ---
08/11/2023 20:31:42 INFO: Starting the Wazuh manager installation.
08/11/2023 20:32:42 INFO: Wazuh manager installation finished.
08/11/2023 20:32:42 INFO: Starting service wazuh-manager.
08/11/2023 20:33:03 INFO: wazuh-manager service started.
08/11/2023 20:33:03 INFO: Starting Filebeat installation.
08/11/2023 20:33:13 INFO: Filebeat installation finished.
08/11/2023 20:33:14 INFO: Filebeat post-install configuration finished.
08/11/2023 20:33:14 INFO: Starting service filebeat.
08/11/2023 20:33:16 INFO: filebeat service started.
08/11/2023 20:33:16 INFO: --- Wazuh dashboard ---
08/11/2023 20:33:18 INFO: Starting Wazuh dashboard installation.
08/11/2023 20:34:14 INFO: Wazuh dashboard installation finished.
08/11/2023 20:34:15 INFO: Wazuh dashboard post-install configuration finished.
08/11/2023 20:34:15 INFO: Starting service wazuh-dashboard.
08/11/2023 20:34:15 INFO: wazuh-dashboard service started.
08/11/2023 20:34:17 INFO: Updating the internal users.
08/11/2023 20:34:25 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
08/11/2023 20:34:57 INFO: Initializing Wazuh dashboard web application.
08/11/2023 20:34:58 INFO: Wazuh dashboard web application initialized.
08/11/2023 20:34:58 INFO: --- Summary ---
08/11/2023 20:34:58 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: reEDY2ML7Cbt.pb+ONuFMWx5imTVhNNY
08/11/2023 20:34:58 INFO: Installation finished.
root@ip-172-31-73-213:/home/ubuntu# 
```
</details>

After performing an AIO installation and forcing the apt lock using the apt package manager in another process, the uninstallation generates the following log. Notice the warning messages of the removal of the packages:

<details><summary>:green_circle: AIO removal - Ubuntu 22</summary>

```console
root@ip-172-31-73-213:/home/ubuntu# bash wazuh-install.sh -u
09/11/2023 09:39:26 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
09/11/2023 09:39:26 INFO: Verbose logging redirected to /var/log/wazuh-install.log
09/11/2023 09:39:27 INFO: Removing Wazuh manager.
09/11/2023 09:39:28 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (1/10)
09/11/2023 09:39:29 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (2/10)
09/11/2023 09:39:30 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (3/10)
09/11/2023 09:39:31 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (4/10)
09/11/2023 09:39:32 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (5/10)
09/11/2023 09:39:33 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (6/10)
09/11/2023 09:39:34 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (7/10)
09/11/2023 09:39:35 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (8/10)
09/11/2023 09:39:36 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (9/10)
09/11/2023 09:39:37 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (10/10)
09/11/2023 09:39:40 WARNING: The Wazuh manager package could not be removed.
09/11/2023 09:39:42 INFO: Removing Wazuh indexer.
09/11/2023 09:39:42 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (1/10)
09/11/2023 09:39:43 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (2/10)
09/11/2023 09:39:44 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (3/10)
09/11/2023 09:39:45 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (4/10)
09/11/2023 09:39:46 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (5/10)
09/11/2023 09:39:47 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (6/10)
09/11/2023 09:39:48 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (7/10)
09/11/2023 09:39:49 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (8/10)
09/11/2023 09:39:50 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (9/10)
09/11/2023 09:39:51 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (10/10)
09/11/2023 09:39:53 WARNING: The Wazuh indexer package could not be removed.
09/11/2023 09:39:53 INFO: Removing Filebeat.
09/11/2023 09:39:53 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (1/10)
09/11/2023 09:39:54 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (2/10)
09/11/2023 09:39:55 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (3/10)
09/11/2023 09:39:56 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (4/10)
09/11/2023 09:39:57 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (5/10)
09/11/2023 09:39:58 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (6/10)
09/11/2023 09:39:59 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (7/10)
09/11/2023 09:40:00 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (8/10)
09/11/2023 09:40:01 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (9/10)
09/11/2023 09:40:02 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (10/10)
09/11/2023 09:40:04 WARNING: The Filebeat package could not be removed.
09/11/2023 09:40:04 INFO: Removing Wazuh dashboard.
09/11/2023 09:40:04 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (1/10)
09/11/2023 09:40:05 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (2/10)
09/11/2023 09:40:06 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (3/10)
09/11/2023 09:40:07 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (4/10)
09/11/2023 09:40:08 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (5/10)
09/11/2023 09:40:09 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (6/10)
09/11/2023 09:40:10 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (7/10)
09/11/2023 09:40:11 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (8/10)
09/11/2023 09:40:12 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (9/10)
09/11/2023 09:40:13 INFO: Another process is using APT. Waiting for it to release the lock. Next retry in 1 seconds (10/10)
09/11/2023 09:40:15 WARNING: The Wazuh dashboard package could not be removed.
```
</details>

Same error has been reproduced in CentOS 7, in this case uninstalling the Wazuh indexer package:

<details><summary>:green_circle: Wazuh indexer removal - CentOS 7</summary>

```console
[root@centos7 vagrant]# bash wazuh-install.sh -u
09/11/2023 10:28:33 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
09/11/2023 10:28:33 INFO: Verbose logging redirected to /var/log/wazuh-install.log
09/11/2023 10:28:35 INFO: Wazuh manager not found in the system so it was not uninstalled.
09/11/2023 10:28:35 INFO: Filebeat not found in the system so it was not uninstalled.
09/11/2023 10:28:35 INFO: Wazuh dashboard not found in the system so it was not uninstalled.
09/11/2023 10:28:49 INFO: Removing Wazuh indexer.
09/11/2023 10:28:49 INFO: Another process is using YUM. Waiting for it to release the lock. Next retry in 1 seconds (1/10)
09/11/2023 10:28:50 INFO: Another process is using YUM. Waiting for it to release the lock. Next retry in 1 seconds (2/10)
09/11/2023 10:28:51 INFO: Another process is using YUM. Waiting for it to release the lock. Next retry in 1 seconds (3/10)
09/11/2023 10:28:52 INFO: Another process is using YUM. Waiting for it to release the lock. Next retry in 1 seconds (4/10)
09/11/2023 10:28:53 INFO: Another process is using YUM. Waiting for it to release the lock. Next retry in 1 seconds (5/10)
09/11/2023 10:28:54 INFO: Another process is using YUM. Waiting for it to release the lock. Next retry in 1 seconds (6/10)
09/11/2023 10:28:55 INFO: Another process is using YUM. Waiting for it to release the lock. Next retry in 1 seconds (7/10)
09/11/2023 10:28:56 INFO: Another process is using YUM. Waiting for it to release the lock. Next retry in 1 seconds (8/10)
09/11/2023 10:28:57 INFO: Another process is using YUM. Waiting for it to release the lock. Next retry in 1 seconds (9/10)
09/11/2023 10:28:58 INFO: Another process is using YUM. Waiting for it to release the lock. Next retry in 1 seconds (10/10)
09/11/2023 10:28:59 WARNING: The Wazuh indexer package could not be removed.
```
</details>
