### ISSUE TITLE
Wazuh indexer GHA test fails to install 4.6.0 as the `securityconfig` directory does not exist

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2636]
## Description

An error has been reported in a Wazuh indexer Debian GHA, where the 4.6.0 package cannot be installed

- https://github.com/wazuh/wazuh-packages/actions/runs/6979091415/job/18991690888?pr=2633

```
Setting up wazuh-indexer (4.6.0-1) ...
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
Processing triggers for libc-bin (2.35-0ubuntu3.4) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 6.2.0-1016-azure
NEEDRESTART-KEXP:6.2.0-1016-azure
NEEDRESTART-KSTA: 1
Error: the directory does not exist. /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig.
Error: Process completed with exit code 1.
```

Two things should be mentioned here:

1. `NEEDRESTART` messages
2. `securityconfig` directory not existing error

---

### About point 1

- These messages do not appear in a common way, from what has been investigated, they come from the worker node where the installation is executed, during the process, it can be seen that the system contains Azure repositories, possibly for the mentioned package `6.2.0-1016-azure`

```
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
```

- We need to determine if it is necessary to modify the GHA runner

### About point 2

- Starting with 4.4 included, the files found in the `/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig` directory were now located in `/etc/wazuh-indexer/opensearch-security/`
- In this specific case, the installation of the 4.6.0 package should not search or access the directory found in `/usr/share/`, all references in the SPECs files are found within the upgrade section, and in this case, it is a clean install.

https://github.com/search?q=repo%3Awazuh%2Fwazuh-packages%20securityconfig&type=code

- The installation has been carried out successfully both on RPM systems, on Ubuntu 22.04.2, and by replaying the failed test (Ubuntu 22.04.3)
- We need to determine if there is any problem with the installation process or not

---

## Tasks

- [ ] Validate the integrity of the runner node used for the Debian test
- [ ] Validate the integrity of the Wazuh indexer installation process on Debian systems (Ubuntu)
- [ ] Make the necessary modifications

## Validation

- [ ] The package is installed successfully
