### ISSUE TITLE
Duplicate code in  the Wazuh indexer package

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2637]
## Description

Analyzing the problem reported in https://github.com/wazuh/wazuh-packages/issues/2636, it has been detected that there is code duplication in the Wazuh indexer

- https://github.com/wazuh/wazuh-packages/blame/v4.6.0/stack/indexer/rpm/wazuh-indexer.spec#L171-L193

![image](https://github.com/wazuh/wazuh-packages/assets/14913942/27258920-6324-42d0-b87d-49a7f8022090)

It is necessary to review the code of the Wazuh indexer and Wazuh Dashboard components to validate the integrity of the code and avoid possible problems in the use and generation of the components.

After reviewing the commit history, it is very possible that the problem is due to failed conflict resolution, it is very possible that there is more affected code in the rest of the repository.

:warning: The v4.5.4 tag does not contain this duplicated code https://github.com/wazuh/wazuh-packages/blame/v4.5.4/stack/indexer/rpm/wazuh-indexer.spec but those changes were added in the 4.4 version

## Tasks

- [x] Review the Wazuh indexer code
- [x] Review the Wazuh dashboard code
- [x] Delete or correct the necessary code

## Validation

- [ ] Stack components do not contain repeated code, packages are built and tests are executed without errors

**Comment by pro-akim** [comment]
## Update
Checking that there are no other wrongly solved conflicts. (Basically, duplicated code)

**Comment by pro-akim** [comment]
## Update
Reviewing the code in Stack/Dashboard and Stack/indexer, I haven't found any other repetitions or code defects that could lead to similar errors.
Fixes are done and now it will be tested

**Comment by davidjiglesias** [comment]
LGTM!
