### ISSUE TITLE
Support new stage RC 1 for 4.7.1 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2643]
## Description

This issue attempts to support a new stage RC 1 for 4.7.1 in the wazuh-packages repository.

## Tasks

- [ ] Ensure changelog is updated for 4.7.1 (if applicable).
- [ ] Bump revision for branch 4.7.1 on wazuh-packages repository.
- [ ] Add release ETA
- [ ] Create tag v4.7.1-rc1 from branch 4.7.1 on wazuh-packages repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.7.1-rc1.
