### ISSUE TITLE
The Wazuh indexer ISM log file should not be located in the `tmp` directory

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2657]
## Description

It has been detected that the Wazuh indexer package is creating a log file in `/tmp/wazuh-indexer`, this is not correct and it should use the package's log directory: `/var/log/wazuh-indexer`

https://github.com/wazuh/wazuh-packages/blob/d7487a68f35a514a534ac4cd8df0937b0e2a2003/stack/indexer/indexer-ism-init.sh#L15

A log file should be permanent since a reboot of the machine would lose this data.

Additionally, on certain systems, the `tmp` directory has the `noexec` flag, which prevents the installation of the package, this has been reported by many users, and an issue was opened to change it: https://github.com/wazuh/wazuh-packages/issues/1539

![image](https://github.com/wazuh/wazuh-packages/assets/14913942/4df5ceef-4d44-4459-a957-208c40ed43cb)

Related PR: https://github.com/wazuh/wazuh-packages/pull/2606/files

## Tasks

- [x] Change the ISM log file to `/var/log/wazuh-indexer`

## Validation

- [x] The operation of the package is correct
- [x] Logs are created and maintained correctly
- [x] Temporary directory is not used

**Comment by pro-akim** [comment]
## Review Notes
LGTM

**Comment by davidjiglesias** [comment]
LGTM
