### ISSUE TITLE
Support new Wazuh version 4.7.2 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2658]
## Description

This issue attempts to support a new version 4.7.2 in the wazuh-packages repository.

## Tasks

- [x] Create numbered branch for version (4.7.2) using branch 4.7.1 on wazuh-packages repository.
- [x] Bump 4.7.2 branch to 4.7.2 version on wazuh-packages repository, including revision and changelog.
- [x] Build and push testing images for GitHub actions.
