### ISSUE TITLE
Investigate if `gpg|gnupg` package is necessary as dependency in WIA

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2663]
## Description

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.1 | Wazuh stack | Wazuh central components | Installation Assistant | RHEL 9 |

In https://github.com/wazuh/wazuh/issues/20519, it would be necessary to investigate if the `gpg` or the `gnupg` package is necessary in the WIA.

In the Step-by-step documentation, it is not specified as a dependency in RPM-based systems: https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html#adding-the-wazuh-repository

https://github.com/wazuh/wazuh-packages/blob/d345399031a4e6e4c801277f56796755e0ec6ac0/unattended_installer/install_functions/installCommon.sh#L370

## Tasks

- [x] Remove the `gpg` or the `gnupg` package of a RPM-based system.
- [x] Check if the installation if performed correctly

If it is not necessary:

- [x] Remove the `gnupg` package of the dependency list

If it is necessary

- [ ] Add the `gnupg` package as a dependency in the documentation.
