### ISSUE TITLE
Function `installCommon_checkAptLock` is not found in WIA

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2686]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.8.0 | Installation Assistant | Install | Any |

## Description

It has been observed that the WIA is broken in 4.8.0.

```console
root@ubuntu22:/home/vagrant# bash wazuh-install.sh -a
13/12/2023 10:09:47 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
13/12/2023 10:09:47 INFO: Verbose logging redirected to /var/log/wazuh-install.log
13/12/2023 10:10:02 INFO: Verifying that your system meets the recommended minimum hardware requirements.
13/12/2023 10:10:02 INFO: Wazuh web interface port will be 443.
13/12/2023 10:10:07 INFO: --- Dependencies ----
13/12/2023 10:10:07 INFO: Installing apt-transport-https.
wazuh-install.sh: line 1808: installCommon_checkAptLock: command not found
wazuh-install.sh: line 1810: [: : integer expression expected
13/12/2023 10:10:07 ERROR: Cannot install dependency: apt-transport-https.
```

After some investigation, it has been found that the `installCommon_checkAptLock` has disappeared from the code. 
Related:
- https://github.com/wazuh/wazuh-packages/pull/2577/
- https://github.com/wazuh/wazuh-packages/pull/2639/

It is necessary to include the `installCommon_checkAptLock` in the `common.sh` file, rename the function, and call it when necessary.

## Tasks

- [x] Investigate a fix
- [x] Apply the fix
- [x] Validate the fix: 
  - [x] The `checkAptLock` function is included in the WIA and the rest of the tools: the cert and password tool.
  - [x] The cert tool works correctly
  - [x] The password tool works correctly
  - [x] The WIA works correctly

**Comment by davidcr01** [comment]
# Update Report

## Development

- The function has been moved to the `common.sh` file and renamed to `common_checkAptLock`
- The occurrences of `installCommon_checkAptLock` have been replaced to `common_checkAptLock`
- The function is correctly included in the password and certificates tools:
```console
>  cat wazuh-passwords-tool.sh| grep common_checkAptLock
function common_checkAptLock() {

> cat wazuh-certs-tool.sh| grep common_checkAptLock 
function common_checkAptLock() {
```

**Comment by jnasselle** [comment]
# RCA

Code was removed in this PR/commit https://github.com/wazuh/wazuh-packages/pull/2648/files#diff-31d5f1eaa91b837b7f91a80dbee9b531e84575ff1fcc23280e484ef223b7cadaL183-L196
