### ISSUE TITLE
Post release tasks for 4.7.1

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2704]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.1.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.1-into-4.7.2`.

## Tasks

- [x] Merge branch `4.7.1` into branch `4.7.2`. - https://github.com/wazuh/wazuh-packages/pull/2714
- [x] Merge branch `4.7.2` into branch `4.8.0`. - https://github.com/wazuh/wazuh-packages/pull/2715
- [x] Merge branch `4.8.0` into branch `4.8.1`.  - https://github.com/wazuh/wazuh-packages/pull/2718
- [x] Merge branch `4.8.1` into branch `master`. - https://github.com/wazuh/wazuh-packages/pull/2721
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.7.1 (https://github.com/wazuh/wazuh-packages/releases).
- [x] Delete all stage tags for v4.7.1. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.1-rc1, 4.7.1-alpha1, etc.
- [x] Delete branch `4.7.1`.

**Comment by vikman90** [comment]
## Deleting branch

Deleting _4.7.1_, it has no new commits:

```
ab7ec2e0 (HEAD -> 4.7.1, tag: v4.7.1-rc3, tag: v4.7.1-rc2, tag: v4.7.1, origin/4.7.1) Merge pull request #2675 from wazuh/bug/fix-source-branch-4.7.1
```

**Comment by jotacarma90** [comment]
Pending to merge last PR:
Merge branch 4.8.1 into branch master. - https://github.com/wazuh/wazuh-packages/pull/2721

Some of the checks that fail are known, as mentioned in the comment: https://github.com/wazuh/wazuh-packages/pull/2721#issuecomment-1867808211
Other checks are waiting to the wazuh/wazuh repo to last merge: https://github.com/wazuh/wazuh/pull/21024

**Comment by MarcelKemp** [comment]
Done.
