### ISSUE TITLE
Post release tasks for 4.7.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#2757]
## Description

This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.2.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.2-into-4.8.0`.

## Tasks

- [x] Merge branch `4.7.2` into branch `4.8.0`. (There are no changes to merge)
- [x] Merge branch `4.8.0` into branch `4.8.1`. #2759
- [x] Merge branch `4.8.1` into branch `4.8.2`. #2764
- [x] Merge branch `4.8.2` into branch `master`. #2768
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.7.2 (https://github.com/wazuh/wazuh-packages/releases).
- [x] Delete all stage tags for v4.7.2. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.2-rc1, 4.7.2-alpha1, etc.
- [x] Delete branch `4.7.2`.
