### ISSUE TITLE
Add roll back to the different WIA exit points

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#2785]
## Description

Analyzing the `WIA`, it was found that at different points of failure of the installer, the script outputs with `exit 1` are generated, but the installation is not rolled back, leaving an incomplete installation on the user's machine, for example:

```console
function dashboard_copyCertificates() {

    common_logger -d "Copying Wazuh dashboard certificates."
    eval "rm -f ${dashboard_cert_path}/* ${debug}"
    name=${dashboard_node_names[pos]}

    if [ -f "${tar_file}" ]; then
        if ! tar -tvf "${tar_file}" | grep -q "${name}" ; then
            common_logger -e "Tar file does not contain certificate for the node ${name}."
            installCommon_rollBack
            exit 1;
        fi
        eval "mkdir ${dashboard_cert_path} ${debug}"
        eval "sed -i s/dashboard.pem/${name}.pem/ /etc/wazuh-dashboard/opensearch_dashboards.yml ${debug}"
        eval "sed -i s/dashboard-key.pem/${name}-key.pem/ /etc/wazuh-dashboard/opensearch_dashboards.yml ${debug}"
        eval "tar -xf ${tar_file} -C ${dashboard_cert_path} wazuh-install-files/${name}.pem --strip-components 1 ${debug}"
        eval "tar -xf ${tar_file} -C ${dashboard_cert_path} wazuh-install-files/${name}-key.pem --strip-components 1 ${debug}"
        eval "tar -xf ${tar_file} -C ${dashboard_cert_path} wazuh-install-files/root-ca.pem --strip-components 1 ${debug}"
        eval "chown -R wazuh-dashboard:wazuh-dashboard /etc/wazuh-dashboard/ ${debug}"
        eval "chmod 500 ${dashboard_cert_path} ${debug}"
        eval "chmod 400 ${dashboard_cert_path}/* ${debug}"
        eval "chown wazuh-dashboard:wazuh-dashboard ${dashboard_cert_path}/* ${debug}"
        common_logger -d "Wazuh dashboard certificate setup finished."
    else
        common_logger -e "No certificates found. Wazuh dashboard  could not be initialized."
        exit 1
    fi

}
```

## Tasks

- [x] Analyze all the `exit 1`s that exist in the `WIA` and add a call to the `installCommon_rollBack` function previously

## Validation

- [x] Verify that in the event of these errors the script eliminates what was previously installed

**Comment by davidcr01** [comment]
# Update Report

## Research

The following functions have an `exit 1`. Each function has been reviewed and checked if it is necessary to add a rollback or not.

- [x] ~~offline_download~~ There is no installation when the function is called.
- [x] ~~manager_install~~ Rollback already added.
- [x] ~~getHelp~~ There is no installation when the function is called.
- [x] ~~main~~ Exit codes of wrong arguments.
- [x] ~~checks_arch~~ There is no installation when the function is called.
- [x] ~~checks_arguments~~ There is no installation when the function is called.
- [x] ~~check_dist~~ There is no installation when the function is called.
- [x] ~~checks_health~~ There is no installation when the function is called.
- [x] ~~checks_names~~ There is no installation when the function is called.
- [x] ~~checks_previousCertificate~~ There is no installation when the function is called.
- [x] ~~checks_ports~~ There is no installation when the function is called.
- [x] ~~checks_available_port~~ There is no installation when the function is called.
- [x] ~~installCommon_cleanExit~~ Rollback already added.
- [x] ~~installCommon_addWazuhRepo~~ There is no installation when the function is called.
- [ ] installCommon_aptInstallList
- [x] ~~installCommon_createInstallFiles~~ There is no installation when the function is called.
- [ ] installCommon_changePasswords
- [x] ~~installCommon_extractConfig~~ There is no installation when the function is called.
- [x] ~~installCommon_getConfig~~ Rollback already added.
- [x] ~~installCommon_readPasswordFileUsers~~ Rollback already added.
- [x] ~~installCommon_startService~~ Rollback already added.
- [ ] installCommon_yumInstallList
- [x] ~~installCommon_yumRemoveWIADependencies~~ Not applicable as it is a removal function.
- [x] ~~installCommon_aptRemoveWIADependencies~~ Not applicable as it is a removal function.
- [ ] dashboard_copyCertificates
- [x] ~~dashboard_initialize~~ Rollback already added.
- [x] ~~dashboard_initializeAIO~~ Rollback already added.
- [x] ~~dashboard_install~~ Rollback already added.
- [x] ~~filebeat_configure~~ Rollback already added.
- [ ] filebeat_copyCertificates
- [x] ~~filebeat_install~~ Rollback already added.
- [x] ~~indexer_copyCertificates~~ Rollback already added.
- [x] ~~indexer_initialize~~ Rollback already added.
- [x] ~~indexer_install~~ Rollback already added.
- [ ] indexer_startCluster
- [x] ~~common_checkRoot~~ There is no installation when the function is called.
- [x] ~~common_checkSystem~~ There is no installation when the function is called.
- [x] ~~common_checkWazuhConfigYaml~~ There is no installation when the function is called.
- [x] ~~cert_checkOpenSSL~~ There is no installation when the function is called.
- [x] ~~cert_checkRootCA~~ There is no installation when the function is called.
- [x] ~~cert_executeAndValidate~~ There is no installation when the function is called.
- [ ] cert_generateCertificateconfiguration
- [x] ~~cert_readConfig~~ There is no installation when the function is called.
- [x] ~~passwords_checkUser~~ Not necessary as it is only used in the Password tool.
- [x] ~~passwords_checkPassword~~ Rollback already added.
- [ ] passwords_createBackUp
- [ ] passwords_generateHash
- [ ] passwords_generatePassword
- [x] ~~passwords_getApiToken~~ Rollback already added.
- [x] ~~passwords_getApiUserId~~ Rollback already added.
- [x] ~~passwords_readFileUsers~~ Not necessary as it is only used in the Password tool.
- [x] ~~passwords_restartService~~ Rollback already added.
- [ ] passwords_runSecurityAdmin

As a conclusion, the functions that may need to add a rollback:
- [ ] installCommon_aptInstallList
- [ ] installCommon_changePasswords
- [ ] installCommon_yumInstallList
- [ ] dashboard_copyCertificates
- [ ] filebeat_copyCertificates
- [ ] indexer_startCluster
- [ ] cert_generateCertificateconfiguration
- [ ] passwords_createBackUp
- [ ] passwords_generateHash
- [ ] passwords_generatePassword
- [ ] passwords_runSecurityAdmin
