### ISSUE TITLE
OVA report alerts before first use

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2816]
## Description

The OVA v4.8.0-beta1 reports alerts before the start of the virtual machine, in this case, corresponding to the construction period of the OVA, these alerts should not have been indexed since the environment should reach the user clean

![image](https://github.com/wazuh/wazuh-packages/assets/14913942/f3c7dbdd-97fb-4782-be63-7a7d75961cd6)

## Tasks

- [x] Investigate why the OVA registers alerts before the first use
- [x] Check if this affects the AMI or Docker images
- [x] Modify as necessary so that there are no alerts before first use

## Validation

- [x] Wazuh virtual machines are clean before first use

**Comment by davidcr01** [comment]
# Update Report

## Workaround

The workaround is the following:
- Stop manager and Filebeat services
- Delete indexes.
- Stop indexer and dashboard services.
- Delete files: ossec.log, alerts.log, alerts.json, indexer. etc.

Related lines: https://github.com/wazuh/wazuh-packages/blob/4.8.0/ova/provision.sh#L44-L49

**Comment by davidcr01** [comment]
# Update Report

I found a problem and it seems that the `/usr/share/wazuh-dasboard/data/wazuh/config/wazuh.yml` file is empty after the OVA generation, leading to this error:

![image](https://github.com/wazuh/wazuh-packages/assets/72193239/398430f1-692d-4f03-929d-274c13166b7b)

I am currently investigating why this file is empty.

**Comment by davidcr01** [comment]
# Update Report

## Investigation

After a further investigation with @rauldpm, we concluded that it is necessary a shutdown of the VM before generating the OVA to save the state of the machine. With this shutdown, it is proven that the `wazuh.yml` of the Wazuh dashboard has the correct content.

This is related to:
- https://github.com/wazuh/wazuh-packages/pull/2365/files
- https://github.com/wazuh/wazuh-jenkins/issues/2541#issuecomment-832924588

To summarize, the deleted `postProvision.sh` script that was removed of the OVA generation was deleted. This script is in charge of cleaning up all the unnecessary files, removing the vagrant user (currently unnecessary because the Vagrant box used to generate the OVA does not have the Vagrant user), and shutting down the machine to save the state of the machine.

The **shutdown** can't be added directly to the `provision.sh` because this script is used in the automated OVA generation in Jenkins, related:
- https://github.com/wazuh/wazuh-jenkins/blob/master/ansible-playbooks/wazuh_ova_generation.yml

In this YAML, the cleanup and the shutdown of the machine is performed in other tasks. Then, we can not the shutdown in the `provision.sh` because it will shutdown the machine before all tasks are executed:

The shutdown will be executed in the `Run provision script` and the machine will be powered off
```yml
    - name: Run provision script
      command: "sh provision.sh {{ repository }} {{ debug }}"
      args:
        chdir: "{{ packages_path }}/ova"

    - name: Clean provision files
      file:
        path: /var/provision/
        state: absent

    - name: Clean unattended resources
      file:
        path: /tmp/{{ unattended_scripts }}
        state: absent

    - name: Clean logs
      command: find /var/log/ -type f -exec bash -c 'cat /dev/null > {}' \;

    - name: Clean history
      shell: cat /dev/null > ~/.bash_history && history -c
```

Another possible solution could be to add these tasks to the `provision.sh` script, but to modularize the tasks of the OVA generation and to preserve the definition and objective of these files, is better to have these tasks separately.

As a conclusion, the `postProvision.sh` script will be restored to the OVA generation, saving the machine state and performing all the clean up stages, without affecting the pipeline.

**Comment by davidcr01** [comment]
# Update Report

## :green_circle:  Testing in local

After the OVA generation in local, it seems that the alerts have been collected and generated since the machine is started (the first alert is generated at `12:57:11.329`, one minute after the machine is started), so no previous logs are displayed:

![image](https://github.com/wazuh/wazuh-packages/assets/72193239/4adef836-5fc1-4c69-822e-6e878a3d3cd0)

(Notice that it is necessary to add an hour to get real-time)
```console
[root@wazuh-server wazuh-user]#uptime -p -s
2024-02-14 11:56:42
```

The indices are created and in a green state:
![image](https://github.com/wazuh/wazuh-packages/assets/72193239/e9f908af-a2ff-4460-aca1-6bb70929395b)


After these changes

## Testing in Jenkins
