### ISSUE TITLE
Support new Wazuh version 5.0.0 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2823]
## Description

This issue attempts to support a new version 5.0.0 in the wazuh-packages repository.

## Tasks

- [x] Create numbered branch for current master version (4.9.0) using master branch on wazuh-packages repository.
- [x] Bump master branch to 5.0.0 on wazuh-packages repository, including revision and changelog.
- [ ] Build and push testing images for GitHub actions.
