### ISSUE TITLE
Support new stage Beta 2 for 4.8.0 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2851]
## Description

This issue attempts to support a new stage Beta 2 for 4.8.0 in the wazuh-packages repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.0 (if applicable).
- [ ] Bump revision for branch 4.8.0 on wazuh-packages repository.
- [ ] Add release ETA
- [ ] Create tag v4.8.0-beta2 from branch 4.8.0 on wazuh-packages repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.8.0-beta2.
