### ISSUE TITLE
Installation assistant should backup logs before rollback

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2881]
## Description

Adding rollbacks in https://github.com/wazuh/wazuh-packages/issues/2785, the team thought that it would be interesting that the Installation Assistant collected the logs of the components that are going to be uninstalled and save them in a folder.

This backup of the logs could be useful in case of performing a rollback in case of error. By consulting the backup logs, more information can be considered by guessing the error cause.

## Tasks

- [ ] Decide the path of the log and the name of the log file.
- [ ] Develop the logic.
- [ ] Test that the log of the components that were removed is collected in the log file.
