### ISSUE TITLE
Support new Wazuh version 4.7.4 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2914]
## Description

This issue attempts to support a new version 4.7.4 in the wazuh-packages repository.

## Tasks

- [ ] Bump 4.7.4 branch to 4.7.4 version on wazuh-packages repository, including revision and changelog.
- [ ] Build and push testing images for GitHub actions.
- [ ] Build ECR and create ECS tasks definition if needed.
