### ISSUE TITLE
Support new Wazuh version 4.7.4 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2918]
## Description

This issue attempts to support a new version 4.7.4 in the wazuh-packages repository.

## Tasks

- [x] Bump 4.7.4 branch to 4.7.4 version on wazuh-packages repository, including revision and changelog.
  - https://github.com/wazuh/wazuh-packages/pull/2919
  - Expected failed checks: https://github.com/wazuh/wazuh-packages/pull/2919#issuecomment-2064343310
- [x] ~Build and push testing images for GitHub actions.~ The previously created `4.7` tag should be used.
- [x] Build ECR and create ECS tasks definition if needed.
