### ISSUE TITLE
Wazuh packages redesign tier 2 - DevOps migration

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2938]
| Epic issue |
| :--: |
| https://github.com/wazuh/wazuh-packages/issues/2904 |

# Description

This stage is intended to migrate the DevOps repositories from wazuh-packages to the DevOps repositories and add CI testing

## Functional and non-functional requirements

- See https://github.com/wazuh/internal-devel-requests/issues/187#issue-1871209243
- TBD Tier 2 requirements

## Pre-requisites

- https://github.com/wazuh/internal-devel-requests/issues/187

## Resources

- [Related resources at wazuh-packages](https://github.com/wazuh/wazuh-packages) 
  - OVA
  - Wazuh Unattended Scripts
  - puppet_module
- [Related resources at wazuh-jenkins](https://github.com/wazuh/wazuh-jenkins)
  - AMI 

# Tasks

Each of the following tasks should be considered a sub-epic (level/task) issue, each issue should be opened in the new repositories

- [x] Create and configure new GitHub repositories for Wazuh Virtual Machines and Wazuh Unattended Scripts
  - Repositories already created by @havidarou 
    - https://github.com/wazuh/wazuh-virtual-machines
    - https://github.com/wazuh/wazuh-installation-assistant
- [ ] https://github.com/wazuh/wazuh-installation-assistant/issues/1 
- [ ] https://github.com/wazuh/wazuh-virtual-machines/issues/1
- [ ] https://github.com/wazuh/wazuh-virtual-machines/issues/2
- [ ] https://github.com/wazuh/wazuh-puppet/issues/926
- [ ] Demo deployment

Each task must meet the following objectives

- Research and set ETA for the parent issue (notify DRI)
- Issue: Migrate tool code to target repository - Manual package generation
- Issue: Package creation through CI
- Issue: Add secrets to GH (S3 and CloudFront access - QA team)
- Issue: Add CI testing
- Issue: Upload packages to S3 through CI. This must be done after the testing phase

# Approved by

- DRI name: TBD

**Comment by damarisg** [comment]
Duplicated
