### ISSUE TITLE
Support new Wazuh version 4.7.5 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2949]
## Description

This issue attempts to support a new version 4.7.5 in the wazuh-packages repository.

## Tasks

- [x] Bump 4.7.5 branch to 4.7.5 version on wazuh-packages repository, including revision and changelog.
- [x] Build and push testing images for GitHub actions. (No necessary if it is a patch version)
- [x] Build ECR and create ECS tasks definition if needed.
