### ISSUE TITLE
Fix `Test_unattended` and `Test_unattended_distributed` pytests

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-packages#2952]
## Description

We have observed that the `Test_unattended` and `Test_unattended_distributed` Jenkins pipelines are failing constantly because the `test_check_log_errors` function of the `test_unattended.py` pytest is matching an error.
This makes the pipeline fail, even if the installation process has been completed successfully.

It is necessary to fix this.

```console
=================================== FAILURES ===================================____________________________ test_check_log_errors _____________________________


@pytest.mark.wazuh    
def test_check_log_errors():        
found_error = False
       with open('/var/ossec/logs/ossec.log', 'r') as f:
            for line in f.readlines():
                if 'ERROR' in line:
                    if 'ERROR: Cluster error detected' not in line and 'agent-upgrade: ERROR: (8123): There has been an error executing the request in the tasks manager.' not in line:
                        found_error = True
                        break
>       assert found_error == False, line
E       AssertionError: 2024/05/15 19:15:55 wazuh-modulesd: ERROR: Could not send message through the cluster after '10' attempts.
E         
E       assert True == False
E         +True
E         -False

test_unattended.py:217: AssertionError\n=============================== 
```

## Tasks

- [x] Check the error that is causing the `pytest` to fail.
- [x] Add the exception to the test
- [x] Launch both pipelines and check they pass correctly.

**Comment by davidcr01** [comment]
# Update Report

After some testing, it seems that the error logs reported in the `/var/ossec/logs/ossec.log` file are the following:

````console
root@ip-172-31-86-128:/var/snap/amazon-ssm-agent/4046# cat /var/ossec/logs/ossec.log | grep -i ERROR
2024/05/17 09:12:39 wazuh-modulesd: WARNING: Cluster error detected
2024/05/17 09:12:40 wazuh-modulesd: WARNING: Cluster error detected
2024/05/17 09:12:41 wazuh-modulesd: WARNING: Cluster error detected
2024/05/17 09:12:42 wazuh-modulesd: WARNING: Cluster error detected
2024/05/17 09:12:43 wazuh-modulesd: WARNING: Cluster error detected
2024/05/17 09:12:44 wazuh-modulesd: WARNING: Cluster error detected
2024/05/17 09:12:45 wazuh-modulesd: WARNING: Cluster error detected
2024/05/17 09:12:46 wazuh-modulesd: WARNING: Cluster error detected
2024/05/17 09:12:47 wazuh-modulesd: WARNING: Cluster error detected
2024/05/17 09:12:48 wazuh-modulesd: WARNING: Cluster error detected
2024/05/17 09:12:48 wazuh-modulesd: ERROR: Could not send message through the cluster after '10' attempts.
2024/05/17 09:12:48 wazuh-modulesd:agent-upgrade: ERROR: (8123): There has been an error executing the request in the tasks manager.
```

- The `Cluster error detected` is added as an exception in the pytest.
- The `There has been an error executing the request in the tasks manager` is added as an exception in the pytest.

The error that seems to be causing the pipeline to fail is the `ERROR: Could not send message through the cluster after '10' attempts.` error.
