### ISSUE TITLE
Support new Wazuh version 4.8.1 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#2981]
## Description

This issue attempts to support a new version 4.8.1 in the wazuh-packages repository.

## Tasks

- [x] Bump 4.8.1 branch to 4.8.1 version on wazuh-packages repository, including revision and changelog.
  - https://github.com/wazuh/wazuh-packages/pull/2982
- [x] Build and push testing images for GitHub actions. (No necessary if it is a patch version)
- [x] Build ECR and create ECS tasks definition if needed.
