### ISSUE TITLE
Support new stage Alpha 1 for 4.9.0 in wazuh-packages repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#3010]
## Description

This issue attempts to support a new stage Alpha 1 for 4.9.0 in the wazuh-packages repository.

## Tasks

- [ ] Ensure changelog is updated for 4.9.0 (if applicable).
- [ ] Bump revision for branch 4.9.0 on wazuh-packages repository.
- [ ] Add release ETA
- [ ] Create tag v4.9.0-alpha1 from branch 4.9.0 on wazuh-packages repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.9.0-alpha1.
