### ISSUE TITLE
Wazuh installation assistant fails in v4.9.0-alpha1

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#3013]
# Description

The Wazuh installation assistant failed to install an All In One deployment in 4.9.0 when trying to initialize the Wazuh dashboard in a YUM-based system

Full log: [wazuh-install.log](https://github.com/user-attachments/files/15928534/wazuh-install.log)

```
21/06/2024 13:22:22 INFO: Initializing Wazuh dashboard web application.
21/06/2024 13:22:22 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:22:37 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:22:52 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:23:07 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:23:22 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:23:37 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:23:52 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:24:08 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:24:23 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:24:38 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:24:53 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:25:08 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:25:23 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:25:38 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:25:53 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:26:08 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:26:23 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:26:38 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:26:53 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:27:08 INFO: Wazuh dashboard web application not yet initialized. Waiting...
21/06/2024 13:27:23 ERROR: Wazuh dashboard installation failed.
21/06/2024 13:27:23 INFO: --- Removing existing Wazuh installation ---
```

The following messages are also observed

```
21/06/2024 13:20:51 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
21/06/2024 13:20:56 INFO: Updated username and password in Filebeat Keystore. Also updated filebeat.yml file to use the Filebeat Keystore username and password.
```

Please consider changing the sentence `Also updated filebeat.yml file to use the Filebeat Keystore username and password.` to something more fluent like: `The filebeat.yml file has been updated to use the Filebeat Keystore username and password.`

# Tasks

- [ ] Remove undesired messages from the non-debug output (deprecation messages)
- [ ] Investigate and fix the Wazuh dashboard installation
- [ ] Improve Filebeat keystore message

**Comment by c-bordon** [comment]
## Update report

Doing an All in One installation, the Wazuh indexer installation failed because the package manager cannot find a package for version 4.9.0

```console
24/06/2024 10:01:34 INFO: Starting Wazuh indexer installation.
Reading package lists... Building dependency tree... Reading state information... Package wazuh-indexer is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source E: Version '4.9.0-*' for 'wazuh-indexer' was not found
24/06/2024 10:01:34 DEBUG: Checking Wazuh installation.
24/06/2024 10:01:35 ERROR: Wazuh indexer installation failed.
24/06/2024 10:01:35 INFO: --- Removing existing Wazuh installation ---

```

This behavior was reported to the Wazuh indexer team and may be a problem in the package repository metadata.

**Comment by rauldpm** [comment]
@c-bordon Sorry I should have specified that this is a YUM system, not an APT system, please check the log file

**Comment by c-bordon** [comment]
## Update report

### Apt test

```console
root@ubuntu-jammy:~# curl -sO https://packages-dev.wazuh.com/4.9/wazuh-install.sh
root@ubuntu-jammy:~# bash wazuh-install.sh -a
24/06/2024 14:51:01 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
24/06/2024 14:51:01 INFO: Verbose logging redirected to /var/log/wazuh-install.log
24/06/2024 14:51:26 INFO: Verifying that your system meets the recommended minimum hardware requirements.
24/06/2024 14:51:29 INFO: Wazuh web interface port will be 443.
24/06/2024 14:51:35 INFO: --- Dependencies ----
24/06/2024 14:51:35 INFO: Installing apt-transport-https.
24/06/2024 14:51:38 INFO: Installing debhelper.
24/06/2024 14:52:07 INFO: Wazuh development repository added.
24/06/2024 14:52:07 INFO: --- Configuration files ---
24/06/2024 14:52:07 INFO: Generating configuration files.
24/06/2024 14:52:08 INFO: Generating the root certificate.
24/06/2024 14:52:08 INFO: Generating Admin certificates.
24/06/2024 14:52:08 INFO: Generating Wazuh indexer certificates.
24/06/2024 14:52:08 INFO: Generating Filebeat certificates.
24/06/2024 14:52:08 INFO: Generating Wazuh dashboard certificates.
24/06/2024 14:52:09 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
24/06/2024 14:52:09 INFO: --- Wazuh indexer ---
24/06/2024 14:52:09 INFO: Starting Wazuh indexer installation.
24/06/2024 14:52:10 ERROR: Wazuh indexer installation failed.
24/06/2024 14:52:10 INFO: --- Removing existing Wazuh installation ---
24/06/2024 14:52:10 INFO: Installation cleaned. Check the /var/log/wazuh-install.log file to learn more about the issue.
root@ubuntu-jammy:~# bash wazuh-install.sh -a -v
24/06/2024 14:52:16 DEBUG: Checking root permissions.
24/06/2024 14:52:16 DEBUG: Checking sudo package.
24/06/2024 14:52:16 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
24/06/2024 14:52:16 INFO: Verbose logging redirected to /var/log/wazuh-install.log
24/06/2024 14:52:16 DEBUG: APT package manager will be used.
24/06/2024 14:52:16 DEBUG: Checking system distribution.
24/06/2024 14:52:16 DEBUG: Detected distribution name: ubuntu
24/06/2024 14:52:16 DEBUG: Detected distribution version: 22
24/06/2024 14:52:16 DEBUG: Installing check dependencies.
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists...
24/06/2024 14:52:21 DEBUG: Checking Wazuh installation.
24/06/2024 14:52:21 DEBUG: Checking system architecture.
24/06/2024 14:52:21 INFO: Verifying that your system meets the recommended minimum hardware requirements.
24/06/2024 14:52:21 DEBUG: CPU cores detected: 4
24/06/2024 14:52:21 DEBUG: Free RAM memory detected: 7937
24/06/2024 14:52:21 DEBUG: Installing check dependencies.
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists...
24/06/2024 14:52:25 INFO: Wazuh web interface port will be 443.
24/06/2024 14:52:25 DEBUG: Checking ports availability.
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists...
24/06/2024 14:52:28 DEBUG: Installing prerequisites dependencies.
24/06/2024 14:52:31 DEBUG: Checking curl tool version.
24/06/2024 14:52:31 DEBUG: Adding the Wazuh repository.
gpg: keyring '/usr/share/keyrings/wazuh.gpg' created
gpg: key 96B3EE5F29111145: public key "Wazuh.com (Wazuh Signing Key) <support@wazuh.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages-dev.wazuh.com/pre-release/apt/ unstable main
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 https://packages-dev.wazuh.com/pre-release/apt unstable InRelease [17.3 kB]
Get:6 https://packages-dev.wazuh.com/pre-release/apt unstable/main amd64 Packages [38.9 kB]
Fetched 56.2 kB in 2s (29.3 kB/s)
Reading package lists...
24/06/2024 14:52:35 INFO: Wazuh development repository added.
24/06/2024 14:52:35 INFO: --- Configuration files ---
24/06/2024 14:52:35 INFO: Generating configuration files.
24/06/2024 14:52:35 DEBUG: Creating Wazuh certificates.
24/06/2024 14:52:35 DEBUG: Reading configuration file.
24/06/2024 14:52:35 DEBUG: Checking if 127.0.0.1 is private.
24/06/2024 14:52:35 DEBUG: Checking if 127.0.0.1 is private.
24/06/2024 14:52:35 DEBUG: Checking if 127.0.0.1 is private.
24/06/2024 14:52:35 INFO: Generating the root certificate.
24/06/2024 14:52:35 INFO: Generating Admin certificates.
24/06/2024 14:52:35 DEBUG: Generating Admin private key.
24/06/2024 14:52:35 DEBUG: Converting Admin private key to PKCS8 format.
24/06/2024 14:52:35 DEBUG: Generating Admin CSR.
24/06/2024 14:52:35 DEBUG: Creating Admin certificate.
24/06/2024 14:52:35 INFO: Generating Wazuh indexer certificates.
24/06/2024 14:52:35 DEBUG: Creating the certificates for wazuh-indexer indexer node.
24/06/2024 14:52:35 DEBUG: Generating certificate configuration.
24/06/2024 14:52:35 DEBUG: Creating the Wazuh indexer tmp key pair.
24/06/2024 14:52:36 DEBUG: Creating the Wazuh indexer certificates.
24/06/2024 14:52:36 INFO: Generating Filebeat certificates.
24/06/2024 14:52:36 DEBUG: Generating the certificates for wazuh-server server node.
24/06/2024 14:52:36 DEBUG: Generating certificate configuration.
24/06/2024 14:52:36 DEBUG: Creating the Wazuh server tmp key pair.
24/06/2024 14:52:36 DEBUG: Creating the Wazuh server certificates.
24/06/2024 14:52:36 INFO: Generating Wazuh dashboard certificates.
24/06/2024 14:52:36 DEBUG: Generating certificate configuration.
24/06/2024 14:52:36 DEBUG: Creating the Wazuh dashboard tmp key pair.
24/06/2024 14:52:36 DEBUG: Creating the Wazuh dashboard certificates.
24/06/2024 14:52:36 DEBUG: Cleaning certificate files.
24/06/2024 14:52:36 DEBUG: Generating password file.
24/06/2024 14:52:36 DEBUG: Generating random passwords.
24/06/2024 14:52:36 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
24/06/2024 14:52:36 DEBUG: Extracting Wazuh configuration.
24/06/2024 14:52:36 DEBUG: Reading configuration file.
24/06/2024 14:52:36 DEBUG: Checking if 127.0.0.1 is private.
24/06/2024 14:52:36 DEBUG: Checking if 127.0.0.1 is private.
24/06/2024 14:52:36 DEBUG: Checking if 127.0.0.1 is private.
24/06/2024 14:52:36 INFO: --- Wazuh indexer ---
24/06/2024 14:52:36 INFO: Starting Wazuh indexer installation.
Reading package lists... Building dependency tree... Reading state information... Package wazuh-indexer is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source E: Version '4.9.0-*' for 'wazuh-indexer' was not found
24/06/2024 14:52:37 DEBUG: Checking Wazuh installation.
24/06/2024 14:52:38 ERROR: Wazuh indexer installation failed.
24/06/2024 14:52:38 INFO: --- Removing existing Wazuh installation ---
24/06/2024 14:52:38 DEBUG: Removing GPG key from system.
24/06/2024 14:52:38 INFO: Installation cleaned. Check the /var/log/wazuh-install.log file to learn more about the issue.
```

Using the wizard, the `4.9.0` package is not found on this system.

With manual installation, the package that is installed is `4.5.2`

```console
root@ubuntu-jammy:~# apt-get install gnupg apt-transport-https -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gnupg is already the newest version (2.2.27-3ubuntu2.1).
gnupg set to manually installed.
apt-transport-https is already the newest version (2.4.12).
0 upgraded, 0 newly installed, 0 to remove and 101 not upgraded.
root@ubuntu-jammy:~# curl -s https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
gpg: keyring '/usr/share/keyrings/wazuh.gpg' created
gpg: key 96B3EE5F29111145: public key "Wazuh.com (Wazuh Signing Key) <support@wazuh.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
root@ubuntu-jammy:~# echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages-dev.wazuh.com/4.x/apt/ unstable main" | tee -a /etc/apt/sources.list.d/wazuh.list
deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages-dev.wazuh.com/4.x/apt/ unstable main
root@ubuntu-jammy:~# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 https://packages-dev.wazuh.com/4.x/apt unstable InRelease [17.3 kB]
Get:6 https://packages-dev.wazuh.com/4.x/apt unstable/main amd64 Packages [6105 B]
Fetched 23.4 kB in 2s (11.5 kB/s)   
Reading package lists... Done
root@ubuntu-jammy:~# apt-get -y install wazuh-indexer
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  wazuh-indexer
0 upgraded, 1 newly installed, 0 to remove and 101 not upgraded.
Need to get 688 MB of archives.
After this operation, 971 MB of additional disk space will be used.
Get:1 https://packages-dev.wazuh.com/4.x/apt unstable/main amd64 wazuh-indexer amd64 4.5.2-0.0.0.2139 [688 MB]
Fetched 688 MB in 1min 12s (9570 kB/s)                                                                                                                                                                                                     
Selecting previously unselected package wazuh-indexer.
(Reading database ... 70918 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.5.2-0.0.0.2139_amd64.deb ...
Creating wazuh-indexer group... OK
Creating wazuh-indexer user... OK
Unpacking wazuh-indexer (4.5.2-0.0.0.2139) ...
Setting up wazuh-indexer (4.5.2-0.0.0.2139) ...
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
Processing triggers for libc-bin (2.35-0ubuntu3.6) ...
Scanning processes...                                                                                                                                                                                                                       
Scanning candidates...                                                                                                                                                                                                                      
Scanning linux images...                                                                                                                                                                                                                    

Running kernel seems to be up-to-date.

Restarting services...
 systemctl restart cron.service irqbalance.service multipathd.service packagekit.service polkit.service rsyslog.service serial-getty@ttyS0.service snapd.service ssh.service systemd-journald.service systemd-networkd.service systemd-resolved.service systemd-timesyncd.service systemd-udevd.service
Service restarts being deferred:
 /etc/needrestart/restart.d/dbus.service
 systemctl restart getty@tty1.service
 systemctl restart networkd-dispatcher.service
 systemctl restart systemd-logind.service
 systemctl restart unattended-upgrades.service
 systemctl restart user@1000.service

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
root@ubuntu-jammy:~# cat /etc/wazuh-indexer/
.opensearch.keystore.initial_md5sum  jvm.options.d/                       opensearch-notifications/            opensearch-observability/            opensearch-reports-scheduler/        opensearch.keystore
jvm.options                          log4j2.properties                    opensearch-notifications-core/       opensearch-performance-analyzer/     opensearch-security/                 opensearch.yml
root@ubuntu-jammy:~# cat /etc/wazuh-indexer/
.opensearch.keystore.initial_md5sum  jvm.options.d/                       opensearch-notifications/            opensearch-observability/            opensearch-reports-scheduler/        opensearch.keystore
jvm.options                          log4j2.properties                    opensearch-notifications-core/       opensearch-performance-analyzer/     opensearch-security/                 opensearch.yml
root@ubuntu-jammy:~# cat /usr/share/wazuh-indexer/VERSION 
4.5.2

```

**Comment by c-bordon** [comment]
## Update report

### Yum test

```console
[root@centos8 ~]# systemctl  status wazuh-dashboard -l
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2024-06-24 15:51:04 UTC; 1min 40s ago
 Main PID: 34626 (node)
    Tasks: 11 (limit: 49489)
   Memory: 198.6M
   CGroup: /system.slice/wazuh-dashboard.service
           └─34626 /usr/share/wazuh-dashboard/node/bin/node /usr/share/wazuh-dashboard/src/cli/dist -c /etc/wazuh-dashboard/opensearch_dashboards.yml

Jun 24 15:51:04 centos8.localdomain systemd[1]: Started wazuh-dashboard.
Jun 24 15:51:04 centos8.localdomain systemd[34626]: wazuh-dashboard.service: Failed to connect stdout to the journal socket, ignoring: Permission denied
[root@centos8 ~]# journalctl -xe -u wazuh-dashboard.service --no-pager
-- Logs begin at Mon 2024-06-24 14:48:49 UTC, end at Mon 2024-06-24 15:51:50 UTC. --
Jun 24 14:56:37 centos8.localdomain systemd[1]: Started wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished starting up.
-- 
-- The start-up result is done.
Jun 24 14:56:37 centos8.localdomain systemd[8708]: wazuh-dashboard.service: Failed to connect stdout to the journal socket, ignoring: Permission denied
Jun 24 14:57:11 centos8.localdomain systemd[1]: Stopping wazuh-dashboard...
-- Subject: Unit wazuh-dashboard.service has begun shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has begun shutting down.
Jun 24 14:57:11 centos8.localdomain systemd[1]: wazuh-dashboard.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit wazuh-dashboard.service has successfully entered the 'dead' state.
Jun 24 14:57:11 centos8.localdomain systemd[1]: Stopped wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished shutting down.
Jun 24 14:57:11 centos8.localdomain systemd[1]: Started wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished starting up.
-- 
-- The start-up result is done.
Jun 24 14:57:11 centos8.localdomain systemd[10531]: wazuh-dashboard.service: Failed to connect stdout to the journal socket, ignoring: Permission denied
Jun 24 15:02:52 centos8.localdomain systemd[1]: Stopping wazuh-dashboard...
-- Subject: Unit wazuh-dashboard.service has begun shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has begun shutting down.
Jun 24 15:02:53 centos8.localdomain systemd[1]: wazuh-dashboard.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit wazuh-dashboard.service has successfully entered the 'dead' state.
Jun 24 15:02:53 centos8.localdomain systemd[1]: Stopped wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished shutting down.
Jun 24 15:18:30 centos8.localdomain systemd[1]: Started wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished starting up.
-- 
-- The start-up result is done.
Jun 24 15:18:30 centos8.localdomain systemd[17889]: wazuh-dashboard.service: Failed to connect stdout to the journal socket, ignoring: Permission denied
Jun 24 15:19:05 centos8.localdomain systemd[1]: Stopping wazuh-dashboard...
-- Subject: Unit wazuh-dashboard.service has begun shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has begun shutting down.
Jun 24 15:19:05 centos8.localdomain systemd[1]: wazuh-dashboard.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit wazuh-dashboard.service has successfully entered the 'dead' state.
Jun 24 15:19:05 centos8.localdomain systemd[1]: Stopped wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished shutting down.
Jun 24 15:19:05 centos8.localdomain systemd[1]: Started wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished starting up.
-- 
-- The start-up result is done.
Jun 24 15:19:05 centos8.localdomain systemd[19697]: wazuh-dashboard.service: Failed to connect stdout to the journal socket, ignoring: Permission denied
Jun 24 15:24:46 centos8.localdomain systemd[1]: Stopping wazuh-dashboard...
-- Subject: Unit wazuh-dashboard.service has begun shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has begun shutting down.
Jun 24 15:24:47 centos8.localdomain systemd[1]: wazuh-dashboard.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit wazuh-dashboard.service has successfully entered the 'dead' state.
Jun 24 15:24:47 centos8.localdomain systemd[1]: Stopped wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished shutting down.
Jun 24 15:32:24 centos8.localdomain systemd[1]: Started wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished starting up.
-- 
-- The start-up result is done.
Jun 24 15:32:24 centos8.localdomain systemd[26773]: wazuh-dashboard.service: Failed to connect stdout to the journal socket, ignoring: Permission denied
Jun 24 15:32:57 centos8.localdomain systemd[1]: Stopping wazuh-dashboard...
-- Subject: Unit wazuh-dashboard.service has begun shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has begun shutting down.
Jun 24 15:32:57 centos8.localdomain systemd[1]: wazuh-dashboard.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit wazuh-dashboard.service has successfully entered the 'dead' state.
Jun 24 15:32:57 centos8.localdomain systemd[1]: Stopped wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished shutting down.
Jun 24 15:32:57 centos8.localdomain systemd[1]: Started wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished starting up.
-- 
-- The start-up result is done.
Jun 24 15:32:57 centos8.localdomain systemd[28630]: wazuh-dashboard.service: Failed to connect stdout to the journal socket, ignoring: Permission denied
Jun 24 15:34:55 centos8.localdomain systemd[1]: Stopping wazuh-dashboard...
-- Subject: Unit wazuh-dashboard.service has begun shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has begun shutting down.
Jun 24 15:34:55 centos8.localdomain systemd[1]: wazuh-dashboard.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit wazuh-dashboard.service has successfully entered the 'dead' state.
Jun 24 15:34:55 centos8.localdomain systemd[1]: Stopped wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished shutting down.
Jun 24 15:51:04 centos8.localdomain systemd[1]: Started wazuh-dashboard.
-- Subject: Unit wazuh-dashboard.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-dashboard.service has finished starting up.
-- 
-- The start-up result is done.
Jun 24 15:51:04 centos8.localdomain systemd[34626]: wazuh-dashboard.service: Failed to connect stdout to the journal socket, ignoring: Permission denied
```

In the manual installation the same error can be validated, apparently there are some problems in the package.

**Comment by c-bordon** [comment]
The issue for Wazuh dashboard package for YUM systems were reported here: https://github.com/wazuh/wazuh-dashboard/issues/222

**Comment by c-bordon** [comment]
New tests: https://github.com/wazuh/wazuh-dashboard/issues/222#issuecomment-2188845014
