### ISSUE TITLE
Spike - Research and design scaffolding of new DevOps repositories 

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-packages#3019]
| Objective |
|-----|
| https://github.com/wazuh/wazuh-packages/issues/2904 |

## Description

As part of the _Packages redesign tier 2_ objective, we need to re-structure some of our repositories, this issue aims to analyze and propose a design for the new DevOps repositories structure.

### Considerations

- Content related to OVA, AMI, and installation assistant now inside `wazuh-packages` must be moved to the new designed repository/repositories.

## Tasks

- [ ] Investigate the current repositories and their content
- [ ] Analyze what must be kept and what will be deprecated
- [ ] Propose a scaffolding design for the new repositories
