### ISSUE TITLE
Support new stage RC 1 for 4.8.1 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#3024]
## Description

This issue attempts to support a new stage RC 1 for 4.8.1 in the wazuh-packages repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.1 (if applicable).
- [x] Bump revision for branch 4.8.1 on wazuh-packages repository.
- https://github.com/wazuh/wazuh-packages/pull/3025
- [x] Create tag v4.8.1-rc1 from branch 4.8.1 on wazuh-packages repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.8.1-rc1.
