### ISSUE TITLE
Remove migrated code in the Wazuh packages redesign

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#3037]
## Description

This issue is intended to remove the migrated code from the wazuh-packages repository to the wazuh, wazuh-dashboard, wazuh-indexer, and wazuh-dashboard-plugins repositories

This PR will also remove the packages that are not going to be supported

## Related

- https://github.com/wazuh/internal-devel-requests/issues/187

# Tasks

- [x] Remove migrated code
  - [x] debs: Migrated to wazuh/wazuh
  - [x] macos: Migrated to wazuh/wazuh
  - [x] rpms: Migrated to wazuh/wazuh
  - [x] stack: Migrated to wazuh-dashboard and wazuh-indexer
  - [x] wazuhapp: Migrated to wazuh-dashboard-plugins
  - [x] windows: Migrated to wazuh/wazuh
  - [x] wpk: Migrated to wazuh/wazuh
- [x] Remove unsupported code
  - [x] alpine: https://github.com/wazuh/wazuh-packages/issues/3012#issuecomment-2186026225
  - [x] arch: No official package support - Community addition
  - [x] splunkapp: last supported version 4.5.4
- [x] Test the PR_wazuh pipeline
- [x] Review and remove wazuh-packages GHA not needed

## Working branch

- https://github.com/wazuh/wazuh-packages/tree/maintenance/3037-remove-migrated-code

**Comment by rauldpm** [comment]
## Logs

- Main package generation
  - [package_generation_2024-07-12_14-53-10-177.log](https://github.com/user-attachments/files/16194770/package_generation_2024-07-12_14-53-10-177.log)

**Comment by rauldpm** [comment]
## Update report

- Removed migrated code
- Removed unsupported code
- Removed actions
- Tested CI https://github.com/wazuh/wazuh/pull/25090/checks (https://ci.wazuh.info/job/PR_wazuh/23107/console)
  - Failed builds are expected -> no testing is launched using packages
  - Only tests that do not use packages are launched
- The bump_version.py tool does not seems to be affected

```
╰─➤  python3 bump_version.py -v 4.99.0 -r 49900 -d 09-09-1999                                                                                                                                                  
Bumping version in aix/SPECS/wazuh-agent-aix.spec
Bumping version in solaris/solaris10/pkginfo
Bumping version in tests/unattended/unit/suites/test-indexer.sh
Bumping version in tests/unattended/unit/suites/test-dashboard.sh
Bumping version in tests/unattended/unit/suites/test-manager.sh
Bumping version in tests/unattended/unit/suites/test-filebeat.sh
Bumping version in tests/unattended/unit/suites/test-checks.sh
Bumping version in tests/unattended/unit/suites/test-installCommon.sh
Bumping version in tests/unattended/unit/suites/test-common.sh
Bumping version in tests/unattended/unit/suites/test-certFunctions.sh
Bumping version in tests/unattended/unit/suites/test-passwordsFunctions.sh
Bumping version in unattended_installer/install_functions/installVariables.sh
Bumping version in CHANGELOG.md
Bumping version in VERSION
Bumping version in unattended_installer/builder.sh
╰─➤  git status
On branch maintenance/3037-remove-migrated-code
Your branch is up to date with 'origin/maintenance/3037-remove-migrated-code'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   CHANGELOG.md
	modified:   VERSION
	modified:   aix/SPECS/wazuh-agent-aix.spec
	modified:   solaris/solaris10/pkginfo
	modified:   tests/unattended/unit/suites/test-common.sh
	modified:   tests/unattended/unit/suites/test-dashboard.sh
	modified:   tests/unattended/unit/suites/test-indexer.sh
	modified:   unattended_installer/builder.sh
	modified:   unattended_installer/install_functions/installVariables.sh
```

**Comment by fcaffieri** [comment]
LGTM
