### ISSUE TITLE
Post release tasks for 4.8.1

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#3045]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.8.1.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.1-into-4.9.0`.

## Tasks

- https://github.com/wazuh/wazuh-packages/pull/3047
- https://github.com/wazuh/wazuh-packages/pull/3048
- https://github.com/wazuh/wazuh-packages/pull/3052
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.8.1 (https://github.com/wazuh/wazuh-packages/releases).
- [x] Delete all stage tags for v4.8.1. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.8.1-rc1, 4.8.1-alpha1, etc.

**Comment by vikman90** [comment]
## Conflict at passwordFunctions.sh

- https://github.com/wazuh/wazuh-packages/blob/4.9.0/unattended_installer/passwords_tool/passwordsFunctions.sh
- https://github.com/wazuh/wazuh-packages/blob/4.10.0/unattended_installer/passwords_tool/passwordsFunctions.sh

**Possible related commit:** https://github.com/wazuh/wazuh-packages/commit/c6f3ca0d9bdc1021e9ed3ee0f44df9927c28e2e5

```
<<<<<<< HEAD

=======
            eval "echo ${adminpass} | filebeat keystore add password --force --stdin ${debug}"
            conf="$(awk '{sub("password: .*", "password: ${password}")}1' /etc/filebeat/filebeat.yml)"
            echo "${conf}" > /etc/filebeat/filebeat.yml
            eval "echo admin | filebeat keystore add username --force --stdin ${debug}"
            conf="$(awk '{sub("username: .*", "username: ${username}")}1' /etc/filebeat/filebeat.yml)"
            echo "${conf}" > /etc/filebeat/filebeat.yml
            common_logger "The filebeat.yml file has been updated to use the Filebeat Keystore username and password."
>>>>>>> 4.10.0
```

**Comment by davidcr01** [comment]
The new lines must be added to the `5.0` branch. These changes come from https://github.com/wazuh/wazuh-packages/pull/2989/ (merged in `4.9.0`), then, the changes were bumped into `4.10.0`, and now it is necessary to bump it to the master branch.
