### ISSUE TITLE
Support new Wazuh version 4.8.2 in wazuh-packages repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#3075]
## Description

This issue attempts to support a new version 4.8.2 in the wazuh-packages repository.

## Tasks

- [x] Bump 4.8.2 branch to 4.8.2 version on wazuh-packages repository, including revision and changelog.
- [x] Build and push testing images for GitHub actions.
- [x] Build ECR and create ECS tasks definition if needed.

**Comment by vikman90** [comment]
This issue is **blocked** by:
- https://github.com/wazuh/internal-devel-requests/issues/1461

**Comment by vikman90** [comment]
## Update
### Build ECR and create ECS tasks definition

- [x] Create task definitions.
  Take the previous version's JSON and generate a new task definition:
  - [x] 2 Dashboard
  - [x] 2 Indexer
  - [x] Dashboard App
- [x] Create Docker images.
  - [x] Build Docker images
  - [x] Disable repository immutability at `package-generation` ECR.
  - [x] Push Docker images.
  - [x] Clean branch.
- [x] Generate Dashboard App packages: [#210533](https://ci.wazuh.info/job/Packages_builder/210533).
- [x] Run Packages Tier for _Manager_, _Agent_, _Indexer_ and _Dashboard_ on amd64. [#3524](https://ci.wazuh.info/job/Packages_builder_tier/3524)
- [x] Relaunch PR checks.

**Comment by vikman90** [comment]
Reopened by @jnasselle: https://github.com/wazuh/wazuh/issues/25237#issuecomment-2296315756
