### ISSUE TITLE
Post release tasks for 4.8.2

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-packages#3080]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.8.2.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.2-into-4.9.0`.

## Tasks

- https://github.com/wazuh/wazuh-packages/pull/3083
- https://github.com/wazuh/wazuh-packages/pull/3084
- https://github.com/wazuh/wazuh-packages/pull/3085
- https://github.com/wazuh/wazuh-packages/pull/3086
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.8.2 (https://github.com/wazuh/wazuh-packages/releases).
- [x] Delete all stage tags for v4.8.2. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.8.2-rc1, 4.8.2-alpha1, etc.
