### ISSUE TITLE
Test the Installation assistant deployment. Verify it installs the 4.9.0-2 package.

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#3105]
related: https://github.com/wazuh/wazuh-automation/issues/1830

## Description

Due to a bug found after the 4.9.0, a new revision (2) for the wazuh-dashboard will be released. We will need to perform some tests with Wazuh installation assistant to ensure that the correct package of Wazuh dashboard is installed.

## Test

- [x] Test AIO installation in DEB distribution  https://github.com/wazuh/wazuh-packages/issues/3105#issuecomment-2334532556
- [x] Test AIO installation in RPM distribution https://github.com/wazuh/wazuh-packages/issues/3105#issuecomment-2334562649
- [x] Update offline installation https://github.com/wazuh/wazuh-packages/issues/3105#issuecomment-2334662260

**Comment by c-bordon** [comment]
## Ubuntu 22.04 test 🟢 

```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios$ ssh -i /tmp/wazuh-qa/deb-test-5208/instance_key -o StrictHostKeyChecking=no vagrant@192.168.57.183
Warning: Permanently added '192.168.57.183' (ED25519) to the list of known hosts.
Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-92-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

  System information as of Fri Sep  6 17:27:40 UTC 2024

  System load:  0.19970703125     Processes:               122
  Usage of /:   3.7% of 38.70GB   Users logged in:         0
  Memory usage: 2%                IPv4 address for enp0s3: 10.0.2.15
  Swap usage:   0%                IPv4 address for enp0s8: 192.168.57.183


Expanded Security Maintenance for Applications is not enabled.

0 updates can be applied immediately.

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status


The list of available updates is more than a week old.
To check for new updates run: sudo apt update

vagrant@ubuntu-jammy:~$ curl -O https://packages-dev.wazuh.com/4.9/wazuh-install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  185k  100  185k    0     0   111k      0  0:00:01  0:00:01 --:--:--  111k
vagrant@ubuntu-jammy:~$ sudo bash wazuh-install.sh -a
06/09/2024 17:28:37 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
06/09/2024 17:28:37 INFO: Verbose logging redirected to /var/log/wazuh-install.log
06/09/2024 17:28:54 INFO: Verifying that your system meets the recommended minimum hardware requirements.
06/09/2024 17:28:54 INFO: Wazuh web interface port will be 443.
06/09/2024 17:28:59 INFO: --- Dependencies ----
06/09/2024 17:28:59 INFO: Installing apt-transport-https.
06/09/2024 17:29:03 INFO: Installing debhelper.
06/09/2024 17:29:30 INFO: Wazuh development repository added.
06/09/2024 17:29:30 INFO: --- Configuration files ---
06/09/2024 17:29:30 INFO: Generating configuration files.
06/09/2024 17:29:30 INFO: Generating the root certificate.
06/09/2024 17:29:30 INFO: Generating Admin certificates.
06/09/2024 17:29:31 INFO: Generating Wazuh indexer certificates.
06/09/2024 17:29:31 INFO: Generating Filebeat certificates.
06/09/2024 17:29:31 INFO: Generating Wazuh dashboard certificates.
06/09/2024 17:29:31 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
06/09/2024 17:29:31 INFO: --- Wazuh indexer ---
06/09/2024 17:29:31 INFO: Starting Wazuh indexer installation.
06/09/2024 17:31:26 INFO: Wazuh indexer installation finished.
06/09/2024 17:31:26 INFO: Wazuh indexer post-install configuration finished.
06/09/2024 17:31:26 INFO: Starting service wazuh-indexer.
06/09/2024 17:31:37 INFO: wazuh-indexer service started.
06/09/2024 17:31:37 INFO: Initializing Wazuh indexer cluster security settings.
06/09/2024 17:31:40 INFO: Wazuh indexer cluster security configuration initialized.
06/09/2024 17:31:40 INFO: Wazuh indexer cluster initialized.
06/09/2024 17:31:40 INFO: --- Wazuh server ---
06/09/2024 17:31:40 INFO: Starting the Wazuh manager installation.
06/09/2024 17:33:06 INFO: Wazuh manager installation finished.
06/09/2024 17:33:06 INFO: Wazuh manager vulnerability detection configuration finished.
06/09/2024 17:33:06 INFO: Starting service wazuh-manager.
06/09/2024 17:33:21 INFO: wazuh-manager service started.
06/09/2024 17:33:21 INFO: Starting Filebeat installation.
06/09/2024 17:33:48 INFO: Filebeat installation finished.
06/09/2024 17:33:54 INFO: Filebeat post-install configuration finished.
06/09/2024 17:33:54 INFO: Starting service filebeat.
06/09/2024 17:33:55 INFO: filebeat service started.
06/09/2024 17:33:55 INFO: --- Wazuh dashboard ---
06/09/2024 17:33:55 INFO: Starting Wazuh dashboard installation.
06/09/2024 17:35:18 INFO: Wazuh dashboard installation finished.
06/09/2024 17:35:18 INFO: Wazuh dashboard post-install configuration finished.
06/09/2024 17:35:18 INFO: Starting service wazuh-dashboard.
06/09/2024 17:35:19 INFO: wazuh-dashboard service started.
06/09/2024 17:35:20 INFO: Updating the internal users.
06/09/2024 17:35:23 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
06/09/2024 17:35:30 INFO: The filebeat.yml file has been updated to use the Filebeat Keystore username and password.
06/09/2024 17:36:03 INFO: Initializing Wazuh dashboard web application.
06/09/2024 17:36:04 INFO: Wazuh dashboard web application initialized.
06/09/2024 17:36:04 INFO: --- Summary ---
06/09/2024 17:36:04 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: H5+UC7Qyg*NXsp8HuPs+MF?VYFbcEa2.
06/09/2024 17:36:04 INFO: Installation finished.
vagrant@ubuntu-jammy:~$ apt --installed list | grep wazuh-dashboard

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

wazuh-dashboard/now 4.9.0-2 amd64 [installed,local]
vagrant@ubuntu-jammy:~$ apt --installed list | grep wazuh-indexer

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

wazuh-indexer/now 4.9.0-1 amd64 [installed,local]
vagrant@ubuntu-jammy:~$ apt --installed list | grep wazuh-manager

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

wazuh-manager/now 4.9.0-1 amd64 [installed,local]

```

### opensearch_dashboards.yml

```console
vagrant@ubuntu-jammy:~$ sudo su -
root@ubuntu-jammy:~# cat /etc/wazuh-dashboard/opensearch_dashboards.yml 
server.host: 0.0.0.0
opensearch.hosts: https://127.0.0.1:9200
server.port: 443
opensearch.ssl.verificationMode: certificate
# opensearch.username: kibanaserver
# opensearch.password: kibanaserver
opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/etc/wazuh-dashboard/certs/wazuh-dashboard-key.pem"
server.ssl.certificate: "/etc/wazuh-dashboard/certs/wazuh-dashboard.pem"
opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/wz-home
opensearch_security.cookie.secure: true
```

![image](https://github.com/user-attachments/assets/dae62dd3-d1e3-480a-8ca0-fbfc68334db4)

**Comment by c-bordon** [comment]
## Test in Amazon Linux 2

```console
cbordon@cbordon-MS-7C88:~$ ssh -i /tmp/wazuh-qa/rpm-test-4070/instance_key -o StrictHostKeyChecking=no vagrant@192.168.57.31
Warning: Permanently added '192.168.57.31' (ED25519) to the list of known hosts.

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
101 package(s) needed for security, out of 134 available
Run "sudo yum update" to apply all updates.

This system is built by the Bento project by Chef Software
More information can be found at https://github.com/chef/bento
[vagrant@vagrant ~]$ curl -O https://packages-dev.wazuh.com/4.9/wazuh-install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  185k  100  185k    0     0   188k      0 --:--:-- --:--:-- --:--:--  187k
[vagrant@vagrant ~]$ sudo bash wazuh-install.sh -a
06/09/2024 17:47:10 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
06/09/2024 17:47:10 INFO: Verbose logging redirected to /var/log/wazuh-install.log
06/09/2024 17:47:10 INFO: Verifying that your system meets the recommended minimum hardware requirements.
06/09/2024 17:47:10 INFO: Wazuh web interface port will be 443.
06/09/2024 17:47:11 INFO: Wazuh development repository added.
06/09/2024 17:47:11 INFO: --- Configuration files ---
06/09/2024 17:47:11 INFO: Generating configuration files.
06/09/2024 17:47:12 INFO: Generating the root certificate.
06/09/2024 17:47:12 INFO: Generating Admin certificates.
06/09/2024 17:47:12 INFO: Generating Wazuh indexer certificates.
06/09/2024 17:47:12 INFO: Generating Filebeat certificates.
06/09/2024 17:47:12 INFO: Generating Wazuh dashboard certificates.
06/09/2024 17:47:12 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
06/09/2024 17:47:12 INFO: --- Wazuh indexer ---
06/09/2024 17:47:12 INFO: Starting Wazuh indexer installation.
06/09/2024 17:49:15 INFO: Wazuh indexer installation finished.
06/09/2024 17:49:15 INFO: Wazuh indexer post-install configuration finished.
06/09/2024 17:49:15 INFO: Starting service wazuh-indexer.
06/09/2024 17:49:56 INFO: wazuh-indexer service started.
06/09/2024 17:49:56 INFO: Initializing Wazuh indexer cluster security settings.
06/09/2024 17:50:09 INFO: Wazuh indexer cluster security configuration initialized.
06/09/2024 17:50:09 INFO: Wazuh indexer cluster initialized.
06/09/2024 17:50:09 INFO: --- Wazuh server ---
06/09/2024 17:50:09 INFO: Starting the Wazuh manager installation.
06/09/2024 17:51:14 INFO: Wazuh manager installation finished.
06/09/2024 17:51:14 INFO: Wazuh manager vulnerability detection configuration finished.
06/09/2024 17:51:14 INFO: Starting service wazuh-manager.
06/09/2024 17:51:24 INFO: wazuh-manager service started.
06/09/2024 17:51:24 INFO: Starting Filebeat installation.
06/09/2024 17:51:24 INFO: Another process is using YUM. Waiting for it to release the lock. Next retry in 30 seconds (1/10)
06/09/2024 17:52:12 INFO: Filebeat installation finished.
06/09/2024 17:52:14 INFO: Filebeat post-install configuration finished.
06/09/2024 17:52:14 INFO: Starting service filebeat.
06/09/2024 17:52:14 INFO: filebeat service started.
06/09/2024 17:52:14 INFO: --- Wazuh dashboard ---
06/09/2024 17:52:14 INFO: Starting Wazuh dashboard installation.
06/09/2024 17:52:14 INFO: Another process is using YUM. Waiting for it to release the lock. Next retry in 30 seconds (1/10)
06/09/2024 17:54:00 INFO: Wazuh dashboard installation finished.
06/09/2024 17:54:00 INFO: Wazuh dashboard post-install configuration finished.
06/09/2024 17:54:00 INFO: Starting service wazuh-dashboard.
06/09/2024 17:54:00 INFO: wazuh-dashboard service started.
06/09/2024 17:54:00 INFO: Updating the internal users.
06/09/2024 17:54:12 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
06/09/2024 17:54:28 INFO: The filebeat.yml file has been updated to use the Filebeat Keystore username and password.
06/09/2024 17:55:09 INFO: Initializing Wazuh dashboard web application.
06/09/2024 17:55:09 INFO: Wazuh dashboard web application initialized.
06/09/2024 17:55:09 INFO: --- Summary ---
06/09/2024 17:55:09 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: TNfAGG5wv83189eyoK7jM+nngSj+Qqd5
06/09/2024 17:55:09 INFO: Installation finished.
[vagrant@vagrant ~]$ sudo yum list installed | grep wazuh-dashboard
wazuh-dashboard.x86_64               4.9.0-2                           @wazuh   
[vagrant@vagrant ~]$ sudo yum list installed | grep wazuh-indexer
wazuh-indexer.x86_64                 4.9.0-1                           @wazuh   
[vagrant@vagrant ~]$ sudo yum list installed | grep wazuh-manager
wazuh-manager.x86_64                 4.9.0-1                           @wazuh
```

### opensearch_dashboards.yml

```console
[vagrant@vagrant ~]$ sudo cat /etc/wazuh-dashboard/opensearch_dashboards.yml
server.host: 0.0.0.0
opensearch.hosts: https://127.0.0.1:9200
server.port: 443
opensearch.ssl.verificationMode: certificate
# opensearch.username: kibanaserver
# opensearch.password: kibanaserver
opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/etc/wazuh-dashboard/certs/wazuh-dashboard-key.pem"
server.ssl.certificate: "/etc/wazuh-dashboard/certs/wazuh-dashboard.pem"
opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/wz-home
opensearch_security.cookie.secure: true
```

![image](https://github.com/user-attachments/assets/b14debea-d02d-4e58-8b37-1777b6be49d0)

**Comment by c-bordon** [comment]
## Offline download

### DEB

```console
cbordon@cbordon-MS-7C88:~$ curl -O https://packages-dev.wazuh.com/4.9/wazuh-install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  185k  100  185k    0     0   179k      0  0:00:01  0:00:01 --:--:--  179k
cbordon@cbordon-MS-7C88:~$ sudo bash wazuh-install.sh -dw deb
[sudo] password for cbordon: 
06/09/2024 16:01:23 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
06/09/2024 16:01:23 INFO: Verbose logging redirected to /var/log/wazuh-install.log
06/09/2024 16:01:31 INFO: Verifying that your system meets the recommended minimum hardware requirements.
06/09/2024 16:01:31 INFO: --- Download Packages ---
06/09/2024 16:01:31 INFO: Starting Wazuh packages download.
06/09/2024 16:01:31 INFO: Downloading Wazuh deb packages for x86_64.
06/09/2024 16:02:16 INFO: The manager package was downloaded.
06/09/2024 16:02:19 INFO: The filebeat package was downloaded.
06/09/2024 16:03:56 INFO: The indexer package was downloaded.
06/09/2024 16:04:16 INFO: The dashboard package was downloaded.
06/09/2024 16:04:16 INFO: The packages are in wazuh-offline/wazuh-packages
06/09/2024 16:04:16 INFO: Downloading configuration files and assets.
06/09/2024 16:04:17 INFO: The resource https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH was downloaded.
06/09/2024 16:04:18 INFO: The resource https://packages-dev.wazuh.com/4.9/tpl/wazuh/filebeat/filebeat.yml was downloaded.
06/09/2024 16:04:18 INFO: The resource https://raw.githubusercontent.com/wazuh/wazuh/4.9.0/extensions/elasticsearch/7.x/wazuh-template.json was downloaded.
06/09/2024 16:04:19 INFO: The resource https://packages-dev.wazuh.com/pre-release/filebeat/wazuh-filebeat-0.4.tar.gz was downloaded.
06/09/2024 16:04:19 INFO: The configuration files and assets are in wazuh-offline.tar.gz
06/09/2024 16:04:54 INFO: You can follow the installation guide here https://documentation.wazuh.com/current/deployment-options/offline-installation.html
cbordon@cbordon-MS-7C88:~$ sudo tar xvf wazuh-offline.tar.gz 
wazuh-offline/
wazuh-offline/wazuh-packages/
wazuh-offline/wazuh-packages/wazuh-dashboard_4.9.0-2_amd64.deb
wazuh-offline/wazuh-packages/wazuh-indexer_4.9.0-1_amd64.deb
wazuh-offline/wazuh-packages/filebeat-oss-7.10.2-amd64.deb
wazuh-offline/wazuh-packages/wazuh-manager_4.9.0-1_amd64.deb
wazuh-offline/wazuh-files/
wazuh-offline/wazuh-files/filebeat.yml
wazuh-offline/wazuh-files/wazuh-template.json
wazuh-offline/wazuh-files/GPG-KEY-WAZUH
wazuh-offline/wazuh-files/wazuh-filebeat-0.4.tar.gz
```

### RPM

```console
cbordon@cbordon-MS-7C88:~$ sudo bash wazuh-install.sh -dw rpm
06/09/2024 16:05:37 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
06/09/2024 16:05:37 INFO: Verbose logging redirected to /var/log/wazuh-install.log
06/09/2024 16:05:42 INFO: Verifying that your system meets the recommended minimum hardware requirements.
06/09/2024 16:05:42 INFO: --- Download Packages ---
06/09/2024 16:05:42 INFO: Starting Wazuh packages download.
06/09/2024 16:05:42 INFO: Downloading Wazuh rpm packages for x86_64.
06/09/2024 16:06:27 INFO: The manager package was downloaded.
06/09/2024 16:06:31 INFO: The filebeat package was downloaded.
06/09/2024 16:08:10 INFO: The indexer package was downloaded.
06/09/2024 16:08:41 INFO: The dashboard package was downloaded.
06/09/2024 16:08:41 INFO: The packages are in wazuh-offline/wazuh-packages
06/09/2024 16:08:41 INFO: Downloading configuration files and assets.
06/09/2024 16:08:42 INFO: The resource https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH was downloaded.
06/09/2024 16:08:43 INFO: The resource https://packages-dev.wazuh.com/4.9/tpl/wazuh/filebeat/filebeat.yml was downloaded.
06/09/2024 16:08:43 INFO: The resource https://raw.githubusercontent.com/wazuh/wazuh/4.9.0/extensions/elasticsearch/7.x/wazuh-template.json was downloaded.
06/09/2024 16:08:44 INFO: The resource https://packages-dev.wazuh.com/pre-release/filebeat/wazuh-filebeat-0.4.tar.gz was downloaded.
06/09/2024 16:08:44 INFO: The configuration files and assets are in wazuh-offline.tar.gz
06/09/2024 16:09:21 INFO: You can follow the installation guide here https://documentation.wazuh.com/current/deployment-options/offline-installation.html
cbordon@cbordon-MS-7C88:~$ sudo tar xvf wazuh-offline.tar.gz
wazuh-offline/
wazuh-offline/wazuh-packages/
wazuh-offline/wazuh-packages/wazuh-dashboard-4.9.0-2.x86_64.rpm
wazuh-offline/wazuh-packages/wazuh-manager-4.9.0-1.x86_64.rpm
wazuh-offline/wazuh-packages/filebeat-oss-7.10.2-x86_64.rpm
wazuh-offline/wazuh-packages/wazuh-indexer-4.9.0-1.x86_64.rpm
wazuh-offline/wazuh-files/
wazuh-offline/wazuh-files/filebeat.yml
wazuh-offline/wazuh-files/wazuh-template.json
wazuh-offline/wazuh-files/GPG-KEY-WAZUH
wazuh-offline/wazuh-files/wazuh-filebeat-0.4.tar.gz
```
