### ISSUE TITLE
Support new stage RC 1 for 4.9.1 in wazuh-packages repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#3123]
## Description
Bump revision for branch 4.9.1 on wazuh-packages repository with `-s` rc1
This issue attempts to support a new stage RC 1 for 4.9.1 in the wazuh-packages repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.1 (if applicable).
- https://github.com/wazuh/wazuh-packages/pull/3124
- [x] Add release ETA
- [x] Create tag v4.9.1-rc1 from branch 4.9.1 on wazuh-packages repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.9.1-rc1.
- https://github.com/wazuh/wazuh-packages/pull/3125
