### ISSUE TITLE
Support new stage Alpha 1 for 4.10.0 in wazuh-packages repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#3126]
## Description
Bump revision for branch 4.10.0 on wazuh-packages repository with `-s` alpha1
This issue attempts to support a new stage Alpha 1 for 4.10.0 in the wazuh-packages repository.

## Tasks

- [x] Ensure changelog is updated for 4.10.0 (if applicable).
- [x] Bump revision for branch 4.10.0 on wazuh-packages repository.
- https://github.com/wazuh/wazuh-packages/pull/3129
- [x] Create tag v4.10.0-alpha1 from branch 4.10.0 on wazuh-packages repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.10.0-alpha1.
- [x] ~Restore `source_branch` for installation assitant executing `bump_version.py` without `-s`option.~
