### ISSUE TITLE
Support new Wazuh version 4.10.1 in wazuh-packages repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#3130]
## Description

This issue attempts to support a new version 4.10.1 in the wazuh-packages repository.

## Tasks

- [x] https://github.com/wazuh/wazuh-packages/pull/3131
- [x] ~Build and push testing images for GitHub actions.~
  - After the migration of packages to wazuh/wazuh in `4.9.0`, this repository is deprecated, so this step is not necessary.
- [x] ~Build ECR and create ECS tasks definition if needed.~
  - After the migration of packages in `4.9.0` to the Dashboard and Indexer repositories themselves, this repository is deprecated, so this step is not necessary.

**Comment by vikman90** [comment]
## Work Update

- PR to bump version:
  - https://github.com/wazuh/wazuh-packages/pull/3131
