### ISSUE TITLE
Support new stage RC 2 for 4.9.1 in wazuh-packages repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#3132]
## Description
Bump revision for branch 4.9.1 on wazuh-packages repository with `-s` rc2
This issue attempts to support a new stage RC 2 for 4.9.1 in the wazuh-packages repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.1 (if applicable).
- [x] Bump revision for branch 4.9.1 on wazuh-packages repository.
- https://github.com/wazuh/wazuh-packages/pull/3133
- [x] Create tag v4.9.1-rc2 from branch 4.9.1 on wazuh-packages repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.9.1-rc2.
- https://github.com/wazuh/wazuh-packages/pull/3134

**Comment by vikman90** [comment]
## Issue blocked

We need a new release ETA.
