### ISSUE TITLE
Support new Wazuh version 4.10.2 in wazuh-packages repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#3137]
## Description

This issue attempts to support a new version 4.10.2 in the wazuh-packages repository.

## Tasks

- [x] https://github.com/wazuh/wazuh-packages/issues/3137
- [x] ~Build and push testing images for GitHub actions.~
- [x] ~Build ECR and create ECS tasks definition if needed.~
