### ISSUE TITLE
Support new stage RC 3 for 4.9.1 in wazuh-packages repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#3139]
## Description
Bump revision for branch 4.9.1 on wazuh-packages repository with `-s` rc3
This issue attempts to support a new stage RC 3 for 4.9.1 in the wazuh-packages repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.1 (if applicable).
- [x] Bump revision for branch 4.9.1 on wazuh-packages repository.
- [x] Add release ETA
  - https://github.com/wazuh/wazuh-packages/pull/3140
- [x] Create tag v4.9.1-rc3 from branch 4.9.1 on wazuh-packages repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.9.1-rc3.
- [x] Restore `source_branch` for installation assitant executing `bump_version.py` without `-s`option.
  - https://github.com/wazuh/wazuh-packages/pull/3141
