### ISSUE TITLE
Support new stage Alpha 2 for 4.10.0 in wazuh-packages repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#3146]
## Description
Bump revision for branch 4.10.0 on wazuh-packages repository with `-s` alpha2
This issue attempts to support a new stage Alpha 2 for 4.10.0 in the wazuh-packages repository.

## Tasks

- [x] Ensure changelog is updated for 4.10.0 (if applicable).
- [x] Bump revision for branch 4.10.0 on wazuh-packages repository.
- [x] Add release ETA
- [x] Create tag v4.10.0-alpha2 from branch 4.10.0 on wazuh-packages repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.10.0-alpha2.
- [x] ~Restore `source_branch` for installation assitant executing `bump_version.py` without `-s`option.~

**Comment by cborla** [comment]
LGTM!
