### ISSUE TITLE
Support new stage RC 4 for 4.9.1 in wazuh-packages repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#3147]
## Description
Bump revision for branch 4.9.1 on wazuh-packages repository with `-s` rc4
This issue attempts to support a new stage RC 4 for 4.9.1 in the wazuh-packages repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.1 (if applicable).
- [x] Bump revision for branch 4.9.1 on wazuh-packages repository.
  - https://github.com/wazuh/wazuh-packages/pull/3148
- [x] Add release ETA
- [x] Create tag v4.9.1-rc4 from branch 4.9.1 on wazuh-packages repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.9.1-rc4.
- [x] Restore `source_branch` for installation assitant executing `bump_version.py` without `-s`option.
  - https://github.com/wazuh/wazuh-packages/pull/3149

**Comment by MarcelKemp** [comment]
LGTM.
