### ISSUE TITLE
Support new Wazuh version 4.9.2 in wazuh-packages repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-packages#3157]
## Description

This issue attempts to support a new version 4.9.2 in the wazuh-packages repository.

## Tasks

- [ ] Bump 4.9.2 branch to 4.9.2 version on wazuh-packages repository, including revision and changelog.
- [ ] Build and push testing images for GitHub actions.
- [ ] Build ECR and create ECS tasks definition if needed.
