### ISSUE TITLE
Support new stage RC 1 for 4.9.2 in wazuh-packages repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-packages#3160]
## Description
Bump revision for branch 4.9.2 on wazuh-packages repository with `-s` rc1
This issue attempts to support a new stage RC 1 for 4.9.2 in the wazuh-packages repository.

## Tasks

- [ ] ~Delete previous Alpha 2 release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.10.0-alpha2.~
- [ ] ~Delete previous v4.10.0-alpha2 tag.~
- [x] Ensure changelog is updated for 4.9.2 (if applicable).
- [x] Bump revision for branch 4.9.2 on wazuh-packages repository.
  - https://github.com/wazuh/wazuh-packages/pull/3161 
- [x] Add release ETA
- [x] Create tag v4.9.2-rc1 from branch 4.9.2 on wazuh-packages repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.9.2-rc1.
- [x] Restore `source_branch` for installation assitant executing `bump_version.py` without `-s`option.
