### ISSUE TITLE
Support new stage Alpha 3 for 4.10.0 in wazuh-packages repository 

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#3169]
## Description
Bump revision for branch 4.10.0 on wazuh-packages repository with `-s` alpha3
This issue attempts to support a new stage Alpha 3 for 4.10.0 in the wash-packages repository.

## Tasks

- [ ] ~Ensure changelog is updated for 4.10.0 (if applicable).~
- [ ] ~Bump revision for branch 4.10.0 on wazuh-packages repository.~
- [ ] ~Add release ETA~
- [x] Create tag v4.10.0-alpha3 from branch 4.10.0 on wazuh-packages repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-packages/releases/tag/v4.10.0-alpha3.
- [ ] ~Restore `source_branch` for installation assistant executing `bump_version.py` without `-s`option.~
