### ISSUE TITLE
Transfer Wazuh specs to the main repository

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-packages#492]
## Description
This issue aims to move any spec file used to build a binary package to the main repository [wazuh/wazuh](https://github.com/wazuh/wazuh). 

## Goals
- Simplify the build and release process.
- Simplify the process to introduce changes in the binary packages.
- Move to a _trunk based development_ workflow.

## Tasks
- [ ] Move the specs to wazuh/wazuh. 
    - [ ] Allocate the specs in `wazuh/packages/{rpm,deb,etc}/{manager/api}`.
    - [ ] Move the last version and remove any reference to the version in the spec file name.
    - [ ] Remove the specs files from `wazuh-packages` repository, leaving only the build tools in it.
    - [ ] Plan how to deprecate the current build system to allow building custom legacy packages (v3.13.0 for example).
    - [ ] Transfer the issues refering to the specs files to wazuh/wazuh.
- [ ] Modify Docker's _entrypoint_ to use the specs from wazuh/wazuh if the version is equal or greater to 4.1.0.
- [ ] Disable `--dev` parameter if the version is equal or greater to 4.1.0.
- [ ] Move `wazuh-installer.wxs` to `wazuh/packages/windows/`.
- [ ] Update README.md files in wazuh-packages.
- [ ] Update README.md files in wazuh.
- [ ] Update wazuh-documentation pages related to how to build binary packages.
