### ISSUE TITLE
Change core paths according to the new Wazuh naming standard in wazuh-packages

### ISSUE THREAD

**Issue by danimegar** [wazuh/wazuh-packages#570]
## Description

Hello team,

According to the described in wazuh/wazuh#6885, the directories containing the word `ossec` inside installations are being removed.

It should be applied to:

- Linux (manager)
- Linux/Unix (agent)

In Linux installations we have found two directories that apply to this requirement:

- logs/ossec/: folder where rotated logs are stored. It will be renamed by **logs/wazuh/** (don't confuse it with the log files such as ossec.log, we are talking about the folder for the rotated logs).

- queue/ossec/: where Unix sockets are located. It will be renamed by **queue/sockets/**

Other requirements:
- No residual folders after the upgrade
- The content of the `logs/ossec` (rotated logs) should be persistent during upgrades inside the new folder `/logs/wazuh`

It is necessary to modify SPEC files (RPM) and others to adapt this repository to the core changes, which are attempted to be released in 4.2.0.

**Comment by DFolchA** [comment]
Hello team,

I have been investigating hos to solve this issue in Solaris 11, the major problem we have in this system is the lack of a post install script, to bypass this the package needs to create a service that will activate after the package is installed which will act as post install.

In this branch there is a small proof of concept: 
https://github.com/wazuh/wazuh-packages/tree/change-solaris11-log-dir-postinstall

![image](https://user-images.githubusercontent.com/19505384/105062889-652f2d80-5a7b-11eb-85ed-499077b7b556.png)

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
### STATUS REPORT

**Working branch:** [570-change-new-paths](https://github.com/wazuh/wazuh-packages/tree/570-change-new-paths)

**Tasks**
- [ ] Modify building tools:
  - [ ] AIX
  - [ ] RPM
  - [ ] DEB
  - [ ] MacOS
  - [ ] Windows
  - [ ] Solaris11 
 
- [ ] Test Packages:
  - [ ] AIX
  - [ ] RPM
  - [ ] DEB
  - [ ] MacOS
  - [ ] Windows
  - [ ] Solaris11

**Comment by DFolchA** [comment]
### STATUS REPORT

**Working branch:** [570-change-new-paths](https://github.com/wazuh/wazuh-packages/tree/570-change-new-paths)

**Tasks**
- [ ] Modify building tools:
  - [x] AIX
  - [x] RPM
  - [x] DEB
  - [x] MacOS
  - [ ] Windows
  - [ ] Solaris11 
 
- [ ] Test Packages:
  - [x] AIX
  - [x] RPM
  - [x] DEB
  - [ ] MacOS
  - [ ] Windows
  - [ ] Solaris11 
  
**Resume**
- Work in Windows changes
- Test AIX DEB and RPM

**Comment by DFolchA** [comment]
### STATUS REPORT

**Working branch:** [570-change-new-paths](https://github.com/wazuh/wazuh-packages/tree/570-change-new-paths)

**Tasks**
- [ ] Modify building tools:
  - [x] AIX
  - [x] RPM
  - [x] DEB
  - [x] MacOS
  - [X] Windows
  - [ ] Solaris11 (in progress)
 
- [ ] Test Packages:
  - [x] AIX
  - [x] RPM 
  - [x] DEB 
  - [ ] MacOS (in progress)
  - [ ] Windows (in progress)
  - [ ] Solaris11 

**Resume**
- Fix Warnings in DEB and RPM
- Finish Windows and start testing
- macOS package testing
- Start Solaris 11 package with changes from PoC (https://github.com/wazuh/wazuh-packages/issues/570#issuecomment-762957411)

**Comment by DFolchA** [comment]
### STATUS REPORT

**Working branch:** [570-change-new-paths](https://github.com/wazuh/wazuh-packages/tree/570-change-new-paths)

**Tasks**
- [ ] Modify building tools:
  - [x] AIX
  - [x] RPM
  - [x] DEB
  - [x] MacOS
  - [X] Windows
  - [ ] Solaris11 (in progress)
 
- [ ] Test Packages:
  - [x] AIX
  - [x] RPM 
  - [x] DEB 
  - [ ] MacOS (in progress)
  - [ ] Windows (in progress)
  - [ ] Solaris11 

**Resume**
- Test macOS
- Test Windows
- Work in Solaris 11

**Comment by DFolchA** [comment]
### STATUS REPORT

### DEB packages
**Install**
![image](https://user-images.githubusercontent.com/19505384/107373248-9c2ab900-6ae6-11eb-86b3-b30e12cb10a8.png)
**Upgrade**
![image](https://user-images.githubusercontent.com/19505384/107373670-13f8e380-6ae7-11eb-80fe-e3ba8b8d8fe1.png)

**Comment by DFolchA** [comment]
### STATUS REPORT

### RPM packages
**Install**
![image](https://user-images.githubusercontent.com/19505384/107380229-faa76580-6aed-11eb-9456-dd4a44bef0dd.png)

**Upgrade**
![image](https://user-images.githubusercontent.com/19505384/107394826-8de79780-6afc-11eb-8329-91304dca4c0e.png)

**Comment by DFolchA** [comment]
### STATUS REPORT

### macOS packages
**Install**
![image](https://user-images.githubusercontent.com/19505384/107499917-d3a46e80-6b95-11eb-84e0-24c6252d4997.png)
**Upgrade**
![image](https://user-images.githubusercontent.com/19505384/107499669-888a5b80-6b95-11eb-9be0-f57f4fab8e2c.png)

**Comment by DFolchA** [comment]
### STATUS REPORT

**Working branch:** [570-change-new-paths](https://github.com/wazuh/wazuh-packages/tree/570-change-new-paths)

**Tasks**
- [ ] Modify building tools:
  - [x] AIX
  - [x] RPM
  - [x] DEB
  - [x] MacOS
  - [x] Solaris11 
 
- [ ] Test Packages:
  - [x] AIX
  - [x] RPM 
  - [x] DEB 
  - [x] MacOS
  - [ ] Solaris11 (in progress)

**Resume**
- Finish testing RPM, MacOS and DEB
- Create Solaris11 package and test various use cases

**Comment by DFolchA** [comment]
### STATUS REPORT

### Solaris 11 Packages
**Upgrade**
![image](https://user-images.githubusercontent.com/19505384/107673969-c327ed00-6c96-11eb-851c-73ba370faea2.png)

**Comment by alberpilot** [comment]
Please update
