### ISSUE TITLE
Wazuh packages repository branching model adaptation

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#764]
## Goal

The `wazuh/wazuh-packages` repository needs to stop including all versions SPECs. The new branching model needs to split into branches accordingly to the `wazuh` repository. This new format allows us to work in a building script without taking into account all the possible builds. 

# Use cases
- To build 3.x package, it must checkout to `legacy` branch and run the desired script. 
- To build 4.0.x package, it must checkout to `4.0` branch. 
- To build 4.1. packages, it must checkout to `4.1`branch.
  - If the 4.1 package version is lower than 4.1.4 and use docker, it must checkout to the corresponding tag.
- To build 4.2 packages, it must checkout to `4.2` branch. 
- To build 4.3 packages, currently, it must checkout to `master` branch. 
- To build 5.0 packages, it must checkout to `5.0-dev` branch. 

# Tasks
### Iteration `#1`: SPECs cleaning (#765)
- [x] Remove from `4.0` branch all SPECS non 4.0.x. 
- [x] Remove from `4.1` branch all SPECS non 4.1.x.
- [x] Remove from `4.2` branch all SPECS non 4.2.0. (Review if completed)
- [x] Remove from `master` branch all SPECS non 4.3.x.
- [x] Remove from `5.0-dev` branch all SPECS non 5.0.x. 
- [x] All branches README must be updated with the new package building model. 
- [x] Pull request to wazuh-documentation.

### Iteration `#2`: Adapting scripts (#790)
- [ ] New file VERSION must be added to the root folder. It must contain the latest branch tag. 
- [ ] Remove unnecessary folders hierarchy. 
- [ ] Remove SPEC versioning. 
- [ ] Modify building scripts to access directly to their specs and accept the new hierarchy. 
- [ ] Pull request to wazuh-documentation.
- [ ] Wazuh Jenkins Bumps / check the Jenkins packages builder
- [ ] Review docker building images.

**Comment by alberpilot** [comment]
Done
