### ISSUE TITLE
Wazuh packages repository branching model adaptation: Iteration 1

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#765]
Epic: #764 

## Tasks:

- [x] Remove from `4.0` branch all SPECS non 4.0.x. 
- [x] Remove from `4.1` branch all SPECS non 4.1.x.
- [x] Remove from `4.2` branch all SPECS non 4.2.0. (Review if completed)
- [x] Remove from `master` branch all SPECS non 4.3.x.
- [x] Remove from `5.0-dev` branch all SPECS non 5.0.x. 
- [x] All branches README must be updated with the new package building model. 
- [x] Pull request to wazuh-documentation.

**Comment by rauldpm** [comment]
Thursday 2021-05-13

- Branch created [4.0-spec_clean](https://github.com/wazuh/wazuh-packages/tree/4.0-spec_clean)
- Deleted SPECS non 4.0.x files in 4.0-spec_clean branch
- Investigated AIX package generation due to errors due to errors generating the package and checking that it works with the remaining specs

**Comment by rauldpm** [comment]
Tuesday 2021-05-18

- Cleaned non 4.0 specs and created PR https://github.com/wazuh/wazuh-packages/pull/768
- Cleaned non 4.1.0 to 4.1.3 specs and created PR https://github.com/wazuh/wazuh-packages/pull/769
- Cleaned non 4.1.4, 4.1.5 specs and created PR https://github.com/wazuh/wazuh-packages/pull/770
- Cleaned non 4.3 specs and created PR https://github.com/wazuh/wazuh-packages/pull/771
- Cleaned non 5.0 specs and create PR https://github.com/wazuh/wazuh-packages/pull/772

**Comment by rauldpm** [comment]
Wednesday 2021-05-19

- Created branch 4.1_specs-clean and created PR to 4.1
- Change all readmes with branch section
