### ISSUE TITLE
Wazuh packages repository branching model adaptation: Iteration 2

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#790]
Epic: #764 

Working branches:

- [legacy-790-branch_model_adaptation](https://github.com/wazuh/wazuh-packages/tree/legacy-790-branch_model_adaptation)
- [4.0-790-branch_model_adaptation](https://github.com/wazuh/wazuh-packages/tree/4.0-790-branch_model_adaptation)
- [4.1-790-branch_model_adaptation](https://github.com/wazuh/wazuh-packages/tree/4.1-790-branch_model_adaptation)
- [4.2-790-branch_model_adaptation](https://github.com/wazuh/wazuh-packages/tree/4.2-790-branch_model_adaptation)
- [master-790-branch_model_adaptation](https://github.com/wazuh/wazuh-packages/tree/master-790-branch_model_adaptation)
- [5.0-dev-790-branch_model_adaptation](https://github.com/wazuh/wazuh-packages/tree/5.0-dev-790-branch_model_adaptation)

## Tasks:

- [x] New file VERSION must be added to the root folder. It must contain the latest branch tag. 
- [x] Remove unnecessary folders hierarchy. 
- [x] Remove SPEC versioning. 
- [x] Modify building scripts to access directly to their specs and accept the new hierarchy. 
- [ ] Wazuh Jenkins Bumps / check the Jenkins packages builder
- [ ] Pull request to wazuh-documentation.
- [ ] Review docker building images.

**Comment by rauldpm** [comment]
Tuesday 2021-06-01

- Fixed branch versions of legacy branch in https://github.com/wazuh/wazuh-packages/commit/1b977a78f0ed8cf20c6965fbe5f0b946426ee16e
- Fixed branch versions of 4.0 branch in https://github.com/wazuh/wazuh-packages/commit/5fba2b01790842570d1d62b59d940a0f28b3a1b6
- Removed node dependency from 4.0 debs packages in https://github.com/wazuh/wazuh-packages/commit/c4402a5d492d16fe4ac20bea3773f20c5a23d3c5
- Locally tested all packages that use docker in legacy and 4.0
  - splunkapp, wazuhapp, debs (i386/amd64), rpms, wpk, windows (agent)
  - For the rest of the packages, another platform is necessary, it will be tested in the future in aws instances
- Investigated the generation of wpk packages, certificates to sign, docker image and aws use

**Comment by rauldpm** [comment]
Wednesday 2021-06-02

- Fixed branch versions of 4.1 branch in
- Locally tested all packages that use docker in legacy and 4.0
  - splunkapp, wazuhapp, debs (i386/amd64), rpms, wpk, windows (agent)
  - Found error in wazuhapp -> Error: Cannot find module 'require-in-the-middle'
    - This bug is reproduced in 4.0 but the build is successful
    - The generation files of 4.1 and 4.0 are the same
    - Investigating what has changed from the wazuh-kibana-app repository
  - For the rest of the packages, another platform is necessary, it will be tested in the future in aws instances

**Comment by rauldpm** [comment]
Friday 2021-06-04

- Branch 4.1 does not generate any package corresponding to version 4.1.x
- The Master branch does generate packages 4.1.5-7.10.2
- Updated branch 4.1-790-branch_model_adaptation with Master scripts
- The tags corresponding to v4.1.x do not contain these changes
- Successful builds: v4.1.5-7.10.2, v4.1.5-7-10.0, v4.1.4-7.10.0
- Failed builds: v4.1.4-7.10.2

tag: [v4.1.5-7.10.2](https://github.com/wazuh/wazuh-kibana-app/releases/tag/v4.1.5-7.10.2)
![image](https://user-images.githubusercontent.com/14913942/120854308-4094a780-c57d-11eb-9380-36aeb647b7f9.png)

tag: [v4.1.5-7.10.0](https://github.com/wazuh/wazuh-kibana-app/releases/tag/v4.1.5-7.10.0)
![image](https://user-images.githubusercontent.com/14913942/120854863-07106c00-c57e-11eb-8320-e5b28f09391f.png)

tag: [v4.1.4-7.10.2](https://github.com/wazuh/wazuh-kibana-app/releases/tag/v4.1.4-7.10.2)
![image](https://user-images.githubusercontent.com/14913942/120852819-04604780-c57b-11eb-8219-be3c56a97e6a.png)

tag: [v4.1.4-7.10.0](https://github.com/wazuh/wazuh-kibana-app/releases/tag/v4.1.4-7.10.0)
![image](https://user-images.githubusercontent.com/14913942/120853355-c7e11b80-c57b-11eb-9e7f-400f8e7b5e38.png)

**Comment by rauldpm** [comment]
Monday 2021-06-07

- Fixed branch versions of 4.2 branch in https://github.com/wazuh/wazuh-packages/commit/0bdcaa3be0c89fdf0abb66217868d13646c54d3c
- Removed node from amd64 debs packages in https://github.com/wazuh/wazuh-packages/commit/3c81e5733d399c93a2b96d0c05fd3ca9c65a7b34
- Locally tested all packages that use docker in 4.1 branch
  - splunkapp, wazuhapp, debs (i386/amd64), rpms, wpk, windows (agent)

**Comment by rauldpm** [comment]
Tuesday 2021-06-08

**Comment by rauldpm** [comment]
Wednesday 2021-06-09

- Investigated structure of  deb packages generation
- Adapted for new structure
- Adapted future package generation
- Future packages fails
  - Investigated changes related to src/Makefile of wazuh repository
  - Testing changes produced by the use of downloaded assets in the execution of the makefile. With no apparent changes, it is no longer necessary to change the value of VERSION / DEPS_VERSION in Makefile
  - Fixed hierarchy of future packages
  - The version of the generated package is not changed, it remains at 4.3.0 when it should be 4.30.0
  - The problem seems to be within the package generation itself, specifically in:
```
dh_builddeb
dpkg-deb --build debian/wazuh-manager ..
dpkg-deb: building package `wazuh-manager' in `../wazuh-manager_4.3.0-1_amd64.deb'.
```

**Comment by rauldpm** [comment]
Thursday 2021-06-10

- Fixed future generation
- Removed api target
- Investigated preinst, postinst, prerm, postrm

**Comment by rauldpm** [comment]
Friday 2021-06-11

- Fully adapted rpm scripts
  - Removed api target
  - Adapted to new specs hierarchy
  - Fixed future generation
  - Fixed legacy when target is manager
  - Tried to adapt it for maximum similarity with debs

**Comment by rauldpm** [comment]
Tuesday 2021-06-15

- Tested aix packages
  - wazuh /wazuh repository download is successful but seems corrupt as it cannot be unzipped. It seems a problem with the configuration of the aix machine since in another system it works correctly

![image](https://user-images.githubusercontent.com/14913942/122128200-9f3b0a80-ce34-11eb-96e4-83c22beae688.png)

  - Detected an error with the package generation
  - It seems to be related to perl or libssl
  - Perl 5 needs to be pre-built due to version change from aix5 to aix6. This fixes the last error
  - Fixed legacy, 4.0, 4.1, master and 5.0 with perl 5 pre build.
  - Legacy and 4.1 keeps the problem, 4.0 builds correctly

**Comment by rauldpm** [comment]
Wednesday 2021-06-16

- Solaris
  - Master branch 
    - Fixed vagrantfile example versions
    - Adapted solaris11 for new specs folder hierarchy
    - Adapted packages generation with vagrant, now its not necessary copy solaris11 or solaris10 to package_generation/src. Vagrant automatically use the needed folder through synced folder.
    - The generated packaged is now located inside a "output" folder of solaris11 or solaris10.
    - Tested with vagrant. Boxes tested: solaris10, solaris11, solaris10_cmake, solaris11_cmake
  - 4.2 branch
    - Fixed branches to v4.2.0-rc7
    - Fixed vagrantfile example versions
    - Tested with vagrant. Boxes tested: solaris10, solaris11, solaris10_cmake, solaris11_cmake

**Comment by rauldpm** [comment]
Thursday 2021-06-17

- Finished debs, rpms, solaris, wazuhapp and splunkapp in legacy, 4.0, 4.1, 4.2, master branches.
- Partially finished: aix (need to check in aix machine), wpk, windows
- Pending: hpux
- In general, the changes have been maintained as far as possible for each branch so that the behavior is the most similar
  - Fixed and added new main checks
  - Fixed outputs dir
  - Added legacy (centos5) checks in rpms
  - FIxed help messages
  - Fixed versions
  - Revert default target to required
  - Removed all api build from rpms except in legacy
  - Clean .vagrant folders in solaris
  - Revised default variables

**Comment by rauldpm** [comment]
Friday 2021-06-18

- Working in wpk generation
- Simplified parameters
- Simplified main
- Removed duplicated code
- Add news checks
- Identified error in windows generation
  - Localized error in wpkpack.py in _mergeappend
  - iisfile () throws an exception
  - Path problem, a list of strings corresponding to files/directories are passed as a parameter, but they do not exist in the current path

**Comment by rauldpm** [comment]
Monday 2021-06-22

- All packages have been adapted for the new spec hierarchy
- Final review for packages: aix, hpux, macos, solaris, splunkapp, wazuhapp, windows, wpk
- Added wazuhapp and splunkapp branch to VERSION file
- Fixed checksum value if not checksumdir is specified. If not checksum option is used, checksum default value is "no"
- All master packages have all their optional parameters except when you have to specify a target or certificates

**Comment by rauldpm** [comment]
Tuesday 2021-06-23

- Finished all packages.
- Readapted all packages to use both local specs and downloaded specs as a forecast for a repository change of the specs
- Started review of Dockerfiles
- Started review of Jenkins Packages Builder

**Comment by rauldpm** [comment]
Thursday 2021-06-24

- Updated development branches with main branches
- Resolved conflicts
- Check package generation with last updates
- Reviewed dockerfiles. Removed all nodejs from master branch
- Investigated Jenkins Packages_builder pipeline
  - All executions use the master branch by default
  - Cant specify to use master development branch
  - Investigated differences with a 4.2 build
  - Apparently the main generation script is not used but directly the build.sh script
  - This makes it impossible to directly test these changes, it may be necessary to test the scripts on a dedicated machine manually.
  - Apparently the build_linux_packages.yml ansible playbook is not used. It is not called by any other file in the wazuh-jenkins repository unlike the ova playbook

**Comment by rauldpm** [comment]
Friday 2021-06-25

- Investigated docker image ECR
- Configured aws-cli
- Pushed deb image in package_generation as deb_builder_amd64_cmake_specs
- Jenkins Packages_builder didn't recognize new container 
- Investigated Jenkins Shared Library

**Comment by rauldpm** [comment]
Monday 2021-06-28

- Investigated AWS TasksDefinitions
- Investigated how to add multiples containers to TasksDefinitions
- Added new container "deb_builder_amd64_cmake_specs" to "Packages_deb_amd64_cmake" task definition
- Added new parametrers to Jenkins Pipeline to modify the suffix that identifies the taskdefinition and the name of the container

**Comment by rauldpm** [comment]
Tuesday 2021-06-29

- Add multiples containers in one TasksDeinitions it is not viable. Containers do not run independent but parallelly, producing a termination of execution as soon as a container ends.
- Created new TasksDefinition "Packages_deb_amd64_cmake_specs" and linked "deb_builder_amd64_cmake_specs" container.
- Tested Generation deb amd64 successfully
- Investigated pipeline for generation of ECR images.
- Updated deb amd64/i386 and rpm x86_64 containers (with _specs suffix)
- Looking for an alternative to modify and upload containers that I can not build locally
-

**Comment by rauldpm** [comment]
Wednesday 2021-06-30

- Review docker building images
  - Investigated required instances in aws
  - Builded arm images in AWS
  - Researched and started modifying Packages_builder_tier to allow passing ecr suffix to use in Packages_builder pipeline

**Comment by rauldpm** [comment]
Thursday 2021-07-1

- Review docker building images
  - Updated 4.2 and master deb and rpm images
  - Tested 4.2 and master deb and rpm images
  - Added to Packages_builder_tier option to specify suffix. Tested
  - Trying to generate a centos 6 i386 docker image. 
    - Error in local (linux / amd64) missing dependencies. 
    - Generation successful through functional pipeline. 
    - Looking for instance in aws. 
    - Error in aws instances

**Comment by rauldpm** [comment]
Friday 2021-07-02

- Review docker building images
  - Working on centos 6 i386 fix
