### ISSUE TITLE
Unattended migration to packages

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#834]
Hello team,

We come from https://github.com/wazuh/wazuh-documentation/issues/3364
Wazuh-documentation project: https://github.com/wazuh/wazuh-documentation/projects/20

We want to include the unattended scripts to our packages repository. To achieve that we need to do the following tasks:
- [x] #835
- [ ] #848
- [ ] #847
- [ ] #839
- [ ] https://github.com/wazuh/wazuh-packages/issues/867
- [ ] https://github.com/wazuh/wazuh-packages/issues/866
- [ ] https://github.com/wazuh/wazuh-packages/issues/865
- [ ] 100% coverage tests of unattended options
- [ ] https://github.com/wazuh/wazuh-packages/issues/865
- [ ] https://github.com/wazuh/wazuh-packages/issues/883

Related PR in wazuh-documentation:
- https://github.com/wazuh/wazuh-documentation/pull/3992

Desirable issues:
- [ ] Develop GHA for uploading files to AWS
- [x] https://github.com/wazuh/wazuh-packages/issues/858
- [ ] Add automatic bump to resources files
- [ ] #854
- [x] https://github.com/wazuh/wazuh-packages/issues/864
- [ ] Include last OVA changes into unattended
- [ ] Check user generation in unattended
- [ ] https://github.com/wazuh/wazuh-packages/issues/863
- [ ] https://github.com/wazuh/wazuh-packages/issues/862
- [ ] https://github.com/wazuh/wazuh-packages/issues/861

**Comment by alberpilot** [comment]
We will continue here: https://github.com/wazuh/wazuh-packages/issues/982
