### ISSUE TITLE
Automatize the release  of unattended script

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#857]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2.1 | Manager | Install | unattended script |

We need to automate the release of the unattended script, to do this we need to implement a mechanism that  uploads the modified script to our S3 repository when we merge a PR that modifies these scripts.

## TASKS

- [ ] Rename the directory containing the unattended installation scripts.
- [ ] Create Jenkins pipeline or GitHub action to upload the modified files when a PR is merged in [stable](https://github.com/wazuh/wazuh-packages/tree/stable)

The process that uploads the scripts needs the following requirements:

- [ ] Identify when a PR has been merged in the `stable` branch.
- [ ] Identify which files have been modified.
- [ ] Find out if the files in the `unatteded-script` directory have been modified
- [ ] Upload the modified files in the `unatteded-script` directory.
