### ISSUE TITLE
Rename the directory containing the unattended installation scripts.

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#858]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2.1 | Manager | Install | unattended script |

The directory containing the unattended script has to be renamed from `resources` to `unatteded-script`

## TASKS
- [x] Rename directory, at lease in [stable](https://github.com/wazuh/wazuh-packages/tree/stable), [master](https://github.com/wazuh/wazuh-packages/tree/master) and [4.2](https://github.com/wazuh/wazuh-packages/tree/4.2) branches.
- [x] Modify [OVA scripts](https://github.com/wazuh/wazuh-packages/tree/4.2/ova).
- [x] Modify documentation if needed
