### ISSUE TITLE
Unattended installer improvements and fixes

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#982]
After Unattended installer migration from `wazuh-documentation` to `wazuh-packages` we planned a list of improvements / fixes that must be tracked in this issue:

## Bugs
- [ ] #847 
- [x] #896
- [ ] #968
- [x] #952
- [x] #967
- [x] #839
- [x] #974
- [x] #869 
- [x] #947 
- [x] #920 
- [x] #897
- [x] #984

## Improvements
- [ ] Read the installation failed component log and attach it to to de unattended log
- [ ] #863
- [ ] #862
- [x] #867
- [x] #854
- [x] #848 
- [x] #865 
- [x] #943
- [x] #866 
- [x] #901
- [x] #877
- [x] #898
- [x] #883 
- [x] #886 
- [x] #858
- [x] #882 
- [x] #946
- [x] #835
- [x] https://github.com/wazuh/wazuh-jenkins/issues/2924
- [x] #834

## To take into account
- [ ] Unit/integration testing
- [ ] Automatic bump
- [ ] #861

*Additional info*
We come from https://github.com/wazuh/wazuh-documentation/issues/3364
Wazuh-documentation project: https://github.com/wazuh/wazuh-documentation/projects/20
